module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"pt_PT" },
      "Validation Summary:":[ null,
        "Sumário de validação:" ],
      Code:[ null,
        "Código" ],
      Message:[ null,
        "Mensagem" ],
      Description:[ null,
        "Descrição" ],
      File:[ null,
        "Ficheiro" ],
      Line:[ null,
        "Linha" ],
      Column:[ null,
        "Coluna" ],
      "Invalid nesting of selectors found":[ null,
        "Aninhamento inválido de seletores encontrado" ],
      "A CSS syntax error was encountered":[ null,
        "Um erro de sintaxe CSS foi encontrado" ],
      "Your FTL is not valid.":[ null,
        "O seu FTL não é válido." ],
      "Your FTL file could not be parsed.":[ null,
        "O seu ficheiro FTL não pôde ser analisado." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Scripts remotos não são permitidos conforme as políticas de extras." ],
      "Inline scripts blocked by default":[ null,
        "Scripts inline bloqueados por predefinição" ],
      "Unadvised 3rd-party JS library":[ null,
        "Biblioteca JS de terceiros desaconselhada" ],
      "Known JS library detected":[ null,
        "Biblioteca JS conhecida detetada" ],
      "{{api}} is not supported":[ null,
        "{{api}} não é suportado" ],
      "This API has not been implemented by Firefox.":[ null,
        "Esta API ainda não foi implementada pelo Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" foi removido da versão 3 do manifesto (propriedade `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} está obsoleta" ],
      "This API has been deprecated by Firefox.":[ null,
        "Esta API foi descontinuada pelo Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" está obsoleto ou não está implementado" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener chamado com o quarto argumento." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} não é suportado na versão {{minVersion}} do Firefox" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Esta API não está implementada pela versão mínima indicada do Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} não é suportado na versão {{minVersion}} do Firefox para Android" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Esta API não está implementada pela versão mínima indicada do Firefox para Android" ],
      "Content script file could not be found.":[ null,
        "O ficheiro de script de conteúdo não pôde ser encontrado." ],
      "Content script file could not be found":[ null,
        "O ficheiro de script de conteúdo não pôde ser encontrado" ],
      "Content script file name should not be empty.":[ null,
        "O nome do ficheiro de script de conteúdo não deve estar vazio." ],
      "Content script file name should not be empty":[ null,
        "O nome do ficheiro de script de conteúdo não deve estar vazio" ],
      "JavaScript syntax error":[ null,
        "Erro de sintaxe JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Global inesperado passado como um argumento" ],
      "Use of document.write strongly discouraged.":[ null,
        "Utilização de document.write fortemente desencorajada." ],
      "Banned 3rd-party JS library":[ null,
        "Biblioteca JS de terceiros banida" ],
      "Your JSON contains block comments.":[ null,
        "O seu JSON contém comentários em bloco." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Chaves duplicadas não são permitidas em ficheiros JSON." ],
      "Your JSON is not valid.":[ null,
        "O seu JSON não é válido." ],
      "Your JSON file could not be parsed.":[ null,
        "O seu ficheiro JSON não pôde ser analisado." ],
      "Reserved filename found.":[ null,
        "Foi encontrado um nome de ficheiro reservado." ],
      "We were unable to decompress the zip file.":[ null,
        "Não conseguimos descomprimir o ficheiro zip." ],
      "manifest.json was not found":[ null,
        "manifest.json não foi encontrado" ],
      "File is too large to parse.":[ null,
        "Ficheiro é muito grande para analisar." ],
      "Hidden file flagged":[ null,
        "Ficheiro oculto marcado" ],
      "Flagged filename found":[ null,
        "Nome de ficheiro marcado encontrado" ],
      "Flagged file extensions found":[ null,
        "Extensões de ficheiro marcadas encontradas" ],
      "Package contains duplicate entries":[ null,
        "Pacote contém entradas duplicadas" ],
      "Flagged file type found":[ null,
        "Tipo de ficheiro marcado encontrado" ],
      "Package already signed":[ null,
        "Pacote já assinado" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Extras do Firefox não têm permissão para executar \"coin miners\"." ],
      "String name is reserved for a predefined message":[ null,
        "Nome de string está reservado para uma mensagem predefinida" ],
      "Placeholder for message is missing":[ null,
        "Marcador de posição para a mensagem está em falta" ],
      "A placeholder used in the message is not defined.":[ null,
        "Um marcador de posição utilizado na mensagem não está definido." ],
      "Placeholder name contains invalid characters":[ null,
        "Nome de marcador de posição contém caracteres inválidos" ],
      "Placeholder is missing the content property":[ null,
        "Marcador de posição tem em falta a propriedade do conteúdo" ],
      "Translation string is missing the message property":[ null,
        "String de tradução está em falta na propriedade de mensagem" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Nenhuma propriedade de mensagem \"message\" está definida para uma string (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Consulte https://mzl.la/2Qn0fWC (MDN Docs) para mais informação." ],
      "Invalid host permission.":[ null,
        "Permissão de hospedeiro desconhecida." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" no manifest.json não é um valor válido" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Veja https://mzl.la/20PenXl (MDN Docs) para mais informação." ],
      "The \"name\" property must be a string.":[ null,
        "A propriedade \"name\" deve ser uma string." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Veja http://mzl.la/1STmr48 (MDN Docs) para mais informação." ],
      "The \"version\" property must be a string.":[ null,
        "A propriedade \"version\" tem de ser uma string." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Veja http://mzl.la/1kXIADa (MDN Docs) para mais informação." ],
      "The field is invalid.":[ null,
        "O campo é inválido." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "A propriedade \"version\" utiliza um formato específico do Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Veja https://mzl.la/1ZOhoEN (MDN Docs) para mais informação." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" não é permitido." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "A propriedade \"update_url\" não é utilizada pelo Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" não é requerido." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Um ícone definido no manifesto não pôde ser encontrado no pacote." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Ícone não pôde ser encontrado em \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Não foi possível encontrar um script de segundo plano definido no manifesto." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Não foi possível encontrar uma página de segundo plano definida no manifesto." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Script de fundo não pôde ser encontrado em \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Página de fundo não pôde ser encontrada em \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Não foi possível encontrar um script de conteúdo definido no manifesto." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Não foi possível encontrar um ficheiro de conteúdo css definido no manifesto." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Não foi possível encontrar em \"%(path)s\" um script de conteúdo definido no manifesto." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Ficheiro de css do script de conteúdo definido no manifesto não pôde ser encontrado em \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Não foi possível encontrar um ficheiro de dicionário definido no manifesto." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Não foi possível encontrar em \"%(path)s\" um ficheiro de dicionário definido no manifesto." ],
      "The manifest contains multiple dictionaries.":[ null,
        "O manifesto contém múltiplos dicionários." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Foram definidos múltiplos dicionários no manifesto, o que não é suportado." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "O manifesto contém um objeto de dicionários, mas está vazio." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Foi definido um objeto de dicionários no manifesto, mas este estava vazio." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "O manifesto contém um dicionário, mas nenhuma propriedade de identificação." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Foi encontrado um dicionário no manifesto, mas não havia nenhuma identificação definida." ],
      "Forbidden content found in add-on.":[ null,
        "Conteúdo proibido encontrado no extra." ],
      "This add-on contains forbidden content.":[ null,
        "Este extra contém conteúdo proibido." ],
      "Icons must be square.":[ null,
        "Ícones têm de ser quadrados." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ícone em \"%(path)s\" tem de ser quadrado." ],
      "The size of the icon does not match the manifest.":[ null,
        "O tamanho do ícone não corresponde ao manifesto." ],
      "Corrupt image file":[ null,
        "Ficheiro de imagem corrupto" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Ficheiro de ícone esperado em \"%(path)s\" está corrompido" ],
      "This property has been deprecated.":[ null,
        "Esta propriedade foi descontinuada." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Este nome alternativo do tema LWT foi removido no Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Consulte https://mzl.la/2T11Lkc (Documentação da MDN) para mais informação." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Não foi possível encontrar em \"%(path)s\" a imagem do tema para \"%(type)s\"" ],
      "Corrupted theme image file":[ null,
        "Ficheiro de imagem de tema corrompido" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "O ficheiro de imagem do tema em \"%(path)s\" está corrompido" ],
      "Theme image file has an unsupported file extension":[ null,
        "O ficheiro de imagem do tema tem uma extensão de ficheiro não suportada" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "O ficheiro de imagem do tema em \"%(path)s\" tem uma extensão de ficheiro não suportada" ],
      "Theme image file has an unsupported mime type":[ null,
        "O ficheiro de imagem do tema tem um tipo de MIME não suportado" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "O ficheiro de imagem do tema em \"%(path)s\" tem um tipo de MIME \"%(mime)s\" não suportado" ],
      "Theme image file mime type does not match its file extension":[ null,
        "O tipo de MIME do ficheiro de imagem do tema não corresponde com a sua extensão de ficheiro" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "O ficheiro de imagem do tema em \"%(path)s\" não corresponde com o seu tipo de MIME \"%(mime)s\" atual" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "O \"default_locale\" tem falta de idiomas." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "O \"default_locale\" está em falta mas \"_locales\" existe." ],
      "Unsupported image extension":[ null,
        "Extensão de imagem não suportada" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Íones devem ser um de JPG/JPEG, WebP, GIF, PNG ou SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Propriedade \"applications\" foi substituída pela propriedade \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Diretório de idiomas vazio" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Ficheiro messages.json em falta em \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Chave de manifesto não suportada pela versão mínima especificada do Firefox" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Permissão não suportada pela versão mínima do Firefox especificada" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Permissão não suportada pela versão mínima do Firefox para Android especificada" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Permissão não suportada versão mínima do Firefox para Android especificada" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "A ligação a \"addons.mozilla.org\" não é permitida" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Não podem ser utilizadas ligações na página inicial que direcionem para \"addons.mozilla.org\"" ],
      "The permission type is unsupported.":[ null,
        "O tipo de permissão não é suportado." ],
      "The field is required.":[ null,
        "O campo é requerido." ],
      "Unknown permission.":[ null,
        "Permissão desconhecida." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Veja https://mzl.la/1R1n1t0 (MDN Docs) para mais informação." ] } } }