module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n > 1);",
        lang:"fr" },
      "Validation Summary:":[ null,
        "Résumé des validations :" ],
      Code:[ null,
        "Code" ],
      Message:[ null,
        "Message" ],
      Description:[ null,
        "Description" ],
      File:[ null,
        "Fichier" ],
      Line:[ null,
        "Ligne" ],
      Column:[ null,
        "Colonne" ],
      "Invalid nesting of selectors found":[ null,
        "Imbrication invalide de sélecteurs trouvée" ],
      "A CSS syntax error was encountered":[ null,
        "Une erreur de syntaxe CSS a été rencontrée" ],
      "Your FTL is not valid.":[ null,
        "Votre fichier FTL n’est pas valide." ],
      "Your FTL file could not be parsed.":[ null,
        "Votre fichier FTL n’a pas pu être analysé." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Les scripts externes ne sont pas autorisés, comme indiqué dans les termes relatifs aux modules." ],
      "Inline scripts blocked by default":[ null,
        "Les scripts inline sont bloqués par défaut" ],
      "Unadvised 3rd-party JS library":[ null,
        "Bibliothèque JS tierce déconseillée" ],
      "Known JS library detected":[ null,
        "Bibliothèque JS connue détectée" ],
      "{{api}} is not supported":[ null,
        "{{api}} n’est pas pris en charge" ],
      "This API has not been implemented by Firefox.":[ null,
        "Cette API n’a pas été implémentée dans Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "« {{api}} » a été supprimé dans Manifest Version 3 (propriété `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} n’est pas pris en charge" ],
      "This API has been deprecated by Firefox.":[ null,
        "Firefox considère désormais cette API obsolète." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "« {{api}} » est obsolète ou non implémenté" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener a été appelé avec un quatrième argument considéré comme vrai (truthy)." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} n’est pas pris en charge par la version {{minVersion}} de Firefox" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Cette API n'est pas implémentée par la version minimale de Firefox indiquée" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} n’est pas pris en charge par la version {{minVersion}} de Firefox pour Android" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Cette API n'est pas implémentée par la version minimale donnée de Firefox pour Android" ],
      "Content script file could not be found.":[ null,
        "Impossible de trouver le fichier de script." ],
      "Content script file could not be found":[ null,
        "Impossible de trouver le fichier de script de contenu" ],
      "Content script file name should not be empty.":[ null,
        "Le fichier du script de contenu doit avoir un nom." ],
      "Content script file name should not be empty":[ null,
        "Le fichier du script de contenu doit avoir un nom" ],
      "JavaScript syntax error":[ null,
        "Erreur de syntaxe JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Variable globale inattendue passée comme un argument" ],
      "Use of document.write strongly discouraged.":[ null,
        "L’utilisation de document.write est fortement déconseillée." ],
      "Banned 3rd-party JS library":[ null,
        "Bibliothèque JS tierce interdite d’utilisation" ],
      "Your JSON contains block comments.":[ null,
        "Le code JSON contient des blocs de commentaires." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Les clés dupliquées ne sont pas autorisées dans les fichiers JSON." ],
      "Your JSON is not valid.":[ null,
        "Votre JSON n’est pas valide." ],
      "Your JSON file could not be parsed.":[ null,
        "Votre fichier JSON n’a pas pu être analysé." ],
      "Reserved filename found.":[ null,
        "Nom de fichier réservé détecté." ],
      "We were unable to decompress the zip file.":[ null,
        "Il est impossible de décompresser le fichier zip." ],
      "manifest.json was not found":[ null,
        "Le fichier manifest.json est introuvable" ],
      "File is too large to parse.":[ null,
        "Le fichier est trop volumineux pour être analysé." ],
      "Hidden file flagged":[ null,
        "Un fichier caché a été détecté" ],
      "Flagged filename found":[ null,
        "Nom de fichier signalé détecté" ],
      "Flagged file extensions found":[ null,
        "Extensions de fichiers signalées détectées" ],
      "Package contains duplicate entries":[ null,
        "Le paquet contient des entrées dupliquées" ],
      "Flagged file type found":[ null,
        "Type de fichier signalé détecté" ],
      "Package already signed":[ null,
        "Le paquet est déjà signé" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Les modules Firefox ne peuvent pas miner de cryptomonnaies." ],
      "String name is reserved for a predefined message":[ null,
        "Le nom de la chaîne est déjà réservé à un message prédéfini" ],
      "Placeholder for message is missing":[ null,
        "L’emplacement pour le message est manquant" ],
      "A placeholder used in the message is not defined.":[ null,
        "L’emplacement utilisé dans le message n’est pas défini." ],
      "Placeholder name contains invalid characters":[ null,
        "Le nom de l’emplacement contient des caractères invalides" ],
      "Placeholder is missing the content property":[ null,
        "L’emplacement ne possède pas de propriété de contenu" ],
      "Translation string is missing the message property":[ null,
        "La chaîne de traduction ne contient pas la propriété « message »" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Aucune propriété de « message » n’est attribuée à une chaîne (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Voir https://mzl.la/2Qn0fWC (MDN Docs) pour plus d’informations." ],
      "Invalid host permission.":[ null,
        "Autorisation de l’hôte invalide." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "La valeur « manifest_version » dans le fichier manifest.json est invalide" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Voir https://mzl.la/20PenXl (MDN Docs) pour plus d’informations." ],
      "The \"name\" property must be a string.":[ null,
        "La propriété « name » doit être une chaîne de caractères." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Voir https://mzl.la/1STmr48 (MDN Docs) pour plus d’informations." ],
      "The \"version\" property must be a string.":[ null,
        "La propriété « version » doit être une chaîne de caractères." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Voir https://mzl.la/1kXIADa (MDN Docs) pour plus d’informations." ],
      "The field is invalid.":[ null,
        "Le champ est invalide." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "La propriété « version » s’appuie sur un format spécifique à Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Voir https://mzl.la/1ZOhoEN (MDN Docs) pour plus d’informations." ],
      "\"update_url\" is not allowed.":[ null,
        "« update_url » n’est pas autorisé." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "La propriété « update_url » n’est pas utilisée par Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "« strict_max_version » n’est pas nécessaire." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Une icône définie dans le manifeste est introuvable dans le paquet." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Icône introuvable à l’emplacement « %(path)s »." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Impossible de trouver un script d’arrière-plan défini dans le manifeste." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Impossible de trouver une page d’arrière-plan définie dans le manifeste." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Le script d’arrière-plan n’a pu être trouvé à l’emplacement « %(path)s »." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "La page d’arrière-plan n’a pu être trouvée à l’emplacement « %(path)s »." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Impossible de trouver un script de contenu défini dans le manifeste." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Impossible de trouver un fichier de script de contenu CSS défini dans le manifeste." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Impossible de trouver dans « %(path)s » le script de contenu défini dans le manifeste." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Le script de contenu CSS défini dans le manifeste est introuvable à l’emplacement « %(path)s »." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Impossible de trouver un fichier de dictionnaire défini dans le manifeste." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Impossible de trouver un fichier de dictionnaire défini dans le manifeste à l’emplacement « %(path)s »." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Le fichier manifest contient plusieurs dictionnaires." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Plusieurs dictionnaires sont définis dans le fichier manifest, ce qui n’est pas pris en charge." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Le manifeste contient un objet dictionnaire, mais il est vide." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Un objet dictionnaire a été défini dans le manifeste, mais il est vide." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Le manifeste contient un dictionnaire, mais pas la propriété id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Un dictionnaire a été trouvé dans le manifeste, mais aucun id n’a été défini." ],
      "Forbidden content found in add-on.":[ null,
        "Contenu interdit détecté dans le module." ],
      "This add-on contains forbidden content.":[ null,
        "Ce module contient des éléments interdits." ],
      "Icons must be square.":[ null,
        "Les icônes doivent être carrées." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "L’icône située à l’emplacement « %(path)s » doit être carrée." ],
      "The size of the icon does not match the manifest.":[ null,
        "La taille de l’icône ne correspond pas au manifeste." ],
      "Corrupt image file":[ null,
        "Fichier image corrompu" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "L’icône attendue, située à l’emplacement « %(path)s » est corrompue" ],
      "This property has been deprecated.":[ null,
        "Cette propriété est désormais obsolète." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "L’alias de ce thème LWT a été supprimé dans Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Voir la documentation MDN à l’adresse https://mzl.la/2T11Lkc pour plus d’informations." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "L’image du thème pour « %(type)s » n’a pu être trouvée à l’emplacement « %(path)s »" ],
      "Corrupted theme image file":[ null,
        "Fichier image du thème corrompu" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "L’image du thème à l’emplacement « %(path)s » est corrompue" ],
      "Theme image file has an unsupported file extension":[ null,
        "L’extension du fichier de l'image du thème n'est pas prise en charge" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "L’extension du fichier de l’image du thème à l’emplacement « %(path)s » n'est pas prise en charge" ],
      "Theme image file has an unsupported mime type":[ null,
        "Le type MIME du fichier de l’image du thème n’est pas pris en charge" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Le type MIME « %(mime)s » du fichier de l’image du thème à l’emplacement « %(path)s » n’est pas pris en charge" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Le type MIME du fichier de l’image du thème ne correspond pas à l’extension de son fichier" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "L’extension du fichier de l’image du thème à l’emplacement « %(path)s » ne correspond pas au type MIME « %(mime)s » contenu" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Des traductions sont manquantes pour « default_locale »." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "« default_locale » est manquant, mais « _locales » existe." ],
      "Unsupported image extension":[ null,
        "Extension d’image non prise en charge" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Les icônes doivent être au format JPG/JPEG, WebP, GIF, PNG ou SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Propriété « applications » remplacée par la propriété « browser_specific_settings »" ],
      "Empty language directory":[ null,
        "Répertoire de langues vide" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Fichier messages.json manquant dans « %(path)s »" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "La clé du manifeste n’est pas prise en charge par la version minimale de Firefox spécifiée" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "La permission n’est pas prise en charge par la version minimale de Firefox spécifiée" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "La clé du manifeste n’est pas prise en charge par la version minimale de Firefox pour Android spécifiée" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "La permission n’est pas prise en charge par la version minimale de Firefox pour Android spécifiée" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Les liens vers « addons.mozilla.org » ne sont pas autorisés" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Les liens vers « addons.mozilla.org » ne sont pas autorisés comme page d’accueil" ],
      "The permission type is unsupported.":[ null,
        "Ce type de permission n’est pas pris en charge." ],
      "The field is required.":[ null,
        "Ce champ est requis." ],
      "Unknown permission.":[ null,
        "Permission inconnue." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Voir https://mzl.la/1R1n1t0 (MDN Docs) pour plus d’informations." ] } } }