module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"es" },
      "Validation Summary:":[ null,
        "Resumen de la validación:" ],
      Code:[ null,
        "Código" ],
      Message:[ null,
        "Mensaje" ],
      Description:[ null,
        "Descripción" ],
      File:[ null,
        "Archivo" ],
      Line:[ null,
        "Línea" ],
      Column:[ null,
        "Columna" ],
      "Invalid nesting of selectors found":[ null,
        "Encontrado anidamiento incorrecto de selectores" ],
      "A CSS syntax error was encountered":[ null,
        "Encontrado un error de sintaxis CSS" ],
      "Your FTL is not valid.":[ null,
        "Tu FTL no es válido." ],
      "Your FTL file could not be parsed.":[ null,
        "Tu archivo FTL no se ha podido interpretar." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Los scripts remotos no están permitidos por las políticas de complementos." ],
      "Inline scripts blocked by default":[ null,
        "Los scripts incrustados están bloqueados por defecto" ],
      "Unadvised 3rd-party JS library":[ null,
        "Biblioteca JS de terceros desaconsejada" ],
      "Known JS library detected":[ null,
        "Detectada biblioteca JS conocida" ],
      "{{api}} is not supported":[ null,
        "{{api}} no compatible" ],
      "This API has not been implemented by Firefox.":[ null,
        "Firefox no ha implementado esta API." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListenerllamado con un cuarto argumento válido." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} no es compatible con la versión {{minVersion}} de Firefox" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "La versión mínima de Firefox no ha implementado esta API" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} no es compatible con la versión {{minVersion}} de Firefox para Android" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "La versión mínima de Firefox para Android no ha implementado esta API" ],
      "Content script file could not be found.":[ null,
        "No se puede encontrar el archivo script de contenido." ],
      "Content script file could not be found":[ null,
        "No se puede encontrar el archivo script de contenido" ],
      "Content script file name should not be empty.":[ null,
        "El nombre del archivo script de contenido no puede estar vacío." ],
      "Content script file name should not be empty":[ null,
        "El nombre del archivo script de contenido no puede estar vacío" ],
      "JavaScript syntax error":[ null,
        "error de sintaxis de JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Variable global inesperada pasada como argumento" ],
      "Use of document.write strongly discouraged.":[ null,
        "Se desaconseja el uso de document.write." ],
      "Banned 3rd-party JS library":[ null,
        "Biblioteca JS de terceros prohibida" ],
      "Your JSON contains block comments.":[ null,
        "Tu archivo JSON incluye comentarios multilínea." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "No se pueden duplicar claves en los archivos JSON." ],
      "Your JSON is not valid.":[ null,
        "Tu JSON no es válido." ],
      "Your JSON file could not be parsed.":[ null,
        "No se puede analizar tu archivo JSON." ],
      "Reserved filename found.":[ null,
        "Se encontró un nombre de archivo reservado." ],
      "We were unable to decompress the zip file.":[ null,
        "No pudimos descomprimir el archivo zip." ],
      "manifest.json was not found":[ null,
        "no se encontró manifest.json" ],
      "File is too large to parse.":[ null,
        "Archivo demasiado largo para su análisis." ],
      "Hidden file flagged":[ null,
        "Se destacó un archivo oculto" ],
      "Flagged filename found":[ null,
        "Se encontró un nombre de archivo destacado" ],
      "Flagged file extensions found":[ null,
        "Se encontraron extensiones de archivo destacadas" ],
      "Package contains duplicate entries":[ null,
        "El paquete incluye algunas entradas duplicadas" ],
      "Flagged file type found":[ null,
        "Se encontró un tipo de archivo destacado" ],
      "Package already signed":[ null,
        "Paquete ya firmado" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Los complementos de Firefox no tienen permitido minar criptomonedas." ],
      "String name is reserved for a predefined message":[ null,
        "El nombre de la cadena está reservado para un mensaje predefinido" ],
      "Placeholder for message is missing":[ null,
        "Falta el marcador de posición para mensajes" ],
      "A placeholder used in the message is not defined.":[ null,
        "No se definió el marcador de posición que se utilizó en el mensaje." ],
      "Placeholder name contains invalid characters":[ null,
        "El nombre del marcador de posición contiene caracteres no válidos" ],
      "Placeholder is missing the content property":[ null,
        "Al marcador de posición le faltan propiedades de contenido" ],
      "Translation string is missing the message property":[ null,
        "Falta la propiedad del mensaje en la cadena de traducción" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "No se configuró ninguna propiedad de mensaje en la cadena (https://mzl.la/2DSBTjA)." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" en el archivo manifest.json no tiene un valor válido" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Para más información, consulta https://mzl.la/20PenXl (documento de MDN)." ],
      "The \"name\" property must be a string.":[ null,
        "La propiedad \"name\" debe ser un string." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Para más información, consulta http://mzl.la/1STmr48 (documento de MDN)." ],
      "The \"version\" property must be a string.":[ null,
        "La propiedad \"version\" debe ser un string." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Para más información, consulta http://mzl.la/1kXIADa (documento de MDN)." ],
      "The field is invalid.":[ null,
        "El campo no es válido." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "La propiedad \"version\" utiliza un formato específico de Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Para más información, consulta https://mzl.la/1ZOhoEN (documento de MDN)." ],
      "\"update_url\" is not allowed.":[ null,
        "no se permite \"update_url\"." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Firefox no utiliza la propiedad \"update_url\"." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" no es obligatoria." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "No se pudo encontrar en el paquete un icono definido en el manifiesto." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "No se pudo encontrar el icono en \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "No se pudo encontrar el script de fondo definido en el manifiesto." ],
      "A background page defined in the manifest could not be found.":[ null,
        "No se pudo encontrar la página de fondo definida en el manifiesto." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "No se pudo encontrar el script de segundo plano en \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "No se pudo encontrar la página en segundo plano en \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "No se pudo encontrar el script de contenido definido en el manifiesto." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "No se pudo encontrar el archivo css del script de contenido definido en el manifiesto." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "El script de contenido definido en el manifiesto no se pudo encontrar en \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "No se encontró en \"%(path)s\" el archivo css de script de contenido definido en el manifiesto." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "No se pudo encontrar el archivo de diccionario definido en el manifiesto." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "No se pudo encontrar el archivo de diccionario definido en el manifiesto en la ubicación \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "El manifesto incluye varios diccionarios." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Se definieron varios diccionarios en el manifiesto y eso es incompatible." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "El manifesto incluye un objeto en forma de diccionario, pero está vacío." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Se definió un objeto en forma de diccionario en el manifesto, pero estaba vacío." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "El manifesto incluye un diccionario, pero ninguna propiedad de identificación." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Se encontró un diccionario en el manifiesto, pero no se estableció ninguna identificación." ],
      "Forbidden content found in add-on.":[ null,
        "Se encontró contenido prohibido en el complemento." ],
      "This add-on contains forbidden content.":[ null,
        "Este complemento incluye contenido prohibido." ],
      "Icons must be square.":[ null,
        "Los iconos deben ser cuadrados." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "El icono en \"%(path)s\" debe ser cuadrado." ],
      "The size of the icon does not match the manifest.":[ null,
        "El tamaño del icono no coincide con el del manifiesto." ],
      "Corrupt image file":[ null,
        "Archivo de imagen corrupto" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "El archivo de icono previsto en \"%(path)s\" está corrupto" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Este alias del tema LWS se ha eliminado en Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Para más información, consulta https://mzl.la/2T11Lkc (MDN Docs)." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "No se pudo encontrar la imagen del tema \"%(type)s\" en \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Archivo de imagen de tema corrupto" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "El archivo de imagen de tema en \"%(path)s\" está corrupto" ],
      "Theme image file has an unsupported file extension":[ null,
        "El archivo de imagen del tema tiene una extensión de archivo no compatible" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "El archivo de imagen del tema ubicado en \"%(path)s\" tiene una extensión de archivo no compatible" ],
      "Theme image file has an unsupported mime type":[ null,
        "El archivo de imagen del tema tiene un tipo MIME no compatible" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "El archivo de imagen del tema ubicado en \"%(path)s\" tiene un tipo \"%(mime)s\" no compatible" ],
      "Theme image file mime type does not match its file extension":[ null,
        "El tipo de mime del archivo de imagen del tema no coincide con su extensión de archivo" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "La extensión del archivo de imagen del tema en \"%(path)s\" no coincide con su tipo mimereal \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Faltan traducciones en \"default_locale\"." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Falta \"default_locale\", pero sí existe \"_locales\"." ],
      "Unsupported image extension":[ null,
        "Extensión de imagen no admitida" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Los iconos deberían ser JPG/JPEG, WebP, GIF, PNG o SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "Directorio de idioma vacío" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "No existe el archivo messages.json en \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "La versión mínima especificada por Firefox no admite la clave de manifiesto" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "La versión mínima especificada por Firefox no admite el permiso" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "La versión mínima especificada por Firefox para Android no admite la clave de manifiesto" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "La versión mínima especificada por Firefox para Android no admite el permiso" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "No se admite el tipo de permiso." ],
      "The field is required.":[ null,
        "Este campo es obligatorio." ],
      "Unknown permission.":[ null,
        "Permiso desconocido." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Para más información, consulta https://mzl.la/1R1n1t0 (documento de MDN)." ] } } }