module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=1; plural=0;",
        lang:"vi" },
      "Validation Summary:":[ null,
        "Tóm tắt xác nhận:" ],
      Code:[ null,
        "Đoạn mã" ],
      Message:[ null,
        "Tin nhắn" ],
      Description:[ null,
        "Mô tả" ],
      File:[ null,
        "Tập tin" ],
      Line:[ null,
        "Dòng" ],
      Column:[ null,
        "Cột" ],
      "Invalid nesting of selectors found":[ null,
        "Đã tìm thấy lồng ghép không hợp lệ" ],
      "A CSS syntax error was encountered":[ null,
        "Đã xảy ra lỗi cú pháp CSS" ],
      "Your FTL is not valid.":[ null,
        "FTL của bạn không hợp lệ." ],
      "Your FTL file could not be parsed.":[ null,
        "Tệp FTL của bạn không thể phân tích cú pháp." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Các tập lệnh từ xa không được phép theo Chính sách tiện ích mở rộng." ],
      "Inline scripts blocked by default":[ null,
        "Các tập lệnh nội tuyến bị chặn theo mặc định" ],
      "Unadvised 3rd-party JS library":[ null,
        "Thư viện JS của bên thứ 3 không được chấp nhận" ],
      "Known JS library detected":[ null,
        "Đã phát hiện thư viện JS" ],
      "{{api}} is not supported":[ null,
        "{{api}} không được hỗ trợ" ],
      "This API has not been implemented by Firefox.":[ null,
        "API này chưa được Firefox triển khai." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" đã bị xóa trong Manifest phiên bản 3 (thuộc tính `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} không được hỗ trợ" ],
      "This API has been deprecated by Firefox.":[ null,
        "API này đã bị loại bỏ khỏi Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" không được dùng nữa và sẽ không hỗ trợ" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` đã được gọi với tham số thứ tư là True." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} không được hỗ trợ trong Firefox phiên bản {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "API này không được triển khai bởi phiên bản Firefox tối thiểu quy định" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} không được hỗ trợ trong Firefox dành cho Android phiên bản {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "API này không được triển khai bởi phiên bản Firefox tối thiểu dành cho Android" ],
      "Content script file could not be found.":[ null,
        "Không thể tìm thấy tập lệnh nội dung." ],
      "Content script file could not be found":[ null,
        "Không thể tìm thấy tập lệnh nội dung" ],
      "Content script file name should not be empty.":[ null,
        "Tên tập tin nội dung không được để trống." ],
      "Content script file name should not be empty":[ null,
        "Tên tập tin nội dung không được để trống" ],
      "JavaScript syntax error":[ null,
        "Lỗi cú pháp JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Việc sử dụng biến toàn cục làm đối số không mong muốn" ],
      "Use of document.write strongly discouraged.":[ null,
        "Không khuyến khích sử dụng document.write." ],
      "Banned 3rd-party JS library":[ null,
        "Thư viện JS của bên thứ 3 bị cấm" ],
      "Your JSON contains block comments.":[ null,
        "JSON của bạn chứa các bình luận (comment) bị chặn." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Các khóa trùng lặp không được phép trong các tệp JSON." ],
      "Your JSON is not valid.":[ null,
        "JSON của bạn không hợp lệ." ],
      "Your JSON file could not be parsed.":[ null,
        "Tập tin JSON của bạn không thể phân tích cú pháp." ],
      "Reserved filename found.":[ null,
        "Đã tìm thấy tên tập tin dành riêng." ],
      "We were unable to decompress the zip file.":[ null,
        "Chúng tôi không thể giải nén tập tin zip." ],
      "manifest.json was not found":[ null,
        "Không tìm thấy manifest.json" ],
      "File is too large to parse.":[ null,
        "Tập tin quá lớn để phân tích cú pháp." ],
      "Hidden file flagged":[ null,
        "Tập tin ẩn được gắn cờ" ],
      "Flagged filename found":[ null,
        "Đã tìm thấy tên tập tin được gắn cờ" ],
      "Flagged file extensions found":[ null,
        "Đã tìm thấy phần mở rộng tập tin được gắn cờ" ],
      "Package contains duplicate entries":[ null,
        "Gói chứa các mục trùng lặp" ],
      "Flagged file type found":[ null,
        "Đã tìm thấy loại tập tin được gắn cờ" ],
      "Package already signed":[ null,
        "Gói đã được ký" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Tiện ích Firefox không được phép chạy các công cụ khai thác tiền ảo (coin miners)." ],
      "String name is reserved for a predefined message":[ null,
        "Tên chuỗi được dành riêng cho một tin nhắn được xác định trước" ],
      "Placeholder for message is missing":[ null,
        "Trình giữ chỗ cho tin nhắn bị thiếu" ],
      "A placeholder used in the message is not defined.":[ null,
        "" ],
      "Placeholder name contains invalid characters":[ null,
        "" ],
      "Placeholder is missing the content property":[ null,
        "" ],
      "Translation string is missing the message property":[ null,
        "Chuỗi dịch bị thiếu thuộc tính tin nhắn" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Không có thuộc tính thông báo \"message\" nào được đặt cho một chuỗi (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Xem tại https://mzl.la/2Qn0fWC (Tài liệu MDN) để biết thêm thông tin." ],
      "Invalid host permission.":[ null,
        "Quyền hạn host không hợp lệ." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" trong manifest.json không phải là một giá trị hợp lệ" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Xem tại https://mzl.la/20PenXl (Tài liệu MDN) để biết thêm thông tin." ],
      "The \"name\" property must be a string.":[ null,
        "Thuộc tính \"name\" phải là một chuỗi kí tự." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Xem tại http://mzl.la/1STmr48 (Tài liệu MDN) để biết thêm thông tin." ],
      "The \"version\" property must be a string.":[ null,
        "Thuộc tính \"version\" phải là một chuỗi kí tự." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Xem tại http://mzl.la/1kXIADa (Tài liệu MDN) để biết thêm thông tin." ],
      "The field is invalid.":[ null,
        "Trường không hợp lệ." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Thuộc tính \"version\" sử dụng định dạng dành riêng cho Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Xem https://mzl.la/1ZOhoEN (Tài liệu MDN) để biết thêm thông tin." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" không được cho phép." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Thuộc tính \"update_url\" không được sử dụng bởi Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" không bắt buộc." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Không thể tìm thấy biểu tượng được xác định trong tập tin manifest trong gói." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Không thể tìm thấy biểu tượng ở \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Không thể tìm thấy tập lệnh nền được xác định trong tập tin kê khai." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Không thể tìm thấy một trang nền được xác định trong tập tin kê khai." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Không thể tìm thấy tập lệnh nền tại \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Không thể tìm thấy trang nền tại \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Không thể tìm thấy tập lệnh nội dung được xác định trong tập tin kê khai." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Không thể tìm thấy tập tin css tập lệnh nội dung được xác định trong tập tin kê khai." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Không thể tìm thấy tập lệnh nội dung được xác định trong tập tin manifest tại \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Không thể tìm thấy tệp css tập lệnh nội dung được xác định trong tập tin manifest tại \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Không thể tìm thấy tập tin từ điển được xác định trong tập tin kê khai." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Không thể tìm thấy tập tin từ điển được xác định trong tập tin kê khai tại \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Tập tin kê khai chứa nhiều từ điển." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Nhiều từ điển đã được định nghĩa trong kê khai, mà nó không được hỗ trợ." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Tập tin kê khai chứa một đối tượng từ điển, nhưng nó trống." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Một đối tượng từ điển đã được định nghĩa trong tập tin kê khai, nhưng nó trống." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Tập tin kê khai chứa một từ điển nhưng không có thuộc tính id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Một từ điển đã được tìm thấy trong tập tin kê khai, nhưng không được đặt id." ],
      "Forbidden content found in add-on.":[ null,
        "Đã tìm thấy nội dung bị cấm trong tiện ích." ],
      "This add-on contains forbidden content.":[ null,
        "Tiện ích này chứa nội dung bị cấm." ],
      "Icons must be square.":[ null,
        "Biểu tượng phải là hình vuông." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Biểu tượng tại \"%(path)s\" phải là hình vuông." ],
      "The size of the icon does not match the manifest.":[ null,
        "Kích thước của biểu tượng không phù hợp với manifest." ],
      "Corrupt image file":[ null,
        "Tập tin bị hỏng" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Tập tin biểu tượng tại \"%(path)s\" bị hỏng" ],
      "This property has been deprecated.":[ null,
        "Thuộc tính này đã không còn được dùng nữa." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Bí danh chủ đề LWT này đã bị xóa trong Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Xem tại https://mzl.la/2T11Lkc (Tài liệu MDN) để biết thêm thông tin." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Không thể tìm thấy hình ảnh của chủ đề cho \"%(type)s\" tại \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Tập tin hình ảnh của chủ đề bị hỏng" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Tập tin hình ảnh của chủ đề tại \"%(path)s\" bị hỏng" ],
      "Theme image file has an unsupported file extension":[ null,
        "Tập tin hình ảnh chủ đề có phần mở rộng không được hỗ trợ" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Tập tin hình ảnh chủ đề tại \"%(path)s\" có phần mở rộng không được hỗ trợ" ],
      "Theme image file has an unsupported mime type":[ null,
        "Tập tin hình ảnh chủ đề có loại mime không được hỗ trợ" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Tập tin hình ảnh chủ đề tại \"%(path)s\" có loại mime không được hỗ trợ \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Loại mime của tập tin hình ảnh chủ đề không khớp với phần mở rộng tập tin của nó" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Phần mở rộng Tập tin hình ảnh chủ đề tại \"%(path)s\" không khớp với loại mime thực của nó \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Thuộc tính \"default_locale\" bị thiếu bản địa hóa." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Thuộc tính \"default_locale\" bị thiếu nhưng \"_locales\" tồn tại." ],
      "Unsupported image extension":[ null,
        "Phần mở rộng của hình ảnh không được hỗ trợ" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Các biểu tượng phải là một trong JPG/JPEG, WebP, GIF, PNG hoặc SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Thuộc tính \"applications\" bị ghi đè bởi thuộc tính \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Thư mục ngôn ngữ trống" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Thiếu tập tin messages.json trong \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Khóa kê khai không được hỗ trợ bởi phiên bản Firefox tối thiểu đã chỉ định" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Quyền hạn không được hỗ trợ bởi phiên bản Firefox tối thiểu đã chỉ định" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Khóa kê khai không được hỗ trợ bởi Firefox dành cho Android phiên bản tối thiểu đã chỉ định" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Quyền hạn không được hỗ trợ bởi Firefox dành cho Android phiên bản tối thiểu đã chỉ định" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Liên kết đến \"addons.mozilla.org\" không được phép" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Các liên kết trực tiếp đến \"addons.mozilla.org\" đều không được phép sử dụng cho trang chủ" ],
      "The permission type is unsupported.":[ null,
        "Loại quyền hạn không được hỗ trợ." ],
      "The field is required.":[ null,
        "Trường này là bắt buộc." ],
      "Unknown permission.":[ null,
        "Không rõ quyền hạn." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Xem tại https://mzl.la/1R1n1t0 (Tài liệu MDN) để biết thêm thông tin." ] } } }