module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"ia" },
      "Validation Summary:":[ null,
        "Summario de validation:" ],
      Code:[ null,
        "Codice" ],
      Message:[ null,
        "Message" ],
      Description:[ null,
        "Description" ],
      File:[ null,
        "File" ],
      Line:[ null,
        "Linea" ],
      Column:[ null,
        "Columna" ],
      "Invalid nesting of selectors found":[ null,
        "Annidamento non valide de selectores trovate" ],
      "A CSS syntax error was encountered":[ null,
        "Un error de syntaxe de CSS occurreva" ],
      "Your FTL is not valid.":[ null,
        "Tu FTL non es valide." ],
      "Your FTL file could not be parsed.":[ null,
        "Tu file FTL non pote ser analysate." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Le scripts remote non es permittite per le politicas concernente le additivos." ],
      "Inline scripts blocked by default":[ null,
        "Le scripts inline es blocate per predefinition" ],
      "Unadvised 3rd-party JS library":[ null,
        "Bibliotheca JS de tertios disconsiliate" ],
      "Known JS library detected":[ null,
        "Revelate bibliotheca JS note" ],
      "{{api}} is not supported":[ null,
        "{{api}} non es supportate" ],
      "This API has not been implemented by Firefox.":[ null,
        "Iste API non ha essite implementate per Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" ha essite removite in File manifesto Version 3 (`manifest_version` property)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} es obsolete" ],
      "This API has been deprecated by Firefox.":[ null,
        "Iste API ha essite obsolete per Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" es obsolete o non  implementate" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` appellate con un quarte argumento ‘truthy’ (considerate como ver)." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} non es supportate in le version {{minVersion}} de Firefox" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Iste API non ha essite implementate per version minime de Firefox indicate" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} non es supportate in le version {{minVersion}} de Firefox pro Android" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Iste API non ha essite implementate per version minime de Firefox pro Android indicate" ],
      "Content script file could not be found.":[ null,
        "Impossibile trovar le file script de contento." ],
      "Content script file could not be found":[ null,
        "Impossibile trovar le file script de contento" ],
      "Content script file name should not be empty.":[ null,
        "Le nomine de file script de contento non debe ser vacue." ],
      "Content script file name should not be empty":[ null,
        "Le nomine de file script de contento non debe ser vacue" ],
      "JavaScript syntax error":[ null,
        "Error de syntaxe de JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Variabile global non expectate passate como argumento" ],
      "Use of document.write strongly discouraged.":[ null,
        "Le uso de document.write es fortemente discoragiate." ],
      "Banned 3rd-party JS library":[ null,
        "Bibliotheca JS de tertios prohibite" ],
      "Your JSON contains block comments.":[ null,
        "Tu JSON contine commentos in bloco." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Le claves duplicate non es permittite in le files JSON." ],
      "Your JSON is not valid.":[ null,
        "Tu JSON non es valide." ],
      "Your JSON file could not be parsed.":[ null,
        "Tu file JSON non pote ser analysate." ],
      "Reserved filename found.":[ null,
        "Nomine de file reservate trovate." ],
      "We were unable to decompress the zip file.":[ null,
        "Nos non poteva decomprimer le file zip." ],
      "manifest.json was not found":[ null,
        "manifest.json non esseva trovate" ],
      "File is too large to parse.":[ null,
        "Le file es troppo grande pro esser analysate." ],
      "Hidden file flagged":[ null,
        "File celate signalate" ],
      "Flagged filename found":[ null,
        "Nomine de file signalate trovate" ],
      "Flagged file extensions found":[ null,
        "Extensiones de file signalate trovate" ],
      "Package contains duplicate entries":[ null,
        "Le pacchetto contine entratas duplicate" ],
      "Flagged file type found":[ null,
        "Typo de file signalate trovate" ],
      "Package already signed":[ null,
        "Pacchetto ja signate" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Le additivos de Firefox non es autorisate a minar cryptomonetas." ],
      "String name is reserved for a predefined message":[ null,
        "Nomine de catena reservate a un message predefinite" ],
      "Placeholder for message is missing":[ null,
        "Manca un spatio reservate del message" ],
      "A placeholder used in the message is not defined.":[ null,
        "Un spatio reservate usate in le message non es definite." ],
      "Placeholder name contains invalid characters":[ null,
        "Le nomine del spatio reservate contine characteres non valide" ],
      "Placeholder is missing the content property":[ null,
        "Le spatio reservate non ha le proprietate de contento" ],
      "Translation string is missing the message property":[ null,
        "Catena de traduction mancante del proprietates del message" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Nulle proprietate de message \"message\" es definite pro un catena (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Vide https://mzl.la/2Qn0fWC (MDN Docs) pro altere informationes." ],
      "Invalid host permission.":[ null,
        "Permission de servitor invalide." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" in le file manifest.json non es un valor valide" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Vide https://mzl.la/20PenXl (MDN Docs) pro altere informationes." ],
      "The \"name\" property must be a string.":[ null,
        "Le proprietate del \"nomine\" debe ser un catena." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Vider http://mzl.la/1STmr48 (MDN Docs) pro altere informationes." ],
      "The \"version\" property must be a string.":[ null,
        "Le proprietate del \"version\" debe ser un catena." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Vider http://mzl.la/1kXIADa (MDN Docs) pro altere informationes." ],
      "The field is invalid.":[ null,
        "Le campo es invalide." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Le proprietate \"version\" usa un formato Firefox-specific." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Vide https://mzl.la/1ZOhoEN (MDN Docs) pro plus de informationes." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" non es permittite." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Le proprietate \"update_url\" non es usate per Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" non obligatori." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Un icone definite in le file manifesto non pote ser trovate in le pacchetto." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Icone non pote ser trovate al \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Un script de fundo definite in le file manifesto non pote ser trovate." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Un pagina de fundo definite in le file manifesto non pote ser trovate." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Le script de fundo non pote ser trovate al \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Le pagina de fundo non pote ser trovate al \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Un script de contento definite in le file manifesto non pote ser trovate." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Le file css script de contento definite in le file manifesto non pote ser trovate." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Le script de contento definite in le file manifesto non pote ser trovate al \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Le file css script de contento definite in le file manifesto non pote ser trovate al \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Un file dictionario definite in le file manifesto non pote ser trovate." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Le file dictionario definite in le file manifesto non pote ser trovate in \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Le file manifesto contine plure dictionarios." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "In le file manifesto era definite plure dictionarios, ma isto non es supportate." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Le file manifesto contine un objecto dictionarios, ma illo es vacue." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Un objecto dictionarios ha essite definite in le file manifesto, ma illo era vacue." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Le manifesto contine un dictionario ma nulle proprietate id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Un dictionario ha essite trovate in le manifesto, ma sin id definite." ],
      "Forbidden content found in add-on.":[ null,
        "Contento prohibite trovate in le additivo." ],
      "This add-on contains forbidden content.":[ null,
        "Iste additivo ha contento prohibite." ],
      "Icons must be square.":[ null,
        "Le icones debe ser quadrate." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Le icone al \"%(path)s\" debe ser un quadrato." ],
      "The size of the icon does not match the manifest.":[ null,
        "Le dimension del icone non concorda con le manifesto." ],
      "Corrupt image file":[ null,
        "File imagine corrupte" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Le file icone expectate al \"%(path)s\" es corrupte" ],
      "This property has been deprecated.":[ null,
        "Iste proprietate ha essite obsolete." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Iste thema LWT alias ha essite eliminate in Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Vide https://mzl.la/2T11Lkc (MDN Docs) pro saper plus." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Le imagine de thema pro \"%(type)s\" non pote ser trovate al \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "File imagine de thema corrupte" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "File imagine de thema corrupte a \"%(path)s\" es corrupte" ],
      "Theme image file has an unsupported file extension":[ null,
        "Le file imagine del thema ha un extension non supportate" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Le file imagine del thema a \"%(path)s\" ha un extension non supportate" ],
      "Theme image file has an unsupported mime type":[ null,
        "Le file imagine del thema ha un typo de mime non supportate" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Le file imagine del thema a \"%(path)s\" ha le typo de mime non tractate \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Le typo de mime del file imagine del thema non concorda su extension" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Le extension del file imagine del thema a \"%(path)s\" non concorda su actual typo de mime \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Le \"default_locale\" manca de localisationes." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Le \"default_locale\" manca, ma \"_locales\" existe." ],
      "Unsupported image extension":[ null,
        "Extension de imagine non supportate" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Icones debe ser uno de JPG/JPEG, WebP, GIF, PNG o SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "proprietate \"applicationes\" supplantate per le proprietate \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Directorio de linguas vacue" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "File messages.json mancante in \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Clave de file manifesto non supportate per le minime version de Firefox specificate" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Permission non supportate per le version minime de Firefox specificate" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Clave del file manifesto non supportate per le minime version specificate de Firefox pro Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Permission non supportate per le version minime specificate de Firefox pro Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Le ligamine a \"addons.mozilla.org\" non es permittite" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Il non es permittite usar ligamines dirigente a \"addons.mozilla.org\" pro pagina principal" ],
      "The permission type is unsupported.":[ null,
        "Iste typo de permission non es supportate." ],
      "The field is required.":[ null,
        "Le campo es obligatori." ],
      "Unknown permission.":[ null,
        "Permission incognite." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Vide https://mzl.la/1R1n1t0 (MDN Docs) pro altere informationes." ] } } }