module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=1; plural=0;",
        lang:"id" },
      "Validation Summary:":[ null,
        "Ringkasan Validasi:" ],
      Code:[ null,
        "Kode" ],
      Message:[ null,
        "Pesan" ],
      Description:[ null,
        "Deskripsi" ],
      File:[ null,
        "Berkas" ],
      Line:[ null,
        "Baris" ],
      Column:[ null,
        "Kolom" ],
      "Invalid nesting of selectors found":[ null,
        "Pemilih beranak yang tidak valid ditemukan" ],
      "A CSS syntax error was encountered":[ null,
        "Kesalahan syntax CSS ditemukan" ],
      "Your FTL is not valid.":[ null,
        "FTL Anda tidak valid." ],
      "Your FTL file could not be parsed.":[ null,
        "File FTL Anda tidak dapat diurai." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Skrip jarak jauh tidak diperkenankan menurut Kebijakan Pengaya." ],
      "Inline scripts blocked by default":[ null,
        "Skrip selarik berkelanjutan diblokir" ],
      "Unadvised 3rd-party JS library":[ null,
        "Pustaka JS pihak ke-3 yang tidak dianjurkan" ],
      "Known JS library detected":[ null,
        "Pustaka JS yang diketahui terdeteksi" ],
      "{{api}} is not supported":[ null,
        "{{api}} tidak didukung" ],
      "This API has not been implemented by Firefox.":[ null,
        "API ini belum diimplementasikan oleh Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener disebut dengan argumen yang seolah benar keempat." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} tidak didukung di Firefox versi {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "API ini belum diimplementasikan pada versi Firefox minimum yang diberikan" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} tidak didukung di Firefox untuk Android versi {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "API ini belum diimplementasikan pada versi Firefox untuk Android minimum yang diberikan" ],
      "Content script file could not be found.":[ null,
        "Berkas skrip konten tidak dapat ditemukan." ],
      "Content script file could not be found":[ null,
        "Berkas skrip konten tidak dapat ditemukan" ],
      "Content script file name should not be empty.":[ null,
        "Nama berkas skrip konten tidak boleh kosong." ],
      "Content script file name should not be empty":[ null,
        "Nama berkas skrip konten tidak boleh kosong" ],
      "JavaScript syntax error":[ null,
        "Galat sintaksis JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Variabel global tiba-tiba diluluskan sebagai argumen" ],
      "Use of document.write strongly discouraged.":[ null,
        "Penggunaan document.write sangat tidak dianjurkan." ],
      "Banned 3rd-party JS library":[ null,
        "Pustaka JS pihak ke-3 yang dilarang" ],
      "Your JSON contains block comments.":[ null,
        "JSON Anda mengandung komentar pemblokiran." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Kunci duplikat tidak diizinkan dalam berkas JSON." ],
      "Your JSON is not valid.":[ null,
        "JSON Anda tidak valid." ],
      "Your JSON file could not be parsed.":[ null,
        "File JSON Anda tidak bisa diurai." ],
      "Reserved filename found.":[ null,
        "Nama-berkas cadangan ditemukan." ],
      "We were unable to decompress the zip file.":[ null,
        "Kami tidak dapat mendekompresi berkas yang di-zip." ],
      "manifest.json was not found":[ null,
        "manifest.json tidak ditemukan" ],
      "File is too large to parse.":[ null,
        "Berkas terlalu besar untuk diurai." ],
      "Hidden file flagged":[ null,
        "Berkas tersembunyi yang ditandai" ],
      "Flagged filename found":[ null,
        "Nama berkas yang ditandai ditemukan" ],
      "Flagged file extensions found":[ null,
        "Ekstensi berkas yang ditandai ditemukan" ],
      "Package contains duplicate entries":[ null,
        "Paket mengandung entri ganda" ],
      "Flagged file type found":[ null,
        "Jenis berkas yang ditandai ditemukan" ],
      "Package already signed":[ null,
        "Paket yang sudah ditandatangani" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Pengaya Firefox tidak diizinkan untuk menjalankan penambang koin." ],
      "String name is reserved for a predefined message":[ null,
        "Nama string disiapkan untuk pesan yang telah ditentukan" ],
      "Placeholder for message is missing":[ null,
        "Placeholder untuk pesan hilang" ],
      "A placeholder used in the message is not defined.":[ null,
        "Placeholder yang digunakan dalam pesan tidak ditentukan." ],
      "Placeholder name contains invalid characters":[ null,
        "Nama placeholder berisi karakter yang tidak sah" ],
      "Placeholder is missing the content property":[ null,
        "Placeholder tidak memiliki properti konten" ],
      "Translation string is missing the message property":[ null,
        "String terjemahan tidak memiliki properti pesan" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Tidak ada properti pesan \"message\" yang ditentukan untuk string (https://mzl.la/2DSBTjA)." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" dalam manifest.json bukan nilai yang valid" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Lihat https://mzl.la/20PenXl (Dokumen MDN) untuk informasi lebih lanjut." ],
      "The \"name\" property must be a string.":[ null,
        "Properti \"name\" harus sebuah string." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Lihat http://mzl.la/1STmr48 (MDN Docs) untuk informasi lebih lanjut." ],
      "The \"version\" property must be a string.":[ null,
        "Properti \"version\" harus sebuah string." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Lihat http://mzl.la/1kXIADa (MDN Docs) untuk informasi lebih lanjut." ],
      "The field is invalid.":[ null,
        "Bidang ini tidak valid." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Properti \"version\" menggunakan format khusus untuk Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Lihat https://mzl.la/1ZOhoEN (MDN Docs) untuk informasi lebih lanjut." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" tidak diizinkan." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Properti \"update_url\" tidak digunakan oleh Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" tidak diperlukan." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Ikon yang ditentukan di manifes tidak ditemukan di dalam paket." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Ikon tidak ditemukan dalam \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Skrip latar belakang yang ditentukan di manifes tidak ditemukan." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Laman latar belakang yang ditentukan di manifes tidak ditemukan." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Skrip latar tidak dapat ditemukan di \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Laman latar belakang tidak dapat ditemukan dalam \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Skrip konten yang ditentukan di manifes tidak ditemukan." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Berkas css skrip konten yang ditentukan di manifes tidak ditemukan." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Skrip konten yang ditentukan di manifes tidak ditemukan di \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Berkas css skrip konten yang ditentukan di manifes tidak ditemukan di \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Berkas kamus yang ditentukan di manifes tidak ditemukan." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Berkas kamus yang ditentukan di manifes tidak ditemukan di \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifes berisi berbagai kamus." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Kamus ganda terdefinisi di dalam manifest, dan ini tidak didukung." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifes berisikan obyek kamus, namun tidak ada isinya." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Objek kamus didefinisikan di dalam manifes, namun kosong." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifes berisikan kamus tanpa properti id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Kamus ditemukan di dalam manifes, namun tidak ada id yang diatur." ],
      "Forbidden content found in add-on.":[ null,
        "Konten yang dilarang ditemukan di pengaya." ],
      "This add-on contains forbidden content.":[ null,
        "Pengaya ini berisi konten yang dilarang." ],
      "Icons must be square.":[ null,
        "Ikon harus persegi." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikon di \"%(path)s\" harus persegi." ],
      "The size of the icon does not match the manifest.":[ null,
        "Ukuran ikon tidak cocok dengan manifesnya." ],
      "Corrupt image file":[ null,
        "Berkas gambar rusak" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Berkas ikon yang diharapkan di %(path)s rusak" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Alias LWT tema ini telah dihapus di Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Lihat https://mzl.la/2T11Lkc (MDN Docs) untuk informasi lebih lanjut." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Gambar tema untuk \"%(type)s\" tidak dapat ditemukan di \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Berkas gambar tema rusak" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Berkas gambar tema di \"%(path)s\" rusak" ],
      "Theme image file has an unsupported file extension":[ null,
        "Berkas gambar tema memiliki ekstensi berkas yang tidak didukung" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Berkas gambar tema di \"%(path)s\" memiliki ekstensi berkas yang tidak didukung" ],
      "Theme image file has an unsupported mime type":[ null,
        "Berkas gambar tema memiliki tipe mime yang tidak didukung" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Berkas gambar tema pada \"%(path)s\" memiliki mime tipe \"%(mime)s\" yang tidak didukung" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Jenis mime berkas gambar tema tidak cocok dengan ekstensi berkasnya" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Ekstensi berkas gambar tema di \"%(path)s\" tidak cocok dengan mime jenis \"%(mime)s\" yang sebenarnya" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "\"default_locale\" tidak memiliki pelokalan." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Ada \"_locales\", tetapi \"default_locale\" tidak ditemukan." ],
      "Unsupported image extension":[ null,
        "Ekstensi gambar tidak didukung" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikon harus salah satu dari JPG/JPEG, WebP, GIF, PNG, atau SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "Direktori bahasa kosong" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Berkas messages.json tidak ada dalam \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Kunci manifes tidak didukung oleh versi Firefox minimum yang dispesifikasikan" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Izin tidak didukung oleh versi Firefox minimum yang dispesifikasikan" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Kunci manifes tidak didukung oleh versi Firefox untuk Android minimum yang dispesifikasikan" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Izin tidak didukung oleh versi Firefox untuk Android minimum yang dispesifikasikan" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "Tipe izin tidak didukung." ],
      "The field is required.":[ null,
        "Bidang yang wajib diisi." ],
      "Unknown permission.":[ null,
        "Izin tidak dikenal." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Lihat https://mzl.la/1R1n1t0 (MDN Docs) untuk informasi lebih lanjut." ] } } }