module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"tr" },
      "Validation Summary:":[ null,
        "Doğrulama özeti:" ],
      Code:[ null,
        "Kod" ],
      Message:[ null,
        "Mesaj" ],
      Description:[ null,
        "Açıklama" ],
      File:[ null,
        "Dosya" ],
      Line:[ null,
        "Satır" ],
      Column:[ null,
        "Sütun" ],
      "Invalid nesting of selectors found":[ null,
        "Seçicilerin geçersiz gruplanması tespit edildi" ],
      "A CSS syntax error was encountered":[ null,
        "Bir CSS söz dizimi hatasıyla karşılaşıldı" ],
      "Your FTL is not valid.":[ null,
        "FTL geçerli değil." ],
      "Your FTL file could not be parsed.":[ null,
        "FTL dosyanız işlenemedi." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Eklenti Politikası gereğince uzak betikler kabul edilmemektedir." ],
      "Inline scripts blocked by default":[ null,
        "Satıriçi betikler varsayılan olarak engellenmiştir" ],
      "Unadvised 3rd-party JS library":[ null,
        "Önerilmeyen üçüncü taraf JS kütüphanesi" ],
      "Known JS library detected":[ null,
        "Bilindik JS kütüphanesi algılandı" ],
      "{{api}} is not supported":[ null,
        "{{api}} desteklenmiyor" ],
      "This API has not been implemented by Firefox.":[ null,
        "Bu API Firefox'ta kullanılamamaktadır." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" Manifest Version 3'te kaldırılmıştır (`manifest_version` özelliği)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} kullanımdan kaldırıldı" ],
      "This API has been deprecated by Firefox.":[ null,
        "Bu API, Firefox tarafından kullanımdan kaldırıldı." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" kullanımdan kaldırıldı veya mevcut değil" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` truthy dördüncü argüman ile çağrıldı." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} Firefox'un {{minVersion}}. sürümünde desteklenmiyor" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Bu API, belirtilen minimum Firefox sürümünde kullanılamamaktadır" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} Android için Firefox'un {{minVersion}}. sürümünde desteklenmiyor" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Bu API, belirtilen minimum Android için Firefox sürümünde kullanılamamaktadır" ],
      "Content script file could not be found.":[ null,
        "İçerik betik dosyası bulunamadı." ],
      "Content script file could not be found":[ null,
        "İçerik betik dosyası bulunamadı" ],
      "Content script file name should not be empty.":[ null,
        "İçerik betiği adı boş bırakılmamalıdır." ],
      "Content script file name should not be empty":[ null,
        "İçerik betiği adı boş bırakılmamalıdır" ],
      "JavaScript syntax error":[ null,
        "JavaScript söz dizimi hatası" ],
      "Unexpected global passed as an argument":[ null,
        "Argüman olarak beklenmeyen global aktarıldı" ],
      "Use of document.write strongly discouraged.":[ null,
        "document.write kullanımı kesinlikle önerilmez." ],
      "Banned 3rd-party JS library":[ null,
        "Yasaklı üçüncü taraf JS kütüphanesi" ],
      "Your JSON contains block comments.":[ null,
        "JSON dosyanız blok yorumlar çeriyor." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "JSON dosyalarında yinelenen anahtarlara izin verilmemektedir." ],
      "Your JSON is not valid.":[ null,
        "JSON geçerli değil." ],
      "Your JSON file could not be parsed.":[ null,
        "JSON dosyanız ayrıştırılamadı." ],
      "Reserved filename found.":[ null,
        "Rezerve dosya adı bulundu." ],
      "We were unable to decompress the zip file.":[ null,
        "Zip dosyasını açamadık." ],
      "manifest.json was not found":[ null,
        "manifest.json dosyası bulunamadı" ],
      "File is too large to parse.":[ null,
        "Dosya ayrıştırma için çok büyük." ],
      "Hidden file flagged":[ null,
        "Gizli dosya işaretlendi" ],
      "Flagged filename found":[ null,
        "İşaretli dosya adı bulundu" ],
      "Flagged file extensions found":[ null,
        "İşaretli dosya uzantıları bulundu" ],
      "Package contains duplicate entries":[ null,
        "Paket yinelenen girdiler içermektedir" ],
      "Flagged file type found":[ null,
        "İşaretlenen dosya türü bulundu" ],
      "Package already signed":[ null,
        "Paket zaten imzanmış" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox eklentilerinin sanal para kazıcıları çalıştırmasına izin verilmemektedir." ],
      "String name is reserved for a predefined message":[ null,
        "Dizge adı önceden tanımlanmış bir iletiye ayrılmış" ],
      "Placeholder for message is missing":[ null,
        "Mesaj için yer tutucu eksik" ],
      "A placeholder used in the message is not defined.":[ null,
        "Mesajda kullanılan bir yer tutucu tanımlı değil." ],
      "Placeholder name contains invalid characters":[ null,
        "Yer tutucu adında geçersiz karakterler var" ],
      "Placeholder is missing the content property":[ null,
        "Yer tutucuda content özelliği eksik" ],
      "Translation string is missing the message property":[ null,
        "Çeviri dizgesinin message özelliği eksik" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Bir dizge için \"message\" mesaj özelliği ayarlanmadı (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Daha fazla bilgi için https://mzl.la/2Qn0fWC (MDN Docs) sayfasına bakın." ],
      "Invalid host permission.":[ null,
        "Geçersiz sunucu izni." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "manifest.json dosyasındaki \"manifest_version\" geçerli bir değer değil" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Daha fazla bilgi için https://mzl.la/20PenXl (MDN Docs) sayfasına bakın." ],
      "The \"name\" property must be a string.":[ null,
        "\"name\" özelliği bir string olmalıdır." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Daha fazla bilgi için http://mzl.la/1STmr48 (MDN Docs) sayfasına bakın." ],
      "The \"version\" property must be a string.":[ null,
        "\"version\" özelliği string türünde olmalıdır." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Daha fazla bilgi için http://mzl.la/1kXIADa (MDN Dökümanları) adresini ziyaret edin." ],
      "The field is invalid.":[ null,
        "Alan geçersiz." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "\"version\" özelliği Firefox'a özgü bir biçim kullanıyor." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Daha fazla bilgi için https://mzl.la/1ZOhoEN (MDN Docs) adresine bakabilirsiniz." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" kabul edilmemektedir." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "\"update_url\" özelliği Firefox tarafından kullanılmıyor." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" gerekli değil." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Manifest dosyasında tanımlanan bir simge paketin içinde bulunamadı." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Simge \"%(path)s\" yolunda bulunamadı." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Manifest dosyasında tanımlanan bir arka plan betiği bulunamadı." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Manifest dosyasında tanımlanan bir arka plan sayfası bulunamadı." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Arka plan betiği \"%(path)s\" yolunda bulunamadı." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Arka plan sayfası \"%(path)s\" yolunda bulunamadı." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Manifest dosyasında tanımlanan bir içerik betiği bulunamadı." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Manifest dosyasında tanımlanan bir içerik betiği css dosyası bulunamadı." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Bildirgede tanımlanan içerik betiği \"%(path)s\" yolunda bulunamadı." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Bildirgede tanımlanan içerik betiği css dosyası \"%(path)s\" yolunda bulunamadı." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Manifest dosyasında tanımlanan bir sözlük dosyası bulunamadı." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Manifest dosyasında tanımlanan sözlük dosyası \"%(path)s\" konumunda bulunamadı." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifest birden fazla sözlük içeriyor." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Manifest'te birden fazla sözlük tanımlandı. Bu durum desteklenmiyor." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifest'te dictionaries nesnesi var ama nesne boş." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Manifest'te dictionaries nesnesi tanımlanmış ama nesne boş." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifest bir sözlük içeriyor ancak id özelliği içermiyor." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Manifest'te bir sözlük bulundu, ancak id'si yoktu." ],
      "Forbidden content found in add-on.":[ null,
        "Eklentide yasaklı içerik bulundu." ],
      "This add-on contains forbidden content.":[ null,
        "Bu eklentide yasaklı içerik bulunuyor." ],
      "Icons must be square.":[ null,
        "Simgeler kare olmalıdır." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "\"%(path)s\" yolundaki simge kare olmalıdır." ],
      "The size of the icon does not match the manifest.":[ null,
        "Simge dosyasının boyutu manifest dosyasındaki ile eşleşmiyor." ],
      "Corrupt image file":[ null,
        "Hasarlı resim dosyası" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "\"%(path)s\" yolundaki beklenilen simge dosyası bozuk." ],
      "This property has been deprecated.":[ null,
        "Bu özellik kullanımdan kaldırıldı." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Bu tema LWT alias'ı Firefox 70'te kaldırılmıştır." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Daha fazla bilgi için https://mzl.la/2T11Lkc (MDN Docs) sayfasına bakın." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "\"%(type)s\" için tema görseli \"%(path)s\" konumunda bulunamadı" ],
      "Corrupted theme image file":[ null,
        "Bozuk tema resim dosyası" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "\"%(path)s\" adresindeki tema resmi dosyası bozuk" ],
      "Theme image file has an unsupported file extension":[ null,
        "Tema resmi dosyası desteklenmeyen bir dosya uzantısına sahip" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "\"%(path)s\" adresindeki tema resmi desteklenmeyen bir dosya uzantısına sahip" ],
      "Theme image file has an unsupported mime type":[ null,
        "Tema resmi desteklenmeyen bir mime türüne sahip" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "\"%(path)s\" adresindeki tema resmi desteklenmeyen \"%(mime)s\" mime türüne sahip" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Tema resmi dosyasının mime türü, dosya uzantısıyla eşleşmiyor" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "\"%(path)s\" konumundaki tema resmi dosya uzantısı gerçek \"%(mime)s\" mime türüyle eşleşmiyor" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "\"default_locale\" değerinde yerelleştirmeler eksik." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" eksik fakat \"_locales\" mevcut." ],
      "Unsupported image extension":[ null,
        "Desteklenmeyen resim uzantısı" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Simgeler JPG/JPEG, WebP, GIF, PNG ya da SVG türlerinden biri olmalıdır." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "\"applications\" özelliği \"browser_spec_settings\" özelliği tarafından geçersiz kılındı" ],
      "Empty language directory":[ null,
        "Dil klasörü boş" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "\"%(path)s\" klasöründe messages.json dosyası eksik" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifest anahtarı belirtilen minimum Firefox sürümü tarafından desteklenmiyor" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Bu İzin, belirtilen minimum Firefox sürümü tarafından desteklenmiyor" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifest anahtarı, Android için belirtilen minimum Firefox sürümü tarafından desteklenmiyor" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Bu izin, Android için belirtilen minimum Firefox sürümü tarafından desteklenmiyor" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "\"addons.mozilla.org\" adresine bağlantı veremezsiniz" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "\"addons.mozilla.org\" adresine yönlendiren bağlantıları ana sayfa olarak kullanamazsınız" ],
      "The permission type is unsupported.":[ null,
        "İzin türü desteklenmemektedir." ],
      "The field is required.":[ null,
        "Bu alan zorunludur." ],
      "Unknown permission.":[ null,
        "Bilinmeyen izin." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Daha fazla bilgi için https://mzl.la/1R1n1t0 (MDN Docs) sayfasına bakın." ] } } }