module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=1; plural=0;",
        lang:"ja" },
      "Validation Summary:":[ null,
        "検証結果:" ],
      Code:[ null,
        "コード" ],
      Message:[ null,
        "メッセージ" ],
      Description:[ null,
        "説明" ],
      File:[ null,
        "ファイル" ],
      Line:[ null,
        "行" ],
      Column:[ null,
        "列" ],
      "Invalid nesting of selectors found":[ null,
        "不正な入れ子のセレクターが見つかりました" ],
      "A CSS syntax error was encountered":[ null,
        "CSS 構文エラーが見つかりました" ],
      "Your FTL is not valid.":[ null,
        "FTL が正しくありません。" ],
      "Your FTL file could not be parsed.":[ null,
        "FTL ファイルを解析できませんでした。" ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "アドオンポリシーに従いリモートスクリプトは許可されていません。" ],
      "Inline scripts blocked by default":[ null,
        "インラインスクリプトは既定でブロックされます" ],
      "Unadvised 3rd-party JS library":[ null,
        "不明なサードパーティ JS ライブラリ" ],
      "Known JS library detected":[ null,
        "既知の JS ライブラリーが検出されました" ],
      "{{api}} is not supported":[ null,
        "{{api}} はサポートされていません" ],
      "This API has not been implemented by Firefox.":[ null,
        "この API は Firefox に実装されていません。" ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" はマニフェストバージョン 3 (`manifest_version` プロパティ) で削除されました" ],
      "{{api}} is deprecated":[ null,
        "{{api}} は非推奨です" ],
      "This API has been deprecated by Firefox.":[ null,
        "この API は Firefox で推奨されていません。" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" は非推奨または未実装です" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener の第 4 引数が true と評価される値となっています。" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} は Firefox バージョン {{minVersion}} でサポートされていません" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "この API は指定された最低バージョンの Firefox に実装されていません" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} は Android 版 Firefox バージョン {{minVersion}} でサポートされていません" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "この API は指定された最低バージョンの Android 版 Firefox に実装されていません" ],
      "Content script file could not be found.":[ null,
        "コンテンツスクリプトファイルが見つかりませんでした。" ],
      "Content script file could not be found":[ null,
        "コンテンツスクリプトファイルが見つかりませんでした" ],
      "Content script file name should not be empty.":[ null,
        "コンテンツスクリプトファイル名は空欄にできません。" ],
      "Content script file name should not be empty":[ null,
        "コンテンツスクリプトファイル名は空欄にできません" ],
      "JavaScript syntax error":[ null,
        "JavaScript 構文エラー" ],
      "Unexpected global passed as an argument":[ null,
        "予期せぬグローバル変数が引数として渡されています" ],
      "Use of document.write strongly discouraged.":[ null,
        "document.write の使用は避けてください。" ],
      "Banned 3rd-party JS library":[ null,
        "禁止されているサードパーティ JS ライブラリー" ],
      "Your JSON contains block comments.":[ null,
        "JSON にブロックコメントが含まれています。" ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "JSON ファイルには重複するキーを含められません。" ],
      "Your JSON is not valid.":[ null,
        "JSON の形式が正しくありません。" ],
      "Your JSON file could not be parsed.":[ null,
        "JSON ファイルを解析できませんでした。" ],
      "Reserved filename found.":[ null,
        "予約済みのファイル名が見つかりました。" ],
      "We were unable to decompress the zip file.":[ null,
        "zip ファイルを展開できませんでした。" ],
      "manifest.json was not found":[ null,
        "manifest.json が見つかりませんでした" ],
      "File is too large to parse.":[ null,
        "ファイルサイズが大きすぎるため解析できません。" ],
      "Hidden file flagged":[ null,
        "隠しファイルが特定されました" ],
      "Flagged filename found":[ null,
        "特定のファイル名が確認されました" ],
      "Flagged file extensions found":[ null,
        "特定のファイル拡張子が確認されました" ],
      "Package contains duplicate entries":[ null,
        "パッケージに重複したエントリーが含まれています" ],
      "Flagged file type found":[ null,
        "特定のファイル形式が確認されました" ],
      "Package already signed":[ null,
        "パッケージはすでに署名されています" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox アドオンで仮想通貨のマイニングを行うことは許可されていません。" ],
      "String name is reserved for a predefined message":[ null,
        "文字列名が定義済みメッセージ用に予約されています" ],
      "Placeholder for message is missing":[ null,
        "メッセージのプレースホルダーが見当たりません" ],
      "A placeholder used in the message is not defined.":[ null,
        "メッセージ内で使用されているプレースホルダーが定義されていません。" ],
      "Placeholder name contains invalid characters":[ null,
        "プレースホルダー名に不正な文字が含まれています" ],
      "Placeholder is missing the content property":[ null,
        "プレースホルダーにコンテンツプロパティが含まれていません" ],
      "Translation string is missing the message property":[ null,
        "翻訳メッセージにメッセージプロパティが含まれていません" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "文字列に「message」メッセージプロパティが設定されていません。(https://mzl.la/2DSBTjA)" ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "詳しくは https://mzl.la/2Qn0fWC (MDN Docs) をご覧ください。" ],
      "Invalid host permission.":[ null,
        "無効なホスト権限です。" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "manifest.json 内の「manifest_version」の値が不正です" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "詳しくは https://mzl.la/20PenXl (MDN Docs) をご覧ください。" ],
      "The \"name\" property must be a string.":[ null,
        "「name」プロパティは文字列でなければなりません。" ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "詳しくは http://mzl.la/1STmr48 (MDN Docs) をご覧ください。" ],
      "The \"version\" property must be a string.":[ null,
        "「version」プロパティは文字列でなければなりません。" ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "詳しくは http://mzl.la/1kXIADa (MDN Docs) をご覧ください。" ],
      "The field is invalid.":[ null,
        "項目が無効です。" ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "「version」プロパティに Firefox 固有の形式が採用されています。" ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "詳しい情報は、https://mzl.la/1ZOhoEN (MDN Docs) をご覧ください。" ],
      "\"update_url\" is not allowed.":[ null,
        "「update_url」は使用できません。" ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Firefox では「update_url」プロパティは使われていません。" ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" は必須ではありません。" ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "manifest で定義されたアイコンがパッケージ内に見つかりませんでした。" ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "アイコンが \"%(path)s\" に見つかりませんでした。" ],
      "A background script defined in the manifest could not be found.":[ null,
        "manifest で定義されたバックグラウンドスクリプトが見つかりませんでした。" ],
      "A background page defined in the manifest could not be found.":[ null,
        "manifest で定義されたバックグラウンドページが見つかりませんでした。" ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "バックグラウンドスクリプトが \"%(path)s\" に見つかりませんでした。" ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "バックグラウンドページが \"%(path)s\" に見つかりませんでした。" ],
      "A content script defined in the manifest could not be found.":[ null,
        "manifest で定義されたコンテンツスクリプトが見つかりませんでした。" ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "manifest で定義されたコンテンツスクリプト CSS ファイルが見つかりませんでした。" ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "マニフェストで定義されているコンテンツスクリプトが「%(path)s」に見つかりませんでした。" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "マニフェストで定義されているコンテンツスクリプト CSS ファイルが「%(path)s」に見つかりませんでした。" ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "manifest で定義された辞書ファイルが見つかりませんでした。" ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "manifest で定義された辞書ファイルが「%(path)s」に見つかりませんでした。" ],
      "The manifest contains multiple dictionaries.":[ null,
        "manifest に複数の辞書が含まれています。" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "manifest で複数の辞書が定義されていましたが、これはサポートされていません。" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "manifest に辞書オブジェクトが含まれていますが、中身が空です。" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "manifest で辞書オブジェクトが定義されていましたが、中身が空でした。" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "manifest に辞書が含まれていますが、id プロパティがありません。" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "manifest に辞書が見つかりましたが、id が設定されていませんでした。" ],
      "Forbidden content found in add-on.":[ null,
        "アドオン内に禁止されているコンテンツが見つかりました。" ],
      "This add-on contains forbidden content.":[ null,
        "このアドオンには禁止されているコンテンツが含まれています。" ],
      "Icons must be square.":[ null,
        "アイコンは正方形でなければなりません。" ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "「%(path)s」にあるアイコンは正方形でなければなりません。" ],
      "The size of the icon does not match the manifest.":[ null,
        "アイコンのサイズがマニフェストと一致しません。" ],
      "Corrupt image file":[ null,
        "壊れた画像ファイル" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "「%(path)s」にあると期待されるアイコンファイルが壊れています" ],
      "This property has been deprecated.":[ null,
        "このプロパティは推奨されていません。" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "このテーマ LWT エイリアスは Firefox 70 で削除されました。" ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "詳しくは https://mzl.la/2T11Lkc (MDN Docs) をご覧ください。" ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "「%(type)s」のテーマ画像が「%(path)s」に見つかりませんでした" ],
      "Corrupted theme image file":[ null,
        "壊れたテーマ画像ファイル" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "「%(path)s」にあるテーマ画像ファイルが壊れています" ],
      "Theme image file has an unsupported file extension":[ null,
        "テーマ画像ファイルのファイル拡張子はサポートされていません" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "「%(path)s」のテーマ画像ファイルのファイル拡張子はサポートされていません" ],
      "Theme image file has an unsupported mime type":[ null,
        "テーマ画像ファイルの MIME タイプはサポートされていません" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "「%(path)s」のテーマ画像ファイルの MIME タイプ「%(mime)s」はサポートされていません" ],
      "Theme image file mime type does not match its file extension":[ null,
        "テーマ画像ファイルの MIME タイプがファイル拡張子と一致しません" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "「%(path)s」のテーマ画像ファイルの拡張子が実際の MIME タイプ「%(mime)s」と一致しません" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "「default_locale」でロケールが定義されていません。" ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "「default_locale」が見当たらない一方で「_locales」は存在します" ],
      "Unsupported image extension":[ null,
        "非対応画像拡張子" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "アイコンは、JPG/JPEG、WebP、GIF、PNG あるいは SVG のいずれかでなければなりません。" ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "\"applications\" プロパティは \"browser_specific_settings\" プロパティによって上書きされます" ],
      "Empty language directory":[ null,
        "空の言語ディレクトリー" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "messages.json が「%(path)s」に存在しません" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "manifest キーは指定された Firefox の最低バージョンでサポートされていません" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "許可設定は指定された Firefox の最低バージョンでサポートされていません" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "manifest キーは指定された Android 版 Firefox の最低バージョンでサポートされていません" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "許可設定は指定された Android 版 Firefox の最低バージョンでサポートされていません" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "\"addons.mozilla.org\" へのリンクは許可されていません" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "\"addons.mozilla.org\" へのリンクをホームページに使用することは許可されていません" ],
      "The permission type is unsupported.":[ null,
        "この許可タイプには対応していません。" ],
      "The field is required.":[ null,
        "この項目は必須です。" ],
      "Unknown permission.":[ null,
        "不明な許可設定です。" ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "詳しくは https://mzl.la/1R1n1t0 (MDN Docs) をご覧ください。" ] } } }