module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3);",
        lang:"hsb" },
      "Validation Summary:":[ null,
        "Přepruwowanske zhornjenje:" ],
      Code:[ null,
        "Kod" ],
      Message:[ null,
        "Powěsć" ],
      Description:[ null,
        "Wopisanje" ],
      File:[ null,
        "Dataja" ],
      Line:[ null,
        "Linka" ],
      Column:[ null,
        "Špalta" ],
      "Invalid nesting of selectors found":[ null,
        "Njepłaćiwe zakašćikowanje selektorow namakane" ],
      "A CSS syntax error was encountered":[ null,
        "Syntaksowy zmylk CSS je wustupił" ],
      "Your FTL is not valid.":[ null,
        "Waš FTL płaćiwy njeje." ],
      "Your FTL file could not be parsed.":[ null,
        "Waša FTL-dataja njeda so parsować." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Zdalene skripty po prawidłach přidatkow dowolene njejsu." ],
      "Inline scripts blocked by default":[ null,
        "Skripty inline so po standardźe blokuja" ],
      "Unadvised 3rd-party JS library":[ null,
        "Njeznata JS-biblioteka třećeho poskićowarja" ],
      "Known JS library detected":[ null,
        "Znata JS-biblioteka namakana" ],
      "{{api}} is not supported":[ null,
        "{{api}} so njepodpěruje" ],
      "This API has not been implemented by Firefox.":[ null,
        "Tutón API njeje so přez Firefox implementował." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "„{{api}}“ je so we wersiji 3 manifest wotstronił (kajkosć `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} je zestarjeny" ],
      "This API has been deprecated by Firefox.":[ null,
        "Tutón API so přez Firefox hižo njepodpěruje." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "„{{api}}“ so hižo njepodpěruje abo je njeimplementowany" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` wołany z truthy jako štwórty argument." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} so we wersiji {{minVersion}} Firefox njepodpěruje" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Tutón API njeje so přez podatu minimalnu wersiju Firefox implementował" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} so we wersiji {{minVersion}} Firefox za Android njepodpěruje" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Tutón API njeje so přez podatu minimalnu wersiju Firefox za Android implementował" ],
      "Content script file could not be found.":[ null,
        "Wobsahowa skriptowa dataja njeda so namakać." ],
      "Content script file could not be found":[ null,
        "Wobsahowa skriptowa dataja njeda so namakać" ],
      "Content script file name should not be empty.":[ null,
        "Mjeno wobsahoweje skriptoweje dataje njeměło prózdne być." ],
      "Content script file name should not be empty":[ null,
        "Mjeno wobsahoweje skriptoweje dataje njeměło prózdne być" ],
      "JavaScript syntax error":[ null,
        "Syntaksowy zmylk JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Njewočakowana globala je so jako argument přepodała" ],
      "Use of document.write strongly discouraged.":[ null,
        "Wot wužiwanja document.write so wuraznje wotradźuje." ],
      "Banned 3rd-party JS library":[ null,
        "JS-biblioteka třećeho poskićowarja zakazana" ],
      "Your JSON contains block comments.":[ null,
        "Waš JSON blokowe komentary wobsahuje." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Dwójne kluče w JSON-datajach dowolene njejsu." ],
      "Your JSON is not valid.":[ null,
        "Waš JSON płaćiwy njeje." ],
      "Your JSON file could not be parsed.":[ null,
        "Waša JSON-dataja njeda so parsować." ],
      "Reserved filename found.":[ null,
        "Rezerwowane datajowe mjeno namakane." ],
      "We were unable to decompress the zip file.":[ null,
        "Njemóžachmy zip-dataju rozpakować." ],
      "manifest.json was not found":[ null,
        "manifest.json njeje so namakał" ],
      "File is too large to parse.":[ null,
        "Dataja je přewulka za parsowanje." ],
      "Hidden file flagged":[ null,
        "Schowana dataja woznamjenjena" ],
      "Flagged filename found":[ null,
        "Woznamjenjene datajowe mjeno namakane" ],
      "Flagged file extensions found":[ null,
        "Woznamjenjene datajowe kóncowki namakane" ],
      "Package contains duplicate entries":[ null,
        "Pakćik dwójne zapiski wobsahuje" ],
      "Flagged file type found":[ null,
        "Woznamjenjeny datajowy typ namakany" ],
      "Package already signed":[ null,
        "Pakćik je hižo signowany" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Přidatki Firefox njesmědźa pjenjezykopaki wuwjesć." ],
      "String name is reserved for a predefined message":[ null,
        "Mjeno znamješkoweho rjećazka je wuměnjene za předdefinowanu zdźělenku" ],
      "Placeholder for message is missing":[ null,
        "Zastupowacy symbol za zdźělenku faluje" ],
      "A placeholder used in the message is not defined.":[ null,
        "Zastupowacy symbol, kotryž so w zdźělence wužiwa, njeje definowany." ],
      "Placeholder name contains invalid characters":[ null,
        "Mjeno zastupowaceho symbola njepłaćiwe znamješka wobsahuje" ],
      "Placeholder is missing the content property":[ null,
        "Zastupowacemu symbolej kajkosć content faluje" ],
      "Translation string is missing the message property":[ null,
        "Přełožowanskemu znamješkowemu rjećazkej kajkosć message faluje" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Zdźělenska kajkosć \"message\" njeje za znamješkowy rjećazk nastajena (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Hlejće https://mzl.la/2Qn0fWC (MDN Docs) za dalše informacije." ],
      "Invalid host permission.":[ null,
        "Njepłaćiwe hostowe prawo" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" w manifest.json płaćiwa hódnota njeje" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Hlejće https://mzl.la/20PenXl (MDN Docs) za dalše informacije." ],
      "The \"name\" property must be a string.":[ null,
        "Kajkosć \"name\" dyrbi znamješkowy rjećazk być." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Hlejće http://mzl.la/1STmr48 (MDN Docs) za dalše informacije." ],
      "The \"version\" property must be a string.":[ null,
        "Kajkosć \"version\" dyrbi znamješkowy rjećazk być." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Hlejće http://mzl.la/1kXIADa (MDN Docs) za dalše informacije." ],
      "The field is invalid.":[ null,
        "Polo je njepłaćiwe." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Kajkosć \"version\" format wužiwa, kotryž je specifiski za Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Hlejće https://mzl.la/1ZOhoEN (MDN Docs) za dalše informacije." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" dowoleny njeje." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Kajkosć \"update_url\" so wot Firefox njewužiwa." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" trěbny njeje." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Symbol, kotryž je so w manifesće definował, njeda so w pakćiku namakać." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Symbol njeda so na \"%(path)s\" namakać." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Pozadkowy skript, kotryž je so w manifesće definował, njeda so namakać." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Pozadkowa strona, kotraž je so w manifesće definowała, njeda so namakać." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Pozadkowy skript njeda so na \"%(path)s\" namakać." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Pozadkowa strona njeda so na \"%(path)s\" namakać." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Wobsahowy skript, kotryž je so w manifesće definował, njeda so namakać." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "CSS-dataja wobsahoweho skripta, kotraž je so w manifesće definowała, njeda so namakać." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Wobsahowy skript, kotryž je so w manifesće definował, njeda so na \"%(path)s\" namakać." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "CSS-dataja wobsahoweho skripta, kotraž je so w manifesće definowała, njeda so na \"%(path)s\" namakać." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Słownikowa dataja, kotraž je so w manifesće definowała, njeda so namakać." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Słownikowa dataja, kotraž je so w manifesće definowała, njeda so na \"%(path)s\" namakać." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifest wjacore słowniki wobsahuje." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Wjacore słowniki su so w manifesće definowali, štož so njepodpěruje." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifest słownikowy objekt wobsahuje, ale je prózdny." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Słownikowy objekt je so w manifesće definował, ale je prózdny był." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifest słownik wobsahuje, ale nic kajkosć ID." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Słownik je so w manifesće namakał, ale njeje so žadyn ID postajił." ],
      "Forbidden content found in add-on.":[ null,
        "Zakazany wobsah w přidatku namakany." ],
      "This add-on contains forbidden content.":[ null,
        "Tutón přidatk zakazany wobsah wobsahuje." ],
      "Icons must be square.":[ null,
        "Symbole dyrbja kwadratiske być." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Symbol na \"%(path)s\" dyrbi kwadratiski być." ],
      "The size of the icon does not match the manifest.":[ null,
        "Wulkosć symbola manifestej njewotpowěduje." ],
      "Corrupt image file":[ null,
        "Wobškodźena wobrazowa dataja" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Wočakowana symbolowa dataja na \"%(path)s\" je wobškodźena" ],
      "This property has been deprecated.":[ null,
        "Tuta kajkosć so hižo njepodpěruje." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Alias LWT tuteje drasty je so w Firefox 70 wotstronił." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Hlejće https://mzl.la/2T11Lkc (MDN Docs) za dalše informacije." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Drastowy wobraz za \"%(type)s\" njeda so na \"%(path)s\" namakać" ],
      "Corrupted theme image file":[ null,
        "Wobškodźena wobrazowa dataja drasty" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Wobrazowa dataja drasty na \"%(path)s\" je wobškodźena" ],
      "Theme image file has an unsupported file extension":[ null,
        "Wobrazowa dataja drasty ma datajowu kóncowku, kotraž so njepodpěruje" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Wobrazowa dataja drasty na \"%(path)s\" ma datajowu kóncowku, kotraž so njepodpěruje" ],
      "Theme image file has an unsupported mime type":[ null,
        "Wobrazowa dataja drasty ma typ MIME, kotryž so njepodpěruje" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Wobrazowa dataja drasty na \"%(path)s\" ma typ MIME \"%(mime)s\", kotryž so njepodpěruje" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Typ MIME wobrazoweje dataje drasty jeje datajowej kóncowce njewotpowěduje" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Kóncowka wobrazoweje dataje drasty na \"%(path)s\" jeje woprawdźitemu typej MIME \"%(mime)s\" njewotpowěduje" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "W \"default_locale\" lokalizacije faluja." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" faluje, ale \"_locales\" eksistuje." ],
      "Unsupported image extension":[ null,
        "Kóncowka wobrazoweje dataje so njepodpěruje" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Symbole měli dataje typa JPG/JPEG, WebP, GIF, PNG abo SVG być." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Kajkosć „applications“ je so přez kajkosć „browser_specific_settings“ přepisała" ],
      "Empty language directory":[ null,
        "Pródzny zapis rěčow" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Dataja messages.json w \"%(path)s\" faluje" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifestowy kluč so přez podatu minimalnu wersiju Firefox njepodpěruje" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Prawo so přez podatu minimalnu wersiju Firefox njepodpěruje" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifestowy kluč so přez podatu minimalnu wersiju Firefox za Android njepodpěruje" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Prawo so přez podatu minimalnu wersiju Firefox za Android njepodpěruje" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Wotkazowanje na „addons.mozilla.org“ dowolene njeje" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Wotkazy, kotrež na „addons.mozilla.org“ pokazuja, njesmědźa so za startowu stronu wužiwać." ],
      "The permission type is unsupported.":[ null,
        "Typ dowolnosće so njepodpěruje." ],
      "The field is required.":[ null,
        "Polo je trěbne." ],
      "Unknown permission.":[ null,
        "Njeznata dowolnosć." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Hlejće https://mzl.la/1R1n1t0 (MDN Docs) za dalše informacije." ] } } }