packages:
  - "packages/*"
  - "packages/examples/*"
  - "packages/benchmarks/*"
  - "packages/tsurlfilter/test/builders/*"

catalog:
  lodash-es: ^4.17.21
  '@types/lodash-es': ^4.17.12
  '@types/chrome': ^0.0.305
  tslib: ^2.8.1
  rollup-plugin-cleanup: ^3.2.1
  lint-staged: ^13.2.2
  coveralls: 3.1.1
  style-loader: ^3.3.1
  playwright: ^1.52.0
  css-loader: ^6.7.1
  chalk: 4.1.2
  '@types/react-dom': ^17.0.25
  '@types/react': ^17.0.80
  react: ^17.0.2
  react-dom: ^17.0.2
  vm-browserify: ^1.1.2
  stream-browserify: ^3.0.0
  eslint-webpack-plugin: ^3.2.0
  html-webpack-plugin: ^5.5.0
  crypto-browserify: ^3.12.0
  lru-cache: ^11.0.2
