packages:
  - "packages/*"
  - "packages/examples/*"
  - "packages/benchmarks/*"
  - "packages/tsurlfilter/test/builders/*"

# default catalog
catalog:
  '@adguard/assistant': ^4.3.75
  '@adguard/scriptlets': ^2.2.10
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-commonjs': ^28.0.1
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^15.3.0
  '@rollup/plugin-swc': ^0.4.0
  '@rollup/plugin-terser': ^0.4.4
  '@rollup/plugin-typescript': ^12.1.1
  '@swc-node/register': ^1.10.9
  '@swc/core': ^1.10.18
  '@types/archiver': ^6.0.2
  '@types/benchmark': ^2.1.5
  '@types/chrome': ^0.0.305
  '@types/fs-extra': ^11.0.4
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.14.0
  '@types/react': ^17.0.80
  '@types/react-dom': ^17.0.25
  '@types/webextension-polyfill': ^0.12.1
  '@typescript-eslint/eslint-plugin': ^7.5.0
  '@typescript-eslint/parser': ^7.5.0
  '@vitest/coverage-v8': 2.1.9
  '@vitest/expect': 2.1.9
  archiver: ^7.0.1
  axios: ^1.7.2
  benchmark: ^2.1.4
  bowser: 2.11.0
  chalk: 4.1.2
  clean-webpack-plugin: ^4.0.0
  commander: ^12.1.0
  copy-webpack-plugin: ^10.0.0
  core-js: ^3.33.3
  coveralls: 3.1.1
  cross-env: ^7.0.3
  crypto-browserify: ^3.12.0
  css-loader: ^6.7.1
  date-fns: ^4.1.0
  esbuild: ^0.19.12
  eslint: 8.57.1
  eslint-config-airbnb-base: 15.0.0
  eslint-config-airbnb-typescript: ^18.0.0
  eslint-plugin-import: ^2.29.0
  eslint-plugin-import-newlines: 1.4.0
  eslint-plugin-jsdoc: ^48.11.0
  eslint-webpack-plugin: ^3.2.0
  fs-extra: ^11.2.0
  html-webpack-plugin: ^5.5.0
  husky: ^9.1.7
  is-ip: 3.1.0
  lint-staged: ^13.2.2
  lodash-es: ^4.17.21
  lru-cache: ^11.0.2
  markdown-table: ^3.0.3
  markdownlint: ^0.37.4
  markdownlint-cli: ^0.44.0
  node-fetch: ^3.3.2
  os-name: ^6.0.0
  playwright: ^1.52.0
  react: ^17.0.2
  react-dom: ^17.0.2
  rimraf: ^6.0.1
  rollup: ^4.28.0
  rollup-plugin-cleanup: ^3.2.1
  rollup-plugin-dts: ^6.0.2
  rollup-plugin-node-externals: ^8.0.0
  stream-browserify: ^3.0.0
  style-loader: ^3.3.1
  swc-loader: ^0.2.3
  systeminformation: ^5.22.0
  terser: ^5.21.0
  tldts: ^5.7.112
  ts-morph: ^26.0.0
  tsd: ^0.32.0
  tslib: ^2.8.1
  tsx: ^4.19.3
  typescript: ^5.7.3
  vitest: ^2.1.9
  vm-browserify: ^1.1.2
  webextension-polyfill: 0.12.0
  webpack: ^5.64.2
  zod: 3.24.4

# named catalogs
catalogs:
  eslint9:
    eslint: ^9.8.0
