module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"de" },
      "Validation Summary:":[ null,
        "Validierungs-Zusammenfassung:" ],
      Code:[ null,
        "Quelltext" ],
      Message:[ null,
        "Nachricht" ],
      Description:[ null,
        "Beschreibung" ],
      File:[ null,
        "Datei" ],
      Line:[ null,
        "Zeile" ],
      Column:[ null,
        "Spalte" ],
      "Invalid nesting of selectors found":[ null,
        "Ungültige Schachtelung von Selektoren gefunden" ],
      "A CSS syntax error was encountered":[ null,
        "Ein CSS-Syntaxfehler ist aufgetreten" ],
      "Your FTL is not valid.":[ null,
        "Ihre FTL ist ungültig." ],
      "Your FTL file could not be parsed.":[ null,
        "Ihre FTL-Datei konnte nicht geparst werden." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Fremd-Skripte sind laut Add-on-Regeln nicht erlaubt." ],
      "Inline scripts blocked by default":[ null,
        "Inline-Skripte werden standardmäßig blockiert" ],
      "Unadvised 3rd-party JS library":[ null,
        "Unbekannte externe JS-Bibliothek" ],
      "Known JS library detected":[ null,
        "Bekannte JS-Bibliothek erkannt" ],
      "{{api}} is not supported":[ null,
        "{{api}} wird nicht unterstützt" ],
      "This API has not been implemented by Firefox.":[ null,
        "Diese API wurde von Firefox nicht implementiert." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "„{{api}}“ wurde in Manifest Version 3 entfernt (`manifest_version`-Eigenschaft)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} wird nicht mehr unterstützt" ],
      "This API has been deprecated by Firefox.":[ null,
        "Diese API wird von Firefox nicht mehr unterstützt." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "„{{api}}“ wird nicht mehr unterstützt oder ist nicht implementiert" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener ` mit truthy als viertes Argument aufgerufen." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} wird in Firefox-Version {{minVersion}} nicht unterstützt" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Diese API ist in der angegebenen Mindestversion von Firefox nicht implementiert" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} wird in Firefox-Version für Android {{minVersion}} nicht unterstützt" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Diese API ist in der angegebenen Mindestversion von Firefox für Android nicht implementiert" ],
      "Content script file could not be found.":[ null,
        "Inhalts-Skript-Datei wurde nicht gefunden." ],
      "Content script file could not be found":[ null,
        "Inhalts-Skript-Datei wurde nicht gefunden" ],
      "Content script file name should not be empty.":[ null,
        "Inhalts-Skript-Datei sollte nicht leer sein." ],
      "Content script file name should not be empty":[ null,
        "Inhalts-Skript-Datei sollte nicht leer sein" ],
      "JavaScript syntax error":[ null,
        "JavaScript-Syntaxfehler" ],
      "Unexpected global passed as an argument":[ null,
        "Argument wurde unerwartet als global weitergegeben" ],
      "Use of document.write strongly discouraged.":[ null,
        "Von der Verwendung von document.write wird dringend abgeraten." ],
      "Banned 3rd-party JS library":[ null,
        "Gesperrte externe JS-Bibliothek" ],
      "Your JSON contains block comments.":[ null,
        "Ihre JSON enthält Block-Kommentare." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Doppelte Schlüssel sind in JSON-Dateien nicht erlaubt." ],
      "Your JSON is not valid.":[ null,
        "Ihre JSON ist ungültig." ],
      "Your JSON file could not be parsed.":[ null,
        "Ihre JSON-Datei konnte nicht geparst werden." ],
      "Reserved filename found.":[ null,
        "Reservierter Dateiname gefunden." ],
      "We were unable to decompress the zip file.":[ null,
        "Wir konnten die ZIP-Datei nicht entpacken." ],
      "manifest.json was not found":[ null,
        "manifest.json wurde nicht gefunden" ],
      "File is too large to parse.":[ null,
        "Datei ist zu groß, um geparst zu werden." ],
      "Hidden file flagged":[ null,
        "Versteckte Datei gemeldet" ],
      "Flagged filename found":[ null,
        "Gemeldeter Dateiname gefunden" ],
      "Flagged file extensions found":[ null,
        "Gemeldete Dateiendungen gefunden" ],
      "Package contains duplicate entries":[ null,
        "Paket enthält doppelte Einträge" ],
      "Flagged file type found":[ null,
        "Gemeldeter Dateityp gefunden" ],
      "Package already signed":[ null,
        "Paket bereit signiert" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox-Add-ons dürfen keine Coin-Miner einsetzen." ],
      "String name is reserved for a predefined message":[ null,
        "Stringname ist für eine vordefinierte Nachricht reserviert" ],
      "Placeholder for message is missing":[ null,
        "Platzhalter für Nachricht fehlt" ],
      "A placeholder used in the message is not defined.":[ null,
        "Ein in der Nachricht verwendeter Platzhalter wurde nicht definiert." ],
      "Placeholder name contains invalid characters":[ null,
        "Platzhaltername enthält ungültige Zeichen" ],
      "Placeholder is missing the content property":[ null,
        "Platzhalter hat keine Inhaltseigenschaft" ],
      "Translation string is missing the message property":[ null,
        "Übersetzungsstring hat keine Nachrichteneigenschaft" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Für einen String wurde keine Nachrichteneigenschaft „message“ gesetzt (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Weitere Informationen finden Sie unter https://mzl.la/2Qn0fWC (MDN Docs)." ],
      "Invalid host permission.":[ null,
        "Ungültige Hostberechtigung." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "„manifest_version“ in der manifest.json ist kein gültiger Wert" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Weitere Informationen finden Sie unter https://mzl.la/20PenXl (MDN Docs)." ],
      "The \"name\" property must be a string.":[ null,
        "Die Eigenschaft „name“ muss ein String sein." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Weitere Informationen finden Sie unter http://mzl.la/1STmr48 (MDN Docs)." ],
      "The \"version\" property must be a string.":[ null,
        "Die Eigenschaft „version“ muss ein String sein." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Weitere Informationen finden Sie unter http://mzl.la/1kXIADa (MDN Docs)." ],
      "The field is invalid.":[ null,
        "Das Feld ist ungültig." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Die Eigenschaft „version“ verwendet ein Firefox-spezifisches Format." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Weitere Informationen finden Sie unter https://mzl.la/1ZOhoEN (MDN Docs)." ],
      "\"update_url\" is not allowed.":[ null,
        "„update_url“ ist nicht zulässig." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Die Eigenschaft „update_url“ wird von Firefox nicht verwendet." ],
      "\"strict_max_version\" not required.":[ null,
        "„strict_max_version“ nicht erforderlich." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Ein im Manifest definiertes Symbol konnte im Paket nicht gefunden werden." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Symbol konnte nicht unter „%(path)s“ gefunden werden." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Ein im Manifest definiertes Hintergrundskript wurde nicht gefunden." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Eine im Manifest definierte Hintergrundseite wurde nicht gefunden." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Hintergrundskript konnte nicht unter „%(path)s“ gefunden werden." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Hintergrundseite konnte nicht unter „%(path)s“ gefunden werden." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Ein im Manifest definiertes Inhaltsskript wurde nicht gefunden." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Eine im Manifest definierte Inhaltsskript-CSS-Datei wurde nicht gefunden." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Ein im Manifest definiertes Inhaltsskript konnte unter „%(path)s“ nicht gefunden werden." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Eine im Manifest definierte CSS-Datei konnte unter „%(path)s“ nicht gefunden werden." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Eine im Manifest definierte Wörterbuchdatei wurde nicht gefunden." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Eine im Manifest definierte Wörterbuchdatei wurde unter „%(path)s“ nicht gefunden." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Das Manifest enthält mehrere Wörterbücher." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Im Manifest wurden mehrere Wörterbücher definiert, was nicht unterstützt wird." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Das Manifest enthält ein Wörterbuch-Objekt, es ist jedoch leer." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Im Manifest wurde ein Wörterbuch-Objekt definiert, das jedoch leer war." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Das Manifest enthält ein Wörterbuch, aber keine ID-Eigenschaft." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Es wurde ein Wörterbuch im Manifest gefunden, aber es wurde keine ID festgelegt." ],
      "Forbidden content found in add-on.":[ null,
        "Verbotene Inhalte im Add-on gefunden." ],
      "This add-on contains forbidden content.":[ null,
        "Dieses Add-on enthält verbotene Inhalte." ],
      "Icons must be square.":[ null,
        "Symbole müssen quadratisch sein." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Symbol unter „%(path)s“ muss quadratisch sein." ],
      "The size of the icon does not match the manifest.":[ null,
        "Die Größe des Symbols passt nicht zum Manifest." ],
      "Corrupt image file":[ null,
        "Grafikdatei beschädigt" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Erwartete Symboldatei unter „%(path)s“ ist beschädigt" ],
      "This property has been deprecated.":[ null,
        "Diese Eigenschaft wird nicht mehr unterstützt." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Dieser Theme-LWT-Alias wurde in Firefox 70 entfernt." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Weitere Informationen finden Sie unter https://mzl.la/2T11Lkc (MDN Docs)." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Theme-Grafik für „%(type)s“ konnte nicht unter „%(path)s“ gefunden werden" ],
      "Corrupted theme image file":[ null,
        "Beschädigte Theme-Grafikdatei" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Die Theme-Grafikdatei unter „%(path)s“ ist beschädigt" ],
      "Theme image file has an unsupported file extension":[ null,
        "Die Theme-Grafikdatei hat eine nicht unterstützte Dateierweiterung" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Die Theme-Grafikdatei unter „%(path)s“ hat eine nicht unterstützte Dateierweiterung" ],
      "Theme image file has an unsupported mime type":[ null,
        "Die Theme-Grafikdatei hat einen nicht unterstützten MIME-Typ" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Die Theme-Grafikdatei unter „%(path)s“ hat einen nicht unterstützten MIME-Typ „%(mime)s“" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Der MIME-Typ der Grafikdatei stimmt nicht mit der Dateierweiterung überein" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Die Dateierweiterung der Theme-Grafikdatei unter „%(path)s“ stimmt nicht mit dem tatsächlichen MIME-Typ „%(mime)s“ überein" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "In der „default_locale“ fehlen Lokalisierungen." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Die „default_locale“ fehlt, aber „_locales“ existiert." ],
      "Unsupported image extension":[ null,
        "Nicht unterstützte Endung einer Grafikdatei" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Symbole sollten JPG/JPEG, WebP, GIF, PNG oder SVG sein." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "„applications“-Eigenschaft wird überschrieben durch „browser_specific_settings“-Eigenschaft" ],
      "Empty language directory":[ null,
        "Leeres Sprachverzeichnis" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Datei „messages.json“ fehlt in „%(path)s“" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifest-Schlüssel wird von der angegebenen Mindestversion von Firefox nicht unterstützt" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Die Berechtigung wird von der angegebenen Mindestversion von Firefox nicht unterstützt" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifest-Schlüssel wird von der angegebenen Mindestversion von Firefox für Android nicht unterstützt" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Die Berechtigung wird von der angegebenen Mindestversion von Firefox für Android nicht unterstützt" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Das Verlinken auf „addons.mozilla.org“ ist nicht erlaubt" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Links, die auf „addons.mozilla.org“ verweisen, dürfen nicht für die Homepage verwendet werden" ],
      "The permission type is unsupported.":[ null,
        "Der Erlaubnistyp wird nicht unterstützt." ],
      "The field is required.":[ null,
        "Dieses Feld ist erforderlich." ],
      "Unknown permission.":[ null,
        "Unbekannte Erlaubnis." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Weitere Informationen finden Sie unter https://mzl.la/1R1n1t0 (MDN Docs)." ] } } }