module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);",
        lang:"pl" },
      "Validation Summary:":[ null,
        "Podsumowanie sprawdzania poprawności:" ],
      Code:[ null,
        "Kod" ],
      Message:[ null,
        "Komunikat" ],
      Description:[ null,
        "Opis" ],
      File:[ null,
        "Plik" ],
      Line:[ null,
        "Wiersz" ],
      Column:[ null,
        "Kolumna" ],
      "Invalid nesting of selectors found":[ null,
        "Odnaleziono nieprawidłowe zagnieżdżenie selektorów" ],
      "A CSS syntax error was encountered":[ null,
        "Wystąpił błąd składni CSS" ],
      "Your FTL is not valid.":[ null,
        "Plik FTL jest nieprawidłowy." ],
      "Your FTL file could not be parsed.":[ null,
        "Nie można przetworzyć pliku FTL." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Zdalne skrypty są niedozwolone zgodnie z zasadami dodatków." ],
      "Inline scripts blocked by default":[ null,
        "Wstawione skrypty są domyślnie blokowane" ],
      "Unadvised 3rd-party JS library":[ null,
        "Niezalecana biblioteka JS od firmy trzeciej" ],
      "Known JS library detected":[ null,
        "Wykryto znaną bibliotekę JS" ],
      "{{api}} is not supported":[ null,
        "„{{api}}” jest nieobsługiwane" ],
      "This API has not been implemented by Firefox.":[ null,
        "To API nie zostało zaimplementowane w Firefoksie." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "„{{api}}” zostało usunięte w 3. wersji Manifestu (właściwość „manifest_version”)" ],
      "{{api}} is deprecated":[ null,
        "„{{api}}” jest przestarzałe" ],
      "This API has been deprecated by Firefox.":[ null,
        "To API zostało oznaczone jako przestarzałe w Firefoksie." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "„{{api}}” jest przestarzałe lub niezaimplementowane" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "„addEventListener`” zostało wywołane z czwartym parametrem o wartości „prawda”." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "„{{api}}” nie jest obsługiwane w wersji Firefoksa {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "To API nie jest zaimplementowane w podanej minimalnej wersji Firefoksa" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "„{{api}}” nie jest obsługiwane w wersji Firefoksa na Androida {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "To API nie jest zaimplementowane w podanej minimalnej wersji Firefoksa na Androida" ],
      "Content script file could not be found.":[ null,
        "Nie można odnaleźć pliku skryptu treści." ],
      "Content script file could not be found":[ null,
        "Nie można odnaleźć pliku skryptu treści" ],
      "Content script file name should not be empty.":[ null,
        "Nazwa pliku skryptu treści nie może być pusta." ],
      "Content script file name should not be empty":[ null,
        "Nazwa pliku skryptu treści nie może być pusta" ],
      "JavaScript syntax error":[ null,
        "Błąd składni języka JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Nieoczekiwane „global” przekazane jako parametr" ],
      "Use of document.write strongly discouraged.":[ null,
        "Użycie document.write jest mocno niezalecane." ],
      "Banned 3rd-party JS library":[ null,
        "Zabroniona biblioteka JS od firmy trzeciej" ],
      "Your JSON contains block comments.":[ null,
        "Kod JSON zawiera komentarze blokowe." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Podwójne klucze nie są dozwolone w plikach JSON." ],
      "Your JSON is not valid.":[ null,
        "Plik JSON jest nieprawidłowy." ],
      "Your JSON file could not be parsed.":[ null,
        "Nie można przetworzyć pliku JSON." ],
      "Reserved filename found.":[ null,
        "Odnaleziono zastrzeżoną nazwę pliku." ],
      "We were unable to decompress the zip file.":[ null,
        "Nie można zdekompresować pliku zip." ],
      "manifest.json was not found":[ null,
        "Nie odnaleziono pliku manifest.json" ],
      "File is too large to parse.":[ null,
        "Plik jest za duży, aby można go było przetworzyć." ],
      "Hidden file flagged":[ null,
        "Oznaczono ukryty plik" ],
      "Flagged filename found":[ null,
        "Odnaleziono oznaczoną nazwę pliku" ],
      "Flagged file extensions found":[ null,
        "Odnaleziono oznaczone rozszerzenia plików" ],
      "Package contains duplicate entries":[ null,
        "Pakiet zawiera podwójne wpisy" ],
      "Flagged file type found":[ null,
        "Odnaleziono oznaczony typ pliku" ],
      "Package already signed":[ null,
        "Pakiet jest już podpisany" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Dodatki do Firefoksa nie mogą zawierać kodu wydobywającego waluty." ],
      "String name is reserved for a predefined message":[ null,
        "Nazwa ciągu jest zastrzeżona dla wcześniej określonego komunikatu" ],
      "Placeholder for message is missing":[ null,
        "Brak elementu zastępczego dla komunikatu" ],
      "A placeholder used in the message is not defined.":[ null,
        "Element zastępczy w komunikacie nie jest określony." ],
      "Placeholder name contains invalid characters":[ null,
        "Nazwa elementu zastępczego zawiera nieprawidłowe znaki" ],
      "Placeholder is missing the content property":[ null,
        "W elemencie zastępczym brak właściwości treści" ],
      "Translation string is missing the message property":[ null,
        "W ciągu tłumaczenia brak właściwości komunikatu" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Dla ciągu nie jest ustawiona właściwość komunikatu „message” (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "https://mzl.la/2Qn0fWC (dokumentacja MDN) zawiera więcej informacji." ],
      "Invalid host permission.":[ null,
        "Nieprawidłowe uprawnienie hosta." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "„manifest_version” w pliku manifest.json jest nieprawidłową wartością" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "https://mzl.la/20PenXl (dokumentacja MDN) zawiera więcej informacji." ],
      "The \"name\" property must be a string.":[ null,
        "Właściwość „name” musi być ciągiem." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "http://mzl.la/1STmr48 (dokumentacja MDN) zawiera więcej informacji." ],
      "The \"version\" property must be a string.":[ null,
        "Właściwość „version” musi być ciągiem." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "http://mzl.la/1kXIADa (dokumentacja MDN) zawiera więcej informacji." ],
      "The field is invalid.":[ null,
        "Nieprawidłowe pole." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Właściwość „version” używa formatu specyficznego dla Firefoksa." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "https://mzl.la/1ZOhoEN (dokumentacja MDN) zawiera więcej informacji." ],
      "\"update_url\" is not allowed.":[ null,
        "„update_url” jest niedozwolone." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Właściwość „update_url” nie jest używana w Firefoksie." ],
      "\"strict_max_version\" not required.":[ null,
        "„strict_max_version” nie jest wymagane." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Nie można odnaleźć w pakiecie ikony określonej w manifeście." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Nie można odnaleźć ikony w „%(path)s”." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Nie można odnaleźć skryptu tła określonego w manifeście." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Nie można odnaleźć strony tła określonej w manifeście." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Nie można odnaleźć skryptu tła w „%(path)s”." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Nie można odnaleźć strony tła w „%(path)s”." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Nie można odnaleźć skryptu treści określonego w manifeście." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Nie można odnaleźć pliku CSS skryptu treści określonego w manifeście." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Nie można odnaleźć w „%(path)s” skryptu treści określonego w manifeście." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Nie można odnaleźć w „%(path)s” pliku CSS skryptu treści określonego w manifeście." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Nie można odnaleźć pliku słownika określonego w manifeście." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Nie można odnaleźć w „%(path)s” pliku słownika określonego w manifeście." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifest zawiera wiele słowników." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "W manifeście określono wiele słowników, co jest nieobsługiwane." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifest zawiera obiekt słowników, ale jest pusty." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "W manifeście określono obiekt słowników, ale był pusty." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifest zawiera słownik, ale nie ma właściwości identyfikatora." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "W manifeście odnaleziono słownik, ale nie było ustawionego identyfikatora." ],
      "Forbidden content found in add-on.":[ null,
        "W dodatku odnaleziono zabronione treści." ],
      "This add-on contains forbidden content.":[ null,
        "Ten dodatek zawiera zabronione treści." ],
      "Icons must be square.":[ null,
        "Ikona musi być kwadratowa." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikona w „%(path)s” musi być kwadratowa." ],
      "The size of the icon does not match the manifest.":[ null,
        "Wymiary ikony nie zgadzają się z manifestem." ],
      "Corrupt image file":[ null,
        "Uszkodzony plik obrazu" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Oczekiwany plik ikony w „%(path)s” jest uszkodzony" ],
      "This property has been deprecated.":[ null,
        "Ta właściwość została oznaczona jako przestarzała." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Ten alias LWT motywu został usunięty w Firefoksie 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "https://mzl.la/2T11Lkc (dokumentacja MDN) zawiera więcej informacji." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Nie można odnaleźć obrazu motywu dla „%(type)s” w „%(path)s”" ],
      "Corrupted theme image file":[ null,
        "Uszkodzony plik obrazu motywu" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Plik obrazu motywu w „%(path)s” jest uszkodzony" ],
      "Theme image file has an unsupported file extension":[ null,
        "Plik obrazu motywu ma nieobsługiwane rozszerzenie pliku" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Plik obrazu motywu w „%(path)s” ma nieobsługiwane rozszerzenie pliku" ],
      "Theme image file has an unsupported mime type":[ null,
        "Plik obrazu motywu ma nieobsługiwany typ MIME" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Plik obrazu motywu w „%(path)s” ma nieobsługiwany typ MIME „%(mime)s”" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Typ MIME pliku obrazu motywu nie zgadza się z jego rozszerzeniem" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Rozszerzenie pliku obrazu motywu w „%(path)s” nie zgadza się z jego rzeczywistym typem MIME „%(mime)s”" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "„default_locale” nie ma lokalizacji." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Brakuje „default_locale”, ale istnieje „_locales”." ],
      "Unsupported image extension":[ null,
        "Nieobsługiwane rozszerzenie obrazu" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikony muszą być typu JPG/JPEG, WebP, GIF, PNG lub SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Właściwość „applications” zastąpiona właściwością „browser_specific_settings”" ],
      "Empty language directory":[ null,
        "Pusty katalog języka" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "W „%(path)s” brakuje pliku messages.json" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Klucz manifestu nie jest obsługiwany przez podaną minimalną wersję Firefoksa" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Uprawnienie nie jest obsługiwane przez podaną minimalną wersję Firefoksa" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Klucz manifestu nie jest obsługiwany przez podaną minimalną wersję Firefoksa na Androida" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Uprawnienie nie jest obsługiwane przez podaną minimalną wersję Firefoksa na Androida" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Odsyłanie do „addons.mozilla.org” jest niedozwolone" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Odnośniki prowadzące do „addons.mozilla.org” nie mogą być używane jako strona domowa" ],
      "The permission type is unsupported.":[ null,
        "Typ uprawnienia jest nieobsługiwany." ],
      "The field is required.":[ null,
        "Pole jest wymagane." ],
      "Unknown permission.":[ null,
        "Nieznane uprawnienie." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "https://mzl.la/1R1n1t0 (dokumentacja MDN) zawiera więcej informacji." ] } } }