module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=1; plural=0;",
        lang:"th" },
      "Validation Summary:":[ null,
        "ข้อมูลสรุปการตรวจสอบความถูกต้อง:" ],
      Code:[ null,
        "โค้ด" ],
      Message:[ null,
        "ข้อความ" ],
      Description:[ null,
        "คำอธิบาย" ],
      File:[ null,
        "ไฟล์" ],
      Line:[ null,
        "บรรทัด" ],
      Column:[ null,
        "คอลัมน์" ],
      "Invalid nesting of selectors found":[ null,
        "พบการซ้อนกันของตัวเลือกที่ไม่ถูกต้อง" ],
      "A CSS syntax error was encountered":[ null,
        "พบข้อผิดพลาดไวยากรณ์ CSS" ],
      "Your FTL is not valid.":[ null,
        "FTL ของคุณไม่ถูกต้อง" ],
      "Your FTL file could not be parsed.":[ null,
        "ไม่สามารถแยกวิเคราะห์ไฟล์ FTL ของคุณ" ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "ไม่อนุญาตให้ใช้สคริปต์ระยะไกลตามที่ระบุไว้ในนโยบายส่วนเสริม" ],
      "Inline scripts blocked by default":[ null,
        "สคริปต์แบบอินไลน์ถูกบล็อกตามค่าเริ่มต้น" ],
      "Unadvised 3rd-party JS library":[ null,
        "ไลบรารี JS ของบุคคลที่สามที่ไม่แนะนำให้ใช้" ],
      "Known JS library detected":[ null,
        "ตรวจพบไลบรารี JS ที่รู้จัก" ],
      "{{api}} is not supported":[ null,
        "ไม่รองรับ {{api}}" ],
      "This API has not been implemented by Firefox.":[ null,
        "API นี้ยังไม่ได้ถูกนำมาใช้โดย Firefox" ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener ถูกเรียกโดยอาร์กิวเมนต์ที่ 4 ที่เป็นค่าจริง" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "ไม่รองรับ {{api}} ใน Firefox รุ่น {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "API นี้ไม่ได้ถูกนำมาใช้โดย Firefox รุ่นต่ำสุดที่ระบุ" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "ไม่รองรับ {{api}} ใน Firefox สำหรับ Android รุ่น {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "API นี้ไม่ได้ถูกนำมาใช้โดย Firefox สำหรับ Android รุ่นต่ำสุดที่ระบุ" ],
      "Content script file could not be found.":[ null,
        "ไม่พบไฟล์สคริปต์เนื้อหา" ],
      "Content script file could not be found":[ null,
        "ไม่พบไฟล์สคริปต์เนื้อหา" ],
      "Content script file name should not be empty.":[ null,
        "ชื่อไฟล์สคริปต์เนื้อหาไม่ควรว่างเปล่า" ],
      "Content script file name should not be empty":[ null,
        "ชื่อไฟล์สคริปต์เนื้อหาไม่ควรว่างเปล่า" ],
      "JavaScript syntax error":[ null,
        "ข้อผิดพลาดไวยากรณ์ JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "ตัวแปรส่วนกลางที่ไม่คาดคิดถูกส่งผ่านเป็นอาร์กิวเมนต์" ],
      "Use of document.write strongly discouraged.":[ null,
        "ไม่แนะนำให้ใช้ document.write เป็นอย่างยิ่ง" ],
      "Banned 3rd-party JS library":[ null,
        "ไลบรารี JS ของบุคคลที่สามที่ถูกห้าม" ],
      "Your JSON contains block comments.":[ null,
        "JSON ของคุณมีความคิดเห็นเกี่ยวกับการปิดกั้น" ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "ไม่อนุญาตให้ใช้คีย์ที่ซ้ำกันในไฟล์ JSON" ],
      "Your JSON is not valid.":[ null,
        "JSON ของคุณไม่ถูกต้อง" ],
      "Your JSON file could not be parsed.":[ null,
        "ไม่สามารถแยกวิเคราะห์ไฟล์ JSON ของคุณได้" ],
      "Reserved filename found.":[ null,
        "พบชื่อไฟล์ที่สงวนไว้" ],
      "We were unable to decompress the zip file.":[ null,
        "เราไม่สามารถคลายการบีบอัดไฟล์ zip ได้" ],
      "manifest.json was not found":[ null,
        "ไม่พบ manifest.json" ],
      "File is too large to parse.":[ null,
        "ไฟล์มีขนาดใหญ่เกินกว่าที่จะแยกวิเคราะห์ได้" ],
      "Hidden file flagged":[ null,
        "ตั้งค่าสถานะไฟล์ที่ซ่อนอยู่แล้ว" ],
      "Flagged filename found":[ null,
        "พบชื่อไฟล์ที่ถูกตั้งค่าสถานะ" ],
      "Flagged file extensions found":[ null,
        "พบนามสกุลไฟล์ที่ถูกตั้งค่าสถานะ" ],
      "Package contains duplicate entries":[ null,
        "แพ็คเกจมีรายการที่ซ้ำกัน" ],
      "Flagged file type found":[ null,
        "พบชนิดไฟล์ที่ถูกตั้งค่าสถานะ" ],
      "Package already signed":[ null,
        "แพ็คเกจถูกเซ็นชื่อแล้ว" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "ส่วนเสริมของ Firefox ไม่ได้รับอนุญาตให้เรียกใช้ตัวทำเหมืองเหรียญ" ],
      "String name is reserved for a predefined message":[ null,
        "ชื่อสตริงถูกสงวนไว้สำหรับข้อความที่กำหนดไว้ล่วงหน้า" ],
      "Placeholder for message is missing":[ null,
        "ตัวยึดตำแหน่งสำหรับข้อความขาดหายไป" ],
      "A placeholder used in the message is not defined.":[ null,
        "ตัวยึดตำแหน่งที่ใช้ในข้อความไม่ได้ถูกกำหนดไว้" ],
      "Placeholder name contains invalid characters":[ null,
        "ชื่อตัวยึดตำแหน่งมีอักขระที่ไม่ถูกต้อง" ],
      "Placeholder is missing the content property":[ null,
        "ตัวยึดตำแหน่งขาดคุณสมบัติเนื้อหา" ],
      "Translation string is missing the message property":[ null,
        "สตริงการแปลขาดคุณสมบัติข้อความ" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "ไม่ได้ตั้งค่าคุณสมบัติข้อความ \"message\" สำหรับสตริง (https://mzl.la/2DSBTjA)" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" ที่อยู่ใน manifest.json ไม่ใช่ค่าที่ถูกต้อง" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "ดู https://mzl.la/20PenXl (คู่มือ MDN) สำหรับข้อมูลเพิ่มเติม" ],
      "The \"name\" property must be a string.":[ null,
        "คุณสมบัติ \"name\" ต้องเป็นสตริง" ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "ดู http://mzl.la/1STmr48 (คู่มือ MDN) สำหรับข้อมูลเพิ่มเติม" ],
      "The \"version\" property must be a string.":[ null,
        "คุณสมบัติ \"version\" ต้องเป็นสตริง" ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "ดู http://mzl.la/1kXIADa (คู่มือ MDN) สำหรับข้อมูลเพิ่มเติม" ],
      "The field is invalid.":[ null,
        "ช่องกรอกไม่ถูกต้อง" ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "คุณสมบัติ \"version\" ใช้รูปแบบเฉพาะของ Firefox" ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "ดู https://mzl.la/1ZOhoEN (คู่มือ MDN) สำหรับข้อมูลเพิ่มเติม" ],
      "\"update_url\" is not allowed.":[ null,
        "ไม่ได้รับอนุญาตให้ใช้ \"update_url\"" ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "คุณสมบัติ \"update_url\" ไม่ได้ถูกใช้โดย Firefox" ],
      "\"strict_max_version\" not required.":[ null,
        "ไม่จำเป็นต้องมี \"strict_max_version\"" ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "ไม่พบไอคอนที่กำหนดไว้ในไฟล์กำกับในแพ็คเกจ" ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "ไม่พบไอคอนที่ \"%(path)s\"" ],
      "A background script defined in the manifest could not be found.":[ null,
        "ไม่พบสคริปต์เบื้องหลังที่กำหนดไว้ในไฟล์กำกับ" ],
      "A background page defined in the manifest could not be found.":[ null,
        "ไม่พบหน้าเบื้องหลังที่กำหนดไว้ในไฟล์กำกับ" ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "ไม่พบสคริปต์เบื้องหลังที่ \"%(path)s\"" ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "ไม่พบหน้าเบื้องหลังที่ \"%(path)s\"" ],
      "A content script defined in the manifest could not be found.":[ null,
        "ไม่พบสคริปต์เนื้อหาที่กำหนดไว้ในไฟล์กำกับ" ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "ไม่พบไฟล์ CSS สคริปต์เนื้อหาที่กำหนดไว้ในไฟล์กำกับ" ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "ไม่พบสคริปต์เนื้อหาที่กำหนดไว้ในไฟล์กำกับที่ \"%(path)s\"" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "ไม่พบไฟล์ CSS สคริปต์เนื้อหาที่กำหนดไว้ในไฟล์กำกับที่ \"%(path)s\"" ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "ไม่พบไฟล์พจนานุกรมที่กำหนดไว้ในไฟล์กำกับ" ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "ไม่พบไฟล์พจนานุกรมที่กำหนดไว้ในไฟล์กำกับที่ \"%(path)s\"" ],
      "The manifest contains multiple dictionaries.":[ null,
        "ไฟล์กำกับประกอบด้วยพจนานุกรมหลายเล่ม" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "มีพจนานุกรมหลายเล่มที่กำหนดในไฟล์กำกับซึ่งไม่รองรับ" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "ไฟล์กำกับประกอบด้วยวัตถุพจนานุกรม แต่ว่างเปล่า" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "วัตถุพจนานุกรมถูกกำหนดในไฟล์กำกับ แต่ว่างเปล่า" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "ไฟล์กำกับประกอบด้วยพจนานุกรม แต่ไม่มีคุณลักษณะ id" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "พบพจนานุกรมในไฟล์กำกับ แต่ไม่ได้ตั้งค่า id ไว้" ],
      "Forbidden content found in add-on.":[ null,
        "พบเนื้อหาที่ไม่ได้รับอนุญาตในส่วนเสริม" ],
      "This add-on contains forbidden content.":[ null,
        "ส่วนเสริมนี้มีเนื้อหาที่ไม่ได้รับอนุญาต" ],
      "Icons must be square.":[ null,
        "ไอคอนต้องเป็นสี่เหลี่ยมจัตุรัส" ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "ไอคอนที่ \"%(path)s\" ต้องเป็นสี่เหลี่ยมจัตุรัส" ],
      "The size of the icon does not match the manifest.":[ null,
        "ขนาดของไอคอนไม่ตรงกับไฟล์กำกับ" ],
      "Corrupt image file":[ null,
        "ไฟล์ภาพเสียหาย" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "ไฟล์ไอคอนที่คาดไว้ที่ \"%(path)s\" เสียหาย" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "นามแฝง LWT ของชุดตกแต่งนี้ได้ถูกเอาออกแล้วใน Firefox 70" ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "ดู https://mzl.la/2T11Lkc (คู่มือ MDN) สำหรับข้อมูลเพิ่มเติม" ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "ไม่พบภาพชุดตกแต่งสำหรับ \"%(type)s\" ที่ \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "ไฟล์ภาพชุดตกแต่งเสียหาย" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "ไฟล์ภาพชุดตกแต่งที่ \"%(path)s\" เสียหาย" ],
      "Theme image file has an unsupported file extension":[ null,
        "ไฟล์ภาพชุดตกแต่งมีนามสกุลไฟล์ที่ไม่รองรับ" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "ไฟล์ภาพชุดตกแต่งที่ \"%(path)s\" มีนามสกุลไฟล์ที่ไม่รองรับ" ],
      "Theme image file has an unsupported mime type":[ null,
        "ไฟล์ภาพของชุดตกแต่งมีชนิด MIME ที่ไม่รองรับ" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "ไฟล์ภาพของชุดตกแต่งที่ \"%(path)s\" มีชนิด mime ที่ไม่รองรับ \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "ชนิด mime ของไฟล์ภาพของชุดตกแต่งไม่ตรงกับนามสกุลไฟล์" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "นามสกุลไฟล์ภาพของชุดตกแต่งที่ \"%(path)s\" ไม่ตรงกับชนิด mime จริง \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "\"default_locale\" ขาดข้อมูลการแปลเป็นภาษาท้องถิ่น" ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" ขาดหายไป แต่มี \"_locales\" อยู่" ],
      "Unsupported image extension":[ null,
        "ไม่รองรับนามสกุลไฟล์ภาพนี้" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "ไอคอนควรมีนามสกุลไฟล์เป็น JPG/JPEG, WebP, GIF, PNG หรือ SVG" ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "ไดเรกทอรีภาษาที่ว่างเปล่า" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "ไฟล์ messages.json ขาดหายไปใน \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "คีย์ไฟล์กำกับไม่รองรับโดย Firefox รุ่นขั้นต่ำที่ระบุ" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "สิทธิอนุญาตไม่รองรับโดย Firefox รุ่นขั้นต่ำที่ระบุ" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "คีย์ไฟล์กำกับไม่รองรับโดย Firefox สำหรับ Android รุ่นขั้นต่ำที่ระบุ" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "สิทธิอนุญาตไม่รองรับโดย Firefox สำหรับ Android รุ่นขั้นต่ำที่ระบุ" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "ไม่รองรับชนิดสิทธิอนุญาตนี้" ],
      "The field is required.":[ null,
        "จำเป็นต้องกรอกข้อมูลในช่องนี้" ],
      "Unknown permission.":[ null,
        "ไม่ทราบสิทธิอนุญาต" ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "ดู https://mzl.la/1R1n1t0 (คู่มือ MDN) สำหรับข้อมูลเพิ่มเติม" ] } } }