import { RuleScanner } from './rule-scanner';
import { IndexedRule } from '../../rule';

/**
 * RuleStorageScanner scans multiple RuleScanner instances
 * The rule index is built from the rule index in the list + the list ID
 * First 4 bytes is the rule index in the list
 * Second 4 bytes is the list ID
*/
export class RuleStorageScanner {
    /**
     * Scanners is the list of list scanners backing this combined scanner
     */
    private readonly scanners: RuleScanner[];

    /**
     * Current scanner
     */
    private currentScanner: RuleScanner | null = null;

    /**
     * // Index of the current scanner
     */
    private currentScannerIdx = -1;

    /**
     * Constructor
     *
     * @param scanners
     */
    constructor(scanners: RuleScanner[]) {
        this.scanners = scanners;
    }

    /**
     * Scan advances the RuleStorageScanner to the next rule, which will then be available
     * through the Rule method. It returns false when the scan stops, either by
     * reaching the end of the input or an error.
     * @return true if there is some result
    */
    public scan(): boolean {
        if (this.scanners.length === 0) {
            return false;
        }

        if (!this.currentScanner) {
            this.currentScannerIdx = 0;
            this.currentScanner = this.scanners[this.currentScannerIdx];
        }

        while (true) {
            if (this.currentScanner.scan()) {
                return true;
            }

            // Take the next scanner or just return false if there's nothing more
            if (this.currentScannerIdx === (this.scanners.length - 1)) {
                return false;
            }

            this.currentScannerIdx += 1;
            this.currentScanner = this.scanners[this.currentScannerIdx];
        }
    }

    /**
     * Rule returns the most recent rule generated by a call to Scan, and the index of this rule.
     * See ruleListIdxToStorageIdx for more information on what this index is.
    */
    public getRule(): IndexedRule | null {
        if (!this.currentScanner) {
            return null;
        }

        const rule = this.currentScanner.getRule();
        if (!rule) {
            return null;
        }

        const index = RuleStorageScanner.ruleListIdxToStorageIdx(rule.rule.getFilterListId(), rule.index);
        return new IndexedRule(rule.rule, index);
    }

    /**
     * ruleListIdxToStorageIdx converts pair of listID and rule list index
     * to a single int64 "storage index"
     *
     * @param listId
     * @param ruleIdx
     */
    private static ruleListIdxToStorageIdx(listId: number, ruleIdx: number): number {
        // TODO: Implement ruleListIdxToStorageIdx
        return listId + ruleIdx;
        // return listId << 32 | ruleIdx & 0xFFFFFFFF;
    }
}
