module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;",
        lang:"sk" },
      "Validation Summary:":[ null,
        "Súhrn overenia:" ],
      Code:[ null,
        "Kód" ],
      Message:[ null,
        "Správa" ],
      Description:[ null,
        "Popis" ],
      File:[ null,
        "Súbor" ],
      Line:[ null,
        "Riadok" ],
      Column:[ null,
        "Stĺpec" ],
      "Invalid nesting of selectors found":[ null,
        "Bolo nájdené neplatné vnorenie" ],
      "A CSS syntax error was encountered":[ null,
        "Naša sa chyba syntaxe CSS" ],
      "Your FTL is not valid.":[ null,
        "Vaše FTL je neplatné." ],
      "Your FTL file could not be parsed.":[ null,
        "Vaše FTL nemohlo byť parsované." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Vzdialené skripty nie sú povolené bezpečnostnou politikou doplnkov." ],
      "Inline scripts blocked by default":[ null,
        "Vložené skripty sú v predvolenom nastavení zakázané" ],
      "Unadvised 3rd-party JS library":[ null,
        "Neodporúčaná JS knižnica tretej strany" ],
      "Known JS library detected":[ null,
        "Bola rozpoznaná známa JS knižnica" ],
      "{{api}} is not supported":[ null,
        "{{api}} nie je podporované" ],
      "This API has not been implemented by Firefox.":[ null,
        "Toto API nebolo Firefoxom implementované." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" bolo odstránené v manifeste verzie 3 (vlastnosť `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} je zastarané" ],
      "This API has been deprecated by Firefox.":[ null,
        "Toto rozhranie API bolo pre Firefox zastarané." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" je zastarané alebo neimplementované" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener bol volaný so štvrtým parametrom nastaveným na true." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} nie je podporované vo Firefoxe {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Toto API nebolo danou verziou Firefoxu implementované" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} nie je podporované vo Firefoxe pre Android {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Toto API nebolo danou verziou Firefoxu pre Android implementované" ],
      "Content script file could not be found.":[ null,
        "Obsah súboru so skriptom nebol nájdený." ],
      "Content script file could not be found":[ null,
        "Obsah súboru so skriptom nebol nájdený" ],
      "Content script file name should not be empty.":[ null,
        "Názov súboru so skriptom by nemal byť prázdny." ],
      "Content script file name should not be empty":[ null,
        "Názov súboru so skriptom by nemal byť prázdny" ],
      "JavaScript syntax error":[ null,
        "Chyba v syntaxi JavaScriptu" ],
      "Unexpected global passed as an argument":[ null,
        "Neočakávaná globálna premenná prešla ako parameter" ],
      "Use of document.write strongly discouraged.":[ null,
        "Použitie document.write sa neodporúča." ],
      "Banned 3rd-party JS library":[ null,
        "Zakázaná JS knižnica tretej strany" ],
      "Your JSON contains block comments.":[ null,
        "Váš JSON obsahuje blokové komentáre." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "V súboroch JSON nie sú povolené duplicitné kľúče." ],
      "Your JSON is not valid.":[ null,
        "Váš JSON nie je platný." ],
      "Your JSON file could not be parsed.":[ null,
        "Váš JSON nemohol byť parsovaný." ],
      "Reserved filename found.":[ null,
        "Bol nájdený súbor s rezervovaným názvom." ],
      "We were unable to decompress the zip file.":[ null,
        "Nepodarilo sa nám rozbaliť zip archív." ],
      "manifest.json was not found":[ null,
        "manifest.json sa nepodarilo nájsť" ],
      "File is too large to parse.":[ null,
        "Súbor je na analýzu príliš veľký." ],
      "Hidden file flagged":[ null,
        "Bol označený skrytý súbor" ],
      "Flagged filename found":[ null,
        "Bol nájdený označený názov súboru" ],
      "Flagged file extensions found":[ null,
        "Bol nájdený označený súbor rozšírenia" ],
      "Package contains duplicate entries":[ null,
        "Balíček obsahuje duplicitné položky" ],
      "Flagged file type found":[ null,
        "Bol nájdený označený typ súboru" ],
      "Package already signed":[ null,
        "Balíček už bol podpísaný" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Doplnky Firefoxu nesmú ťažiť kryptomeny." ],
      "String name is reserved for a predefined message":[ null,
        "Názov reťazca je rezervovaný pre preddefinovanú správu" ],
      "Placeholder for message is missing":[ null,
        "Placeholder pre správu chýba" ],
      "A placeholder used in the message is not defined.":[ null,
        "Placeholder použitý v správe nie je definovaný." ],
      "Placeholder name contains invalid characters":[ null,
        "Placeholder obsahuje neplatné znaky" ],
      "Placeholder is missing the content property":[ null,
        "Placeholderu chýba vlastnosť content" ],
      "Translation string is missing the message property":[ null,
        "Reťazcu prekladu chýba vlastnosť message" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Pre reťazec nie je nastavená správa vo vlastnosti „message“ (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Ďalšie informácie nájdete na https://mzl.la/2Qn0fWC (Dokumenty MDN)." ],
      "Invalid host permission.":[ null,
        "Neplatné povolenie hostiteľa." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "„manifest_version“ nie je v súbore manifest.json platná hodnota" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Ďalšie informácie nájdete na https://mzl.la/20PenXl (dokumentácia na MDN)." ],
      "The \"name\" property must be a string.":[ null,
        "Vlastnosť „name“ musí byť reťazec." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Ďalšie informácie nájdete na http://mzl.la/1STmr48 (dokumentácia na MDN)." ],
      "The \"version\" property must be a string.":[ null,
        "Vlastnosť „version“ musí byť reťazec." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Ďalšie informácie nájdete na http://mzl.la/1kXIADa (dokumentácia na MDN)." ],
      "The field is invalid.":[ null,
        "Pole je neplatné." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Vlastnosť „version“ používa vo Firefoxe špecifický formát." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Ďalšie informácie nájdete na https://mzl.la/1ZOhoEN (dokumentácia na MDN)." ],
      "\"update_url\" is not allowed.":[ null,
        "„update_url“ nie je povolené." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Vlastnosť „update_url“ nie je Firefoxom používaná." ],
      "\"strict_max_version\" not required.":[ null,
        "„strict_max_version“ nie je vyžadované." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Ikona definovaná v manifeste nebola v balíčku nájdená." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "V umiestnení „%(path)s“ nebola nájdená ikona." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Skript obsahu definovaný v manifeste nebol nájdený." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Ikona pozadia definovaná v manifeste nebola v balíčku nájdená." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Skript nebol nájdený v „%(path)s“." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Stránka pozadia nebola nájdená v „%(path)s“." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Skript obsahu definovaný v manifeste nebol nájdený." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Skript obsahu súboru css definovaný v manifeste nebol nájdený." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Skript obsahu definovaný v manifeste nebol nájdený v „%(path)s“." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Skript obsahu súboru css definovaný v manifeste nebol nájdený v „%(path)s“." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Slovník definovaný v manifeste nebol nájdený." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Slovník definovaný v manifeste nebol nájdený v „%(path)s“." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifest obsahuje viacero slovníkov." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "V manifeste boli uvedené viaceré slovníky. Toto nie je podporované." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifest obsahuje objekt so slovníkom, no ten je prázdny." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Objekt so slovníkom bol v manifeste definovaný, no je prázdny." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifest obsahuje slovník, no žiadne id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "V manifeste bol nájdený slovník, no nemá nastavené id." ],
      "Forbidden content found in add-on.":[ null,
        "V doplnku bol nájdený zakázaný obsah." ],
      "This add-on contains forbidden content.":[ null,
        "Doplnok obsahuje zakázaný obsah." ],
      "Icons must be square.":[ null,
        "Ikony musia byť štvorcové." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikona v „%(path)s“ musí byť štvorcová." ],
      "The size of the icon does not match the manifest.":[ null,
        "Veľkosť ikony nezodpovedá manifestu." ],
      "Corrupt image file":[ null,
        "Poškodený súbor s obrázkom" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Očakávaný súbor ikony v „%(path)s“ je poškodený" ],
      "This property has been deprecated.":[ null,
        "Táto vlastnosť je zastaraná." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Tento LWT alias témy vzhľadu bol odstránený vo Firefoxe 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Ďalšie informácie nájdete na https://mzl.la/2T11Lkc (dokumentácia na MDN)." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Obrázok témy vzhľadu pre „%(type)s“ nebol v „%(path)s“ nájdený" ],
      "Corrupted theme image file":[ null,
        "Poškodený súbor s obrázkom" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Obrázok témy vzhľadu v „%(path)s“ je poškodený" ],
      "Theme image file has an unsupported file extension":[ null,
        "Súbor s obrázkom témy vzhľadu obsahuje nepodporované rozšírenie" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Súbor s obrázkom témy vzhľadu v „%(path)s“ obsahuje nepodporované rozšírenie" ],
      "Theme image file has an unsupported mime type":[ null,
        "Súbor s obrázkom témy vzhľadu má nepodporovaný typ mime" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Súbor s obrázkom témy vzhľadu v „%(path)s“ má nepodporovaný typ mime „%(mime)s“" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Typ mime súboru s obrázkom témy vzhľadu nezodpovedá svojmu rozšíreniu" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Rozšírenie obrázka témy vzhľadu v „%(path)s“ nezodpovedá typu mime „%(mime)s“" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Jazyku „default_locale“ chýbajú preklady." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Jazyk „default_locale“ chýba, no „_locales“ existuje." ],
      "Unsupported image extension":[ null,
        "Nepodporovaný formát obrázku" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikony by mala mať formát JPG/JPEG, WebP, GIF, PNG alebo SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Vlastnosť \"applications\" prepísaná vlastnosťou \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Prázdny adresár s jazykmy" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "V „%(path)s“ chýba súbor messages.json" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Kľúč manifestu nie je podporovaný danou minimálnou verziou Firefoxu" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Povolenie nie je podporované danou minimálnou verziou Firefoxu" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Kľúč manifestu nie je podporovaný danou minimálnou verziou Firefoxu pre Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Povolenie nie je podporované danou minimálnou verziou Firefoxu pre Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Odkaz na „addons.mozilla.org“ nie je povolený" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Odkazy smerujúce na \"addons.mozilla.org\" nie je možné použiť ako domovskú stránku" ],
      "The permission type is unsupported.":[ null,
        "Tento typ povolenia nie je podporovaný." ],
      "The field is required.":[ null,
        "Toto pole je povinné." ],
      "Unknown permission.":[ null,
        "Neznáme povolenie." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Ďalšie informácie nájdete na https://mzl.la/1R1n1t0 (dokumentácia na MDN)." ] } } }