module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"fy_NL" },
      "Validation Summary:":[ null,
        "Falidaasjegearfetting:" ],
      Code:[ null,
        "Koade" ],
      Message:[ null,
        "Berjocht" ],
      Description:[ null,
        "Beskriuwing" ],
      File:[ null,
        "Bestân" ],
      Line:[ null,
        "Rige" ],
      Column:[ null,
        "Kolom" ],
      "Invalid nesting of selectors found":[ null,
        "Unjildich nesten fan selectors fûn" ],
      "A CSS syntax error was encountered":[ null,
        "Der is in CSS-syntaksisflater oantroffen" ],
      "Your FTL is not valid.":[ null,
        "Jo FTL is net jildich." ],
      "Your FTL file could not be parsed.":[ null,
        "Jo FTL-bestân koe net ferwurke wurde." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Neefens it add-onbelied binne eksterne scripts net tastien." ],
      "Inline scripts blocked by default":[ null,
        "Ynline scripts wurde standert blokkearre" ],
      "Unadvised 3rd-party JS library":[ null,
        "Ofrêden JS-biblioteek fan tredden" ],
      "Known JS library detected":[ null,
        "Bekende JS-biblioteek detektearre" ],
      "{{api}} is not supported":[ null,
        "{{api}} is net stipe" ],
      "This API has not been implemented by Firefox.":[ null,
        "Dizze API is net troch Firefox ymplemintearre." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "‘{{api}}’ is fuortsmiten yn Manifest ferzje 3 (eigenskip ‘manifest_version’)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} is ferâldere" ],
      "This API has been deprecated by Firefox.":[ null,
        "Dizze API is yn Firefox ferâldere." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "‘{{api}}’ is ferâldere of net ymplemintearre" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` oanroppen mei ‘truthy’ fjirde argumint." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} wurdt net stipe yn Firefox ferzje {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Dizze API is net troch de opjûne minimumferzje fan Firefox ymplemintearre" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} wurdt net stipe yn Firefox foar Android ferzje {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Dizze API is net troch de opjûne minimumferzje fan Firefox foar Android ymplemintearre" ],
      "Content script file could not be found.":[ null,
        "Ynhâldsscriptbestân koe net fûn wurde." ],
      "Content script file could not be found":[ null,
        "Ynhâldsscriptbestân koe net fûn wurde" ],
      "Content script file name should not be empty.":[ null,
        "Namme fan ynhâldsscriptbestân mei net leech wêze." ],
      "Content script file name should not be empty":[ null,
        "Namme fan ynhâldsscriptbestân mei net leech wêze" ],
      "JavaScript syntax error":[ null,
        "JavaScript-syntaksisflater" ],
      "Unexpected global passed as an argument":[ null,
        "Unferwachte globale fariabele trochjûn as argumint" ],
      "Use of document.write strongly discouraged.":[ null,
        "Gebrûk fan document.write wurdt strang ôfrêd." ],
      "Banned 3rd-party JS library":[ null,
        "Blokkearre JS-biblioteek fan tredden" ],
      "Your JSON contains block comments.":[ null,
        "Jo JSON befettet blokkommentaren." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Dûbele kaaien binne net tastien yn JSON-bestannen." ],
      "Your JSON is not valid.":[ null,
        "Jo JSON is net jildich." ],
      "Your JSON file could not be parsed.":[ null,
        "Jo JSON-bestân koe net ferwurke wurde." ],
      "Reserved filename found.":[ null,
        "Reservearre bestânsnamme fûn." ],
      "We were unable to decompress the zip file.":[ null,
        "Wy koene it zip-bestân net útpakke." ],
      "manifest.json was not found":[ null,
        "manifest.json is net fûn" ],
      "File is too large to parse.":[ null,
        "Bestân is te grut om te parsen." ],
      "Hidden file flagged":[ null,
        "Ferburgen bestân markearre" ],
      "Flagged filename found":[ null,
        "Markearre bestânsnamme fûn" ],
      "Flagged file extensions found":[ null,
        "Markearre bestânsútwreidingen fûn" ],
      "Package contains duplicate entries":[ null,
        "Pakket befettet dûbele fermeldingen" ],
      "Flagged file type found":[ null,
        "Markearre bestânstype fûn" ],
      "Package already signed":[ null,
        "Pakket al ûndertekene" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox-add-ons meie gjin coinminers útfiere." ],
      "String name is reserved for a predefined message":[ null,
        "Stringnamme is reservearre foar in yn it foar definiearre berjocht" ],
      "Placeholder for message is missing":[ null,
        "Placeholder foar berjocht mist" ],
      "A placeholder used in the message is not defined.":[ null,
        "In placeholder brûkt yn it berjocht is net definiearre." ],
      "Placeholder name contains invalid characters":[ null,
        "Placeholdernamme befettet net jildige karakters" ],
      "Placeholder is missing the content property":[ null,
        "Placeholder mist de eigenskip ynhâld" ],
      "Translation string is missing the message property":[ null,
        "Oersetrigel mist de eigenskip berjocht" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Der is gjin ‘berjocht’ foar de eigenskip berjocht ynsteld foar in rigel (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Sjoch https://mzl.la/2Qn0fWC (MDN Docs) foar mear ynformaasje." ],
      "Invalid host permission.":[ null,
        "Unbekende hosttastimming." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "‘manifest_version’ yn it bestân manifest.json is gjin jildige wearde" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Sjoch https://mzl.la/20PenXl (MDN Docs) foar mear ynformaasje." ],
      "The \"name\" property must be a string.":[ null,
        "De eigenskip ‘name’ moat in tekenreeks wêze." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Sjoch http://mzl.la/1STmr48 (MDN Docs) foar mear ynformaasje." ],
      "The \"version\" property must be a string.":[ null,
        "De eigenskip ‘version’ moat in tekenreeks wêze." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Sjoch http://mzl.la/1kXIADa (MDN Docs) foar mear ynformaasje." ],
      "The field is invalid.":[ null,
        "It fjild is ûnjildich." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "De eigenskip ‘version’ brûkt in Firefox-spesifike notaasje." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Sjoch https://mzl.la/1ZOhoEN (MDN Docs) foar mear ynformaasje." ],
      "\"update_url\" is not allowed.":[ null,
        "‘update_url’ is net tastien." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "De eigenskip ‘update_url’ wurdt net troch Firefox brûkt." ],
      "\"strict_max_version\" not required.":[ null,
        "‘strict_max_version’ net fereaske." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "In yn it manifest definiearre piktogram koe net yn it pakket fûn wurde." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Piktogram koe net fûn wurde fûn yn ‘%(path)s’." ],
      "A background script defined in the manifest could not be found.":[ null,
        "In yn it manifest definiearre eftergrûnscript koe net fûn wurde." ],
      "A background page defined in the manifest could not be found.":[ null,
        "In yn it manifest definiearre eftergrûnside koe net fûn wurde." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Eftergrûnscript koe net fûn wurde yn ‘%(path)s’." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Eftergrûnside koe net fûn wurde yn ‘%(path)s’." ],
      "A content script defined in the manifest could not be found.":[ null,
        "In yn it manifest definiearre ynhâldsscript koe net fûn wurde yn." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "In yn it manifest definiearre CSS-bestân fan ynhâldsscript koe net fûn wurde." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Yn it manifest definiearre ynhâldsscript koe net fûn wurde yn ‘%(path)s’." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Yn it manifest definiearre CSS-bestân fan ynhâldsscript koe net fûn wurde yn ‘%(path)s’." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "In yn it manifest definiearre biblioteekbestân koe net fûn wurde." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "In yn it manifest definiearre biblioteekbestân koe net fûn wurde yn ‘%(path)s’." ],
      "The manifest contains multiple dictionaries.":[ null,
        "It manifest befettet mear wurdboeken." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Der binne mear wurdboeken definiearre yn it manifest, wat net stipe wurdt." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "It manifest befettet in wurdboek-objekt, mar it is leech." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Der is in wurdboek-objekt definiearre yn it manifest, mar it is leech." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "It manifest befettet in wurdboek, mar gjin id-eigenskip." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Der is in wurdboek fûn yn it manifest, mar der is gjin id ynsteld." ],
      "Forbidden content found in add-on.":[ null,
        "Ferbeane ynhâld fûn yn add-on." ],
      "This add-on contains forbidden content.":[ null,
        "Dizze add-on befettet ferbeane ynhâld." ],
      "Icons must be square.":[ null,
        "Piktogrammen moatte fjouwerkant wêze." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Piktogram yn ‘%(path)s’ moat fjouwerkant wêze." ],
      "The size of the icon does not match the manifest.":[ null,
        "De grutte fan it piktogram komt net oerien mei it manifest." ],
      "Corrupt image file":[ null,
        "Skansearre ôfbyldingsbestân" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Ferwacht piktogrambestân yn ‘%(path)s’ is skansearre" ],
      "This property has been deprecated.":[ null,
        "Dizze eigenskip is ferâldere." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "It LWT-alias fan dit tema is fuortsmiten yn Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Sjoch https://mzl.la/2T11Lkc (MDN Docs) foar mear ynformaasje." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Temaôfbylding foar ‘%(type)s’ koe net fûn wurde yn ‘%(path)s’" ],
      "Corrupted theme image file":[ null,
        "Skansearre temaôfbyldingsbestân" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Temaôfbyldingsbestân yn ‘%(path)s’ is skansearre" ],
      "Theme image file has an unsupported file extension":[ null,
        "Temaôfbyldingsbestân hat in net-stipe bestânsekstinsje" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Temaôfbyldingsbestân op ‘%(path)s’ hat in net-stipe bestânsekstinsje" ],
      "Theme image file has an unsupported mime type":[ null,
        "Temaôfbyldingsbestân hat in net-stipe mime-type" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Temaôfbyldingsbestân op ‘%(path)s’ hat it net-stipe mime-type ‘%(mime)s’" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Mime-type fan it temaôfbyldingsbestân komt net oerien mei de bestandsekstinsje" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Temaôfbyldingsbestân op ‘%(path)s’ komt net oerien mei it wurklike mime-type ‘%(mime)s’" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "De ‘default_locale’ mist lokalisaasjes." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "De ‘default_locale’ ûntbrekt, mar ‘_locales’ bestiet." ],
      "Unsupported image extension":[ null,
        "Net-stipe ôfbyldingsútwreding" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Piktogrammen moatte JPG/JPEG, WebP, GIF, PNG of SVG wêze." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Eigenskip ‘applications’ wurdt oerskreaun troch de eigenskip ‘browser_specific_settings’" ],
      "Empty language directory":[ null,
        "Lege taalmap" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Bestân messages.json ûntbrekt yn ‘%(path)s’" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifestkaai net stipe troch de opjûne minimale Firefox-ferzje" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Tastimming net stipe troch de opjûne minimale Firefox-ferzje" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifestkaai net stipe troch de opjûne minimale Firefox foar Android-ferzje" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Tastemming net stipe troch de opjûne minimale Firefox foar Android-ferzje" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Keppeljen nei ‘addons.mozilla.org’ is net tastien" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Keppelingen dy’t ferwize nei ‘addons.mozilla.org’ meie net foar de startside brûkt wurde" ],
      "The permission type is unsupported.":[ null,
        "It tastimmingstype wurdt net stipe." ],
      "The field is required.":[ null,
        "It fjild is fereaske." ],
      "Unknown permission.":[ null,
        "Unbekende tastimming." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Sjoch https://mzl.la/1R1n1t0 (MDN Docs) foar mear ynformaasje." ] } } }