module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"hu" },
      "Validation Summary:":[ null,
        "Ellenőrzési összefoglaló:" ],
      Code:[ null,
        "Kód" ],
      Message:[ null,
        "Üzenet" ],
      Description:[ null,
        "Leírás" ],
      File:[ null,
        "Fájl" ],
      Line:[ null,
        "Sor" ],
      Column:[ null,
        "Oszlop" ],
      "Invalid nesting of selectors found":[ null,
        "Érvénytelen egymásba ágyazott választók találva" ],
      "A CSS syntax error was encountered":[ null,
        "CSS szintaktikai hiba észlelve" ],
      "Your FTL is not valid.":[ null,
        "Az FTL érvénytelen." ],
      "Your FTL file could not be parsed.":[ null,
        "Az FTL fájl nem dolgozható fel." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "A távoli parancsfájlok a kiegészítők irányelvei szerint nem engedélyezettek." ],
      "Inline scripts blocked by default":[ null,
        "A soron belüli parancsfájlok alapértelmezetten blokkoltak" ],
      "Unadvised 3rd-party JS library":[ null,
        "Nem tanácsolt harmadik féltől származó JS könyvtár" ],
      "Known JS library detected":[ null,
        "Ismert JS könyvtár észlelve" ],
      "{{api}} is not supported":[ null,
        "A(z) {{api}} nem támogatott" ],
      "This API has not been implemented by Firefox.":[ null,
        "Ez az API még nincs megvalósítva a Firefoxban." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "A(z) „{{api}}” el lett távolítva a leíró 3. verziójából (`manifest_version` tulajdonság)" ],
      "{{api}} is deprecated":[ null,
        "A(z) {{api}} elavult" ],
      "This API has been deprecated by Firefox.":[ null,
        "Ez az API elavult a Firefoxban." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "A(z) „{{api}}” elavult és nincs megvalósítva" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "`addEventListener` igaz értékű negyedik argumentummal meghívva." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "A(z) {{api}} nem támogatott a Firefox {{minVersion}} verzióban" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Ez az API még nincs megvalósítva a megadott minimális Firefox verzióban" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "A(z) {{api}} nem támogatott a Firefox for Android {{minVersion}} verzióban" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Ez az API még nincs megvalósítva a megadott minimális Firefox for Android verzióban" ],
      "Content script file could not be found.":[ null,
        "A tartalomparancsfájl nem található." ],
      "Content script file could not be found":[ null,
        "A tartalomparancsfájl nem található" ],
      "Content script file name should not be empty.":[ null,
        "A tartalomparancsfájl neve nem lehet üres." ],
      "Content script file name should not be empty":[ null,
        "A tartalomparancsfájl neve nem lehet üres" ],
      "JavaScript syntax error":[ null,
        "JavaScript szintaktikai hiba" ],
      "Unexpected global passed as an argument":[ null,
        "Nem várt argumentumként átadott globális változó" ],
      "Use of document.write strongly discouraged.":[ null,
        "A document.write használata erősen ellenjavallt." ],
      "Banned 3rd-party JS library":[ null,
        "Tiltott harmadik féltől származó JS könyvtár" ],
      "Your JSON contains block comments.":[ null,
        "A JSON megjegyzésblokkot tartalmaz." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Az ismétlődő kulcsok nem megengedettek a JSON fájlokban." ],
      "Your JSON is not valid.":[ null,
        "A JSON érvénytelen." ],
      "Your JSON file could not be parsed.":[ null,
        "Az JSON fájl nem dolgozható fel." ],
      "Reserved filename found.":[ null,
        "Fenntartott fájlnév találva." ],
      "We were unable to decompress the zip file.":[ null,
        "Nem sikerült a zip fájl kibontása." ],
      "manifest.json was not found":[ null,
        "a manifest.json nem található" ],
      "File is too large to parse.":[ null,
        "A fájl túl nagy a feldolgozáshoz" ],
      "Hidden file flagged":[ null,
        "Rejtett fájl megjelölve" ],
      "Flagged filename found":[ null,
        "Megjelölt fájlnév találva" ],
      "Flagged file extensions found":[ null,
        "Megjelölt fájlkiterjesztés találva" ],
      "Package contains duplicate entries":[ null,
        "A csomag ismétlődő bejegyzéseket tartalmaz" ],
      "Flagged file type found":[ null,
        "Megjelölt fájltípus találva" ],
      "Package already signed":[ null,
        "A csomag már aláírt" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "A Firefox kiegészítők nem futtathatnak kriptovaluta bányász programokat." ],
      "String name is reserved for a predefined message":[ null,
        "A karakterlánc neve egy előre definiált üzenetnek van fenntartva" ],
      "Placeholder for message is missing":[ null,
        "Az üzenet helykitöltője hiányzik" ],
      "A placeholder used in the message is not defined.":[ null,
        "Az üzenetben használt helykitöltő nincs definiálva." ],
      "Placeholder name contains invalid characters":[ null,
        "A helykitöltő neve érvénytelen karaktereket tartalmaz" ],
      "Placeholder is missing the content property":[ null,
        "A helykitöltőből hiányzik a content tulajdonság" ],
      "Translation string is missing the message property":[ null,
        "A fordítási karakterláncból hiányzik a message tulajdonság" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Nincs „message” üzenettulajdonság beállítva a karakterlánchoz (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "További információkért lásd: https://mzl.la/2Qn0fWC (MDN dokumentáció)." ],
      "Invalid host permission.":[ null,
        "Érvénytelen gazdagép-engedély." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "A manifest.json fájlban szereplő „manifest_version” értéke érvénytelen" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "További információkért lásd: https://mzl.la/20PenXl (MDN dokumentáció)." ],
      "The \"name\" property must be a string.":[ null,
        "A „name” tulajdonságnak karakterláncnak kell lennie." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "További információkért lásd: http://mzl.la/1STmr48 (MDN dokumentáció)." ],
      "The \"version\" property must be a string.":[ null,
        "A „version” tulajdonságnak karakterláncnak kell lennie." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "További információkért lásd: http://mzl.la/1kXIADa (MDN dokumentáció)." ],
      "The field is invalid.":[ null,
        "A mező érvénytelen." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "A „name” tulajdonságnak Firefox-függő formátumot használ." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "További információkért lásd: https://mzl.la/1ZOhoEN (MDN dokumentáció)." ],
      "\"update_url\" is not allowed.":[ null,
        "Az „update_url” nem engedélyezett." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Az „update_url” tulajdonságot nem használja a Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "A „strict_max_version” nem kötelező." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "A leíróban definiált ikon nem található a csomagban." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "A(z) „%(path)s” helyen lévő ikon nem található." ],
      "A background script defined in the manifest could not be found.":[ null,
        "A leíróban definiált háttérparancsfájl nem található." ],
      "A background page defined in the manifest could not be found.":[ null,
        "A leíróban definiált háttéroldal nem található." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "A háttérparancsfájl nem található itt: „%(path)s”." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "A háttéroldal nem található itt: „%(path)s”." ],
      "A content script defined in the manifest could not be found.":[ null,
        "A leíróban definiált tartalomparancsfájl nem található." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "A leíróban definiált css fájl nem található." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "A leíróban definiált tartalomparancsfájl nem található itt: „%(path)s”." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "A leíróban definiált tartalom CSS fájl nem található itt: „%(path)s”. " ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "A leíróban definiált szótárfájl nem található." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "A leíróban definiált szótárfájl nem található itt: „%(path)s”." ],
      "The manifest contains multiple dictionaries.":[ null,
        "A leíró több szótárat is tartalmaz." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Több szótárat is definiált a leíróban, amely nem támogatott." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "A leíró szótárobjektumot tartalmaz, de az üres." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "A leíróban egy szótár lett definiálva, de az üres volt." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "A leírófájl szótárat tartalmaz, de nincs id tulajdonsága." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Egy szótár található a leíróban, de nincs id tulajdonság megadva." ],
      "Forbidden content found in add-on.":[ null,
        "Tiltott tartalom található a kiegészítőben." ],
      "This add-on contains forbidden content.":[ null,
        "Ez a kiegészítő tiltott tartalmat tartalmaz." ],
      "Icons must be square.":[ null,
        "Az ikonoknak négyzetesnek kell lennie." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "A(z) „%(path)s” helyen lévő ikonnak négyzetesnek kell lennie." ],
      "The size of the icon does not match the manifest.":[ null,
        "Az ikon mérete nem egyezik a leíróval." ],
      "Corrupt image file":[ null,
        "Sérült képfájl" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "A(z) „%(path)s” helyen várt ikon sérült" ],
      "This property has been deprecated.":[ null,
        "Ez a tulajdonság elavult." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "A téma LWT álneve eltávolításra került a Firefox 70-ben." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "További információkért lásd: https://mzl.la/2T11Lkc (MDN dokumentáció)." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "A(z) „%(type)s” típushoz tartozó témakép nem található itt: „%(path)s”" ],
      "Corrupted theme image file":[ null,
        "Sérült témaképfájl" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "A(z) „%(path)s” helyen lévő témaképfájl sérült" ],
      "Theme image file has an unsupported file extension":[ null,
        "A téma képfájlja nem támogatott fájlkiterjesztéssel rendelkezik" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "A(z) „%(path)s” helyen lévő témafájl kiterjesztése nem támogatott" ],
      "Theme image file has an unsupported mime type":[ null,
        "A téma képfájlja nem támogatott MIME-típussal rendelkezik" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "A(z) „%(path)s” helyen lévő képfájl nem támogatott MIME-típussal rendelkezik" ],
      "Theme image file mime type does not match its file extension":[ null,
        "A téma képfájljának MIME-típusa nem egyezik a fájlkiterjesztésével" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "A(z) „%(path)s” helyen lévő képfájl kiterjesztése nem egyezik a tényleges „%(mime)s” MIME-típusával." ],
      "The \"default_locale\" is missing localizations.":[ null,
        "A „default_locale” területi beállításhoz hiányoznak a fordítások." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "A „default_locale” hiányzik, de a „_locales” létezik." ],
      "Unsupported image extension":[ null,
        "Nem támogatott képkiterjesztés" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Az ikonoknak JPG/JPEG, WebP, GIF, PNG vagy SVG fájloknak kell lenniük." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Az „applications” tulajdonságot felülírja a „browser_specific_settings” tulajdonság" ],
      "Empty language directory":[ null,
        "Üres nyelvi könyvtár" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "A messages.json fájl hiányzik innen: „%(path)s”" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "A leírókulcs nem támogatott a megadott minimális Firefox verzióban" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Az engedély nem támogatott a megadott minimális Firefox verzióban" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "A leírókulcs nem támogatott a megadott minimális Firefox for Android verzióban" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Az engedély nem támogatott a megadott minimális Firefox for Android verzióban" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Az „addons.mozilla.org” webhelyre való hivatkozás nem engedélyezett" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Az „addons.mozilla.org” oldalra mutató hivatkozások nem használhatók honlapként" ],
      "The permission type is unsupported.":[ null,
        "Az engedélytípus nem támogatott." ],
      "The field is required.":[ null,
        "A mező kötelező." ],
      "Unknown permission.":[ null,
        "Ismeretlen engedély." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "További információkért lásd: https://mzl.la/1R1n1t0 (MDN dokumentáció)." ] } } }