module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5);",
        lang:"ar" },
      "Validation Summary:":[ null,
        "ملخص التحقق:" ],
      Code:[ null,
        "الرمز" ],
      Message:[ null,
        "الرسالة" ],
      Description:[ null,
        "الوصف" ],
      File:[ null,
        "الملف" ],
      Line:[ null,
        "السطر" ],
      Column:[ null,
        "العمود" ],
      "Invalid nesting of selectors found":[ null,
        "عُثر على تشعّب مُنتقيات غير صالح" ],
      "A CSS syntax error was encountered":[ null,
        "عُثر على خطأ في صياغة CSS" ],
      "Your FTL is not valid.":[ null,
        "ملف FTL غير صحيح." ],
      "Your FTL file could not be parsed.":[ null,
        "تعذّر تحليل ملف FTL." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "ليس مسموحا بالسكربتات البعيدة حسب سياسات الإضافات." ],
      "Inline scripts blocked by default":[ null,
        "السكربتات الداخلية/Inline ممنوعة مبدئيا" ],
      "Unadvised 3rd-party JS library":[ null,
        "مكتبة جافاسكربت من طرف ثالث غير منصوح بها" ],
      "Known JS library detected":[ null,
        "اكتُشفت مكتبة جافاسكربت معروفة" ],
      "{{api}} is not supported":[ null,
        "{{api}} غير مدعومة" ],
      "This API has not been implemented by Firefox.":[ null,
        "لم يُنفّذ فَيَرفُكس واجهة API هذه." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "" ],
      "Content script file could not be found.":[ null,
        "تعذر العثور على ملف سكربت المحتوى." ],
      "Content script file could not be found":[ null,
        "تعذر العثور على ملف سكربت المحتوى" ],
      "Content script file name should not be empty.":[ null,
        "لا يمكن أن يكون اسم ملف المحتوى فارغا." ],
      "Content script file name should not be empty":[ null,
        "لا يمكن أن يكون اسم ملف المحتوى فارغا" ],
      "JavaScript syntax error":[ null,
        "خطأ في صياغة جافاسكربت" ],
      "Unexpected global passed as an argument":[ null,
        "مُرّر متغير عالمي باعتباره معطى بشكل غير متوقع" ],
      "Use of document.write strongly discouraged.":[ null,
        "لا يُنصح بتاتا باستخدام document.write." ],
      "Banned 3rd-party JS library":[ null,
        "مكتبة جافاسكربت من طرف ثالث محجوبة" ],
      "Your JSON contains block comments.":[ null,
        "يحتوي ملف JSON تعليقات كتلية." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "ليس مسموحا بتكرار المفاتيح في ملفات JSON." ],
      "Your JSON is not valid.":[ null,
        "ملف JSON غير صحيح." ],
      "Your JSON file could not be parsed.":[ null,
        "تعذر تحليل ملف JSON." ],
      "Reserved filename found.":[ null,
        "" ],
      "We were unable to decompress the zip file.":[ null,
        "تعذر علينا فك ضغط ملف ZIP." ],
      "manifest.json was not found":[ null,
        "لم يُعثر على manifest.json" ],
      "File is too large to parse.":[ null,
        "حجم الملف كبير جدا لتحليله." ],
      "Hidden file flagged":[ null,
        "وُجدت ملفات مخفية" ],
      "Flagged filename found":[ null,
        "وُجدت أسماء ملفات لا داعي لها" ],
      "Flagged file extensions found":[ null,
        "وُجدت امتدادات ملفات لا داعي لها" ],
      "Package contains duplicate entries":[ null,
        "تحتوي الحزمة مدخلات مكررة" ],
      "Flagged file type found":[ null,
        "" ],
      "Package already signed":[ null,
        "وُقّعت الحزمة بالفعل" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "ليس مسموحا بأن تُشغّل إضافات فَيَرفُكس المُنقّبات عن العملات." ],
      "String name is reserved for a predefined message":[ null,
        "اسم السلسلة النصية محجوز لرسالة معرّفة مسبقا" ],
      "Placeholder for message is missing":[ null,
        "حافظ مكان الرسالة ناقص" ],
      "A placeholder used in the message is not defined.":[ null,
        "استُخدم حافظ مكان في الرسالة ولكنه لم يُعرّف." ],
      "Placeholder name contains invalid characters":[ null,
        "يحتوي اسم حافظ المكان محارف غير صحيحة" ],
      "Placeholder is missing the content property":[ null,
        "ينقصه حافظ المكان صفة المحتوى/content" ],
      "Translation string is missing the message property":[ null,
        "سلسلة الترجمة النصية ناقصة في صفة الرسالة/message" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "لم تُضبط صفة الرسالة ”message“ للسلسلة النصية (https://mzl.la/2DSBTjA)." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "ليس لِ‍ ”manifest_version“ في manifest.json قيمة صالحة" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "طالع https://mzl.la/20PenXl (وثائق MDN) لمعلومات أكثر." ],
      "The \"name\" property must be a string.":[ null,
        "يجب أن تكون الصفة ”name“ سلسلة نصية." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "طالِع http://mzl.la/1STmr48 (وثائق MDN) لمعلومات أكثر." ],
      "The \"version\" property must be a string.":[ null,
        "يجب أن تكون الصفة ”version“ سلسلة نصية." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "طالِع http://mzl.la/1kXIADa (وثائق MDN) لمعلومات أكثر." ],
      "The field is invalid.":[ null,
        "هذا الحقل غير صالح." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "تستعمل صفة ”version“ نسقًا مخصّصًا لمتصفّح Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "طالع https://mzl.la/1ZOhoEN (وثائق MDN) لمعلومات أكثر." ],
      "\"update_url\" is not allowed.":[ null,
        "ليس مسموحًا بِ‍ ”update_url“." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "لا يستعمل Firefox الصفة ”update_url“." ],
      "\"strict_max_version\" not required.":[ null,
        "‏”strict_max_version“ ليس مطلوبًا." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "لم توجد إحدى الأيقونات المعرّفة في البيان داخل الحزمة." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "لم توجد الأيقونة في ”%(path)s“." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "لم يوجد سكربت الخلفية في ”%(path)s“." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "لم توجد صفحة الخلفية في ”%(path)s“." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "لم يوجد سكربت المحتوى المعرّف في البيان في ”%(path)s“." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "لم يوجد سكربت CSS للمحتوى المعرّف في البيان في ”%(path)s“." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "The manifest contains multiple dictionaries.":[ null,
        "" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "" ],
      "Forbidden content found in add-on.":[ null,
        "وُجد محتوى محظور في الإضافة." ],
      "This add-on contains forbidden content.":[ null,
        "في هذه الإضافة محتوًى محظور." ],
      "Icons must be square.":[ null,
        "يجب أن تكون الأيقونات مربعة الشكل." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "يجب أن تكون الأيقونة في ”%(path)s“ مربعة الشكل." ],
      "The size of the icon does not match the manifest.":[ null,
        "لا يتطابق مقاس الأيقونة مع البيان." ],
      "Corrupt image file":[ null,
        "ملف الصورة معطوب" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "توقّعت ملف أيقونة في ”%(path)s“، ولكنّه تالف" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "" ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "" ],
      "Corrupted theme image file":[ null,
        "" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "" ],
      "Theme image file has an unsupported file extension":[ null,
        "لملف صورة السمة امتدادًا غير مدعوم" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "لملف صورة السمة في ”%(path)s“ امتدادًا غير مدعوم" ],
      "Theme image file has an unsupported mime type":[ null,
        "لملف صورة السمة نوع MIME غير مدعوم" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "ليس في ”default_locale“ أيّ ملفات توطين." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "‏”default_locale“ ليس موجودًا، ولكنّ ”‎_locales“ موجود." ],
      "Unsupported image extension":[ null,
        "امتداد الصورة غير مدعوم" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "يجب أن تكون الصورة: JPG/JPEG أو WebP أو GIF أو PNG أو SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "دليل اللغات فارغ" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "لم يوجد الملف messages.json في ”%(path)s“." ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "نوع التصريح غير مدعوم." ],
      "The field is required.":[ null,
        "هذا الحقل مطلوب." ],
      "Unknown permission.":[ null,
        "التصريح مجهول." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "طالع https://mzl.la/1R1n1t0 (وثائق MDN) لمعلومات أكثر." ] } } }