module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=1; plural=0;",
        lang:"ms" },
      "Validation Summary:":[ null,
        "Ringkasan Pengesahan:" ],
      Code:[ null,
        "Kod" ],
      Message:[ null,
        "Mesej" ],
      Description:[ null,
        "Keterangan" ],
      File:[ null,
        "Fail" ],
      Line:[ null,
        "Baris" ],
      Column:[ null,
        "Lajur" ],
      "Invalid nesting of selectors found":[ null,
        "Menemui sarang pemilih yang tidak sah" ],
      "A CSS syntax error was encountered":[ null,
        "Menemui ralat sintaks CSS" ],
      "Your FTL is not valid.":[ null,
        "FTL anda tidak sah." ],
      "Your FTL file could not be parsed.":[ null,
        "Fail FTL anda tidak dapat dihuraikan." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Skrip jauh tidak dibenarkan mengikut Polisi Add-on." ],
      "Inline scripts blocked by default":[ null,
        "Skrip sebaris disekat secara piawai" ],
      "Unadvised 3rd-party JS library":[ null,
        "Pustaka JS pihak ke-3 yang tidak disyorkan" ],
      "Known JS library detected":[ null,
        "Mengesan pustaka JS yang diketahui" ],
      "{{api}} is not supported":[ null,
        "{{api}} tidak disokong" ],
      "This API has not been implemented by Firefox.":[ null,
        "API ini tidak dilaksanakan oleh Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` dipanggil dengan hujah keempat yang dipercayai." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "" ],
      "Content script file could not be found.":[ null,
        "Fail skrip kandungan tidak dapat ditemui." ],
      "Content script file could not be found":[ null,
        "Fail skrip kandungan tidak dapat ditemui" ],
      "Content script file name should not be empty.":[ null,
        "Nama fail skrip kandungan tidak boleh kosong." ],
      "Content script file name should not be empty":[ null,
        "Nama fail skrip kandungan tidak boleh kosong" ],
      "JavaScript syntax error":[ null,
        "Ralat sintaks JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Global tidak dijangka diluluskan sebagai hujah" ],
      "Use of document.write strongly discouraged.":[ null,
        "Penggunaan document.write sangat tidak digalakkan." ],
      "Banned 3rd-party JS library":[ null,
        "Pustaka JS pihak ke-3 yang disekat" ],
      "Your JSON contains block comments.":[ null,
        "JSON anda mengandungi komen blok." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Kunci pendua tidak dibenarkan dalam fail JSON." ],
      "Your JSON is not valid.":[ null,
        "JSON anda tidak sah." ],
      "Your JSON file could not be parsed.":[ null,
        "Fail JSON anda tidak dapat dihuraikan." ],
      "We were unable to decompress the zip file.":[ null,
        "Kami tidak dapat menyahmampat fail zip." ],
      "manifest.json was not found":[ null,
        "manifest.json tidak ditemui" ],
      "File is too large to parse.":[ null,
        "Fail terlalu besar untuk dihurai." ],
      "Hidden file flagged":[ null,
        "Fail tersorok ditanda" ],
      "Flagged filename found":[ null,
        "Menemui nama fail yang ditanda" ],
      "Flagged file extensions found":[ null,
        "Menemui ekstensi fail yang ditanda" ],
      "Package contains duplicate entries":[ null,
        "Pakej mengandungi penyertaan berganda" ],
      "Flagged file type found":[ null,
        "Menemui jenis fail yang ditanda" ],
      "Package already signed":[ null,
        "Pakej sudah ditandatangani" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Add-ons Firefox tidak diizinkan melaksanakan melombong syiling." ],
      "String name is reserved for a predefined message":[ null,
        "Nama string dikhaskan untuk mesej yang telah ditetapkan" ],
      "Placeholder for message is missing":[ null,
        "Ruang letak mesej telah hilang" ],
      "A placeholder used in the message is not defined.":[ null,
        "Ruang letak yang digunakan dalam mesej tidak ditakrif." ],
      "Placeholder name contains invalid characters":[ null,
        "Nama ruang letak mengandungi aksara yang tidak sah" ],
      "Placeholder is missing the content property":[ null,
        "Ruang letak tiada sifat kandungan" ],
      "Translation string is missing the message property":[ null,
        "String terjemahan kehilangan sifat mesej" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Sifat mesej tiada \"message\" ditetapkan untuk string (https://mzl.la/2DSBTjA)." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" dalam manifest.json bukan nilai yang sah" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Lihat https://mzl.la/20PenXl (Dokumen MDN) untuk maklumat lanjut." ],
      "The \"name\" property must be a string.":[ null,
        "Sifat \"name\" mesti satu string." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Lihat http://mzl.la/1STmr48 (Dokumen MDN) untuk maklumat lanjut." ],
      "The \"version\" property must be a string.":[ null,
        "Sifat \"version\" mesti satu string." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Lihat http://mzl.la/1kXIADa (Dokumen MDN) untuk maklumat lanjut." ],
      "The field is invalid.":[ null,
        "Medan ini tidak sah." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Sifat \"version\" menggunakan format khusus-Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Lihat https://mzl.la/1ZOhoEN (Dokumen MDN) untuk maklumat lanjut." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" tidak dibenarkan." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Sifat \"update_url\" tidak digunakan oleh Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" tidak diperlukan." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Ikon yang ditakrif dalam manifes tidak dapat ditemui dalam pakej." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Ikon tidak ditemui dalam \"%(path)s\"." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Skrip latar belakang tidak ditemui dalam \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Halaman latar belakang tidak ditemui dalam \"%(path)s\"." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Skrip kandungan yang ditakrif dalam manifes tidak ditemui dalam \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Fail css skrip kandungan yang ditakrif dalam manifes tidak ditemui dalam \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "" ],
      "Forbidden content found in add-on.":[ null,
        "Kandungan yang dilarang ditemui dalam add-on." ],
      "This add-on contains forbidden content.":[ null,
        "Add-on ini ada kandungan yang dilarang." ],
      "Icons must be square.":[ null,
        "Ikon mesti segi empat." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikon dalam \"%(path)s\" mesti segi empat." ],
      "The size of the icon does not match the manifest.":[ null,
        "Saiz ikon tidak sepadan dengan manifes." ],
      "Corrupt image file":[ null,
        "Fail imej rosak" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Fail ikon yang dijangka dalam \"%(path)s\" sudah rosak" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "" ],
      "Theme image file has an unsupported file extension":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "" ],
      "Theme image file has an unsupported mime type":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "\"default_locale\" tiada lokalisasi." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" tiada lokalisasi tapi ada \"_locales\"." ],
      "Unsupported image extension":[ null,
        "Ekstensi imej yang tidak disokong" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikon hendaklah samada JPG/JPEG, WebP, GIF, PNG atau SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "Direktori bahasa kosong" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Fail messages.json tiada dalam \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "Jenis keizinan yang tidak disokong." ],
      "The field is required.":[ null,
        "Medan ini diperlukan." ],
      "Unknown permission.":[ null,
        "Izin tidak diketahui." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Lihat https://mzl.la/1R1n1t0 (Dokumen MDN) untuk maklumat lanjut." ] } } }