module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=1; plural=0;",
        lang:"zh_TW" },
      "Validation Summary:":[ null,
        "驗證摘要:" ],
      Code:[ null,
        "程式碼" ],
      Message:[ null,
        "訊息" ],
      Description:[ null,
        "描述" ],
      File:[ null,
        "檔案" ],
      Line:[ null,
        "行" ],
      Column:[ null,
        "欄" ],
      "Invalid nesting of selectors found":[ null,
        "找到無效的巢狀選擇器" ],
      "A CSS syntax error was encountered":[ null,
        "發生 CSS 語法錯誤" ],
      "Your FTL is not valid.":[ null,
        "您的 FTL 無效。" ],
      "Your FTL file could not be parsed.":[ null,
        "無法剖析您的 FTL 檔案。" ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "依照附加元件政策，不允許遠端指令碼。" ],
      "Inline scripts blocked by default":[ null,
        "預設封鎖行內指令碼" ],
      "Unadvised 3rd-party JS library":[ null,
        "不建議使用的第三方 JS 程式庫" ],
      "Known JS library detected":[ null,
        "偵測到已知的 JS 程式庫" ],
      "{{api}} is not supported":[ null,
        "不支援 {{api}}" ],
      "This API has not been implemented by Firefox.":[ null,
        "Firefox 尚未實作此 API。" ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "Manifest Version 3 當中已移除「{{api}}」（`manifest_version` 屬性）" ],
      "{{api}} is deprecated":[ null,
        "{{api}} 已棄用" ],
      "This API has been deprecated by Firefox.":[ null,
        "Firefox 已棄用此 API。" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "「{{api}}」已棄用，或尚未實作" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "使用 truthy fourth argument 呼叫了 addEventListener。" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "Firefox 版本 {{minVersion}} 不支援 {{api}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "指定的最小 Firefox 版本尚未實作此 API。" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "Firefox for Android 版本 {{minVersion}} 不支援 {{api}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "指定的最小 Firefox for Android 版本尚未實做此 API。" ],
      "Content script file could not be found.":[ null,
        "找不到內容指令碼檔案。" ],
      "Content script file could not be found":[ null,
        "找不到內容指令碼檔案" ],
      "Content script file name should not be empty.":[ null,
        "內容指令碼檔案名稱不應為空白。" ],
      "Content script file name should not be empty":[ null,
        "內容指令碼檔案名稱不應為空白" ],
      "JavaScript syntax error":[ null,
        "JavaScript 語法錯誤" ],
      "Unexpected global passed as an argument":[ null,
        "未預期的全域變數被作為引數傳遞" ],
      "Use of document.write strongly discouraged.":[ null,
        "非常不建議使用 document.write。" ],
      "Banned 3rd-party JS library":[ null,
        "被禁止的第三方 JS 程式庫" ],
      "Your JSON contains block comments.":[ null,
        "您的 JSON 包含區塊注解。" ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "JSON 檔案中不允許使用重複的鍵值。" ],
      "Your JSON is not valid.":[ null,
        "您的 JSON 無效。" ],
      "Your JSON file could not be parsed.":[ null,
        "無法剖析您的 JSON 檔案。" ],
      "Reserved filename found.":[ null,
        "找到保留的檔案名稱。" ],
      "We were unable to decompress the zip file.":[ null,
        "無法解壓縮 zip 檔案。" ],
      "manifest.json was not found":[ null,
        "找不到 manifest.json" ],
      "File is too large to parse.":[ null,
        "檔案太大無法剖析。" ],
      "Hidden file flagged":[ null,
        "標示了隱藏檔案" ],
      "Flagged filename found":[ null,
        "找到被標記的檔案名稱" ],
      "Flagged file extensions found":[ null,
        "找到被標記的檔案副檔名" ],
      "Package contains duplicate entries":[ null,
        "封包包含重複項目" ],
      "Flagged file type found":[ null,
        "找到被標記的檔案類型" ],
      "Package already signed":[ null,
        "封包已簽名" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox 附加元件中不允許進行挖礦。" ],
      "String name is reserved for a predefined message":[ null,
        "字串名稱是為預設訊息保留的名稱" ],
      "Placeholder for message is missing":[ null,
        "缺少訊息的預留位置" ],
      "A placeholder used in the message is not defined.":[ null,
        "未定義訊息中使用的預留位置。" ],
      "Placeholder name contains invalid characters":[ null,
        "預留位置名稱包含無效字元" ],
      "Placeholder is missing the content property":[ null,
        "缺少預留位置的內容屬性" ],
      "Translation string is missing the message property":[ null,
        "翻譯字串缺少訊息屬性" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "字串中，未為訊息設定「message」屬性（https://mzl.la/2DSBTjA）。" ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "請參考 https://mzl.la/2Qn0fWC（MDN 文件）上的更多資訊。" ],
      "Invalid host permission.":[ null,
        "host 權限無效。" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "manifest.json 當中的「manifest_version」不是有效值" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "請參考 https://mzl.la/20PenXl（MDN 文件）上的更多資訊。" ],
      "The \"name\" property must be a string.":[ null,
        "「name」屬性必須是字串。" ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "請參考 http://mzl.la/1STmr48（MDN 文件）上的更多資訊。" ],
      "The \"version\" property must be a string.":[ null,
        "「version」屬性必須是字串。" ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "請參考 http://mzl.la/1kXIADa（MDN 文件）上的更多資訊。" ],
      "The field is invalid.":[ null,
        "欄位無效。" ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "「version」屬性使用了 Firefox 專屬格式。" ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "請參考 https://mzl.la/1ZOhoEN（MDN 文件）上的更多資訊。" ],
      "\"update_url\" is not allowed.":[ null,
        "不允許「update_url」。" ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Firefox 不使用「update_url」屬性。" ],
      "\"strict_max_version\" not required.":[ null,
        "「strict_max_version」不是必要的。" ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "無法在封裝檔案找到安裝資訊中定義的圖示。" ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "無法在「%(path)s」找到圖示。" ],
      "A background script defined in the manifest could not be found.":[ null,
        "找不到安裝資訊檔中定義的背景指令碼。" ],
      "A background page defined in the manifest could not be found.":[ null,
        "找不到安裝資訊檔中定義的背景頁面。" ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "無法在「%(path)s」找到背景指令碼。" ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "無法在「%(path)s」找到背景頁面。" ],
      "A content script defined in the manifest could not be found.":[ null,
        "找不到安裝資訊檔中定義的內容指令碼。" ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "找不到安裝資訊檔中定義的內容指令碼 CSS 檔案。" ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "無法在「%(path)s」找到安裝資訊檔中定義的內容指令碼。" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "無法在「%(path)s」找到安裝資訊檔中定義的內容指令碼 CSS 檔案。" ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "找不到安裝資訊檔中定義的字典檔案。" ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "無法在「%(path)s」找到安裝資訊檔中定義的字典檔案。" ],
      "The manifest contains multiple dictionaries.":[ null,
        "安裝資訊檔中包含多個字典。" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "不支援在安裝資訊檔中定義多個字典。" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "安裝資訊檔中包含字典物件，但是是空白的。" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "安裝資訊檔中定義了字典物件，但是是空白的。" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "安裝資訊中包含字典，但沒有 ID 屬性。" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "在安裝資訊檔中找到字典，但沒有設定 ID。" ],
      "Forbidden content found in add-on.":[ null,
        "附加元件中出現被禁止的內容。" ],
      "This add-on contains forbidden content.":[ null,
        "此附加元件包含被禁止的內容。" ],
      "Icons must be square.":[ null,
        "圖示必須是正方形。" ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "位於「%(path)s」的圖示應為正方形。" ],
      "The size of the icon does not match the manifest.":[ null,
        "圖示大小與安裝資訊檔不同。" ],
      "Corrupt image file":[ null,
        "圖檔已損壞" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "位於「%(path)s」的圖示檔案已損壞。" ],
      "This property has been deprecated.":[ null,
        "此屬性已棄用。" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "此佈景主題的 LWT 別名，已於 Firefox 70 移除。" ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "請參考 https://mzl.la/2T11Lkc（MDN 文件）的更多資訊。" ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "無法在「%(path)s」找到「%(type)s」的佈景主題圖片" ],
      "Corrupted theme image file":[ null,
        "損壞的佈景主題圖檔" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "位於「%(path)s」的佈景主題圖檔已毀損" ],
      "Theme image file has an unsupported file extension":[ null,
        "此圖片使用不支援的副檔名" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "位於「%(path)s」的佈景主題圖檔，副檔名不支援" ],
      "Theme image file has an unsupported mime type":[ null,
        "佈景主題圖檔的 MIME 類型不受支援" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "位於「%(path)s」的佈景主題圖檔，其 MIME 類型「%(mime)s」不受支援" ],
      "Theme image file mime type does not match its file extension":[ null,
        "佈景主題圖檔的 MIME 類型，與其副檔名不符" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "位於「%(path)s」的佈景主題圖檔，其 MIME 類型「%(mime)s」與副檔名不符" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "「default_locale」缺少在地化內容。" ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "缺少「default_locale」但有「_locales」存在。" ],
      "Unsupported image extension":[ null,
        "不支援的圖片副檔名" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "圖示格式應為 JPG/JPEG、WebP、GIF、PNG 或 SVG 任一。" ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "「applications」屬性被「browser_specific_settings」屬性覆蓋" ],
      "Empty language directory":[ null,
        "語言目錄空白" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "無法在「%(path)s」找到 messages.json 檔案。" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "指定的最小 Firefox 版本，不支援安裝資訊鍵值" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "指定的最小 Firefox 版本，不支援權限" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "指定的最小 Firefox for Android 版本，不支援安裝資訊鍵值" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "指定的最小 Firefox for Android 版本，不支援權限" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "不允許連結到「addons.mozilla.org」" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "不允許將首頁連結指到「addons.mozilla.org」" ],
      "The permission type is unsupported.":[ null,
        "不受支援的權限類型。" ],
      "The field is required.":[ null,
        "此欄位是必要的。" ],
      "Unknown permission.":[ null,
        "權限未知。" ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "請參考 https://mzl.la/1R1n1t0（MDN 文件）上的更多資訊。" ] } } }