module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=1; plural=0;",
        lang:"zh_CN" },
      "Validation Summary:":[ null,
        "验证概要：" ],
      Code:[ null,
        "代码" ],
      Message:[ null,
        "消息" ],
      Description:[ null,
        "描述" ],
      File:[ null,
        "文件" ],
      Line:[ null,
        "行" ],
      Column:[ null,
        "列" ],
      "Invalid nesting of selectors found":[ null,
        "发现无效的选择器嵌套" ],
      "A CSS syntax error was encountered":[ null,
        "遇到一个CSS 语法错误" ],
      "Your FTL is not valid.":[ null,
        "您的 FTL 文件无效。" ],
      "Your FTL file could not be parsed.":[ null,
        "您的 FTL 文件无法解析。" ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "依照附加组件政策，不允许执行远程脚本。" ],
      "Inline scripts blocked by default":[ null,
        "内联脚本默认被屏蔽" ],
      "Unadvised 3rd-party JS library":[ null,
        "不建议使用的第三方 JS 库" ],
      "Known JS library detected":[ null,
        "检测到已知 JS 库" ],
      "{{api}} is not supported":[ null,
        "不支持 {{api}}" ],
      "This API has not been implemented by Firefox.":[ null,
        "Firefox 尚未实现此 API。" ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "“{{api}}”已从 Manifest V3 中删除（“manifest_version”属性）" ],
      "{{api}} is deprecated":[ null,
        "{{api}} 已不赞成使用" ],
      "This API has been deprecated by Firefox.":[ null,
        "此 API 已不赞成在 Firefox 上使用。" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "“{{api}}”已不赞成使用或尚未实现" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "调用了 addEventListener，且第四个参数为真。" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "Firefox 版本 {{minVersion}} 不支持 {{api}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "给定的最低 Firefox 版本尚未实现此 API" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "适用于 Android 的 Firefox 版本 {{minVersion}} 不支持 {{api}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "给定的最低适用于 Android 的 Firefox 版本尚未实现此 API" ],
      "Content script file could not be found.":[ null,
        "无法找到内容脚本文件。" ],
      "Content script file could not be found":[ null,
        "无法找到内容脚本文件" ],
      "Content script file name should not be empty.":[ null,
        "内容脚本文件名不应为空。" ],
      "Content script file name should not be empty":[ null,
        "内容脚本文件名不应为空" ],
      "JavaScript syntax error":[ null,
        "JavaScript 语法错误" ],
      "Unexpected global passed as an argument":[ null,
        "意外的将 global 传递为一个参数" ],
      "Use of document.write strongly discouraged.":[ null,
        "强烈不建议使用 document.write。" ],
      "Banned 3rd-party JS library":[ null,
        "被禁止的第三方 JS 库" ],
      "Your JSON contains block comments.":[ null,
        "您的 JSON 包含块注释。" ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "JSON 文件中不允许有重复的键。" ],
      "Your JSON is not valid.":[ null,
        "您的 JSON 无效。" ],
      "Your JSON file could not be parsed.":[ null,
        "无法解析您的 JSON 文件。" ],
      "Reserved filename found.":[ null,
        "发现保留的文件名。" ],
      "We were unable to decompress the zip file.":[ null,
        "我们无法解压缩该 zip 文件。" ],
      "manifest.json was not found":[ null,
        "未找到 manifest.json" ],
      "File is too large to parse.":[ null,
        "文件太大而未解析。" ],
      "Hidden file flagged":[ null,
        "隐藏文件已被标记" ],
      "Flagged filename found":[ null,
        "找到已标记的文件名" ],
      "Flagged file extensions found":[ null,
        "找到已标记的文件扩展名" ],
      "Package contains duplicate entries":[ null,
        "包包含重复的项" ],
      "Flagged file type found":[ null,
        "找到已标记的文件类型" ],
      "Package already signed":[ null,
        "包已被签名" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox 附加组件不得进行挖矿。" ],
      "String name is reserved for a predefined message":[ null,
        "字符串名称已为预定义消息保留" ],
      "Placeholder for message is missing":[ null,
        "消息占位符缺失" ],
      "A placeholder used in the message is not defined.":[ null,
        "消息中已使用的一个占位符未定义。" ],
      "Placeholder name contains invalid characters":[ null,
        "占位符名称包含无效字符" ],
      "Placeholder is missing the content property":[ null,
        "占位符缺少内容属性" ],
      "Translation string is missing the message property":[ null,
        "翻译字符串缺少消息属性" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "一个字符串没有设置 \"message\" 消息属性 (https://mzl.la/2DSBTjA)。" ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "详细信息请参阅 https://mzl.la/2Qn0fWC （MDN 文档）。" ],
      "Invalid host permission.":[ null,
        "主机权限无效。" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "manifest.json 中的 \"manifest_version\" 不是有效的值" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "详细信息请参阅 https://mzl.la/20PenXl (MDN文档)。" ],
      "The \"name\" property must be a string.":[ null,
        "“name”属性必须是字符串。" ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "详细信息请参阅 http://mzl.la/1STmr48 (MDN 文档)。" ],
      "The \"version\" property must be a string.":[ null,
        "“version”属性必须是字符串。" ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "详细信息请参阅 http://mzl.la/1kXIADa (MDN文档)。" ],
      "The field is invalid.":[ null,
        "该字段无效。" ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "\"version\" 属性须使用 Firefox 要求的格式。" ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "详细信息请参阅 https://mzl.la/1ZOhoEN (MDN 文档)。" ],
      "\"update_url\" is not allowed.":[ null,
        "不应含有“update_url”。" ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Firefox 不使用 \"update_url\" 属性。" ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" 不是必需的。" ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "manifest 中定义的一个图标未在包中找到。" ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "无法在“%(path)s”找到图标。" ],
      "A background script defined in the manifest could not be found.":[ null,
        "未找到清单文件中定义的后台脚本。" ],
      "A background page defined in the manifest could not be found.":[ null,
        "未找到清单文件中定义的背景页面。" ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "无法在“%(path)s”找到后台脚本。" ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "无法在“%(path)s”找到后台页面。" ],
      "A content script defined in the manifest could not be found.":[ null,
        "未找到清单文件中定义的内容脚本。" ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "未找到清单文件中定义的内容脚本 CSS 文件。" ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "manifest 中定义的一个内容脚本无法在“%(path)s”找到。" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "manifest 中定义的一个内容脚本 css 文件无法在“%(path)s”找到。" ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "未找到清单文件中定义的字典文件。" ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "未在“%(path)s”找到清单文件中定义的字典文件。" ],
      "The manifest contains multiple dictionaries.":[ null,
        "清单文件中包含多个字典。" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "不支持在清单文件中定义多个字典。" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "清单文件中包含字典对象，但是为空。" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "清单文件中定义了字典对象，但是为空。" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "清单文件中包含字典对象，但无 ID 属性。" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "清单文件中找到字典，但未设置 ID。" ],
      "Forbidden content found in add-on.":[ null,
        "附加组件含有违禁内容。" ],
      "This add-on contains forbidden content.":[ null,
        "此附加组件包含被禁止的内容。" ],
      "Icons must be square.":[ null,
        "图标必须为正方形。" ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "位于“%(path)s”的图标必须为正方形。" ],
      "The size of the icon does not match the manifest.":[ null,
        "图标的大小与清单不匹配。" ],
      "Corrupt image file":[ null,
        "图像损坏" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "应该位于“%(path)s”的图标文件已损坏" ],
      "This property has been deprecated.":[ null,
        "此属性已不赞成使用。" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "此主题的 LWT 别名已在 Firefox 70 中移除。" ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "详细信息请参阅 https://mzl.la/2T11Lkc (MDN 文档)。" ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "未在“%(path)s”找到“%(type)s”的主题图像" ],
      "Corrupted theme image file":[ null,
        "损坏的主题图像文件" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "位于“%(path)s”的主题图像文件已损坏" ],
      "Theme image file has an unsupported file extension":[ null,
        "该主题图像文件使用不支持的扩展名" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "位于“%(path)s”的主题图像文件使用不支持的扩展名" ],
      "Theme image file has an unsupported mime type":[ null,
        "该主题图像使用不支持的 MIME 类型" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "位于“%(path)s”的主题图像文件使用不支持的 MIME 类型：%(mime)s" ],
      "Theme image file mime type does not match its file extension":[ null,
        "该主题图像文件的 MIME 类型与其扩展名不匹配" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "位于“%(path)s”的主题图像文件的 MIME 类型（%(mime)s）与其扩展名不匹配" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "“default_locale”缺少本地化内容。" ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "“_locales”存在但缺少“default_locale”。" ],
      "Unsupported image extension":[ null,
        "不支持的图像扩展名" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "图标应该为 JPG/JPEG、WebP、GIFF、PNG 或 SVG 文件。" ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "“applications”属性已被“browser_specific_settings”属性覆盖" ],
      "Empty language directory":[ null,
        "空的语言目录" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "“%(path)s”中缺少 messages.json 文件" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "指定的最低 Firefox 版本不支持清单文件标识值" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "指定的最低 Firefox 版本不支持权限" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "指定的最低适用于 Android 的 Firefox 版本，不支持清单文件标识值" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "指定的最低适用于 Android 的 Firefox 版本，不支持权限" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "不允许链接到“addons.mozilla.org”" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "不允许将指向“addons.mozilla.org”的链接用于主页" ],
      "The permission type is unsupported.":[ null,
        "不支持该权限类型。" ],
      "The field is required.":[ null,
        "该字段必填。" ],
      "Unknown permission.":[ null,
        "未知权限。" ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "详细信息请参阅 https://mzl.la/1R1n1t0 (MDN 文档)。" ] } } }