import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import swc from '@rollup/plugin-swc';
import { rollup } from 'rollup';
import { minify } from 'terser';

/**
 * Builds the page-world engine without external runtime dependencies.
 *
 * @returns Completion after the current generated source is saved.
 */
export async function buildCanvasEngineSource(): Promise<void> {
    const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
    const destination = path.join(root, 'src/lib/common/canvas-protection/generated');
    const bundle = await rollup({
        input: path.join(root, 'src/lib/common/canvas-protection/engine-entry.ts'),
        treeshake: { moduleSideEffects: false },
        plugins: [commonjs(), resolve({ browser: true, preferBuiltins: false, extensions: ['.ts', '.js'] }), swc({
            swc: { jsc: { target: 'es2022', parser: { syntax: 'typescript' } } },
        })],
    });
    try {
        const { output } = await bundle.generate({ format: 'iife', name: 'canvasEngine', exports: 'named' });
        await mkdir(destination, { recursive: true });
        const { code } = await minify(output[0].code, { format: { comments: false } });
        const source = '/**\n * Standalone page-world engine, generated by the canvas build.\n */\n'
            + `export const CANVAS_ENGINE_SOURCE = ${JSON.stringify(code)};\n`;
        const file = path.join(destination, 'engine-source.ts');
        let previous: string | undefined;
        try {
            previous = await readFile(file, 'utf8');
        } catch (error) {
            if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
                throw error;
            }
        }
        if (source !== previous) {
            await writeFile(file, source);
        }
    } finally {
        await bundle.close();
    }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    await buildCanvasEngineSource();
}
