import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import swc from '@rollup/plugin-swc';
import { rollup } from 'rollup';

/**
 * Builds the page-world engine without external runtime dependencies.
 *
 * @returns Completion after its generated TypeScript source is saved.
 */
export async function buildCanvasEngineSource(): Promise<void> {
    const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
    const destination = path.join(root, 'src/lib/common/canvas-protection/generated');
    const bundle = await rollup({
        input: path.join(root, 'src/lib/common/canvas-protection/engine-entry.ts'),
        treeshake: { moduleSideEffects: false },
        plugins: [commonjs(), resolve({ browser: true, preferBuiltins: false, extensions: ['.ts', '.js'] }), swc({
            swc: { jsc: { target: 'es2022', parser: { syntax: 'typescript' } } },
        })],
    });
    try {
        const { output } = await bundle.generate({ format: 'iife', name: 'canvasEngine', exports: 'named' });
        await mkdir(destination, { recursive: true });
        await writeFile(
            path.join(destination, 'engine-source.ts'),
            '/**\n * Standalone page-world engine, generated by the canvas build.\n */\n'
            + `export const CANVAS_ENGINE_SOURCE = ${JSON.stringify(output[0].code)};\n`,
        );
    } finally {
        await bundle.close();
    }
}

await buildCanvasEngineSource();
