module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);",
        lang:"bs" },
      "Validation Summary:":[ null,
        "Validacija sažetka:" ],
      Code:[ null,
        "Kod" ],
      Message:[ null,
        "Poruka" ],
      Description:[ null,
        "Opis" ],
      File:[ null,
        "Datoteka" ],
      Line:[ null,
        "Linija" ],
      Column:[ null,
        "Kolona" ],
      "Invalid nesting of selectors found":[ null,
        "Pronađeno je nevažeće gnijezdo selektora" ],
      "A CSS syntax error was encountered":[ null,
        "Došlo je do greške kod CSS sintakse" ],
      "Your FTL is not valid.":[ null,
        "Vaš FTL nije ispravan." ],
      "Your FTL file could not be parsed.":[ null,
        "Vaša FTL datoteka se ne može raščlaniti." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Udaljene skripte nisu dozvoljene prema pravilima dodataka." ],
      "Inline scripts blocked by default":[ null,
        "Skripte iste razine su blokirane po izvornim postavkama" ],
      "Unadvised 3rd-party JS library":[ null,
        "Neutvrđena JS biblioteka treće strane" ],
      "Known JS library detected":[ null,
        "Otkrivena poznata JS biblioteka" ],
      "{{api}} is not supported":[ null,
        "{{api}} nije podržan" ],
      "This API has not been implemented by Firefox.":[ null,
        "Ovaj API nije implementiran od Firefoxa." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` se zove 'istinski' četvrti argument." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "" ],
      "Content script file could not be found.":[ null,
        "Sadržaj datoteke skripte nije pronađen." ],
      "Content script file could not be found":[ null,
        "Sadržaj datoteke skripte nije pronađen" ],
      "Content script file name should not be empty.":[ null,
        "Sadržaj naziva datoteke skripte ne bi trebao biti prazan." ],
      "Content script file name should not be empty":[ null,
        "Sadržaj naziva datoteke skripte ne bi trebao biti prazan" ],
      "JavaScript syntax error":[ null,
        "Greška JavaScript sintakse" ],
      "Unexpected global passed as an argument":[ null,
        "Argument je neočekivano prošao kao globalni" ],
      "Use of document.write strongly discouraged.":[ null,
        "Upotreba document.write je snažno obeshrabrena." ],
      "Banned 3rd-party JS library":[ null,
        "Zabranjena JS biblioteka trećih strana" ],
      "Your JSON contains block comments.":[ null,
        "Vaš JSON sadrži blokirane komentare." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Dupli ključevi nisu dozvoljeni u JSON datotekama." ],
      "Your JSON is not valid.":[ null,
        "Vaš JSON nije ispravan." ],
      "Your JSON file could not be parsed.":[ null,
        "Vaša JSON datoteka se ne može raščlaniti." ],
      "We were unable to decompress the zip file.":[ null,
        "Nismo bili u mogućnosti dekompresirati zip datoteku." ],
      "manifest.json was not found":[ null,
        "manifest.json nije pronađen" ],
      "File is too large to parse.":[ null,
        "Datoteka je prevelika za raščlanjivanje." ],
      "Hidden file flagged":[ null,
        "Skrivena datoteka označena zastavicom" ],
      "Flagged filename found":[ null,
        "Pronađeno ime datoteke sa zastavicom" ],
      "Flagged file extensions found":[ null,
        "Pronađeno proširenje datoteke sa zastavicom" ],
      "Package contains duplicate entries":[ null,
        "Pošiljka sadrži duple unose" ],
      "Flagged file type found":[ null,
        "Pronađen tip datoteke sa zastavicom" ],
      "Package already signed":[ null,
        "Pošiljka već potpisana" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox dodacima nije dozvoljeno pokretanje rudarenja novčića." ],
      "String name is reserved for a predefined message":[ null,
        "Naziv stringa je rezervisan za predefiniranu poruku" ],
      "Placeholder for message is missing":[ null,
        "Nedostaje mjesto za poruku" ],
      "A placeholder used in the message is not defined.":[ null,
        "Korisnik mjesta koji se koristi u poruci nije definisan." ],
      "Placeholder name contains invalid characters":[ null,
        "Naziv rezervisanog mjesta sadrži znakove koji nisu ispravni" ],
      "Placeholder is missing the content property":[ null,
        "Nedostaje sadržaj za rezervisano mjesto" ],
      "Translation string is missing the message property":[ null,
        "Stringu za prijevod nedostaje message svojstvo" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Nije podešeno \"message\" svojstvo za string (https://mzl.la/2DSBTjA)." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" u manifest.json nije važeća vrijednost" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Pogledajte https://mzl.la/20PenXl (MDN dokumente) za više informacija." ],
      "The \"name\" property must be a string.":[ null,
        "Svojstvo \"name\" mora biti niz." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Pogledajte http://mzl.la/1STmr48 (MDN dokumente) za više informacija." ],
      "The \"version\" property must be a string.":[ null,
        "Svojstvo \"version\" mora biti niz." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Pogledajte http://mzl.la/1kXIADa (MDN dokumente) za više informacija." ],
      "The field is invalid.":[ null,
        "Polje je nevažeće." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Svojstvo \"version\" koristi Firefoxov specifični format." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Pogledajte https://mzl.la/1ZOhoEN (MDN dokumente) za više informacija." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" nije dozvoljen." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Svojstvo \"update_url\" nije korišteno od strane Firefoxa." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" nije potreban." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Ikona određena u manifestu nije pronađena u pošiljci." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Ikona nije pronađena na \"%(path)s\"." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Pozadinska skripta nije pronađena na \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Pozadinska stranica nije pronađena na \"%(path)s\"." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Sadržaj skripte definisan u manifestu nije pronađen na \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Sadržaj skripte css datoteke u manifestu nije pronađen na \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "" ],
      "Forbidden content found in add-on.":[ null,
        "Zabranjeni sadržaj pronađen u dodatku." ],
      "This add-on contains forbidden content.":[ null,
        "Ovaj dodatak sadrži zabranjeni sadržaj." ],
      "Icons must be square.":[ null,
        "Ikone moraju biti kvadrati." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikona na \"%(path)s\" mora biti kvadrat." ],
      "The size of the icon does not match the manifest.":[ null,
        "Veličina ikone se ne poklapa sa manifestom." ],
      "Corrupt image file":[ null,
        "Oštećena datoteka slike" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Očekivana ikona datoteke na \"%(path)s\" je pokvarena" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "" ],
      "Theme image file has an unsupported file extension":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "" ],
      "Theme image file has an unsupported mime type":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "U \"default_locale\" nedostaje lokalizacija." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Nedostaje \"default_locale\" ali \"_locales\" postoji." ],
      "Unsupported image extension":[ null,
        "Nepodržano proširenje slike" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikone moraju biti JPG/JPEG, WebP, GIF, PNG ili SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "Prazan jezični direktorij" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "messages.json datoteka nedostaje u \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "Tip dozvole nije podržan." ],
      "The field is required.":[ null,
        "Polje je obavezno." ],
      "Unknown permission.":[ null,
        "Nepoznata dozvola." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Pogledajte https://mzl.la/1R1n1t0 (MDN dokumente) za više informacija." ] } } }