module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"he" },
      "Validation Summary:":[ null,
        "סיום בדיקה:" ],
      Code:[ null,
        "קוד" ],
      Message:[ null,
        "הודעה" ],
      Description:[ null,
        "תיאור" ],
      File:[ null,
        "קובץ" ],
      Line:[ null,
        "שורה" ],
      Column:[ null,
        "עמודה" ],
      "Invalid nesting of selectors found":[ null,
        "נמצא קינון שגוי של בוררים" ],
      "A CSS syntax error was encountered":[ null,
        "התגלתה שגיאת תחביר CSS" ],
      "Your FTL is not valid.":[ null,
        "ה־FTL שלך שגוי." ],
      "Your FTL file could not be parsed.":[ null,
        "לא ניתן לפענח את קובץ ה־FTL שלך." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "תסריטים מרוחקים אסורים לפי מדיניות התוספת." ],
      "Inline scripts blocked by default":[ null,
        "תסריטים פנימיים חסומים כבררת מחדל" ],
      "Unadvised 3rd-party JS library":[ null,
        "ספריית JS בלתי מומלצת מצד שלישי" ],
      "Known JS library detected":[ null,
        "זוהתה ספריית JS מוכרת" ],
      "{{api}} is not supported":[ null,
        "אין תמיכה ב־{{api}}" ],
      "This API has not been implemented by Firefox.":[ null,
        "ה־API הזה לא הוטמע על ידי Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "‏{{api}} אינו נתמך ב־Firefox בגרסה {{minVersion}}" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "‏{{api}} אינו נתמך ב־Firefox עבור Android בגרסה {{minVersion}}" ],
      "Content script file could not be found.":[ null,
        "לא ניתן למצוא קובץ תסריט תוכן." ],
      "Content script file could not be found":[ null,
        "לא ניתן למצוא קובץ תסריט תוכן" ],
      "Content script file name should not be empty.":[ null,
        "שם קובץ תסריט תוכן לא אמור להיות ריק." ],
      "Content script file name should not be empty":[ null,
        "שם קובץ תסריט תוכן לא אמור להיות ריק" ],
      "JavaScript syntax error":[ null,
        "שגיאת תחביר JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "משתנה גלובלי בלתי צפוי הועבר כארגומנט" ],
      "Use of document.write strongly discouraged.":[ null,
        "מומלץ מאוד שלא להשתמש ב־document.write." ],
      "Banned 3rd-party JS library":[ null,
        "ספריית JS חסומה מצד שלישי" ],
      "Your JSON contains block comments.":[ null,
        "ה־JSON שלך מכיל מקטעי הערות." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "אסור להשתמש במפתחות כפולים בקובץ JSON." ],
      "Your JSON is not valid.":[ null,
        "ה־JSON שלך שגוי." ],
      "Your JSON file could not be parsed.":[ null,
        "לא ניתן לפענח את קובץ ה־JSON שלך." ],
      "Reserved filename found.":[ null,
        "נמצא שם קובץ שמור." ],
      "We were unable to decompress the zip file.":[ null,
        "לא הצלחנו לחלץ את קובץ ה־zip." ],
      "manifest.json was not found":[ null,
        "‏manifest.json לא נמצא" ],
      "File is too large to parse.":[ null,
        "הקובץ גדול מכדי לפענח." ],
      "Hidden file flagged":[ null,
        "קובץ מוסתר סומן בדגל" ],
      "Flagged filename found":[ null,
        "נמצא שם קובץ שסומן בדגל" ],
      "Flagged file extensions found":[ null,
        "נמצאה סיומת קובץ שסומנה בדגל" ],
      "Package contains duplicate entries":[ null,
        "החבילה מכילה רשומות כפולות" ],
      "Flagged file type found":[ null,
        "נמצא סוג קובץ שסומן בדגל" ],
      "Package already signed":[ null,
        "החבילה כבר נחתמה" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "התוספות של Firefox אינן מורשות להריץ כורי מטבעות." ],
      "String name is reserved for a predefined message":[ null,
        "שם המחרוזת שמור להודעה שהוגדרה מראש" ],
      "Placeholder for message is missing":[ null,
        "חסר ממלא מקום להודעה" ],
      "A placeholder used in the message is not defined.":[ null,
        "ממלא מקום, שנעשה בו שימוש בהודעה, אינו מוגדר." ],
      "Placeholder name contains invalid characters":[ null,
        "שם ממלא המקום מכיל תווים בלתי תקינים" ],
      "Placeholder is missing the content property":[ null,
        "לממלא המקום חסר המאפיין content" ],
      "Translation string is missing the message property":[ null,
        "למחרוזת התרגום חסר המאפיין message" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "לא הוגדר מאפיין „message” למחרוזת (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "יש לעיין ב־https://mzl.la/2Qn0fWC (מסמכי MDN) למידע נוסף." ],
      "Invalid host permission.":[ null,
        "הרשאת מארח לא חוקית." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "הערך של „manifest_version” בתוך manifest.json שגוי" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "יש לעיין ב־https://mzl.la/20PenXl (מסמכי MDN) למידע נוסף." ],
      "The \"name\" property must be a string.":[ null,
        "המאפיין „name” חייב להיות מחרוזת." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "יש לעיין ב־http://mzl.la/1STmr48 (מסמכי MDN) למידע נוסף." ],
      "The \"version\" property must be a string.":[ null,
        "המאפיין „version” חייב להיות מחרוזת." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "יש לעיין ב־http://mzl.la/1kXIADa (מסמכי MDN) למידע נוסף." ],
      "The field is invalid.":[ null,
        "השדה שגוי." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "המאפיין „version” משתמש בתבנית ייעודית ל־Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "יש לעיין ב־https://mzl.la/1ZOhoEN (מסמכי MDN) למידע נוסף." ],
      "\"update_url\" is not allowed.":[ null,
        "אסור להשתמש ב־„update_url”." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "המאפיין „update_url” אינו בשימוש ב־Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "„strict_max_version” לא נחוץ." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "" ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "לא ניתן למצוא את הסמל ב־„%(path)s”." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "לא ניתן למצוא את סקריפט הרקע ב־„%(path)s”." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "לא ניתן למצוא את עמוד הרקע ב־„%(path)s”." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "The manifest contains multiple dictionaries.":[ null,
        "" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "" ],
      "Forbidden content found in add-on.":[ null,
        "בתוספת נמצא תוכן אסור." ],
      "This add-on contains forbidden content.":[ null,
        "תוספת זו מכילה תוכן אסור." ],
      "Icons must be square.":[ null,
        "הסמלים חייבים להיות מרובעים." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "הסמל ב־„%(path)s” חייב להיות מרובע." ],
      "The size of the icon does not match the manifest.":[ null,
        "" ],
      "Corrupt image file":[ null,
        "קובץ התמונה פגום" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "קובץ הסמל המצופה ב־„%(path)s” פגום" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "" ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "יש לעיין ב־https://mzl.la/2T11Lkc (מסמכי MDN) למידע נוסף." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "לא ניתן למצוא את תמונת ערכת הנושא עבור ״%(type)s״ ב־״%(path)s״" ],
      "Corrupted theme image file":[ null,
        "קובץ התמונה של ערכת הנושא פגום" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "קובץ תמונת ערכת הנושא ב״%(path)s״ פגום" ],
      "Theme image file has an unsupported file extension":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "" ],
      "Theme image file has an unsupported mime type":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "ל־„default_locale” חסרים תרגומים." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "ה־„default_locale” חסר אבל ה־„‎_locales” קיים." ],
      "Unsupported image extension":[ null,
        "סוג קובץ התמונה לא נתמך" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "הסמלים אמורים להיות אחד מסוגי התמונות הבאים: JPG/JPEG‏, WebP‏, GIF‏, PNG או SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "תיקיית שפה ריקה" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "הקובץ messages.json חסר תחת „%(path)s”" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "קישורים המפנים אל \"addons.mozilla.org\" אינם מורשים לשימוש עבור דף הבית" ],
      "The permission type is unsupported.":[ null,
        "סוג ההרשאה אינו נתמך." ],
      "The field is required.":[ null,
        "שדה זה נחוץ." ],
      "Unknown permission.":[ null,
        "הרשאה לא ידועה." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "יש לעיין ב־https://mzl.la/1R1n1t0 (מסמכי MDN) למידע נוסף." ] } } }