module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=3; plural=(n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < 20)) ? 1 : 2);",
        lang:"ro" },
      "Validation Summary:":[ null,
        "Rezumatul validărilor:" ],
      Code:[ null,
        "Cod" ],
      Message:[ null,
        "Mesaj" ],
      Description:[ null,
        "Descriere" ],
      File:[ null,
        "Fișier" ],
      Line:[ null,
        "Rând" ],
      Column:[ null,
        "Coloană" ],
      "Invalid nesting of selectors found":[ null,
        "S-a depistat o imbricare nevalidă a selectorilor" ],
      "A CSS syntax error was encountered":[ null,
        "S-a depistat o eroare de sintaxă CSS" ],
      "Your FTL is not valid.":[ null,
        "FTL-ul tău nu este valid." ],
      "Your FTL file could not be parsed.":[ null,
        "Fișierul FTL nu a putut fi analizat." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Scripturile la distanță nu sunt permise conform politicilor privind suplimentele." ],
      "Inline scripts blocked by default":[ null,
        "Scripturile inline sunt blocate implicit" ],
      "Unadvised 3rd-party JS library":[ null,
        "Bibliotecă JS de la terți nerecomandată" ],
      "Known JS library detected":[ null,
        "S-a depistat o bibliotecă JS cunoscută" ],
      "{{api}} is not supported":[ null,
        "{{api}} nu are suport" ],
      "This API has not been implemented by Firefox.":[ null,
        "Acest API nu a fost implementat de Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` a fost apelat cu un al patrulea argument adevărat." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} nu are suport în versiunea Firefox {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Acest API nu este implementat de versiunea minimă indicată de Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} nu are suport în Firefox pentru versiunea Android {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Acest API nu este implementat de versiunea minimă indicată de Firefox pentru Android" ],
      "Content script file could not be found.":[ null,
        "Nu s-a găsit fișierul cu scriptul de conținut." ],
      "Content script file could not be found":[ null,
        "Nu s-a găsit fișierul cu scriptul de conținut" ],
      "Content script file name should not be empty.":[ null,
        "Fișierul cu scriptul de conținut nu trebuie să fie gol." ],
      "Content script file name should not be empty":[ null,
        "Numele fișierului cu scriptul de conținut nu poate fi lăsat gol" ],
      "JavaScript syntax error":[ null,
        "Eroare de sintaxă JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Variabilă globală neașteptată trecută ca argument" ],
      "Use of document.write strongly discouraged.":[ null,
        "Utilizarea document.write este puternic nerecomandată." ],
      "Banned 3rd-party JS library":[ null,
        "Bibliotecă JS de la terți interzisă" ],
      "Your JSON contains block comments.":[ null,
        "Fișierul tău JSON conține blocuri de comentarii." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "În fișierele JSON nu se permit duplicate de chei." ],
      "Your JSON is not valid.":[ null,
        "Fișierul tău JSON nu este valid." ],
      "Your JSON file could not be parsed.":[ null,
        "Fișierul tău JSON nu a putut fi analizat." ],
      "Reserved filename found.":[ null,
        "S-a depistat o denumire de fișier rezervat." ],
      "We were unable to decompress the zip file.":[ null,
        "Nu am reușit să dezarhivăm fișierul zip." ],
      "manifest.json was not found":[ null,
        "Nu s-a găsit fișierul manifest.json" ],
      "File is too large to parse.":[ null,
        "Fișierul este prea mare ca să poată fi analizat." ],
      "Hidden file flagged":[ null,
        "S-a semnalat un fișier ascuns" ],
      "Flagged filename found":[ null,
        "S-a depistat o denumire de fișier semnalat" ],
      "Flagged file extensions found":[ null,
        "S-au depistat extensii de fișiere semnalate" ],
      "Package contains duplicate entries":[ null,
        "Pachetul conține intrări duplicate" ],
      "Flagged file type found":[ null,
        "S-a depistat un tip de fișier semnalat" ],
      "Package already signed":[ null,
        "Pachetul este deja semnat" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Suplimentelor Firefox nu li se permite să ruleze mineri de criptomonede." ],
      "String name is reserved for a predefined message":[ null,
        "Denumirea șirului este rezervată pentru un mesaj predefinit" ],
      "Placeholder for message is missing":[ null,
        "Substituentul pentru mesaj lipsește" ],
      "A placeholder used in the message is not defined.":[ null,
        "Un substituent utilizat în mesaj nu este definit." ],
      "Placeholder name contains invalid characters":[ null,
        "Denumirea substituentului conține caractere nevalide" ],
      "Placeholder is missing the content property":[ null,
        "Substituentului îi lipsește proprietatea de conținut" ],
      "Translation string is missing the message property":[ null,
        "Proprietatea mesajului lipsește în șirul de traducere" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Nu este setată nicio proprietate de mesaj „mesaj” pentru un șir (https://mzl.la/2DSBTjA)." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "„manifest_version\" din manifest.json nu este o valoare validă" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Vezi https://mzl.la/20PenXl (Documentația MDN) pentru mai multe informații." ],
      "The \"name\" property must be a string.":[ null,
        "Proprietatea „name” trebuie să fie un șir." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Vezi http://mzl.la/1STmr48 (Documentația MDN) pentru mai multe informații." ],
      "The \"version\" property must be a string.":[ null,
        "Proprietatea „versiune” trebuie să fie un șir." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Vezi http://mzl.la/1kXIADa (Documentația MDN) pentru mai multe informații." ],
      "The field is invalid.":[ null,
        "Câmpul este nevalid." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Proprietatea „version” folosește un format specific Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Vezi https://mzl.la/1ZOhoEN (Documentația MDN) pentru mai multe informații.\n\n" ],
      "\"update_url\" is not allowed.":[ null,
        "Nu se permite „update_url\"." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Proprietatea „update_url\" nu este folosită de Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "„strict_max_version\" nu este necesar." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "O pictogramă definită în manifest nu se regăsește în pachet." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Pictograma nu a putut fi găsită la „%(path)s”." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Un script de fundal definit în manifest nu a putut fi găsit." ],
      "A background page defined in the manifest could not be found.":[ null,
        "O pagină de fundal definită în manifest nu a putut fi găsită." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Scriptul de fundal nu a putut fi găsit la „%(path)s”." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Pagina de fundal nu a putut fi găsită la „%(path)s”." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Un script de conținut definit în manifest nu a putut fi găsit." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Un fișier css cu script de conținut, definit în manifest nu a putut fi găsit." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Scriptul de conținut definit în manifest nu a putut fi găsit la „%(path)s”." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Fișierul css cu script de conținut definit în manifest nu a putut fi găsit la „%(path)s”." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Un fișier dicționar definit în manifest nu a putut fi găsit." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Fișierul dicționar definit în manifest nu a putut fi găsit la „%(path)s”." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifestul conține mai multe dicționare." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "În manifest au fost definite mai multe dicționare care nu au suport." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifestul conține un obiect de dicționare, dar este gol." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "În manifest a fost definit un obiect de dicționare, dar era gol." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifestul conține un dicționar, dar nu are nicio proprietate ID." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "S-a găsit un dicționar în manifest, dar nu avea setat niciun ID." ],
      "Forbidden content found in add-on.":[ null,
        "S-a depistat conținut interzis în supliment." ],
      "This add-on contains forbidden content.":[ null,
        "Acest supliment are conținut interzis." ],
      "Icons must be square.":[ null,
        "Pictogramele trebuie să fie pătrate." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Pictograma de la „%(path)s” trebuie să fie pătrată." ],
      "The size of the icon does not match the manifest.":[ null,
        "Mărimea pictogramei nu corespunde manifestului." ],
      "Corrupt image file":[ null,
        "Fișier de imagine corupt" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Fișierul pictogramă așteptat, de la „%(path)s” este corupt" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Acest alias LWT de temă a fost eliminat din Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Vezi https://mzl.la/2T11Lkc (Documentația MDN) pentru mai multe informații.\n\n" ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Imaginea temei pentru „%(type)s” nu a putut fi găsită la „%(path)s”" ],
      "Corrupted theme image file":[ null,
        "Fișier imagine al temei corupt" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Fișierul imagine al temei de la „%(path)s” este corupt" ],
      "Theme image file has an unsupported file extension":[ null,
        "Fișierul de imagine al temei are o extensie de fișier fără suport" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Fișierul de imagine al temei de la „%(path)s” are o extensie de fișier fără suport" ],
      "Theme image file has an unsupported mime type":[ null,
        "Fișierul de imagine al temei are un tip mime fără suport" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Fișierul de imagine al temei de la „%(path)s” are un tip mime „%(mime)s” fără suport" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Tipul mime al fișierului de imagine al temei nu se potrivește cu extensia fișierului" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Extensia fișierului de imagine al temei de la „%(path)s” nu se potrivește cu tipul mime „%(mime)s” efectiv" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "„default_locale\" nu are traduceri." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "„default_locale\" lipsește, dar „_locales\" există." ],
      "Unsupported image extension":[ null,
        "Extensie nepermisă de imagine" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Pictogramele trebuie să fie fișiere JPG/JPEG, WebP, GIF, PNG sau SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "Director de limbi gol" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Fișierul messages.json lipsește în „%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Cheia manifestului nu are suport în versiunea Firefox minimă specificată" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Permisiunea nu are suport în versiunea Firefox minimă specificată" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Cheia manifestului nu are suport în versiunea Firefox minimă specificată pentru versiunea Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Permisiunea nu are suport în versiunea Firefox minimă specificată pentru versiunea Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "Tipul de permisiune nu are suport." ],
      "The field is required.":[ null,
        "Câmpul este necesar." ],
      "Unknown permission.":[ null,
        "Permisiune necunoscută." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Vezi https://mzl.la/1R1n1t0 (Documentația MDN) pentru mai multe informații." ] } } }