module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=1; plural=0;",
        lang:"ko" },
      "Validation Summary:":[ null,
        "유효성 검증 요약:" ],
      Code:[ null,
        "코드" ],
      Message:[ null,
        "메시지" ],
      Description:[ null,
        "설명" ],
      File:[ null,
        "파일" ],
      Line:[ null,
        "행" ],
      Column:[ null,
        "열" ],
      "Invalid nesting of selectors found":[ null,
        "선택자 중첩이 잘못됨" ],
      "A CSS syntax error was encountered":[ null,
        "CSS 문법 오류" ],
      "Your FTL is not valid.":[ null,
        "FTL이 유효하지 않습니다." ],
      "Your FTL file could not be parsed.":[ null,
        "FTL 파일을 파싱하지 못했습니다." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "부가기능 정책에 따라 외부 스크립트는 허용되지 않습니다." ],
      "Inline scripts blocked by default":[ null,
        "기본적으로 인라인 스크립트 차단" ],
      "Unadvised 3rd-party JS library":[ null,
        "권장되지 않는 타사 JS 라이브러리" ],
      "Known JS library detected":[ null,
        "알려진 JS 라이브러리 감지됨" ],
      "{{api}} is not supported":[ null,
        "{{api}}는 지원되지 않음" ],
      "This API has not been implemented by Firefox.":[ null,
        "이 API는 Firefox에서 구현되지 않았습니다." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\"가 Manifest 버전 3(`manifest_version` 속성)에서 제거되었습니다." ],
      "{{api}} is deprecated":[ null,
        "{{api}}는 더 이상 사용되지 않습니다." ],
      "This API has been deprecated by Firefox.":[ null,
        "이 API는 Firefox에서 더 이상 사용되지 않습니다." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\"는 더 이상 사용되지 않거나 구현되지 않았습니다." ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` 가 참으로 계산되는 네 번째 인수와 함께 호출되었습니다." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}는 Firefox 버전 {{minVersion}}에서 지원되지 않습니다" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "이 API는 제공된 최소 Firefox 버전에서 구현되지 않습니다" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}}는 안드로이드용 Firefox {{minVersion}}에서 지원되지 않습니다" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "이 API는 제공된 최소 안드로이드용 Firefox 버전에서 구현되지 않습니다" ],
      "Content script file could not be found.":[ null,
        "컨텐츠 스크립트 파일을 찾을 수 없습니다." ],
      "Content script file could not be found":[ null,
        "컨텐츠 스크립트 파일을 찾을 수 없습니다" ],
      "Content script file name should not be empty.":[ null,
        "컨텐츠 스크립트 파일의 이름은 비어 있을 수 없습니다." ],
      "Content script file name should not be empty":[ null,
        "컨텐츠 스크립트 파일의 이름은 비어 있을 수 없습니다" ],
      "JavaScript syntax error":[ null,
        "JavaScript 구문 오류" ],
      "Unexpected global passed as an argument":[ null,
        "예상치 못한 전역이 인수로 전달됨" ],
      "Use of document.write strongly discouraged.":[ null,
        "document.write는 사용하지 않는 것이 좋습니다." ],
      "Banned 3rd-party JS library":[ null,
        "금지된 타사 JS 라이브러리" ],
      "Your JSON contains block comments.":[ null,
        "JSON에 블록 주석이 포함되어 있습니다." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "JSON 파일에서는 중복된 키가 허용될 수 없습니다." ],
      "Your JSON is not valid.":[ null,
        "JSON 파일이 유효하지 않습니다." ],
      "Your JSON file could not be parsed.":[ null,
        "JSON 파일을 파싱하지 못했습니다." ],
      "Reserved filename found.":[ null,
        "예약된 파일명이 있습니다." ],
      "We were unable to decompress the zip file.":[ null,
        "zip 파일을 압출 해제 할 수 없습니다." ],
      "manifest.json was not found":[ null,
        "manifest.json을 찾을 수 없습니다" ],
      "File is too large to parse.":[ null,
        "분석하기에 파일 용량이 너무 큽니다." ],
      "Hidden file flagged":[ null,
        "숨겨진 파일 플래그" ],
      "Flagged filename found":[ null,
        "플래그 파일명 발견" ],
      "Flagged file extensions found":[ null,
        "플래그 파일 확장자 발견" ],
      "Package contains duplicate entries":[ null,
        "패키지에 중복 된 항목이 있습니다" ],
      "Flagged file type found":[ null,
        "플래그 파일 형식 발견" ],
      "Package already signed":[ null,
        "이미 서명 된 패키지" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox 부가기능은 가상화폐 채굴 코드 운영을 허용하지 않습니다." ],
      "String name is reserved for a predefined message":[ null,
        "String 이름이 사전 정의된 메시지에 예약되어 있음" ],
      "Placeholder for message is missing":[ null,
        "메시지 자리 표시자가 없음" ],
      "A placeholder used in the message is not defined.":[ null,
        "메시지에 사용 된 자리 표시자가 정의되지 않았습니다." ],
      "Placeholder name contains invalid characters":[ null,
        "자리 표시자 이름에 잘못된 문자가 포함됨" ],
      "Placeholder is missing the content property":[ null,
        "자리 표시자에 콘텐츠 속성이 없음" ],
      "Translation string is missing the message property":[ null,
        "번역 문자열에 메시지 속성이 없음" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "문자열(https://mzl.la/2DSBTjA)에 \"message\" 메시지 속성이 설정되어 있지 않습니다." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "자세한 정보는 https://mzl.la/2Qn0fWC (MDN 문서)에서 확인할 수 있습니다." ],
      "Invalid host permission.":[ null,
        "잘못된 호스트 권한입니다." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "manifest.json의 \"manifest_version\"이 유효한 값이 아님" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "자세한 정보는 https://mzl.la/20PenXl (MDN 문서)에서 확인할 수 있습니다." ],
      "The \"name\" property must be a string.":[ null,
        "\"name\" 속성은 문자열 이어야 합니다." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "자세한 정보는 http://mzl.la/1STmr48 (MDN 문서)에서 확인할 수 있습니다." ],
      "The \"version\" property must be a string.":[ null,
        "\"version\" 속성은 반드시 문자열 이어야 합니다." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "자세한 정보는 http://mzl.la/1kXIADa (MDN 문서)에서 확인할 수 있습니다." ],
      "The field is invalid.":[ null,
        "필드가 유효하지 않습니다." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "\"version\" 속성은 Firefox만의 특정한 형식을 사용합니다." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "자세한 정보는 https://mzl.la/1ZOhoEN (MDN 문서)에서 볼 수 있습니다." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\"은 허용되지 않습니다." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Firefox에서는 \"update_url\" 속성을 사용하지 않습니다." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\"은 필요하지 않습니다." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "매니페스트에 정의되어 있는 아이콘을 패키지에서 찾을 수 없습니다." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "\"%(path)s\"에서 아이콘을 찾을 수 없습니다." ],
      "A background script defined in the manifest could not be found.":[ null,
        "매니페스트에 정의된 백그라운드 스크립트를 찾을 수 없습니다." ],
      "A background page defined in the manifest could not be found.":[ null,
        "매니페스트에 정의된 백그라운드 페이지를 찾을 수 없습니다." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "\"%(path)s\"에서 백그라운드 스크립트를 찾을 수 없습니다." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "\"%(path)s\"에서 백그라운드 페이지를 찾을 수 없습니다." ],
      "A content script defined in the manifest could not be found.":[ null,
        "매니페스트에 정의된 콘텐트 스크립트를 찾을 수 없습니다." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "매니페스트에 정의된 콘텐트 스크립트 css 파일을 찾을 수 없습니다." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "매니페스트에 정의된 콘텐트 스크립트를 \"%(path)s\"에서 찾을 수 없습니다." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "매니페스트에 서언된 콘텐트 스크립트 CSS 파일을 \"%(path)s\"에서 찾을 수 없습니다." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "매니페이스에 정의된 사전 파일을 찾을 수 없습니다." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "매니페이스에 정의된 사전 파일을 \"%(path)s\"에서 찾을 수 없습니다." ],
      "The manifest contains multiple dictionaries.":[ null,
        "매니페스트가 여러 개의 사전을 포함하고 있습니다." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "지원되지 않는 여러 개의 사전이 매니페스트에 정의되어 있습니다." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "매니페스트가 사전 객체를 포함하고 있지만 비어 있습니다." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "사전 객체는 매니페스트에 정의되었지만 비어 있었습니다." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "매니페스트가 사전을 포함하고 있지만 id 속성이 없습니다." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "매니페스트에서 사전이 발견되었지만, id set이 없습니다." ],
      "Forbidden content found in add-on.":[ null,
        "부가 기능에 금지된 콘텐츠가 있습니다." ],
      "This add-on contains forbidden content.":[ null,
        "이 부가 기능은 금지된 콘텐츠를 포함하고 있습니다." ],
      "Icons must be square.":[ null,
        "아이콘은 사각형이어야 합니다." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "\"%(path)s\"에 있는 아이콘은 사각형이어야 합니다." ],
      "The size of the icon does not match the manifest.":[ null,
        "아이콘의 크기가 매니페스트와 일치하지 않습니다." ],
      "Corrupt image file":[ null,
        "이미지 파일 손상됨" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "\"%(path)s\"에 있는 예상 아이콘 파일이 손상됨" ],
      "This property has been deprecated.":[ null,
        "이 속성은 더 이상 사용되지 않습니다." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "이 테마 LWT 별칭은 Firefox 70 에서 제외되었습니다." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "자세한 정보는 https://mzl.la/2T11Lkc (MDN 문서)에서 확인할 수 있습니다." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "\"%(path)s\"에서 \"%(type)s\"의 테마 이미지를 찾을 수 없습니다." ],
      "Corrupted theme image file":[ null,
        "테마 이미지 파일 손상됨" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "\"%(path)s\"의 테마 이미지 파일 손상됨" ],
      "Theme image file has an unsupported file extension":[ null,
        "테마 이미지 파일에 지원하지 않는 파일 확장자가 있음" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "\"%(path)s\"의 테마 이미지 파일에 지원하지 않는 파일 확장자가 있음" ],
      "Theme image file has an unsupported mime type":[ null,
        "테마 이미지 파일에 지원하지 않는 MIME 타입이 있음" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "\"%(path)s\"에 있는 테마 이미지 파일에 지원하지 않는 MIME 타입 \"%(mime)s\"이 있음" ],
      "Theme image file mime type does not match its file extension":[ null,
        "MIME 타입 테마 이미지 파일이 파일 확장자와 일치하지 않음" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "\"%(path)s\"에 있는 테마 이미지 파일 확장자가 실제 MIME 타입 \"%(mime)s\"와 일치하지 않음" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "\"default_locale\"은 현지화가 되어 있지 않습니다." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\"은 존재하지 않지만 \"_locales\"는 존재합니다." ],
      "Unsupported image extension":[ null,
        "지원되지 않는 이미지 확장자" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "아이콘은 JPG/JPEG, WebP, GIF, PNG 또는 SVG 중 하나여야 합니다." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "\"browser_specific_settings\" 속성으로 재정의된 \"applications\" 속성" ],
      "Empty language directory":[ null,
        "빈 언어 디렉터리" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "\"%(path)s\"에 messages.json 파일이 없음" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "매니페스트 키가 명시된 최소 Firefox 버전에서 지원되지 않음" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "명시된 최소 Firefox 버전에서 지원하지 않는 권한" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "매니페스트 키가 명시된 최소 Android 용 Firefox 버전에서 지원되지 않음" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "명시된 최소 Android 용 Firefox 버전에서 지원하지 않는 권한" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "\"addons.mozilla.org\"에 대한 링크는 허용되지 않습니다." ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "\"addons.mozilla.org\"로 연결되는 링크는 홈페이지에 사용할 수 없습니다." ],
      "The permission type is unsupported.":[ null,
        "지원하지 않는 권한 타입입니다." ],
      "The field is required.":[ null,
        "이 필드는 필수입니다." ],
      "Unknown permission.":[ null,
        "알 수 없는 권한입니다." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "자세한 정보는 https://mzl.la/1R1n1t0 (MDN 문서)에서 확인할 수 있습니다." ] } } }