module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"te" },
      "Validation Summary:":[ null,
        "ధ్రువీకరణ సారాంశం:" ],
      Code:[ null,
        "కోడ్" ],
      Message:[ null,
        "సందేశం" ],
      Description:[ null,
        "వివరణ" ],
      File:[ null,
        "ఫైలు" ],
      Line:[ null,
        "వరుస" ],
      Column:[ null,
        "నిలువు వరుస" ],
      "Invalid nesting of selectors found":[ null,
        "" ],
      "A CSS syntax error was encountered":[ null,
        "CSS సింటాక్స్ లోపం ఏర్పడింది" ],
      "Your FTL is not valid.":[ null,
        "మీ FTL చెల్లదు." ],
      "Your FTL file could not be parsed.":[ null,
        "" ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "పొడగింతల విధానాల ప్రకారం రిమోట్ స్క్రిప్టులు అనుమతించబడవు." ],
      "Inline scripts blocked by default":[ null,
        "inlinescripts అప్రమేయంగా నిరోధించబడతాయి" ],
      "Unadvised 3rd-party JS library":[ null,
        "సూచించబడని 3వ-పక్ష JS లైబ్రరీ" ],
      "Known JS library detected":[ null,
        "తెలిసిన JS లైబ్రరీ కనుగొనబడింది" ],
      "{{api}} is not supported":[ null,
        "{{api}} కు మద్దతు లేదు" ],
      "This API has not been implemented by Firefox.":[ null,
        "ఈ API Firefox ద్వారా అమలు చేయబడలేదు." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "పేర్కొన్న ఆండ్రాయిడ్ కొరకు Firefox కనిష్ఠ వెర్షనులో ఈ API అమలుచేయబడలేదు" ],
      "Content script file could not be found.":[ null,
        "కంటెంట్ స్క్రిప్ట్ ఫైలు కనుగొనబడలేదు." ],
      "Content script file could not be found":[ null,
        "కంటెంట్ స్క్రిప్ట్ ఫైల్ కనుగొనబడలేదు" ],
      "Content script file name should not be empty.":[ null,
        "కంటెంట్ స్క్రిప్ట్ ఫైలు పేరు ఖాళీగా ఉండకూడదు." ],
      "Content script file name should not be empty":[ null,
        "కంటెంట్ స్క్రిప్ట్ ఫైలు పేరు ఖాళీగా ఉండకూడదు" ],
      "JavaScript syntax error":[ null,
        "JavaScript సింటాక్స్ లోపం" ],
      "Unexpected global passed as an argument":[ null,
        "" ],
      "Use of document.write strongly discouraged.":[ null,
        "document.write వాడకం వారించబడింది." ],
      "Banned 3rd-party JS library":[ null,
        "నిషేధించిన 3వ-పక్ష JS లైబ్రరీ" ],
      "Your JSON contains block comments.":[ null,
        "మీ JSONలో బ్లాక్ వ్యాఖ్యలు ఉన్నాయి." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "JSON ఫైళ్ళలో నకిలీ కీలు అనుమతించబడవు." ],
      "Your JSON is not valid.":[ null,
        "మీ JSON చెల్లదు." ],
      "Your JSON file could not be parsed.":[ null,
        "మీ JSON ఫైలు పార్స్ చెయ్యబడలేదు." ],
      "Reserved filename found.":[ null,
        "రిజర్వుచేయబడిన ఫైలుపేరు కనబడింది." ],
      "We were unable to decompress the zip file.":[ null,
        "మేము జిప్ ఫైలుని డీకంప్రెస్ చెయ్యలేకపోయాం." ],
      "manifest.json was not found":[ null,
        "manifest.json దొరకలేదు" ],
      "File is too large to parse.":[ null,
        "ఫైలు చాలా పెద్దగా ఉన్నందున పార్స్ చెయ్యలేము." ],
      "Hidden file flagged":[ null,
        "దాచిన ఫైల్ ఫ్లాగ్ చేయబడింది" ],
      "Flagged filename found":[ null,
        "ఫ్లాగ్ చేయబడిన ఫైల్ పేరు కనుగొనబడింది" ],
      "Flagged file extensions found":[ null,
        "ఫ్లాగ్ చేయబడిన ఫైల్ పొడిగింతలు కనుగొనబడ్డాయి" ],
      "Package contains duplicate entries":[ null,
        "ప్యాకేజిలో ద్వంద్వ పద్దులు ఉన్నాయి" ],
      "Flagged file type found":[ null,
        "ఫ్లాగ్ చేయబడిన ఫైల్ రకం కనుగొనబడింది" ],
      "Package already signed":[ null,
        "ప్యాకేజీ ఇప్పటికే సంతకం చేయబడింది" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "కాయిన్ మైనర్లను నపడడానికి Firefox పొడగింతలు అనుమతించబడవు." ],
      "String name is reserved for a predefined message":[ null,
        "ముందే నిర్వచించబడిన సందేశానికి స్ట్రింగ్ పేరు రిజర్వ్ చేయబడింది" ],
      "Placeholder for message is missing":[ null,
        "సందేశానికి హోల్డర్ లేదు" ],
      "A placeholder used in the message is not defined.":[ null,
        "సందేశంలో వాడిన ప్లేస్‌హోల్డర్ నిర్వచించబడలేదు." ],
      "Placeholder name contains invalid characters":[ null,
        "ప్లేస్‌హోల్డర్ పేరులో చెల్లని అక్షరాలు ఉన్నాయి" ],
      "Placeholder is missing the content property":[ null,
        "ప్లేస్‌హోల్డర్‌కు కంటెంట్ లక్షణం లేదు" ],
      "Translation string is missing the message property":[ null,
        "అనువాద పదబంధానికి సందేశపు లక్షణం లేదు" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "manifest.json లోని \"manifest_version\" చెల్లుబాటు కాదు" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "మరింత సమాచారం కోసం https://mzl.la/20PenXl (MDN డాక్స్) చూడండి." ],
      "The \"name\" property must be a string.":[ null,
        "\"name\" లక్షణం స్ట్రింగ్ అయి ఉండాలి." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "మరింత సమాచారం కోసం http://mzl.la/1STmr48 (MDN డాక్స్) చూడండి." ],
      "The \"version\" property must be a string.":[ null,
        "\"version\" లక్షణం స్ట్రింగ్ అయి ఉండాలి." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "మరింత సమాచారం కోసం http://mzl.la/1kXIADa (MDN డాక్స్) చూడండి." ],
      "The field is invalid.":[ null,
        "ఆ ఖాళీ చెల్లదు." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "\"version\" లక్షణం Firefoxకి ప్రత్యేకమైన ఫార్మాటును వాడుతుంది." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "మరింత సమాచారం కోసం https://mzl.la/1ZOhoEN (MDN డాక్స్) చూడండి." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" అనుమతించబడదు." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "\"update_url\" లక్షణాన్ని Firefox వాడుకోదు." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" అవసరం లేదు." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "మానిఫెస్ట్‌లో నిర్వచించిన ప్రతీకం ప్యాకేజీలో కనబడలేదు." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "\"%(path)s\" వద్ద ప్రతీకం కనబడలేదు." ],
      "A background script defined in the manifest could not be found.":[ null,
        "" ],
      "A background page defined in the manifest could not be found.":[ null,
        "" ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "వెనుతలపు స్క్రిప్టు \"%(path)s\"లో కనబడలేదు." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "వెనుతలపు పేజీ \"%(path)s\"లో కనబడలేదు." ],
      "A content script defined in the manifest could not be found.":[ null,
        "" ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "" ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "" ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "The manifest contains multiple dictionaries.":[ null,
        "మానిఫెస్ట్ బహుళ నిఘంటువులను కలిగి ఉంది." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "మానిఫెస్ట్‌లో బహుళ నిఘంటువులు నిర్వచించబడ్డాయి, దీనికి తోడ్పాటు లేదు." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "మానిఫెస్ట్‌లో నిఘంటువు వస్తువు ఉంది, కానీ అది ఖాళీగా ఉంది." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "మానిఫెస్ట్‌లో నిఘంటువు వస్తువు నిర్వచించబడింది, కానీ అది ఖాళీగా ఉంది." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "మానిఫెస్ట్‌లో నిఘంటువు ఉంది కాని id లక్షణం లేదు." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "మానిఫెస్ట్‌లో ఒక నిఘంటువు కనుగొనబడింది, కాని id అమర్చి లేదు." ],
      "Forbidden content found in add-on.":[ null,
        "పొడగింతలో నిషేధిత కంటెంట్ కనబడింది." ],
      "This add-on contains forbidden content.":[ null,
        "ఈ పొడిగింత నిషిద్ధ కంటెంట్ను కలిగి ఉంది." ],
      "Icons must be square.":[ null,
        "చిహ్నాలు చదరపు ఆకారంలో ఉండాలి." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "\"%(path)s\" లో ప్రతీకాలు చదరంగా ఉండాలి." ],
      "The size of the icon does not match the manifest.":[ null,
        "ప్రతీకపు పరిమాణం మానిఫెస్ట్‌తో సరిపోలలేదు." ],
      "Corrupt image file":[ null,
        "చెడిపోయిన చిత్రం ఫైలు" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "ఈ అలంకారపు LWT మారుపేరు Firefox 70లో తొలగించబడింది." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "మరింత సమాచారం కోసం https://mzl.la/2T11Lkc (MDN పత్రావళి) చూడండి." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "%(type)s కొరకు అలంకారపు బొమ్మ \"%(path)s\" వద్ద కనబడలేదు" ],
      "Corrupted theme image file":[ null,
        "పాడైన అలంకారపు బొమ్మ ఫైలు" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "" ],
      "Theme image file has an unsupported file extension":[ null,
        "అలంకారపు బొమ్మ ఫైలు తోడ్పాటులేని ఫైలు ఎక్స్‌టెన్షన్ కలిగివుంది" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "" ],
      "Theme image file has an unsupported mime type":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "అలంకారపు బొమ్మ ఫైలు యొక్క మైమ్ రకం దాని ఎక్స్‌టెన్షనుతో సరిపోలలేదు" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "ఈ \"default_locale\" లో స్థానికీకరణలు లేవు." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" లేదు కానీ \"_locales\" మాత్రం ఉన్నాయి." ],
      "Unsupported image extension":[ null,
        "తోడ్పాటు లేని బొమ్మ ఎక్స్‌టెన్షన్" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "ప్రతీకాలు JPG/JPEG, WebP, GIF, PNG లేదా SVGలలో ఒకటయి ఉండాలి." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "\"%(path)s\" లలో messages.json ఫైలు లేదు" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "పేర్కొన్న కనిష్ట Firefox వెర్షనులో మానిఫెస్ట్ కీ తోడ్పాటు లేదు" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "పేర్కొన్న కనీస Firefox వెర్షనులో అనుమతికి తోడ్పాటు లేదు" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "పేర్కొన్న ఆండ్రాయిడ్ కొరకు Firefox కనిష్ట వెర్షనులో మానిఫెస్ట్ కీ తోడ్పాటు లేదు" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "ఆ అనుమతి రకానికి తోడ్పాటు లేదు." ],
      "The field is required.":[ null,
        "ఫీల్డ్ అవసరం." ],
      "Unknown permission.":[ null,
        "తెలియని అనుమతి." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "మరింత సమాచారం కోసం https://mzl.la/1R1n1t0 (MDN డాక్స్) చూడండి." ] } } }