module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"sq" },
      "Validation Summary:":[ null,
        "Përmbledhje Vleftësimi:" ],
      Code:[ null,
        "Kod" ],
      Message:[ null,
        "Mesazh" ],
      Description:[ null,
        "Përshkrim" ],
      File:[ null,
        "Kartelë" ],
      Line:[ null,
        "Rresht" ],
      Column:[ null,
        "Shtyllë" ],
      "Invalid nesting of selectors found":[ null,
        "" ],
      "A CSS syntax error was encountered":[ null,
        "U has një gabim sintakse CSS" ],
      "Your FTL is not valid.":[ null,
        "FTL-ja juaj s’është e vlefshme." ],
      "Your FTL file could not be parsed.":[ null,
        "Kartela juaj FTL s’u përtyp dot." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Programthet e largët nuk lejohen, siç tregohet te Rregulla Shtesash." ],
      "Inline scripts blocked by default":[ null,
        "Programthe të brendshëm të bllokuar si parazgjedhje" ],
      "Unadvised 3rd-party JS library":[ null,
        "Librari e pakëshilluar JS prej palësh të treta" ],
      "Known JS library detected":[ null,
        "U pikas librari JS e njohur" ],
      "{{api}} is not supported":[ null,
        "{{api}} nuk mbulohet" ],
      "This API has not been implemented by Firefox.":[ null,
        "Kjo API s’është sendërtuar nga Firefox-i." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" është hequr te Manifest Version 3 (vetia `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} është nxjerrë nga përdorimi" ],
      "This API has been deprecated by Firefox.":[ null,
        "Kjo API është nxjerrë nga përdorimi nga Firefox-i." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" është nxjerrë nga përdorimi, ose s’është sendërtuar" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} nuk mbulohet në versionin {{minVersion}} të Firefox-it" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Kjo API s’është e sendërtuar nga versioni minimum i dhënë për Firefox-in" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} nuk mbulohet në versionin {{minVersion}} të Firefox-it për Android" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Kjo API s’është e sendërtuar nga versioni minimum i dhënë për Firefox-in për Android" ],
      "Content script file could not be found.":[ null,
        "S’u gjet dot kartelë programthi lëndësh." ],
      "Content script file could not be found":[ null,
        "S’u gjet dot kartelë programthi lëndësh" ],
      "Content script file name should not be empty.":[ null,
        "Emri i kartelës së programthit të lëndës s’duhet të jetë i zbrazët." ],
      "Content script file name should not be empty":[ null,
        "Emri i kartelës së programthit të lëndës s’duhet të jetë i zbrazët" ],
      "JavaScript syntax error":[ null,
        "Gabim sintakse JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "U dha si argument një global i papritur" ],
      "Use of document.write strongly discouraged.":[ null,
        "Përdorimi i document.write shkëshillohet me forcë." ],
      "Banned 3rd-party JS library":[ null,
        "Librari e ndaluar JS prej palësh të treta" ],
      "Your JSON contains block comments.":[ null,
        "Kartela juaj JSON përmban komente blloku." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Në kartela JSON nuk lejohen kyçe të përsëdytur." ],
      "Your JSON is not valid.":[ null,
        "Kartela juaj JSON s’është e vlefshme." ],
      "Your JSON file could not be parsed.":[ null,
        "Kartela juaj JSON s’u përtyp dot." ],
      "Reserved filename found.":[ null,
        "U gjet emër kartele i rezervuar." ],
      "We were unable to decompress the zip file.":[ null,
        "S’qemë në gjendje të shngjeshim kartelën zip." ],
      "manifest.json was not found":[ null,
        "S’u gjet manifest.json" ],
      "File is too large to parse.":[ null,
        "Kartela është shumë e madhe për t’u përtypur." ],
      "Hidden file flagged":[ null,
        "" ],
      "Flagged filename found":[ null,
        "" ],
      "Flagged file extensions found":[ null,
        "" ],
      "Package contains duplicate entries":[ null,
        "Paketa përmban zëra të përsëdytur" ],
      "Flagged file type found":[ null,
        "" ],
      "Package already signed":[ null,
        "Paketë tashmë e nënshkruar" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Shtesat Firefox nuk janë të lejuara të xhirojnë nxjerrës monedhash." ],
      "String name is reserved for a predefined message":[ null,
        "Emri i vargut është i rezervuar për një mesazh të paracaktuar" ],
      "Placeholder for message is missing":[ null,
        "Mungon vendmbajtëse për mesazhin" ],
      "A placeholder used in the message is not defined.":[ null,
        "Një vendmbajtëse e përdorur te mesazhi s’është e përkufizuar." ],
      "Placeholder name contains invalid characters":[ null,
        "Emri i vendmbajtëses përmban shenja të pavlefshme" ],
      "Placeholder is missing the content property":[ null,
        "Mungon vendmbajtëse te veti lënde" ],
      "Translation string is missing the message property":[ null,
        "Mungon varg përkthimi te veti mesazhi" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "S’ka të caktuar veti mesazhi \"message\" për një varg (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Për më tepër hollësi, shihni https://mzl.la/2Qn0fWC (Dokumentin te MDN)." ],
      "Invalid host permission.":[ null,
        "Leje strehe e panjohur." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" te manifest.json s’është vlerë e vlefshme" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Për më tepër të dhëna, shihni https://mzl.la/20PenXl (Dokumentim te MDN)." ],
      "The \"name\" property must be a string.":[ null,
        "Vetia \"name\" duhet të jetë një varg." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Për më tepër të dhëna, shihni http://mzl.la/1STmr48 (Dokumentim te MDN)." ],
      "The \"version\" property must be a string.":[ null,
        "Vetia \"version\" duhet të jetë një varg." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Për më tepër të dhëna, shihni http://mzl.la/1kXIADa (Dokumentim te MDN)." ],
      "The field is invalid.":[ null,
        "Fusha është e pavlefshme." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Vetia \"version\" përdor një format Firefox specifik." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Për më tepër informacion, shihni te https://mzl.la/1ZOhoEN (Dokumentim MDN)." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" nuk lejohet." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Vetia \"update_url\" nuk përdoret nga Firefox-i." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" jo i domosdoshëm." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Te manifesti s’u gjet dot një ikonë e përkufizuar te paketa." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "S’u gjet ikonë te \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "S’u gjet dot programth prapaskene i përkufizuar te manifesti." ],
      "A background page defined in the manifest could not be found.":[ null,
        "S’u gjet dot një faqe prapaskene e përkufizuar te manifesti." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "S’u gjet programth sfondi te \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "S’u gjet faqe sfondi te \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "S’u gjet dot programth lënde i përkufizuar te manifesti." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "S’u gjet dot kartelë CSS programthi lënde të përkufizuar te manifesti." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Te \"%(path)s\" s’u gjet dot programth lënde i përkufizuar te manifesti." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Te \"%(path)s\" s’u gjet dot kartelë CSS programthi lënde të përkufizuar te manifesti." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "S’u gjet dot një kartelë fjalori e përkufizuar te manifesti." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Te \"%(path)s\" s’u gjet dot kartelë fjalori e përkufizuar te manifesti." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifesti përmban fjalorë të shumtë." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Në manifest janë përkufizuar fjalorë të shumtë, gjë që nuk mbulohet." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifesti përmban objekt fjalorësh, por është i zbrazët." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Te manifesti qe përkufizuar objekt fjalorësh, por qe i zbrazët." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifesti përmban një fjalor, por pa veti ID-je." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Te manifesti u gjet një fjalor, por s’pat ID të caktuar." ],
      "Forbidden content found in add-on.":[ null,
        "U gjet lëndë e ndaluar në shtesë." ],
      "This add-on contains forbidden content.":[ null,
        "Kjo shtesë përmban lëndë të ndaluar." ],
      "Icons must be square.":[ null,
        "Ikonat duhet të jenë katrore." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikona te \"%(path)s\" duhet të jenë katrore." ],
      "The size of the icon does not match the manifest.":[ null,
        "Madhësia e ikonës nuk përputhet me atë në manifest." ],
      "Corrupt image file":[ null,
        "Kartelë figure e dëmtuar" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Kartela e pritshme e ikonës te \"%(path)s\" është e dëmtuar" ],
      "This property has been deprecated.":[ null,
        "Kjo veti është nxjerrë nga përdorimi." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Ky alias LWT teme është hequr në Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Për më tepër të dhëna, shihni https://mzl.la/2T11Lkc (Dokumentim te MDN)." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Te \"%(path)s\" s’u gjet dot figurë teme për \"%(type)s\"" ],
      "Corrupted theme image file":[ null,
        "Kartelë figure teme e dëmtuar" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Kartela e figurës së temës te \"%(path)s\" është e dëmtuar" ],
      "Theme image file has an unsupported file extension":[ null,
        "Kartela e figurës së temës ka një zgjerim të pambuluar kartelash" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Kartela e figurës së temës te \"%(path)s\" ka një zgjerim të pambuluar kartelash" ],
      "Theme image file has an unsupported mime type":[ null,
        "Kartela e figurës së temës ka një lloj MIME të pambuluar" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Kartela e figurës së temës te \"%(path)s\" ka një lloj MIME \"%(mime)s\" të pambuluar" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Lloji MIME i kartelës së figurës së temës nuk përputhet me zgjatimin e vet të kartelës" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Zgjatimi i kartelës së figurës së temës te \"%(path)s\" nuk përputhet me llojin e vet aktual MIME \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "\"default_locale\" i mungojnë përkthime." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" mungon, por \"_locales\" ekziston." ],
      "Unsupported image extension":[ null,
        "Zgjerim i pambuluar figurash" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikonat duhet të jenë JPG/JPEG, WebP, GIF, PNG ose SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Vetia “applications” e anashkaluar nga vetia “browser_specific_settings”" ],
      "Empty language directory":[ null,
        "Drejtori gjuhësh e zbrazët" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Mungon kartelë messages.json te \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Zë manifesti i pambuluar nga versioni minimum i specifikuar për Firefox-in" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Leje e pambuluar nga versioni minimum i specifikuar për Firefox-in" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Zë manifesti i pambuluar nga versioni minimum i specifikuar për Firefox-in për Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Leje e pambuluar nga versioni minimum i specifikuar për Firefox-in për Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Nuk lejohet krijim lidhjesh për te “addons.mozilla.org”" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Lidhje që shpien te “addons.mozilla.org” nuk lejohen të përdoren për faqe hyrëse" ],
      "The permission type is unsupported.":[ null,
        "Lloji i lejes është i pambuluar." ],
      "The field is required.":[ null,
        "Fusha është e domosdoshme." ],
      "Unknown permission.":[ null,
        "Leje e panjohur." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Për më tepër të dhëna, shihni https://mzl.la/1R1n1t0 (Dokumentim te MDN)." ] } } }