module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"ka" },
      "Validation Summary:":[ null,
        "შემოწმების შეჯამება:" ],
      Code:[ null,
        "პირველწყარო" ],
      Message:[ null,
        "შეტყობინება" ],
      Description:[ null,
        "აღწერილობა" ],
      File:[ null,
        "ფაილი" ],
      Line:[ null,
        "სტრიქონი" ],
      Column:[ null,
        "სვეტი" ],
      "Invalid nesting of selectors found":[ null,
        "აღმოჩენილია არასწორად მოთავსებული სელექტორი" ],
      "A CSS syntax error was encountered":[ null,
        "შემჩნეულია CSS სინტაქსური შეცდომა" ],
      "Your FTL is not valid.":[ null,
        "თქვენი FTL არამართებულია." ],
      "Your FTL file could not be parsed.":[ null,
        "თქვენი FTL ფაილი ვერ დამუშავდა." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "გარეშე სკრიპტები არაა დაშვებული დამატების დებულებებით." ],
      "Inline scripts blocked by default":[ null,
        "ხაზოვანი სკრიპტები შეზღუდულია ნაგულისხმევად" ],
      "Unadvised 3rd-party JS library":[ null,
        "არასასურველი გარეშე JS ბიბლიოთეკა" ],
      "Known JS library detected":[ null,
        "აღმოჩენილია ცნობილი JS ბიბლიოთეკა" ],
      "{{api}} is not supported":[ null,
        "{{api}} არაა მხარდაჭერილი" ],
      "This API has not been implemented by Firefox.":[ null,
        "ეს API არ გამოიყენება Firefox-ში." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "„{{api}}“ მოცილებულია მანიფესტის 3-ე ვერსიიდან (`manifest_version` – თვისება)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} მოძველებულია" ],
      "This API has been deprecated by Firefox.":[ null,
        "ეს API მოძველებულია Firefox-ში." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "„{{api}}“ მოძველებულია და არ დანერგილა" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener ` გამოძახებულია ჭეშმარიტი მეოთხე არგუმენტით." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} არაა მხარდაჭერილი Firefox-ის {{minVersion}} ვერსიაში" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "ეს API არ გამოიყენება Firefox-ის მოცემულ უმცირეს ვერსიაში" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} არაა მხარდაჭერილი Firefox-ის Android-ვერსიაში" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "ეს API არ გამოიყენება Firefox-ის მოცემულ უმცირეს Android-ვერსიაში" ],
      "Content script file could not be found.":[ null,
        "სკრიპტის შემცველი ფაილი ვერ მოიძებნა." ],
      "Content script file could not be found":[ null,
        "სკრიპტის შემცველი ფაილი ვერ მოიძებნა" ],
      "Content script file name should not be empty.":[ null,
        "სკრიპტის შემცველი ფაილის სახელი ცარიელი არ უნდა იყოს." ],
      "Content script file name should not be empty":[ null,
        "სკრიპტის შემცველი ფაილის სახელი ცარიელი არ უნდა იყოს" ],
      "JavaScript syntax error":[ null,
        "JavaScript სინტაქსური შეცდომა" ],
      "Unexpected global passed as an argument":[ null,
        "არგუმენტი მოულოდნელი გადაიცა გლობალურად" ],
      "Use of document.write strongly discouraged.":[ null,
        "document.write-ის გამოყენება, მეტად არასასურველია." ],
      "Banned 3rd-party JS library":[ null,
        "აკრძალული გარეშე JS ბიბლიოთეკა" ],
      "Your JSON contains block comments.":[ null,
        "თქვენი JSON შეიცავს მრავალხაზიან შენიშვნებს." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "გაორმაგებული გასაღებები დაუშვებელია JSON ფაილებში." ],
      "Your JSON is not valid.":[ null,
        "თქვენი JSON არამართებულია." ],
      "Your JSON file could not be parsed.":[ null,
        "თქვენი JSON ფაილის დამუშავება, ვერ ხერხდება." ],
      "Reserved filename found.":[ null,
        "აღმოჩენილია ფაილის დაკავებული სახელი." ],
      "We were unable to decompress the zip file.":[ null,
        "Zip არქივის გაშიფვრა, ვერ ხერხდება." ],
      "manifest.json was not found":[ null,
        "manifest.json ვერ მოიძებნა" ],
      "File is too large to parse.":[ null,
        "დასამუშავებელი ფაილი ზედმეტად დიდია." ],
      "Hidden file flagged":[ null,
        "გასაჩივრებული დამალული ფაილი" ],
      "Flagged filename found":[ null,
        "აღმოჩენილია გასაჩივრებული ფაილის სახელი" ],
      "Flagged file extensions found":[ null,
        "აღმოჩენილია გასაჩივრებული ფაილის გაფართოება" ],
      "Package contains duplicate entries":[ null,
        "ნაკრები შეიცავს გაორმაგებულ ერთეულებს" ],
      "Flagged file type found":[ null,
        "აღმოჩენილია გასაჩივრებული ფაილის სახეობა" ],
      "Package already signed":[ null,
        "ნაკრები უკვე დამოწმებულია" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox დამატებებით კრიპტოვალუტის წარმოება არაა დაშვებული." ],
      "String name is reserved for a predefined message":[ null,
        "სტრიქონის დასახელება დაკავებულია წინასწარ განსაზღვრული შეტყობინებისთვის" ],
      "Placeholder for message is missing":[ null,
        "შეტყობინების ჩანაცვლების არე ვერ მოიძებნა" ],
      "A placeholder used in the message is not defined.":[ null,
        "ამ შეტყობინებაში გამოყენებული ჩანაცვლების არე არაა განსაზღვრული." ],
      "Placeholder name contains invalid characters":[ null,
        "ჩანაცვლების არის დასახელება შეიცავს დაუშვებელ სიმბოლოებს" ],
      "Placeholder is missing the content property":[ null,
        "ჩანაცვლების არეს არ გააჩნია შიგთავსის თვისება" ],
      "Translation string is missing the message property":[ null,
        "თარგმნილ სტრიქონს არ გააჩნია შეტყობინების თვისება" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "„message“ შეტყობინების თვისება არაა განსაზღვრული სტრიქონისთვის (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "იხილეთ ვრცლად https://mzl.la/2Qn0fWC (MDN-მასალები)." ],
      "Invalid host permission.":[ null,
        "შენახვის უმართებულო უფლება." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "„manifest_version“-ს manifest.json ფაილში არამართებული მნიშვნელობა აქვს" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "იხილეთ https://mzl.la/20PenXl (MDN მასალები), დამატებითი ინფორმაციისთვის." ],
      "The \"name\" property must be a string.":[ null,
        "თვისება „name“ უნდა წარმოადგენდეს სტრიქონს." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "იხილეთ http://mzl.la/1STmr48 (MDN მასალები), დამატებითი ინფორმაციისთვის." ],
      "The \"version\" property must be a string.":[ null,
        "თვისება „version“ უნდა წარმოადგენდეს სტრიქონს." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "იხილეთ http://mzl.la/1kXIADa (MDN მასალები), დამატებითი ინფორმაციისთვის." ],
      "The field is invalid.":[ null,
        "ველი არამართებულია." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "თვისება „version“ იყენებს Firefox-ის სახის ფორმატს." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "იხილეთ https://mzl.la/1ZOhoEN (MDN დოკუმენტაცია) დამატებითი ინფორმაციისთვის." ],
      "\"update_url\" is not allowed.":[ null,
        "„update_url“ არაა დაშვებული." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "„update_url“ თვისებას არ იყენებს Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" არაა აუცილებელი." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "მანიფესტში განსაზღვრული ხატულა, ნაკრებში ვერ მოიძებნა." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "ხატულა, ვერ მოიძებნა მისამართზე „%(path)s“." ],
      "A background script defined in the manifest could not be found.":[ null,
        "მანიფესტში განსაზღვრული ფონური სკრიპტი, ვერ მოიძებნა." ],
      "A background page defined in the manifest could not be found.":[ null,
        "მანიფესტში განსაზღვრული ფონური გვერდი, ვერ მოიძებნა." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "ფონური სკრიპტი ვერ მოიძებნა მისამართზე „%(path)s“." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "ფონური გვერდი ვერ მოიძებნა მისამართზე „%(path)s“." ],
      "A content script defined in the manifest could not be found.":[ null,
        "მანიფესტში განსაზღვრული შიგთავსის სკრიპტი, ვერ მოიძებნა." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "მანიფესტში განსაზღვრული შიგთავსის სკრიპტის css-ფაილი, ვერ მოიძებნა." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "მანიფესტში განსაზღვრული შიგთავსის სკრიპტი, ვერ მოიძებნა მისამართზე „%(path)s“." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "მანიფესტში განსაზღვრული შიგთავსის სკრიპტის css-ფაილი, ვერ მოიძებნა მისამართზე „%(path)s“." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "მანიფესტში განსაზღვრული ლექსიკონის ფაილი, ვერ მოიძებნა." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "მანიფესტში განსაზღვრული ლექსიკონის ფაილი, ვერ მოიძებნა მისამართზე „%(path)s“." ],
      "The manifest contains multiple dictionaries.":[ null,
        "მანიფესტი შეიცავს რამდენიმე ლექსიკონს." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "მანიფესტში განსაზღვრულია რამდენიმე ლექსიკონი, რაც არ არის მხარდაჭერილი." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "მანიფესტი შეიცავს ლექსიკონების ობიექტს, მაგრამ იგი ცარიელია." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "ლექსიკონების ობიექტი მანიფესტში განსაზღვრული, მაგრამ ცარიელი იყო." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "მანიფესტი შეიცავს ლექსიკონს, მაგრამ id-თვისების გარეშე." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "მანიფესტში ნაპოვნი იყო ლექსიკონი, მაგრამ მითითებული არ ჰქონდა id." ],
      "Forbidden content found in add-on.":[ null,
        "დამატებაში აღმოჩენილია აკრძალული შიგთავსი." ],
      "This add-on contains forbidden content.":[ null,
        "დამატება შეიცავს აკრძალულ შიგთავსს." ],
      "Icons must be square.":[ null,
        "ხატულები უნდა იყოს კვადრატული ფორმის." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "ხატულა „%(path)s“ მისამართზე უნდა იყოს კვადრატული." ],
      "The size of the icon does not match the manifest.":[ null,
        "ხატულის ზომა არ ემთხვევა მანიფესტში განსაზღვრულს." ],
      "Corrupt image file":[ null,
        "სურათი დაზიანებულია" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "მითითებულ „%(path)s“ მისამართზე ხატულის ფაილი დაზიანებულია" ],
      "This property has been deprecated.":[ null,
        "ეს თვისება მოძველებულია." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "თემის LWT-მეტსახელი მოცილებულია Firefox 70-იდან." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "იხილეთ https://mzl.la/2T11Lkc (MDN-მასალები), დამატებითი ინფორმაციისთვის." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "თემის გამოსახულება სახეობით „%(type)s“ ვერ მოიძებნა მისამართზე „%(path)s“" ],
      "Corrupted theme image file":[ null,
        "თემის გამოსახულება დაზიანებულია" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "თემის გამოსახულება მისამართზე „%(path)s“ დაზიანებულია" ],
      "Theme image file has an unsupported file extension":[ null,
        "თემის გამოსახულებას ფაილის მხარდაუჭერელი გაფართოება აქვს" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "თემის გამოსახულებას მისამართზე „%(path)s“ ფაილის მხარდაუჭერელი გაფართოება აქვს" ],
      "Theme image file has an unsupported mime type":[ null,
        "თემის გამოსახულება მხარდაუჭერელი mime-სახისაა" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "თემის გამოსახულება მისამართზე „%(path)s“ მხარდაუჭერელი mime-სახისაა „%(mime)s“" ],
      "Theme image file mime type does not match its file extension":[ null,
        "თემის გამოსახულების mime-სახეობა არ ემთხვევა ფაილის გაფართოებას" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "თემის გამოსახულების გაფართოება მისამართზე „%(path)s“ არ ემთხვევა მის არსებულ mime-სახეობას „%(mime)s“" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "„default_locale“ აკლია თარგმანებში." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "„default_locale“ აკლია, თუმცა „_locales“ არსებობს." ],
      "Unsupported image extension":[ null,
        "სურათის ეს გაფართოება არაა მხარდაჭერილი" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "ხატულა უნდა იყოს JPG/JPEG, WebP, GIF, PNG, ან SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "„applications“ თვისებას ანაცვლებს „browser_specific_settings“ თვისება" ],
      "Empty language directory":[ null,
        "ენის საქაღალდე ცარიელია" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "messages.json ფაილი ვერ მოიძებნა „%(path)s“ მისამართზე" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "მანიფესტის გასაღები მხარდაუჭერელია Firefox-ის მითითებული უმცირესი ვერსიით" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "ნებართვები მხარდაუჭერელია Firefox-ის მითითებული უმცირესი ვერსიით" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "მანიფესტის გასაღები არ არის მხარდაჭერილი Firefox Android-ის მითითებული უმცირესი ვერსიით" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "ნებართვები მხარდაუჭერელია Firefox Android-ის მითითებული უმცირესი ვერსიით" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "ბმული „addons.mozilla.org“ საიტთან აკრძალულია" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "ბმულის დადება მისამართზე „addons.mozilla.org“ აკრძალულია მთავარ გვერდზე" ],
      "The permission type is unsupported.":[ null,
        "ამ სახის ნებართვა არაა მხარდაჭერილი." ],
      "The field is required.":[ null,
        "ველის შევსება აუცილებელია." ],
      "Unknown permission.":[ null,
        "უცნობი სახის ნებართვა." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "იხილეთ https://mzl.la/1R1n1t0 (MDN მასალები), დამატებითი ინფორმაციისთვის." ] } } }