module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3);",
        lang:"sl" },
      "Validation Summary:":[ null,
        "Povzetek preverjanja:" ],
      Code:[ null,
        "Koda" ],
      Message:[ null,
        "Sporočilo" ],
      Description:[ null,
        "Opis" ],
      File:[ null,
        "Datoteka" ],
      Line:[ null,
        "Vrstica" ],
      Column:[ null,
        "Stolpec" ],
      "Invalid nesting of selectors found":[ null,
        "Najdeno je bilo neveljavno gnezdenje izbirnikov." ],
      "A CSS syntax error was encountered":[ null,
        "Najdena je bila napaka skladnje CSS." ],
      "Your FTL is not valid.":[ null,
        "Vaš FTL ni veljaven." ],
      "Your FTL file could not be parsed.":[ null,
        "Vaše datoteke FTL ni bilo mogoče razčleniti." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Pravilnik dodatkov ne dovoljuje oddaljenih skriptov." ],
      "Inline scripts blocked by default":[ null,
        "Notranji skripti so privzeto zavrnjeni." ],
      "Unadvised 3rd-party JS library":[ null,
        "Nepriporočena knjižnica JS tretje osebe" ],
      "Known JS library detected":[ null,
        "Zaznana je znana knjižnica JS" ],
      "{{api}} is not supported":[ null,
        "{{api}} ni podprt" ],
      "This API has not been implemented by Firefox.":[ null,
        "Firefox ne podpira tega API-ja." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" je bil odstranjen v različici manifesta 3 (lastnost 'manifest_version')" ],
      "{{api}} is deprecated":[ null,
        "{{api}} ni več podprt" ],
      "This API has been deprecated by Firefox.":[ null,
        "Firefox je opustil ta API." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" je zastarel ali neuveljavljen" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "Klic addEventListener s četrtim argumentom truthy." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} ni podprt v različici Firefox {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Ta API ni uveljavljen v najnižji podprti različici Firefoxa" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} ni podprt v različici Firefox za Android {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Ta API ni uveljavljen v najnižji podprti različici Firefoxa za Android" ],
      "Content script file could not be found.":[ null,
        "Datoteke skripta vsebine ni bilo mogoče najti." ],
      "Content script file could not be found":[ null,
        "Datoteke skripta vsebine ni bilo mogoče najti." ],
      "Content script file name should not be empty.":[ null,
        "Ime datoteke skripta vsebine ne sme biti prazno." ],
      "Content script file name should not be empty":[ null,
        "Ime datoteke skripta vsebine ne sme biti prazno." ],
      "JavaScript syntax error":[ null,
        "Napaka skladnje JavaScripta." ],
      "Unexpected global passed as an argument":[ null,
        "Globalna spremenljivka nepričakovano podana kot argument" ],
      "Use of document.write strongly discouraged.":[ null,
        "Uporaba document.write se močno odsvetuje." ],
      "Banned 3rd-party JS library":[ null,
        "Prepovedana knjižnica JS tretje osebe" ],
      "Your JSON contains block comments.":[ null,
        "Vaša datoteka JSON vsebuje bloke komentarjev." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "V datotekah JSON podvojeni ključi niso dovoljeni." ],
      "Your JSON is not valid.":[ null,
        "Vaša datoteka JSON ni veljavna." ],
      "Your JSON file could not be parsed.":[ null,
        "Vaše datoteke JSON ni bilo mogoče razčleniti." ],
      "Reserved filename found.":[ null,
        "Najdeno rezervirano ime datoteke." ],
      "We were unable to decompress the zip file.":[ null,
        "Datoteke zip ni bilo mogoče razširiti." ],
      "manifest.json was not found":[ null,
        "Datoteke manifest.json ni bilo mogoče najti" ],
      "File is too large to parse.":[ null,
        "Datoteka je prevelika za razčlenjevanje." ],
      "Hidden file flagged":[ null,
        "Skrita datoteka označena" ],
      "Flagged filename found":[ null,
        "Najdeno označeno ime datoteke" ],
      "Flagged file extensions found":[ null,
        "Najdene označene končnice datotek" ],
      "Package contains duplicate entries":[ null,
        "Paket vsebuje podvojene vnose" ],
      "Flagged file type found":[ null,
        "Najdena označena vrsta datoteke" ],
      "Package already signed":[ null,
        "Paket je že podpisan" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Dodatkom za Firefox ni dovoljeno rudariti kriptovalut." ],
      "String name is reserved for a predefined message":[ null,
        "Ime niza je rezervirano za vnaprej določeno sporočilo" ],
      "Placeholder for message is missing":[ null,
        "Manjka označba mesta sporočila" ],
      "A placeholder used in the message is not defined.":[ null,
        "Označba mesta, uporabljena v sporočilu, ni določena." ],
      "Placeholder name contains invalid characters":[ null,
        "Ime označbe mesta vsebuje neveljavne znake" ],
      "Placeholder is missing the content property":[ null,
        "Označbi mesta manjka lastnost vsebine" ],
      "Translation string is missing the message property":[ null,
        "Nizu prevoda manjka lastnost sporočila" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Za niz ni bilo nastavljeno nobeno sporočilo \"message\" (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Za več informacij glejte https://mzl.la/2Qn0fWC (dokumente na MDN-u)." ],
      "Invalid host permission.":[ null,
        "Neveljavno dovoljenje gostitelja." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" v datoteki manifest.json ni veljavna vrednost." ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Za več informacij glejte https://mzl.la/20PenXl (dokumente na MDN-u)." ],
      "The \"name\" property must be a string.":[ null,
        "Lastnost \"name\" mora biti niz." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Za več informacij glejte http://mzl.la/1STmr48 (dokumente na MDN-u)." ],
      "The \"version\" property must be a string.":[ null,
        "Lastnost \"version\" mora biti niz." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Za več informacij glejte http://mzl.la/1kXIADa (dokumente na MDN-u)." ],
      "The field is invalid.":[ null,
        "Polje je neveljavno." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Lastnost \"version\" uporablja obliko, posebno za Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Za več informacij glejte https://mzl.la/1ZOhoEN (dokumente na MDN-u)." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" ni dovoljen." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Lastnosti \"update_url\" Firefox ne uporablja." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" ni zahtevan." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "V paketu ni bilo mogoče najti ikone, določene v manifestu." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "V mapi \"%(path)s\" ni bilo mogoče najti ikone." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Skripta ozadja, določenega v manifestu, ni bilo mogoče najti." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Strani ozadja, določene v manifestu, ni bilo mogoče najti." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "V mapi \"%(path)s\" ni bilo mogoče najti skripta ozadja." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "V mapi \"%(path)s\" ni bilo mogoče najti strani ozadja." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Skripta vsebine, določenega v manifestu, ni bilo mogoče najti." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Datoteke css skripta vsebine, določene v manifestu, ni bilo mogoče najti." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "V mapi \"%(path)s\" ni bilo mogoče najti skripta vsebine, določenega v manifestu." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "V mapi \"%(path)s\" ni bilo mogoče najti datoteke css skripta vsebine, določene v manifestu." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Datoteke slovarja, določene v manifestu, ni bilo mogoče najti." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "V mapi \"%(path)s\" ni bilo mogoče najti datoteke slovarja, določene v manifestu." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifest vsebuje več slovarjev." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "V manifestu je bilo določenih več slovarjev, kar ni podprto." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifest vsebuje predmet slovarjev, vendar je prazen." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "V manifestu je bil opredeljen predmet slovarjev, vendar je bil prazen." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifest vsebuje predmet slovarjev, vendar nima lastnosti id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "V manifestu je bil najden slovar, ki nima nastavljenega id." ],
      "Forbidden content found in add-on.":[ null,
        "V dodatku je bila najdena prepovedana vsebina." ],
      "This add-on contains forbidden content.":[ null,
        "Ta dodatek vsebuje prepovedano vsebino." ],
      "Icons must be square.":[ null,
        "Ikone morajo biti kvadratne." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikona v mapi \"%(path)s\" mora biti kvadratna." ],
      "The size of the icon does not match the manifest.":[ null,
        "Velikost ikone se ne ujema z manifestom." ],
      "Corrupt image file":[ null,
        "Pokvarjena slikovna datoteka" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Pričakovana datoteka ikone v mapi \"%(path)s\" je pokvarjena" ],
      "This property has been deprecated.":[ null,
        "Ta lastnost je opuščena." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Ta vzdevek LWT teme je bil odstranjen v Firefoxu 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Za več informacij glejte https://mzl.la/2T11Lkc (dokumente na omrežju MDN)." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "V mapi \"%(path)s\" ni bilo mogoče najti slike teme za \"%(type)s\"" ],
      "Corrupted theme image file":[ null,
        "Pokvarjena slikovna datoteka teme" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Slika teme v mapi \"%(path)s\" je pokvarjena" ],
      "Theme image file has an unsupported file extension":[ null,
        "Slikovna datoteka teme ima nepodprto pripono" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Slikovna datoteka na \"%(path)s\" ima nepodprto pripono" ],
      "Theme image file has an unsupported mime type":[ null,
        "Slikovna datoteka teme ima nepodprto vrsto mime" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Slikovna datoteka na \"%(path)s\" ima nepodprto vrsto mime \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Vrsta mime slikovne datoteke se ne ujema s pripono datoteke" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Vrsta mime slikovne datoteke na \"%(path)s\" se ne ujema z njeno dejansko vrsto mime \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "V \"default_locale\" manjkajo lokalizacije." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" manjka, vendar obstaja \"_locales\"." ],
      "Unsupported image extension":[ null,
        "Nepodprta pripona slike" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikone morajo biti vrste JPG/JPEG, WebP, GIF, PNG ali SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Lastnost \"applications\" je preglašena z lastnostjo \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Prazna jezikovna mapa" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "V mapi \"%(path)s\" manjka datoteka messages.json." ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Ključ manifesta ni podprt v najnižji podprti različici Firefoxa" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Dovoljenje ni podprto v najnižji podprti različici Firefoxa" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Ključ manifesta ni podprt v najnižji podprti različici Firefoxa za Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Dovoljenje ni podprto v najnižji podprti različici Firefoxa za Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Povezovanje na \"addons.mozilla.org\" ni dovoljeno" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Za domačo stran ni dovoljeno uporabljati povezav, ki usmerjajo na \"addons.mozilla.org\"" ],
      "The permission type is unsupported.":[ null,
        "Vrsta dovoljenja ni podprta." ],
      "The field is required.":[ null,
        "Polje je zahtevano." ],
      "Unknown permission.":[ null,
        "Neznano dovoljenje." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Za več informacij glejte https://mzl.la/1R1n1t0 (dokumente na MDN-u)." ] } } }