module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"nl" },
      "Validation Summary:":[ null,
        "Validatiesamenvatting:" ],
      Code:[ null,
        "Code" ],
      Message:[ null,
        "Bericht" ],
      Description:[ null,
        "Beschrijving" ],
      File:[ null,
        "Bestand" ],
      Line:[ null,
        "Regel" ],
      Column:[ null,
        "Kolom" ],
      "Invalid nesting of selectors found":[ null,
        "Ongeldig nesten van selectors gevonden" ],
      "A CSS syntax error was encountered":[ null,
        "Er is een CSS-syntaxisfout aangetroffen" ],
      "Your FTL is not valid.":[ null,
        "Uw FTL is niet geldig." ],
      "Your FTL file could not be parsed.":[ null,
        "Uw FTL-bestand kon niet worden geparset." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Externe scripts zijn volgens het add-onbeleid niet toegestaan." ],
      "Inline scripts blocked by default":[ null,
        "Inline scripts zijn standaard geblokkeerd" ],
      "Unadvised 3rd-party JS library":[ null,
        "Niet-geadviseerde JS-bibliotheek van derden" ],
      "Known JS library detected":[ null,
        "Bekende JS-bibliotheek gedetecteerd" ],
      "{{api}} is not supported":[ null,
        "{{api}} wordt niet ondersteund" ],
      "This API has not been implemented by Firefox.":[ null,
        "Deze API is niet door Firefox geïmplementeerd." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "‘{{api}}’ is verwijderd in Manifest versie 3 (eigenschap ‘manifest_version’)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} is verouderd" ],
      "This API has been deprecated by Firefox.":[ null,
        "Deze API is in Firefox verouderd." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "‘{{api}}’ is verouderd of niet geïmplementeerd" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` aangeroepen met ‘truthy’ vierde argument." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} wordt niet ondersteund in Firefox versie {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Deze API is niet door de opgegeven minimumversie van Firefox geïmplementeerd" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} wordt niet ondersteund in Firefox voor Android versie {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Deze API is niet door de opgegeven minimumversie van Firefox voor Android geïmplementeerd" ],
      "Content script file could not be found.":[ null,
        "Inhoudsscriptbestand kon niet worden gevonden." ],
      "Content script file could not be found":[ null,
        "Inhoudsscriptbestand kon niet worden gevonden" ],
      "Content script file name should not be empty.":[ null,
        "Naam van inhoudsscriptbestand mag niet leeg zijn." ],
      "Content script file name should not be empty":[ null,
        "Naam van inhoudsscriptbestand mag niet leeg zijn" ],
      "JavaScript syntax error":[ null,
        "JavaScript-syntaxisfout" ],
      "Unexpected global passed as an argument":[ null,
        "Onverwachte globale variabele doorgegeven als argument" ],
      "Use of document.write strongly discouraged.":[ null,
        "Gebruik van document.write wordt sterk afgeraden." ],
      "Banned 3rd-party JS library":[ null,
        "Geblokkeerde JS-bibliotheek van derden" ],
      "Your JSON contains block comments.":[ null,
        "Uw JSON bevat blokcommentaren." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Dubbele sleutels zijn niet toegestaan in JSON-bestanden." ],
      "Your JSON is not valid.":[ null,
        "Uw JSON is niet geldig." ],
      "Your JSON file could not be parsed.":[ null,
        "Uw JSON-bestand kon niet worden geparset." ],
      "Reserved filename found.":[ null,
        "Gereserveerde bestandsnaam gevonden." ],
      "We were unable to decompress the zip file.":[ null,
        "We konden het zip-bestand niet uitpakken." ],
      "manifest.json was not found":[ null,
        "manifest.json is niet gevonden" ],
      "File is too large to parse.":[ null,
        "Bestand is te groot om te parsen." ],
      "Hidden file flagged":[ null,
        "Verborgen bestand gemarkeerd" ],
      "Flagged filename found":[ null,
        "Gemarkeerde bestandsnaam gevonden" ],
      "Flagged file extensions found":[ null,
        "Gemarkeerde bestandsextensies gevonden" ],
      "Package contains duplicate entries":[ null,
        "Pakket bevat dubbele vermeldingen" ],
      "Flagged file type found":[ null,
        "Gemarkeerd bestandstype gevonden" ],
      "Package already signed":[ null,
        "Pakket al ondertekend" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox-add-ons mogen geen coinminers uitvoeren." ],
      "String name is reserved for a predefined message":[ null,
        "Naam van tekenreeks is voor een vooraf gedefinieerd bericht gereserveerd" ],
      "Placeholder for message is missing":[ null,
        "Plaatshouder voor bericht ontbreekt" ],
      "A placeholder used in the message is not defined.":[ null,
        "Een in het bericht gebruikte plaatshouder is niet gedefinieerd." ],
      "Placeholder name contains invalid characters":[ null,
        "Naam van plaatshouder bevat ongeldige tekens" ],
      "Placeholder is missing the content property":[ null,
        "Plaatshouder bevat geen inhoudseigenschap" ],
      "Translation string is missing the message property":[ null,
        "Te vertalen tekenreeks bevat geen berichteigenschap" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Geen berichteigenschap ‘message’ voor een tekenreeks ingesteld (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Zie https://mzl.la/2Qn0fWC (MDN Docs) voor meer informatie." ],
      "Invalid host permission.":[ null,
        "Onbekende hosttoestemming." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "‘manifest_version’ in het bestand manifest.json is geen geldige waarde" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Zie https://mzl.la/20PenXl (MDN Docs) voor meer informatie." ],
      "The \"name\" property must be a string.":[ null,
        "De eigenschap ‘name’ moet een tekenreeks zijn." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Zie http://mzl.la/1STmr48 (MDN Docs) voor meer informatie." ],
      "The \"version\" property must be a string.":[ null,
        "De eigenschap ‘version’ moet een tekenreeks zijn." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Zie http://mzl.la/1kXIADa (MDN Docs) voor meer informatie." ],
      "The field is invalid.":[ null,
        "Het veld is ongeldig." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "De eigenschap ‘version’ gebruikt een Firefox-specifieke notatie." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Zie https://mzl.la/1ZOhoEN (MDN Docs) voor meer informatie." ],
      "\"update_url\" is not allowed.":[ null,
        "‘update_url’ is niet toegestaan." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "De eigenschap ‘update_url’ wordt niet door Firefox gebruikt." ],
      "\"strict_max_version\" not required.":[ null,
        "‘strict_max_version’ niet vereist." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Een in het manifest gedefinieerd pictogram kon niet in het pakket worden gevonden." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Pictogram kon niet worden gevonden in ‘%(path)s’." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Een in het manifest gedefinieerd achtergrondscript kon niet worden gevonden." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Een in het manifest gedefinieerde achtergrondpagina kon niet worden gevonden." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Achtergrondscript kon niet worden gevonden in ‘%(path)s’." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Achtergrondpagina kon niet worden gevonden in ‘%(path)s’." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Een in het manifest gedefinieerd inhoudsscript kon niet worden gevonden." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Een in het manifest gedefinieerd CSS-bestand van inhoudsscript kon niet worden gevonden." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "In het manifest gedefinieerd inhoudsscript kon niet worden gevonden in ‘%(path)s’." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "In het manifest gedefinieerd CSS-bestand van inhoudsscript kon niet worden gevonden in ‘%(path)s’." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Een in het manifest gedefinieerd bibliotheekbestand kon niet worden gevonden." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "In het manifest gedefinieerd bibliotheekbestand kon niet worden gevonden in ‘%(path)s’." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Het manifest bevat meerdere woordenboeken." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Er zijn meerdere woordenboeken gedefinieerd in het manifest, wat niet wordt ondersteund." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Het manifest bevat een woordenboek-object, maar het is leeg." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Er is een woordenboek-object gedefinieerd in het manifest, maar het is leeg." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Het manifest bevat een woordenboek maar geen id-eigenschap." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Er is een woordenboek gevonden in het manifest, maar er is geen id ingesteld." ],
      "Forbidden content found in add-on.":[ null,
        "Verboden inhoud gevonden in add-on." ],
      "This add-on contains forbidden content.":[ null,
        "Deze add-on bevat verboden inhoud." ],
      "Icons must be square.":[ null,
        "Pictogrammen moeten vierkant zijn." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Pictogram in ‘%(path)s’ moet vierkant zijn." ],
      "The size of the icon does not match the manifest.":[ null,
        "De grootte van het pictogram komt niet overeen met het manifest." ],
      "Corrupt image file":[ null,
        "Beschadigd afbeeldingsbestand" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Verwacht pictogrambestand in ‘%(path)s’ is beschadigd" ],
      "This property has been deprecated.":[ null,
        "Deze eigenschap is verouderd." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Het LWT-alias van dit thema is verwijderd in Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Zie https://mzl.la/2T11Lkc (MDN Docs) voor meer informatie." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Thema-afbeelding voor ‘%(type)s’ kon niet worden gevonden in ‘%(path)s’" ],
      "Corrupted theme image file":[ null,
        "Beschadigd thema-afbeeldingsbestand" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Thema-afbeeldingsbestand in ‘%(path)s’ is beschadigd" ],
      "Theme image file has an unsupported file extension":[ null,
        "Thema-afbeeldingsbestand heeft een niet-ondersteunde bestandsextensie" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Thema-afbeeldingsbestand op ‘%(path)s’ heeft een niet-ondersteunde bestandsextensie" ],
      "Theme image file has an unsupported mime type":[ null,
        "Thema-afbeeldingsbestand heeft een niet-ondersteund mime-type" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Thema-afbeeldingsbestand op ‘%(path)s’ heeft het niet-ondersteunde mime-type ‘%(mime)s’" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Mime-type van het thema-afbeeldingsbestand komt niet overeen met de bestandsextensie" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Thema-afbeeldingsbestand op ‘%(path)s’ komt niet overeen met het werkelijke mime-type ‘%(mime)s’" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "De ‘default_locale’ mist lokalisaties." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "De ‘default_locale’ ontbreekt, maar ‘_locales’ bestaat." ],
      "Unsupported image extension":[ null,
        "Niet-ondersteunde afbeeldingsextensie" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Pictogrammen dienen JPG/JPEG, WebP, GIF, PNG of SVG te zijn." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Eigenschap ‘applications’ wordt overschreven door de eigenschap ‘browser_specific_settings’" ],
      "Empty language directory":[ null,
        "Lege taalmap" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Bestand messages.json ontbreekt in ‘%(path)s’" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifestsleutel niet ondersteund door de opgegeven minimale Firefox-versie" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Toestemming niet ondersteund door de opgegeven minimale Firefox-versie" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifestsleutel niet ondersteund door de opgegeven minimale Firefox voor Android-versie" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Toestemming niet ondersteund door de opgegeven minimale Firefox voor Android-versie" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Koppelen naar ‘addons.mozilla.org’ is niet toegestaan" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Koppelingen die verwijzen naar ‘addons.mozilla.org’ mogen niet voor de startpagina worden gebruikt" ],
      "The permission type is unsupported.":[ null,
        "Het toestemmingstype wordt niet ondersteund." ],
      "The field is required.":[ null,
        "Het veld is vereist." ],
      "Unknown permission.":[ null,
        "Onbekende toestemming." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Zie https://mzl.la/1R1n1t0 (MDN Docs) voor meer informatie." ] } } }