module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n > 1);",
        lang:"kab" },
      "Validation Summary:":[ null,
        "Agzul n usentem:" ],
      Code:[ null,
        "Tangalt" ],
      Message:[ null,
        "Izen" ],
      Description:[ null,
        "Aglam" ],
      File:[ null,
        "Afaylu" ],
      Line:[ null,
        "Izirig" ],
      Column:[ null,
        "Tigejdit" ],
      "Invalid nesting of selectors found":[ null,
        "Yir amnekcem gar imsefran yettwaf" ],
      "A CSS syntax error was encountered":[ null,
        "Tuccḍa n tseddast CSS tettwaf" ],
      "Your FTL is not valid.":[ null,
        "FTL inek mačči d ameγtu." ],
      "Your FTL file could not be parsed.":[ null,
        "Ur d-yelli wamek ad yettwasleḍ FTL inek." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Iskripten inmeggagen ur ttwasirgen ara akken i d-yettwalmmel deg tiwtilin icudden ar izegrar." ],
      "Inline scripts blocked by default":[ null,
        "Iskripten inline weḥlen si tazwara" ],
      "Unadvised 3rd-party JS library":[ null,
        "Tamkerḍit JS tis kraḍ d iritt i useqdec" ],
      "Known JS library detected":[ null,
        "Tamkarḍit JS tettwaf" ],
      "{{api}} is not supported":[ null,
        "{{api}} ur yettwaqbel" ],
      "This API has not been implemented by Firefox.":[ null,
        "Asnas-agi API yettwabna di Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "{{api}} is deprecated":[ null,
        "{{api}} ur yettwaqbel ara" ],
      "This API has been deprecated by Firefox.":[ null,
        "Asnas-a API yettuneḥsab d aqbur sɣur Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` yessawl-as-d s tiɣiret n tidet tis kuẓ." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} ur yettwasefrak ara deg lqem-a n Firefox {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Asnas-agi API ur yettwabna ara deg lqem adday n Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} ur yettwasefrak ara deg lqem-a n Firefox i Android {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Asnas-agi API ur yettwabna ara deg lqem adday n Firefox Android" ],
      "Content script file could not be found.":[ null,
        "Afaylu n uskript n ugbur ulac-it." ],
      "Content script file could not be found":[ null,
        "Afaylu n uskript n ugbur ulac-it" ],
      "Content script file name should not be empty.":[ null,
        "Isem n ufaylu n uskript n ugbur ur yessefk ara ad yili d ilem." ],
      "Content script file name should not be empty":[ null,
        "Isem n ufaylu n uskript n ugbur ur yessefk ara ad yili d ilem" ],
      "JavaScript syntax error":[ null,
        "Tuccḍa n tseddast JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Amutti amatu iɛedda am tɣiret" ],
      "Use of document.write strongly discouraged.":[ null,
        "Aseqdec n document.write ur yelhi ara." ],
      "Banned 3rd-party JS library":[ null,
        "Tamkerḍit JS tis kraḍ tegdel i useqdec" ],
      "Your JSON contains block comments.":[ null,
        "Tangalt-ik JSON tegber iḥder n yiwenniten." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Tiisura tusligin ur ttwasirgent ara deg ifuyla JSON." ],
      "Your JSON is not valid.":[ null,
        "JSON inek mačči d ameγtu." ],
      "Your JSON file could not be parsed.":[ null,
        "Tangalt-ik JSON ur tezmir ara tettwasleḍ." ],
      "Reserved filename found.":[ null,
        "Isem n ufauylu ittuḥaṛṛen yettwaf." ],
      "We were unable to decompress the zip file.":[ null,
        "Ur nezmir ara ad n sefruri afaylu zip." ],
      "manifest.json was not found":[ null,
        "Afaylu manifest.json ur yettwaf ara" ],
      "File is too large to parse.":[ null,
        "Afaylu meqqer aṭas akken ad yettwasleḍ." ],
      "Hidden file flagged":[ null,
        "Afaylu uffir yettwacreḍ" ],
      "Flagged filename found":[ null,
        "Isem n ufaylu yettwacerḍen yettwaf" ],
      "Flagged file extensions found":[ null,
        "Isiɣzaf n ufaylu yettwacerḍen ttwafen" ],
      "Package contains duplicate entries":[ null,
        "Akemmus yegber inekcamen usligen" ],
      "Flagged file type found":[ null,
        "Anaw n ufaylu yettwacerḍen yettwaf" ],
      "Package already signed":[ null,
        "Akemmus yettwasezmel yakan" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Izegrar Firefox ur zmiren ara ad selkemen tifextin n tedrimt." ],
      "String name is reserved for a predefined message":[ null,
        "ISem n uzrir n yisekkilen yettwaḥeṛṛ i yizen yettwasbadun yakan" ],
      "Placeholder for message is missing":[ null,
        "Amḍiq yettwaḥerzen i yizen ulac-it" ],
      "A placeholder used in the message is not defined.":[ null,
        "Amḍiq yettwaḥerzen yettwasqedcen deg izen ur yettwasbadu ara." ],
      "Placeholder name contains invalid characters":[ null,
        "Amḍiq yettwaḥerzen yegber yir isekkilen" ],
      "Placeholder is missing the content property":[ null,
        "Amḍiq yettwaḥerzen ulac-it di tmeẓlit n ugbur" ],
      "Translation string is missing the message property":[ null,
        "Azrir n tsuqilt ur yegbir ara taɣara n yizen" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Ulac taɣara n yizen \"message yettusbadun i uzrir (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Wali https://mzl.la/20PenXl (MDN Docs) i wugar n telɣut." ],
      "Invalid host permission.":[ null,
        "Tasiregt n usenneftaɣ d tarameɣtut." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "Azal n \"manifest_version\" di manifest.json mačči d ameɣtu" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Wali https://mzl.la/20PenXl (MDN Docs) i wugar n telɣut." ],
      "The \"name\" property must be a string.":[ null,
        "Yessefk timeẓlit \"name\" ad tili d azrir n yisekkilen." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Wali http://mzl.la/1STmr48 (MDN Docs) i wugar n telɣut." ],
      "The \"version\" property must be a string.":[ null,
        "Talγut \"version\" isefk ad tili d aḍris." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Wali http://mzl.la/1kXIADa (MDN Docs) i wugar n telɣut." ],
      "The field is invalid.":[ null,
        "Aferdis arameγtu." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Timeẓlit \"version\" tseqdac kan  masal n Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Wali https://mzl.la/1ZOhoEN (MDN Docs) i wugar n telɣut." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" ur ittwasireg ara." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Taɣara \"update_url\" ur tt-yesseqdac ara Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" ilaq." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Tignit yettwasbadun deg umeskan ulac-itt deg ukemmus." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Ulac-ot di \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Ur izmir ara ad d-yaf askript n ugilal i yettusbadun deg umeskan." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Ur izmir ara ad d-yaf tugna n ugilal i yettusbadun deg umeskan." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Askript n ugilal ulac-it di \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Asebter n ugilal ulac-it di \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Ur izmir ara ad d-yaf askript n ugbur i yettusbadun deg umeskan." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Ur izmir ara ad d-yaf afaylu css n uskript n ugbur i yettusbadun deg umeskan." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Askript n ugbur deg umeskan ulac-it di \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Askript n ugbur deg ufaylu CSS deg umeskan ulac-it di \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Ur izmir ara ad d-yaf afaylu n umawal i yettusbadun deg umeskan." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Ur izmir ara ad d-yaf afaylu n umawal i yettusbadun deg umeskan deg \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Afaylu ameskan igber ddeqs n yimawalen." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Ddeqs n yimawalen ttusbadun deg umeskan, ayen ur nettusefrak ara." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Ameskan yegber taɣawsa amawal, maca d ilem." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Taɣawsa amawal tettusbadu deg umeskan, maca d ilem." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Ameskan yegber amawal, maca ulac timeẓlit id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Amawal yettwaf deg umeskan, maca ulac asulay id i yettusbadun." ],
      "Forbidden content found in add-on.":[ null,
        "Agbur igedlen yettwaf deg uzegrir." ],
      "This add-on contains forbidden content.":[ null,
        "Azegrir-agi yegber iferdisen yettwagedlen." ],
      "Icons must be square.":[ null,
        "Yessefk tignitin ad ilint d amkuz." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Tignit yellan deg wadi \"%(path)s\" yessefk ad tili d amkuz." ],
      "The size of the icon does not match the manifest.":[ null,
        "Teɣzi n tignit ur temṣada ara akked umeskan." ],
      "Corrupt image file":[ null,
        "Afaylu n tugna irreẓ" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Tignit yettwarǧan deg wadig \"%(path)s\" texseṛ" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Isem n usentel LWT yettwakkes deg Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Wali https://mzl.la/2T11Lkc (MDN Docs) i wugar n yisallen." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Tugna n usentel i \"%(type)s\" ur tettwaf ara deg \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Afaylu n tugna n usentel yeṛṛez" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Afaylu ntugna n usentel deg \"%(path)s\" yexṣer" ],
      "Theme image file has an unsupported file extension":[ null,
        "Asiɣzef n ufaylu n tugna n usentel ur yettusefrak ara" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Asiɣzef n ufaylu deg \"%(path)s\" ɣer-s asiɣzef ur yettusefraken ara" ],
      "Theme image file has an unsupported mime type":[ null,
        "Tugna n usentel ɣur-s anaw mime ur yettisefraken ara" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Tugna n usentel deg \"%(path)s\" ɣur-s anaw mime \"%(mime)s\" ur yettusefraken ara" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Anaw mime n ufaylu n tugna n usentel ur yemṣada ara d usiɣzef n ufaylu-is" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Asiɣzef n ufaylu n usentel deg \"%(path)s\" ur yemṣada ara akked wanaw-is mime amiran \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Tisuqilin ulac-iten i \"default_locale\"." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" ulac-it acu kan \"_locales\" yella." ],
      "Unsupported image extension":[ null,
        "Asiɣzef n tugna ur yettusefrak ara" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Yessefk tignitin ad ilint d yiwet seg  JPG/JPEG, WebP, GIF, PNG neɣ SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "Akaram n tutlayin d ilem" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Afaylu messages.json ulac-it di \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Tasarut n umeskan ur tettusefrak ara deg lqem Firefox adday i d-ittunefken" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Tasiregt ur tettusefrak ara deg lqem Firefox adday i d-ittunefken" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Tasarut n umeskan ur tettusefrak ara deg lqem Firefox Android adday i d-ittunefken" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Tasiregt ur tettusefrak ara deg lqem Firefox Android adday i d-ittunefken" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "Anaw-agi n tsiregt ur yettwasefrak ara." ],
      "The field is required.":[ null,
        "Aferdis-agi yettwasra." ],
      "Unknown permission.":[ null,
        "Tasiragt tarussint." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Wali https://mzl.la/1R1n1t0 (MDN Docs) i wugar n telɣut." ] } } }