export const enum MessageTypes {
    GET_CONFIG = 'GET_CONFIG',
    GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS',
    SET_CONFIG = 'SET_CONFIG',
    SET_CONFIG_SUCCESS = 'SET_CONFIG_SUCCESS',
    SET_CONFIG_FAIL = 'SET_CONFIG_FAIL',
    OPEN_ASSISTANT = 'OPEN_ASSISTANT',
    CLOSE_ASSISTANT = 'CLOSE_ASSISTANT',
}
