module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"nn_NO" },
      "Validation Summary:":[ null,
        "Valideringsoversikt:" ],
      Code:[ null,
        "Kode" ],
      Message:[ null,
        "Melding" ],
      Description:[ null,
        "Skildring" ],
      File:[ null,
        "Fil" ],
      Line:[ null,
        "Linje" ],
      Column:[ null,
        "Kolonne" ],
      "Invalid nesting of selectors found":[ null,
        "Ugyldig nesting av selektorar funne" ],
      "A CSS syntax error was encountered":[ null,
        "Det oppstod ein CSS-syntaksfeil" ],
      "Your FTL is not valid.":[ null,
        "FTL er ikkje gyldig." ],
      "Your FTL file could not be parsed.":[ null,
        "Klarte ikkje å tolke FTL-fila di." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Eksterne skript er ikkje tillatne ifølgje utvidingsretningslinjene." ],
      "Inline scripts blocked by default":[ null,
        "Inline-script er blokkerte som standard" ],
      "Unadvised 3rd-party JS library":[ null,
        "Ikkje-tilrådd tredjeparts JS-bibliotek" ],
      "Known JS library detected":[ null,
        "Kjent JS-bibliotek oppdaga" ],
      "{{api}} is not supported":[ null,
        "{{api}} er ikkje støtta" ],
      "This API has not been implemented by Firefox.":[ null,
        "Denne API-en har ikkje blitt implementert av Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" er tatt bort i Manifest Version 3 (eigenskapen `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} er forelda" ],
      "This API has been deprecated by Firefox.":[ null,
        "Denne API-en har blitt forelda av Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" er forelda eller ikkje implementert" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener' kalla med truthy som fjerde argument." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} er ikkje støtta i Firefox {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Denne API-en er ikkje implementert av den spesifiserte minimumsversjonen av Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} er ikkje støtta i Firefox for Android-versjon {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Denne API-en har ikkje blitt implementert av den spesifiserte minimumsversjonen av Firefox for Android." ],
      "Content script file could not be found.":[ null,
        "Fann ikkje innhaldskriptfila." ],
      "Content script file could not be found":[ null,
        "Fann ikkje innhaldskriptfila" ],
      "Content script file name should not be empty.":[ null,
        "Innhaldskriptfil-namnet skal ikkje vere tomt." ],
      "Content script file name should not be empty":[ null,
        "Innhaldsskript-filnamnet skal ikkje vere tomt" ],
      "JavaScript syntax error":[ null,
        "JavaScript-syntaxfeil" ],
      "Unexpected global passed as an argument":[ null,
        "Uventa global sendt som eit argument" ],
      "Use of document.write strongly discouraged.":[ null,
        "Bruk av document.write er ikkje tilrådd." ],
      "Banned 3rd-party JS library":[ null,
        "Forbydt tredjeparts JS-bibliotek" ],
      "Your JSON contains block comments.":[ null,
        "JSON-en din inneheld blokkkommentarar." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Doble nøklar er ikkje tillatne i JSON-filer." ],
      "Your JSON is not valid.":[ null,
        "JSON-en din er ugyldig." ],
      "Your JSON file could not be parsed.":[ null,
        "Klarte ikkje å tolke JSON-en din." ],
      "Reserved filename found.":[ null,
        "Reservert filnamn funne." ],
      "We were unable to decompress the zip file.":[ null,
        "Vi klarte ikkje å pakke ut zip-fila." ],
      "manifest.json was not found":[ null,
        "manifest.json vart ikkje funne" ],
      "File is too large to parse.":[ null,
        "Fila er for stor for å tolkast." ],
      "Hidden file flagged":[ null,
        "Gøymd fil flagga" ],
      "Flagged filename found":[ null,
        "Flagga filnamn vart funne" ],
      "Flagged file extensions found":[ null,
        "Flagga filutviding funne" ],
      "Package contains duplicate entries":[ null,
        "Pakke inneheld doble oppføringar" ],
      "Flagged file type found":[ null,
        "Flagga filtype vart funne" ],
      "Package already signed":[ null,
        "Pakken er allereie signert" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox tillegg får ikkje køyre coin-miners." ],
      "String name is reserved for a predefined message":[ null,
        "Strengnamn er reservert for ei førdefiniert melding" ],
      "Placeholder for message is missing":[ null,
        "Plasshaldar for meldinga manglar" ],
      "A placeholder used in the message is not defined.":[ null,
        "Ein plasshaldar som vert nytta i meldinga er ikkje definert." ],
      "Placeholder name contains invalid characters":[ null,
        "Namn på plasshaldar inneheld ugyldige teikn" ],
      "Placeholder is missing the content property":[ null,
        "Plasshaldaren manglar innhaldseigenskapen" ],
      "Translation string is missing the message property":[ null,
        "Omsettingsstrengen manglar meldingseigenskapen" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Ingen meldingseigenskap «message» er sett for ein streng (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Sjå https://mzl.la/2Qn0fWC (MDN Docs) for meir informasjon." ],
      "Invalid host permission.":[ null,
        "Ugyldig vertsløyve." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" i manifest.json er ikkje ein gyldig verdi" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Sjå https://mzl.la/20PenXl (MDN Docs) for meir informasjon." ],
      "The \"name\" property must be a string.":[ null,
        "Eigenskapen «namn» må vere ein streng." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Sjå http://mzl.la/1STmr48 (MDN Docs) for meir informasjon." ],
      "The \"version\" property must be a string.":[ null,
        "Eigenskapen «versjon» må vere ein streng." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Sjå http://mzl.la/1kXIADa (MDN Docs) for meir informasjon." ],
      "The field is invalid.":[ null,
        "Feltet er ugyldig." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Eigenskapen «versjon» nyttar eit Firefox-spesifikt format." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Sjå https://mzl.la/1ZOhoEN (MDN Docs) for meir informasjon." ],
      "\"update_url\" is not allowed.":[ null,
        "«update_url» er ikkje lov." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Eigenskapen \"update_url\" vert ikkje brukt av Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "«strict_max_versjon» ikkje påkravd." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Eit ikon definert i manifestet kunne ikkje finnast i pakka." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Klarte ikkje å finne ikon på \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Klarte ikkje å finne eit bakgrunnsskript definiert i manifestet." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Klarte ikkje å finne ei bakgrunnsside definiert i manifestet." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Fann ikkje bakgrunnsskriptet på \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Fann ikkje bakgrunnssida på \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Klarte ikkje å finne eit innehaldskript som er definiert i manifestet." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Klarte ikkje å finne ei css-fil med innhaldsskript som er definert i manifestet.." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Fann ikkje innhaldsskriptet definert i manifestet på \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Fann ikkje innhaldsskriptet til css-fila definert i manifestet på «%(path)s»." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Klarte ikkje å finne ei ordboksfil som er definert i manifestet." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Klarte ikkje å finne ordbokfil definiert i manifestet på \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifestet inneheld fleire ordbøker." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Fleire ordbøker er definert i manifestet som ikkje er støtta." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifestet inneheld eit ordboksobjekt, men det er tomt." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Eit ordboksobjekt er definert i manifestet, men det var tomt." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifestet inneheld ei ordbok men ingen ID-eigenskap." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Ei ordbok vart funnen i manifestet, men ingen ID er spesifisert." ],
      "Forbidden content found in add-on.":[ null,
        "Forbydd innhald funne i utvidinga." ],
      "This add-on contains forbidden content.":[ null,
        "Denne utvidinga inneheld forbydd innhald." ],
      "Icons must be square.":[ null,
        "Ikon må vere kvadratiske." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikona på \"%(path)s\" må vere kvadratiske." ],
      "The size of the icon does not match the manifest.":[ null,
        "Ikonstorleiken passar ikkje med manifestet." ],
      "Corrupt image file":[ null,
        "Skada bildefil" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Forventa ikonfil på \"%(path)s\" er skadd" ],
      "This property has been deprecated.":[ null,
        "Denne eigenskapen er forelda." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Temaet LWT-alias er fjerna frå Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Sjå https://mzl.la/2T11Lkc (MDN Docs) for meir informasjon." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Klarte ikkje å finne temabilde for «%(type)s» på «%(path)s»" ],
      "Corrupted theme image file":[ null,
        "Skada temabildefil" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Temabildefil \"%(path)s\" er skadd" ],
      "Theme image file has an unsupported file extension":[ null,
        "Temabildefila har ei filending som ikkje er støtta." ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Temabildefila på «%(path)s» har ei filending som ikkje er støtta" ],
      "Theme image file has an unsupported mime type":[ null,
        "Temabildefila har ein mime-type som ikkje er støtta" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Temabildefila på \"%(path)s\" har ei mime-type \"%(mime)s\" som ikkje er støtta" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Mime-typen for temabildefila samsvarar ikkje med filendinga" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Filendinga for temabildefila på «%(path)s» samsvarar ikkje med den verkelege mime-typen «%(mime)s»" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "«default_locale» manglar lokaliseringar." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "«default_locale» manglar men «_locales» finst." ],
      "Unsupported image extension":[ null,
        "Ustøtta bildefilending" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikon bør vere av typen JPG/JPEG, WebP, GIFF, PNG eller SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Eigenskapen «applications» overkøyrt av eigenskapen \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Tom språkkatalog" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "messages.json fil manglar i \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifestnøkkel er ikkje støtta av den spesifiserte minimum Firefox-versjonen" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Løyve er ikkje støtta av den spesifiserte minimum Firefox-versjonen" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifestnøkkelen er ikkje støtta av den spesifiserte minimum Firefox for Android-versjonen" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Løyve er ikkje  støtta av den spesifiserte minimum Firefox-versjonen for Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Det er ikkje tillate å lenke til «addons.mozilla.org»" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Lenker som leiar til «addons.mozilla.org» er ikkje tillatne å brukast for heimesida" ],
      "The permission type is unsupported.":[ null,
        "Kompetansetypen vert ikkje støtta." ],
      "The field is required.":[ null,
        "Feltet er påkravd." ],
      "Unknown permission.":[ null,
        "Ukjent løyve." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Sjå https://mzl.la/1R1n1t0 (MDN Docs) for meir informasjon." ] } } }