module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"en_CA" },
      "Validation Summary:":[ null,
        "Validation Summary:" ],
      Code:[ null,
        "Code" ],
      Message:[ null,
        "Message" ],
      Description:[ null,
        "Description" ],
      File:[ null,
        "File" ],
      Line:[ null,
        "Line" ],
      Column:[ null,
        "Column" ],
      "Invalid nesting of selectors found":[ null,
        "Invalid nesting of selectors found" ],
      "A CSS syntax error was encountered":[ null,
        "A CSS syntax error was encountered" ],
      "Your FTL is not valid.":[ null,
        "Your FTL is not valid." ],
      "Your FTL file could not be parsed.":[ null,
        "Your FTL file could not be parsed." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Remote scripts are not allowed as per the Add-on Policies." ],
      "Inline scripts blocked by default":[ null,
        "Inline scripts blocked by default" ],
      "Unadvised 3rd-party JS library":[ null,
        "Unadvised 3rd-party JS library" ],
      "Known JS library detected":[ null,
        "Known JS library detected" ],
      "{{api}} is not supported":[ null,
        "{{api}} is not supported" ],
      "This API has not been implemented by Firefox.":[ null,
        "This API has not been implemented by Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} is deprecated" ],
      "This API has been deprecated by Firefox.":[ null,
        "This API has been deprecated by Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" is deprecated or unimplemented" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` called with truthy fourth argument." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} is not supported in Firefox version {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "This API is not implemented by the given minimum Firefox version" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} is not supported in Firefox for Android version {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "This API is not implemented by the given minimum Firefox for Android version" ],
      "Content script file could not be found.":[ null,
        "Content script file could not be found." ],
      "Content script file could not be found":[ null,
        "Content script file could not be found" ],
      "Content script file name should not be empty.":[ null,
        "Content script file name should not be empty." ],
      "Content script file name should not be empty":[ null,
        "Content script file name should not be empty" ],
      "JavaScript syntax error":[ null,
        "JavaScript syntax error" ],
      "Unexpected global passed as an argument":[ null,
        "Unexpected global passed as an argument" ],
      "Use of document.write strongly discouraged.":[ null,
        "Use of document.write strongly discouraged." ],
      "Banned 3rd-party JS library":[ null,
        "Banned 3rd-party JS library" ],
      "Your JSON contains block comments.":[ null,
        "Your JSON contains block comments." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Duplicate keys are not allowed in JSON files." ],
      "Your JSON is not valid.":[ null,
        "Your JSON is not valid." ],
      "Your JSON file could not be parsed.":[ null,
        "Your JSON file could not be parsed." ],
      "Reserved filename found.":[ null,
        "Reserved filename found." ],
      "We were unable to decompress the zip file.":[ null,
        "We were unable to decompress the zip file." ],
      "manifest.json was not found":[ null,
        "manifest.json was not found" ],
      "File is too large to parse.":[ null,
        "File is too large to parse." ],
      "Hidden file flagged":[ null,
        "Hidden file flagged" ],
      "Flagged filename found":[ null,
        "Flagged filename found" ],
      "Flagged file extensions found":[ null,
        "Flagged file extensions found" ],
      "Package contains duplicate entries":[ null,
        "Package contains duplicate entries" ],
      "Flagged file type found":[ null,
        "Flagged file type found" ],
      "Package already signed":[ null,
        "Package already signed" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox add-ons are not allowed to run coin miners." ],
      "String name is reserved for a predefined message":[ null,
        "String name is reserved for a predefined message" ],
      "Placeholder for message is missing":[ null,
        "Placeholder for message is missing" ],
      "A placeholder used in the message is not defined.":[ null,
        "A placeholder used in the message is not defined." ],
      "Placeholder name contains invalid characters":[ null,
        "Placeholder name contains invalid characters" ],
      "Placeholder is missing the content property":[ null,
        "Placeholder is missing the content property" ],
      "Translation string is missing the message property":[ null,
        "Translation string is missing the message property" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "No “message” message property is set for a string (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "See https://mzl.la/2Qn0fWC (MDN Docs) for more information." ],
      "Invalid host permission.":[ null,
        "Invalid host permission." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "“manifest_version” in the manifest.json is not a valid value" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "See https://mzl.la/20PenXl (MDN Docs) for more information." ],
      "The \"name\" property must be a string.":[ null,
        "The “name” property must be a string." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "See http://mzl.la/1STmr48 (MDN Docs) for more information." ],
      "The \"version\" property must be a string.":[ null,
        "The “version” property must be a string." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "See http://mzl.la/1kXIADa (MDN Docs) for more information." ],
      "The field is invalid.":[ null,
        "The field is invalid." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "The “version” property uses a Firefox-specific format." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "See https://mzl.la/1ZOhoEN (MDN Docs) for more information." ],
      "\"update_url\" is not allowed.":[ null,
        "“update_url” is not allowed." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "The “update_url” property is not used by Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "“strict_max_version” not required." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "An icon defined in the manifest could not be found in the package." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Icon could not be found at “%(path)s”." ],
      "A background script defined in the manifest could not be found.":[ null,
        "A background script defined in the manifest could not be found." ],
      "A background page defined in the manifest could not be found.":[ null,
        "A background page defined in the manifest could not be found." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Background script could not be found at “%(path)s”." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Background page could not be found at “%(path)s”." ],
      "A content script defined in the manifest could not be found.":[ null,
        "A content script defined in the manifest could not be found." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "A content script CSS file defined in the manifest could not be found." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Content script defined in the manifest could not be found at “%(path)s”." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Content script CSS file defined in the manifest could not be found at “%(path)s”." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "A dictionary file defined in the manifest could not be found." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Dictionary file defined in the manifest could not be found at \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "The manifest contains multiple dictionaries." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Multiple dictionaries were defined in the manifest, which is unsupported." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "The manifest contains a dictionaries object, but it is empty." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "A dictionaries object was defined in the manifest, but it was empty." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "The manifest contains a dictionary but no id property." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "A dictionary was found in the manifest, but there was no id set." ],
      "Forbidden content found in add-on.":[ null,
        "Forbidden content found in add-on." ],
      "This add-on contains forbidden content.":[ null,
        "This add-on contains forbidden content." ],
      "Icons must be square.":[ null,
        "Icons must be square." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Icon at “%(path)s” must be square." ],
      "The size of the icon does not match the manifest.":[ null,
        "The size of the icon does not match the manifest." ],
      "Corrupt image file":[ null,
        "Corrupt image file" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Expected icon file at “%(path)s” is corrupted" ],
      "This property has been deprecated.":[ null,
        "This property has been deprecated." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "This theme LWT alias has been removed in Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "See https://mzl.la/2T11Lkc (MDN Docs) for more information." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Theme image for \"%(type)s\" could not be found at \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Corrupted theme image file" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Theme image file at \"%(path)s\" is corrupted" ],
      "Theme image file has an unsupported file extension":[ null,
        "Theme image file has an unsupported file extension" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Theme image file at \"%(path)s\" has an unsupported file extension" ],
      "Theme image file has an unsupported mime type":[ null,
        "Theme image file has an unsupported mime type" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Theme image file mime type does not match its file extension" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "The “default_locale” is missing localizations." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "The “default_locale” is missing but “_locales” exist." ],
      "Unsupported image extension":[ null,
        "Unsupported image extension" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "\"applications\" property overridden by \"browser_specific_settings\" property" ],
      "Empty language directory":[ null,
        "Empty language directory" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "messages.json file missing in “%(path)s”" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifest key not supported by the specified minimum Firefox version" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Permission not supported by the specified minimum Firefox version" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifest key not supported by the specified minimum Firefox for Android version" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Permission not supported by the specified minimum Firefox for Android version" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Linking to \"addons.mozilla.org\" is not allowed" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage" ],
      "The permission type is unsupported.":[ null,
        "The permission type is unsupported." ],
      "The field is required.":[ null,
        "The field is required." ],
      "Unknown permission.":[ null,
        "Unknown permission." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "See https://mzl.la/1R1n1t0 (MDN Docs) for more information." ] } } }