module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=4; plural=(n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3);",
        lang:"dsb" },
      "Validation Summary:":[ null,
        "Pśeglědowańske zespominanje:" ],
      Code:[ null,
        "Kod" ],
      Message:[ null,
        "Powěsć" ],
      Description:[ null,
        "Wopisanje" ],
      File:[ null,
        "Dataja" ],
      Line:[ null,
        "Smužka" ],
      Column:[ null,
        "Słup" ],
      "Invalid nesting of selectors found":[ null,
        "Njepłaśiwe zašachtelikanje selektorow namakane" ],
      "A CSS syntax error was encountered":[ null,
        "Syntaksowa zmólka CSS jo nastała" ],
      "Your FTL is not valid.":[ null,
        "Waš FTL njejo płaśiwy." ],
      "Your FTL file could not be parsed.":[ null,
        "Waša FTL-dataja njejo dała se parsowaś." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Daloke skripty njejsu dowólone pó pšawidłach dodankow." ],
      "Inline scripts blocked by default":[ null,
        "Skripty inline se pó standarźe blokěruju" ],
      "Unadvised 3rd-party JS library":[ null,
        "Njeznata JS-biblioteka tśeśego póbitowarja" ],
      "Known JS library detected":[ null,
        "Znata JS-biblioteka namakana" ],
      "{{api}} is not supported":[ null,
        "{{api}} se njepódpěra" ],
      "This API has not been implemented by Firefox.":[ null,
        "Toś ten API njejo se implementěrował pśez Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "„{{api}}“ jo se wótwónoźeł we wersiji 3 manifest (kakosć `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} se wěcej njepódpěra" ],
      "This API has been deprecated by Firefox.":[ null,
        "Toś ten API se pśez Firefox wěcej njepódpěra." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "„{{api}}“ se wěcej njepódpěra abo jo njeimplementěrowany" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` wołany z truthy ako stwórty argument." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} se we wersiji {{minVersion}} Firefox njepódpěra" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Toś ten API njejo se implementěrował pśez pódanu minimalnu wersiju Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} se we wersiji {{minVersion}} Firefox za Android njepódpěra" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Toś ten API njejo se implementěrował pśez pódanu minimalnu wersiju Firefox za Android" ],
      "Content script file could not be found.":[ null,
        "Wopśimjeśowa skriptowa dataja njejo se namakała." ],
      "Content script file could not be found":[ null,
        "Wopśimjeśowa skriptowa dataja njejo se namakała" ],
      "Content script file name should not be empty.":[ null,
        "Mě wopśimjeśoweje skriptoweje dataje njeměło prozne byś." ],
      "Content script file name should not be empty":[ null,
        "Mě wopśimjeśoweje skriptoweje dataje njeměło prozne byś" ],
      "JavaScript syntax error":[ null,
        "Syntaksowa zmólka JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Njewócakana globala jo se ako argument pśepódała" ],
      "Use of document.write strongly discouraged.":[ null,
        "Wót wužywanja document.write se wuraznje wótraźujo." ],
      "Banned 3rd-party JS library":[ null,
        "JS-biblioteka tśeśego póbitowarja zakazana" ],
      "Your JSON contains block comments.":[ null,
        "Waš JSON blokowe komentary wopśiámujo." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Dwójne kluce njejsu dowólone w JSON-datajach." ],
      "Your JSON is not valid.":[ null,
        "Waš JSON njejo płaśiwy." ],
      "Your JSON file could not be parsed.":[ null,
        "Waša JSON-dataja njejo se dała parsowaś." ],
      "Reserved filename found.":[ null,
        "Rezerwěrowane datajowe mě namakane." ],
      "We were unable to decompress the zip file.":[ null,
        "Njejsmy mógli zip-dataju rozpakowaś." ],
      "manifest.json was not found":[ null,
        "manifest.json njejo se namakał" ],
      "File is too large to parse.":[ null,
        "Dataja jo pśewjelika za parsowanje." ],
      "Hidden file flagged":[ null,
        "Schowana dataja wóznamjenjona" ],
      "Flagged filename found":[ null,
        "Wóznamjenjone datajowe mě namakane" ],
      "Flagged file extensions found":[ null,
        "Woznamjenjone datajowe kóńcowki namakane" ],
      "Package contains duplicate entries":[ null,
        "Pakśik dwójne zapiski wopśimujo" ],
      "Flagged file type found":[ null,
        "Wóznamjenjony datajowy typ namakany" ],
      "Package already signed":[ null,
        "Pakśik jo južo signěrowany" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Dodanki Firefox njesměju pjenjezekopaki wuwjasć." ],
      "String name is reserved for a predefined message":[ null,
        "Mě znamuškowego rjeśazka jo wuměnjone za pśeddefiněrowanu powěźeńku" ],
      "Placeholder for message is missing":[ null,
        "Zastupujucy symbol za powěźeńku felujo" ],
      "A placeholder used in the message is not defined.":[ null,
        "Zastupujucy symbol, kótaryž se w powěźeńce wužywa, njejo definěrowany." ],
      "Placeholder name contains invalid characters":[ null,
        "Mě zastupujucego symbola njepłaśiwe znamuška wopśimujo" ],
      "Placeholder is missing the content property":[ null,
        "Zastupujucemu symboloju kakosć content felujo" ],
      "Translation string is missing the message property":[ null,
        "Pśełožowańskemu znamuškowemu rjeśazkoju kakosć message felujo" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Zdźěleńska kakosć \"message\" njejo za znamuškowy rjeśazk nastajona (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Glejśo https://mzl.la/2Qn0fWC (MDN Docs) za dalšne informacije." ],
      "Invalid host permission.":[ null,
        "Njepłaśiwe hostowe pšawo" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" w manifest.json njejo płaśiwa gódnota" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Glejśo https://mzl.la/20PenXl (MDN Docs) za dalšne informacije." ],
      "The \"name\" property must be a string.":[ null,
        "Kakosć \"name\" musy znamuškowy rjeśazk byś." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Glejśo http://mzl.la/1STmr48 (MDN Docs) za dalšne informacije." ],
      "The \"version\" property must be a string.":[ null,
        "Kakosć \"version\" musy znamuškowy rjeśazk byś." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Glejśo http://mzl.la/1kXIADa (MDN Docs) za dalšne informacije." ],
      "The field is invalid.":[ null,
        "Pólo jo njepłaśiwe." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Kakosć \"version\" format wužywa, kótaryž jo specifiski za Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Glejśo https://mzl.la/1ZOhoEN (MDN Docs) za dalšne informacije." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" njejo dowólony." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Kakosć \"update_url\" se wót Firefox njewužywa." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" njejo trěbny." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Symbol, kótaryž jo se w manifesće definěrował, njedajo se w pakśiku namakaś." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Symbol njedajo se na \"%(path)s\" namakaś." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Slězynowy skript, kótaryž jo se definěrował w manifesće, njedajo se namakaś." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Slězynowy bok, kótaryž jo se definěrował w manifesće, njedajo se namakaś." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Slězynowy skript njedajo se na \"%(path)s\" namakaś." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Slězynowy bok njedajo se na \"%(path)s\" namakaś." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Wopśimjeśowy skript, kótaryž jo se definěrował w manifesće, njedajo se namakaś." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "CSS-dataja wopśimjeśowego skripta, kótaraž jo se definěrowała w manifesće, njedajo se namakaś." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Wopśimjeśowy skript, kótaryž jo se w manifesće definěrował, njedajo se na \"%(path)s\" namakaś." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "CSS-dataja wopśimjeśowego skripta, kótaraž jo se w manifesće definěrowała, njedajo se na \"%(path)s\" namakaś." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Słownikowa dataja, kótaraž jo se definěrowała w manifesće, njedajo se namakaś." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Słownikowa dataja, kótaraž jo se definěrowała w manifesće, njedajo se na \"%(path)s\" namakaś." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifest někotare słowniki wopśimujo." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Někotre słowniki su se w manifesće definěrowali, což se njepódpěra." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifest słownikowy objekt wopśimujo, ale jo prozny." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Słownikowy objekt jo se w manifesće definěrował, ale jo był prozny." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifest słownik wopśimujo, ale nic kakosć ID." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Słownik jo se namakał w manifesće, ale njejo se póstajił žeden ID." ],
      "Forbidden content found in add-on.":[ null,
        "Zakazane wopśimjeśe w dodanku namakany." ],
      "This add-on contains forbidden content.":[ null,
        "Toś ten dodank zakazane wopśimjeśe wopśimujo." ],
      "Icons must be square.":[ null,
        "Symbole muse kwadratiske byś." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Symbol na \"%(path)s\" musy kwadratiski byś." ],
      "The size of the icon does not match the manifest.":[ null,
        "Wjelikosć symbola manifestoju njewótpowědujo." ],
      "Corrupt image file":[ null,
        "Wobškóźona wobrazowa dataja" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Wócakana symbolowa dataja na \"%(path)s\" jo wobškóźona" ],
      "This property has been deprecated.":[ null,
        "Toś ta kakosć se wěcej njepódpěra." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Alias LWT toś teje drastwy jo se wótwónoźeł w Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Glejśo https://mzl.la/2T11Lkc (MDN Docs) za dalšne informacije." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Drastwowy wobraz za \"%(type)s\" njedajo se na \"%(path)s\" namakaś" ],
      "Corrupted theme image file":[ null,
        "Wobškóźona wobrazowa dataja drastwy" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Wobrazowa dataja drastwy na \"%(path)s\" jo wobškóźona" ],
      "Theme image file has an unsupported file extension":[ null,
        "Wobrazowa dataja drastwy ma datajowu kóńcowku, kótaraž se njepódpěra" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Wobrazowa dataja drastwy na \"%(path)s\" ma datajowu kóńcowku, kótaraž se njepódpěra" ],
      "Theme image file has an unsupported mime type":[ null,
        "Wobrazowa dataja drastwy ma typ MIME, kótaryž se njepódpěra" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Wobrazowa dataja drastwy na \"%(path)s\" ma typ MIME \"%(mime)s\", kótaryž se njepódpěra" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Typ MIME wobrazoweje dataje drastwy jeje datajowej kóńcowce njewótpowědujo" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Kóńcowka wobrazoweje dataje drastwy na \"%(path)s\" jeje napšawdnemu typoju MIME \"%(mime)s\" njewótpowěda" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "W \"default_locale\" lokalizacije feluju." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" felujo, ale \"_locales\" eksistěruju." ],
      "Unsupported image extension":[ null,
        "Kóńcowka wobrazoweje dataje se njepódpěra" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Symbole měli dataje typa JPG/JPEG, WebP, GIF, PNG abo SVG byś." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Kakosć „applications“ jo se pśepisała pśez kakosć „browser_specific_settings“" ],
      "Empty language directory":[ null,
        "Prozny zapis rěcow" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Dataja messages.json w \"%(path)s\" felujo" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifestowy kluc se pśez pódanu minimalnu wersiju Firefox njepódpěra" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Pšawo se pśez pódanu minimalnu wersiju Firefox njepódpěra" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifestowy kluc se pśez pódanu minimalnu wersiju Firefox za Android njepódpěra" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Pšawo se pśez pódanu minimalnu wersiju Firefox za Android njepódpěra" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Wótkazowanje na „addons.mozilla.org“ njejo dowólone" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Wótkaze, kótarež na „addons.mozilla.org“ pokazuju, njesměju se za startowy bok wužywaś." ],
      "The permission type is unsupported.":[ null,
        "Typ dowólnosći se njepódpěra." ],
      "The field is required.":[ null,
        "Pólo jo trěbne." ],
      "Unknown permission.":[ null,
        "Njeznata dowólnosć." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Glejśo https://mzl.la/1R1n1t0 (MDN Docs) za dalšne informacije." ] } } }