module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"el" },
      "Validation Summary:":[ null,
        "Σύνοψη επαλήθευσης:" ],
      Code:[ null,
        "Κώδικας" ],
      Message:[ null,
        "Μήνυμα" ],
      Description:[ null,
        "Περιγραφή" ],
      File:[ null,
        "Αρχείο" ],
      Line:[ null,
        "Γραμμή" ],
      Column:[ null,
        "Στήλη" ],
      "Invalid nesting of selectors found":[ null,
        "Βρέθηκε άκυρη εμφώλευση επιλογέων" ],
      "A CSS syntax error was encountered":[ null,
        "Παρουσιάστηκε συντακτικό σφάλμα CSS" ],
      "Your FTL is not valid.":[ null,
        "Το FTL σας δεν είναι έγκυρο." ],
      "Your FTL file could not be parsed.":[ null,
        "Αδυναμία λήψης του αρχείου FTL σας." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Τα απομακρυσμένα σενάρια δεν επιτρέπονται σύμφωνα με τις Πολιτικές Προσθέτων." ],
      "Inline scripts blocked by default":[ null,
        "Τα inline σενάρια αποκλείονται από προεπιλογή" ],
      "Unadvised 3rd-party JS library":[ null,
        "Ασύνετη βιβλιοθήκη JS τρίτου" ],
      "Known JS library detected":[ null,
        "Ανιχνεύθηκε γνωστή βιβλιοθήκη JS" ],
      "{{api}} is not supported":[ null,
        "Το {{api}} δεν υποστηρίζεται" ],
      "This API has not been implemented by Firefox.":[ null,
        "Αυτό το API δεν έχει υλοποιηθεί από το Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "Το «{{api}}» έχει αφαιρεθεί στην έκδοση 3 του μανιφέστου (ιδιότητα `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "Το {{api}} είναι παρωχημένο" ],
      "This API has been deprecated by Firefox.":[ null,
        "Αυτό το API έχει καταργηθεί από το Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "Το «{{api}}» είναι παρωχημένο ή δεν έχει υλοποιηθεί" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` κλήθηκε με τέταρτο όρισμα truthy." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "Το {{api}} δεν υποστηρίζεται στην έκδοση {{minVersion}} του Firefox" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Αυτό το API δεν έχει υλοποιηθεί από τη δεδομένη ελάχιστη έκδοση του Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "Το {{api}} δεν υποστηρίζεται στην έκδοση {{minVersion}} του Firefox για Android" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Αυτό το API δεν έχει υλοποιηθεί από τη δεδομένη ελάχιστη έκδοση του Firefox για Android" ],
      "Content script file could not be found.":[ null,
        "Δεν ήταν δυνατή η εύρεση του αρχείου σεναρίου περιεχομένου." ],
      "Content script file could not be found":[ null,
        "Δεν ήταν δυνατή η εύρεση του αρχείου σεναρίου περιεχομένου" ],
      "Content script file name should not be empty.":[ null,
        "Το όνομα του αρχείου σεναρίου περιεχομένου δεν πρέπει να είναι κενό." ],
      "Content script file name should not be empty":[ null,
        "Το όνομα του αρχείου σεναρίου περιεχομένου δεν πρέπει να είναι κενό" ],
      "JavaScript syntax error":[ null,
        "Συντακτικό σφάλμα JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Μια απροσδόκητη καθολική μεταβλητή πέρασε ως όρισμα" ],
      "Use of document.write strongly discouraged.":[ null,
        "Η χρήση του document.write δεν προτείνεται." ],
      "Banned 3rd-party JS library":[ null,
        "Απαγορευμένη βιβλιοθήκη JS τρίτου" ],
      "Your JSON contains block comments.":[ null,
        "Το JSON σας περιέχει σχόλια μπλοκ." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Δεν επιτρέπονται διπλότυπα κλειδιά στα αρχεία JSON." ],
      "Your JSON is not valid.":[ null,
        "Το JSON σας δεν είναι έγκυρο." ],
      "Your JSON file could not be parsed.":[ null,
        "Δεν ήταν δυνατή η λήψη του αρχείου JSON σας." ],
      "Reserved filename found.":[ null,
        "Βρέθηκε κρατημένο όνομα αρχείου." ],
      "We were unable to decompress the zip file.":[ null,
        "Δεν ήταν δυνατή η αποσυμπίεση του αρχείου zip." ],
      "manifest.json was not found":[ null,
        "Το manifest.json δεν βρέθηκε" ],
      "File is too large to parse.":[ null,
        "Το αρχείο είναι πολύ μεγάλο για λήψη." ],
      "Hidden file flagged":[ null,
        "Το κρυφό αρχείο επισημάνθηκε" ],
      "Flagged filename found":[ null,
        "Βρέθηκε επισημασμένο όνομα αρχείου" ],
      "Flagged file extensions found":[ null,
        "Βρέθηκαν επισημασμένες επεκτάσεις αρχείου" ],
      "Package contains duplicate entries":[ null,
        "Το πακέτο περιέχει διπλότυπες καταχωρήσεις" ],
      "Flagged file type found":[ null,
        "Βρέθηκε επισημασμένος τύπος αρχείου" ],
      "Package already signed":[ null,
        "Το πακέτο έχει ήδη υπογραφεί" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Τα πρόσθετα του Firefox δεν επιτρέπεται να εκτελούν εξόρυξη κρυπτονομισμάτων." ],
      "String name is reserved for a predefined message":[ null,
        "Το όνομα νήματος κρατείται για ένα προκαθορισμένο μήνυμα" ],
      "Placeholder for message is missing":[ null,
        "Το σύμβολο υποκατάστασης για το μήνυμα λείπει" ],
      "A placeholder used in the message is not defined.":[ null,
        "Ένα σύμβολο υποκατάστασης, που χρησιμοποιείται στο μήνυμα, δεν έχει οριστεί." ],
      "Placeholder name contains invalid characters":[ null,
        "Το όνομα συμβόλου υποκατάστασης περιέχει άκυρους χαρακτήρες" ],
      "Placeholder is missing the content property":[ null,
        "Η ιδιότητα \"content\" λείπει από το σύμβολο υποκατάστασης" ],
      "Translation string is missing the message property":[ null,
        "Η ιδιότητα \"message\" λείπει από το νήμα μετάφρασης" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Δεν έχει οριστεί καμία ιδιότητα μηνύματος \"message\" για συμβολοσειρά (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Δείτε το https://mzl.la/2Qn0fWC (MDN Docs) για περισσότερες πληροφορίες." ],
      "Invalid host permission.":[ null,
        "Μη έγκυρο δικαίωμα κεντρικού υπολογιστή." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "Το \"manifest_version\" στο manifest.json δεν είναι έγκυρο όνομα" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Δείτε το https://mzl.la/20PenXl (MDN Docs) για περισσότερες πληροφορίες." ],
      "The \"name\" property must be a string.":[ null,
        "Η ιδιότητα \"name\" πρέπει να είναι συμβολοσειρά." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Δείτε το http://mzl.la/1STmr48 (Έγγραφα MDN) για περισσότερες πληροφορίες." ],
      "The \"version\" property must be a string.":[ null,
        "Η ιδιότητα \"version\" πρέπει να είναι συμβολοσειρά." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Δείτε το http://mzl.la/1kXIADa (Έγγραφα MDN) για περισσότερες πληροφορίες." ],
      "The field is invalid.":[ null,
        "Το πεδίο δεν είναι έγκυρο." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Η ιδιότητα «version» χρησιμοποιεί μια μορφή, ειδικά για το Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Δείτε το https://mzl.la/1ZOhoEN (Έγγραφα MDN) για περισσότερες πληροφορίες." ],
      "\"update_url\" is not allowed.":[ null,
        "Το \"update_url\" δεν επιτρέπεται." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Η ιδιότητα \"update_url\" δεν χρησιμοποιείται από το Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "Δεν απαιτείται «strict_max_version»." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Δεν ήταν δυνατή η εύρεση ενός αρχείου, που ορίζεται στο μανιφέστο, στο πακέτο." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Δεν ήταν δυνατή η εύρεση του εικονιδίου στο \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Δεν ήταν δυνατή η εύρεση του σεναρίου φόντου, που ορίζεται στο μανιφέστο." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Δεν ήταν δυνατή η εύρεση της σελίδας φόντου, που ορίζεται στο μανιφέστο." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Δεν ήταν δυνατή η εύρεση σεναρίου παρασκηνίου στο \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Δεν ήταν δυνατή η εύρεση σελίδας παρασκηνίου στο \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Δεν ήταν δυνατή η εύρεση του σεναρίου περιεχομένου, που ορίζεται στο μανιφέστο." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Δεν ήταν δυνατή η εύρεση του σεναρίου περιεχομένου του αρχείου css, που ορίζεται στο μανιφέστο." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Δεν ήταν δυνατή η εύρεση του σεναρίου περιεχομένου, που ορίζεται στο μανιφέστο, στο \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Δεν ήταν δυνατή η εύρεση του σεναρίου περιεχομένου του αρχείου css, που ορίζεται στο μανιφέστο, στο \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Δεν ήταν δυνατή η εύρεση ενός αρχείου λεξικού, που ορίζεται στο μανιφέστο." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Δεν ήταν δυνατή η εύρεση του αρχείου λεξικού, που ορίζεται στο μανιφέστο, στο \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Το αρχείο μανιφέστου περιέχει πολλαπλά λεξικά." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Ορίζονται πολλαπλά λεξικά στο μανιφέστο, κάτι που δεν υποστηρίζεται." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Το μανιφέστο περιέχει ένα αντικείμενο λεξικών, αλλά είναι κενό." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Ένα αντικείμενο λεξικών ορίστηκε στο μανιφέστο, αλλά ήταν κενό." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Το μανιφέστο περιέχει ένα λεξικό, άλλα καμία ιδιότητα id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Βρέθηκε ένα λεξικο στο μανιφέστο, αλλά δεν ορίστηκε id." ],
      "Forbidden content found in add-on.":[ null,
        "Βρέθηκε απαγορευμένο περιεχόμενο στο πρόσθετο." ],
      "This add-on contains forbidden content.":[ null,
        "Αυτό το πρόσθετο περιέχει απαγορευμένο περιεχόμενο." ],
      "Icons must be square.":[ null,
        "Τα εικονίδια πρέπει να είναι τετράγωνα." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Το εικονίδιο στο \"%(path)s\" πρέπει να είναι τετράγωνο." ],
      "The size of the icon does not match the manifest.":[ null,
        "Το μέγεθος του εικονιδίου δεν αντιστοιχεί στο αρχείο manifest." ],
      "Corrupt image file":[ null,
        "Κατεστραμμένο αρχείο εικόνας" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Το αναμενόμενο αρχείο εικονιδίου στο \"%(path)s\" έχει καταστραφεί" ],
      "This property has been deprecated.":[ null,
        "Αυτή η ιδιότητα έχει καταργηθεί." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Το ψευδώνυμο LWT αυτού του θέματος έχει αφαιρεθεί στο Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Δείτε το https://mzl.la/2T11Lkc (MDN Docs) για περισσότερες πληροφορίες." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Δεν ήταν δυνατή η εύρεση εικόνας θέματος για \"%(type)s\" στο \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Κατεστραμμένο αρχείο εικόνας θέματος" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Το αρχείο εικόνας θέματος στο \"%(path)s\" έχει καταστραφεί" ],
      "Theme image file has an unsupported file extension":[ null,
        "Το αρχείο εικόνας θέματος έχει μια μη υποστηριζόμενη επέκταση αρχείου" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Το αρχείο εικόνας θέματος στο \"%(path)s\" έχει μια μη υποστηριζόμενη επέκταση αρχείου" ],
      "Theme image file has an unsupported mime type":[ null,
        "Το αρχείο εικόνας θέματος έχει ένα μη υποστηριζόμενο τύπο mime" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Το αρχείο εικόνας θέματος στο \"%(path)s\" έχει τον μη υποστηριζόμενο τύπο mime, \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Ο τύπος mime του αρχείου εικόνας θέματος δεν ταιριάζει με την επέκταση αρχείου" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Η επέκταση αρχείου εικόνας θέματος στο \"%(path)s\" δεν αντιστοιχεί στον πραγματικό τύπο mime της, \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Λείπουν μεταφράσεις από τo \"default_locale\"." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Το «default_locale» λείπει, αλλά το «_locales» υπάρχει." ],
      "Unsupported image extension":[ null,
        "Μη υποστηριζόμενη επέκταση εικόνας" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Τα εικονίδια πρέπει να είναι JPG/JPEG, WebP, GIF, PNG ή SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Η ιδιότητα «applications» αντικαταστάθηκε από την ιδιότητα «browser_specific_settings»" ],
      "Empty language directory":[ null,
        "Κενός κατάλογος γλώσσας" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Το αρχείο messages.json λείπει από το «%(path)s»" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Το κλειδί μανιφέστου δεν υποστηρίζεται από την καθορισμένη ελάχιστη έκδοση του Firefox" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Η άδεια δεν υποστηρίζεται από την καθορισμένη ελάχιστη έκδοση του Firefox" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Το κλειδί μανιφέστου δεν υποστηρίζεται από την καθορισμένη ελάχιστη έκδοση του Firefox για Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Η άδεια δεν υποστηρίζεται από την καθορισμένη ελάχιστη έκδοση του Firefox για Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Δεν επιτρέπεται σύνδεσμος για το «addons.mozilla.org»" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Δεν επιτρέπεται η χρήση συνδέσμων προς το «addons.mozilla.org» για την αρχική σελίδα" ],
      "The permission type is unsupported.":[ null,
        "Ο τύπος δικαιώματος δεν υποστηρίζεται." ],
      "The field is required.":[ null,
        "Απαιτούμενο πεδίο." ],
      "Unknown permission.":[ null,
        "Άγνωστο δικαίωμα." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Δείτε το https://mzl.la/1R1n1t0 (MDN Docs) για περισσότερες πληροφορίες." ] } } }