module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"cak" },
      "Validation Summary:":[ null,
        "Ruch'utitzijol Junamana'oj:" ],
      Code:[ null,
        "Bitz'ib'" ],
      Message:[ null,
        "Tzijol" ],
      Description:[ null,
        "Cholonem" ],
      File:[ null,
        "Yakb'äl" ],
      Line:[ null,
        "B'ey" ],
      Column:[ null,
        "Tem" ],
      "Invalid nesting of selectors found":[ null,
        "Ye'ilitäj itzel kisok cha'onela'" ],
      "A CSS syntax error was encountered":[ null,
        "Xilitäj jun rusachj CSS cholb'ab'" ],
      "Your FTL is not valid.":[ null,
        "Man okel ta ri FTL." ],
      "Your FTL file could not be parsed.":[ null,
        "Man xpachq'ominïx ta ri FTL ayakb'al." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Man yek'ul ta ri näj taq skrip kuma ri Chokoy taq Na'ojil." ],
      "Inline scripts blocked by default":[ null,
        "Kan eq'aton wi ri ch'ikon taq skrip" ],
      "Unadvised 3rd-party JS library":[ null,
        "Mechilab'en 3ox-winäq JS wujb'äl" ],
      "Known JS library detected":[ null,
        "Xilitäj etaman JS wujib'äl" ],
      "{{api}} is not supported":[ null,
        "{{api}} man nuk'äm ta ri'" ],
      "This API has not been implemented by Firefox.":[ null,
        "Man ya'on ta rusamajib'al re API re' ruma ri Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` oyon rik'in jun okel rukaj na'oj." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "" ],
      "Content script file could not be found.":[ null,
        "Man nilitäj ta ri skrip ruyakb'al rupam." ],
      "Content script file could not be found":[ null,
        "Man nilitäj ta ri ruyakb'al rupam skrip " ],
      "Content script file name should not be empty.":[ null,
        "Man tikirel ta nikowe' kan ri rub'i' ri ruyakb'al rupam script." ],
      "Content script file name should not be empty":[ null,
        "Man tikirel ta nikowe' kan ri rub'i' ri ruyakb'al rupam script" ],
      "JavaScript syntax error":[ null,
        "Sachoj JavaScript cholb'äl" ],
      "Unexpected global passed as an argument":[ null,
        "Chijun jalajonel man oyob'en ta ojer achi'el jun na'oj" ],
      "Use of document.write strongly discouraged.":[ null,
        "Man nichilab'ëx ta rokisaxik ri document.write." ],
      "Banned 3rd-party JS library":[ null,
        "Q'ilon 3ox-winäq JS wujb'äl" ],
      "Your JSON contains block comments.":[ null,
        "Ri JSON ruk'wan k'ïy cholaj taq tzij." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Man tikirel ta yekamulüx ewan taq tzij pa JSON taq yakb'äl." ],
      "Your JSON is not valid.":[ null,
        "Man okel ta ri JSON." ],
      "Your JSON file could not be parsed.":[ null,
        "Man xpachq'ominïx ta ri JSON ayakb'al." ],
      "We were unable to decompress the zip file.":[ null,
        "Man xojtikïr ta xsol ri zip yakb'äl." ],
      "manifest.json was not found":[ null,
        "ma xilitäj ta ri manifest.json" ],
      "File is too large to parse.":[ null,
        "Yalan nïm ri yakb'äl richin nich'ob'." ],
      "Hidden file flagged":[ null,
        "Xya' ruq'ij jun ewan yakb'äl" ],
      "Flagged filename found":[ null,
        "Xilitäj rub'i' yakb'äl ya'on ruq'ij" ],
      "Flagged file extensions found":[ null,
        "Xilitäj kik'amal yakb'äl ya'on ruq'ij" ],
      "Package contains duplicate entries":[ null,
        "Ri pisoj ruk'wan jujun kamulun taq okitz'ib'" ],
      "Flagged file type found":[ null,
        "Xilitäj ruwäch yakb'äl ya'on ruq'ij" ],
      "Package already signed":[ null,
        "Juch'un chik ri pisoj" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Man ya'on ta q'ij chi ke ri kichokoy Firefox richin yekisamajij taq ko'in-miner." ],
      "String name is reserved for a predefined message":[ null,
        "Ri rub'i' cholajil q'aton richin jun tzijol k'o wi" ],
      "Placeholder for message is missing":[ null,
        "Nrajo' na ri retanel kik'ojlib'al taq tzijol" ],
      "A placeholder used in the message is not defined.":[ null,
        "Man xjikib'äx ta ri retanel k'ojlib'äl xokisäx pa ri rutzijol." ],
      "Placeholder name contains invalid characters":[ null,
        "Ri rub'i' retanel k'ojlib'äl ruk'wan man okel ta taq tz'ib'" ],
      "Placeholder is missing the content property":[ null,
        "Nrajo' na richinil rupam ri retanel k'ojlib'äl" ],
      "Translation string is missing the message property":[ null,
        "Nrajo' na ri richinil rutzijol pa ri rucholajem tzalq'onem" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Majun richinil rutzijol \"rutzijol\" xb'an runuk'ulem pa ri rucholajil (https://mzl.la/2DSBTjA)." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" pa ri manifest.json man okel ta ri rejqalem" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Titz'et https://mzl.la/20PenXl (MDN Wujil) richin ch'aqa' chik etamab'äl." ],
      "The \"name\" property must be a string.":[ null,
        "Ri \"name\" ichinil k'o chi jun string." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Titz'et http://mzl.la/1STmr48 (MDN Wujil) richin ch'aqa' chik etamab'äl." ],
      "The \"version\" property must be a string.":[ null,
        "Ri richinil \"version\" k'o chi jun string." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Titz'et http://mzl.la/1kXIADa (MDN Wujil) richin ch'aqa' chik etamab'äl." ],
      "The field is invalid.":[ null,
        "Man okel ta ri k'ojlem." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Ri \"version\" ichinil nrokisaj jun jikil rub'anikil Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Titz'et https://mzl.la/1ZOhoEN (MDN Wujil) richin ch'aqa' chik etamab'äl." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" man niya' q'ij chi re." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Ri \"update_url\" ichinil man nokisäx ta ruma ri Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" man k'atzinel ta." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Man xilitäj ta pa ri pisoj jun wachib'äl jikib'an pa ri tzijoxik." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Man nilitäj ta ri wachib'äl pa \"%(path)s\"." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Man nilitäj ta ri ruskrip ruka'n b'ey pa \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Man nilitäj ta ri ruxaq richin ruka'n b'ey pa \"%(path)s\"." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Man xilitäj ta ri ruskrip rupam jikib'an pa tzijoxïk pa \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Man xilitäj ta ri css yakb'äl ruskrip rupam jikib'an pa tzijoxïk pa \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "" ],
      "Forbidden content found in add-on.":[ null,
        "Xilitäj man ruk'amon ta rupam pa ri tz'aqat." ],
      "This add-on contains forbidden content.":[ null,
        "Re tz'aqat re' ruk'wan man ruk'amon ta rupam." ],
      "Icons must be square.":[ null,
        "K'o chi kajtz'ik kib'anikil ri taq wachib'äl." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ri wachib'äl pa \"%(path)s\" k'o chi kajtz'ik rub'anikil." ],
      "The size of the icon does not match the manifest.":[ null,
        "Ri runimilem wachib'äl man nuk'äm ta ri' rik'in ri tzijoxïk." ],
      "Corrupt image file":[ null,
        "Ruyakb'al itzel wachib'äl" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Itzelan ri ruyakb'al wachib'al pa \"%(path)s\"" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "" ],
      "Theme image file has an unsupported file extension":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "" ],
      "Theme image file has an unsupported mime type":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Ri \"default_locale\" nrajo' na rutzalq'omanik." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Nrajo' na ri \"default_locale\" po ri \"_locales\" e k'o." ],
      "Unsupported image extension":[ null,
        "Man nik'ul ta ri ruk'amal wachib'äl" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ri taq wachib'äl k'o ta chi e JPG/JPEG, WebP, GIF, PNG o SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "Kowöl kicholb'al ch'ab'äl" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "man k'o ta ri messages.json yakb'äl pa \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "Man nik'ul ta ri ruwäch ya'oj q'ij." ],
      "The field is required.":[ null,
        "K'atzinel ri k'ojlib'äl." ],
      "Unknown permission.":[ null,
        "Man etaman ta ruwäch ya'oj q'ij." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Titz'et https://mzl.la/1R1n1t0 (MDN Wujil) richin ch'aqa' chik etamab'äl." ] } } }