---
version: 2
plan:
  project-key: AJL
  key: ADGUARDAPIMV3TESTS
  name: Adguard API MV3 - tests
variables:
  dockerContainer: adguard/node-ssh:22.14--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            branch="${bamboo_planRepository_branchName}"
            target_branch="${bamboo_repository_pr_targetBranch:-master}"

            is_root_affected() {
              git diff --name-only "${target_branch}"...HEAD | grep -v '^packages/' > /dev/null
            }

            is_project_affected() {
              local project_name="$1"
              pnpm list --filter "...[${target_branch}]" --depth=-1 | grep -q "${project_name}"
            }

            if [ "$branch" != "master" ] && ! is_root_affected && ! is_project_affected "@adguard/tswebextension"; then
              echo "No changes in project, skipping tests"
              exit 0;
            fi

            # Install dependencies
            pnpm install

            # Build api
            npx lerna run build --scope @adguard/api-mv3 --include-dependencies

            # Run e2e tests for api
            npx lerna run e2e --scope @adguard/api-mv3
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []

other:
  concurrent-build-plugin: system-default
