---
version: 2
plan:
  project-key: AJL
  key: ADGUARDAPIINCREMENT
  name: Adguard API  - increment
variables:
  dockerContainer: adguard/node-ssh:16.17--1

stages:
  - Increment:
      manual: 'true'
      final: 'false'
      jobs:
        - Increment

Increment:
  key: INCR
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    # Stop increment when current branch not 'epic/tswebextension',
    # because AdGuard API is only being worked on in the 'epic/tswebextension' branch
    - stop-job:
        success: 'true'
        conditions:
        - variable:
            not-equals:
              bamboo.planRepository.branchName: epic/tswebextension
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Increment @adguard/api
            npx lerna run --scope @adguard/api increment
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

labels: [ ]

other:
  concurrent-build-plugin: system-default
