---
version: 2
plan:
  project-key: AJL
  key: AGTREETEST
  name: AGTree - tests
variables:
  dockerContainer: adguard/node-ssh:16.17--1

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Bootstrap the package
            npx lerna@6 bootstrap --scope @adguard/agtree --include-dependencies

            # Check TypeScript types with TSC
            npx lerna@6 run --scope @adguard/agtree check-types

            # Validate compatibility tables
            npx lerna@6 run --scope @adguard/agtree check-compatibility-tables

            # Check code with ESLint
            npx lerna@6 run --scope @adguard/agtree lint

            # Run tests with Jest
            npx lerna@6 run --scope @adguard/agtree test

            # cleanup parent
            rm -rf node_modules

            # cleanup child packages
            npx lerna@6 clean -y
  final-tasks:
    - clean
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
