---
version: 2
plan:
  project-key: AJL
  key: AGTREETEST
  name: AGTree - tests
variables:
  dockerContainer: adguard/node-ssh:18.19--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            # Run NX CLI to find projects changed since the master branch and check if the specified project is affected.
            # And store grep exit status to determine if the project was found (0) or not (1).
            is_affected=$(pnpm dlx nx show projects --affected --select=projects --base=master --head=HEAD | grep -q "@adguard/agtree"; echo $?)

            branch="${bamboo.planRepository.branchName}"

            # If not on 'master' and the project is not affected, skip tests for it.
            if [ "$branch" != "master" ] && [ "$is_affected" -ne 0 ]; then
              echo "No changes in project, skipping tests"
              exit 0;
            fi

            pnpm install

            # Check TypeScript types with TSC
            pnpm --filter @adguard/agtree check-types

            # Validate compatibility tables
            pnpm --filter @adguard/agtree check-compatibility-tables

            # Check code with ESLint
            pnpm --filter "$project_name" lint

            # Run tests with Jest
            pnpm --filter "$project_name" test
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            pnpm clean
  
            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
