---
version: 2
plan:
  project-key: AJL
  key: AGTREEBUILD
  name: AGTree - build
variables:
  dockerContainer: adguard/node-ssh:22.14--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}
            pnpm install

            # Build dependencies, then the package itself
            pnpm --filter "@adguard/agtree..." --depth=-1 build

            # Pack the AGTree package into a tarball
            cd packages/agtree
            pnpm tgz
    - inject-variables:
        file: ./packages/agtree/dist/build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: agtree-v${bamboo.inject.version}
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            pnpm clean
            rm -rf .git

            echo "Size after cleanup:" && du -h | tail -n 1
  # Store the AGTree package tarball as an artifact
  artifacts:
    - name: agtree.tgz
      location: packages/agtree/
      pattern: agtree.tgz
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []

other:
  concurrent-build-plugin: system-default
