---
version: 2
plan:
  project-key: AJL
  key: AGTREEBUILD
  name: AGTree - build
variables:
  dockerContainer: adguard/node-ssh:16.17--1

stages:
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Bootstrap the packages with Lerna
            npx lerna bootstrap

            # Build AGTree with Rollup
            npx lerna run --scope @adguard/agtree build -- ${bamboo.varsYarn}

            # Pack the AGTree package into a tarball
            cd packages/agtree/
            yarn pack --filename agtree.tgz
            cd ../../

            # Cleanup parent
            rm -rf node_modules

            # Cleanup child packages
            npx lerna clean -y
    - inject-variables:
        file: ./packages/agtree/dist/build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: agtree-v${bamboo.inject.version}
  # Store the AGTree package tarball as an artifact
  artifacts:
    - name: agtree.tgz
      location: packages/agtree/
      pattern: agtree.tgz
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []

other:
  concurrent-build-plugin: system-default
