---
version: 2
plan:
  project-key: AJL
  key: DNRCONVERTERINCREMENT
  name: DNR Converter - increment
variables:
  dockerContainer: adguard/node-ssh:22.17--0

stages:
  - Increment:
      manual: true
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # FIXME: Implement increment
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: true

labels: [ ]

other:
  concurrent-build-plugin: system-default