---
version: 2
plan:
  project-key: AJL
  key: DNRRULESETSTEST
  name: DNR Rulesets - tests
variables:
  dockerContainer: adguard/node-ssh:18.19--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            # Install dependencies
            pnpm --filter @adguard/dnr-rulesets install

            # Run linter
            pnpm --filter @adguard/dnr-rulesets lint
  
            # Run tests
            pnpm --filter @adguard/dnr-rulesets test
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            # Check if node_modules directory exists
            if [ -d "node_modules" ]; then
              pnpm clean
            else
              echo "node_modules directory does not exist, skipping pnpm clean"
            fi

            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
