---
version: 2
plan:
  project-key: AJL
  key: DNRRULESETSAUTOBUILD
  name: DNR Rulesets - auto build

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - DoNothing

# Since auto-build is being run only for stable branches:
# branch 'stable/dnr-rulesets-3.3' - for AdGuard API v3.1
# branch 'stable/dnr-rulesets-4.0' - for AdGuard browser extension v5.3.0.X
# branch 'stable/dnr-rulesets-4.1' - for AdGuard browser extension v5.3.1.X
# we should skip the build stage for other branches.
DoNothing: !include 'jobs/dnr-rulesets-auto-build/do-nothing.yaml'

triggers: []

branches: &branches
  create: manually
  delete: never
  link-to-jira: true

# Run plan only for:
# branch 'stable/dnr-rulesets-3.3' - for AdGuard API v3.1
# branch 'stable/dnr-rulesets-4.0' - for AdGuard browser extension v5.3.X
# branch 'stable/dnr-rulesets-4.1' - for AdGuard browser extension v5.3.1.X
# Override is needed to skip the build stage for other branches,
# because even if branches are not supposed to be run for PRs (due to 'create: manually' above),
# build was triggered by 'cron' anyway.
branch-overrides:
  - '^stable\/dnr-rulesets-(3\.3|4\.0|4\.1)$':
      stages:
        - Build:
            - Build
      Build: !include 'jobs/dnr-rulesets-auto-build/build.yaml'

      # runs plan every 1 hour since our filters are updated every hour.
      triggers:
        - cron:
            expression: 0 0 */1 * * ?

      branches: *branches

      labels: []

      other:
        concurrent-build-plugin: system-default
