---
version: 2
plan:
  project-key: AJL
  key: DNRRULESETSINCREMENT
  name: DNR Rulesets - increment
stages:
  - Increment:
    - Increment
Increment:
  tasks:
    - script:
      - echo 'Task run successfully!'
  requirements:
    - adg-docker: 'true'
    - extension: 'true'
