---
version: 2
plan:
  project-key: AJL
  key: DNRCONVERTERBUILD
  name: DNR Converter - build
variables:
  dockerContainer: adguard/node-ssh:22.17--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # TODO: Implement build (AG-45668)
  artifacts:
    - name: dnr-converter.tgz
      location: packages/dnr-converter/
      pattern: dnr-converter.tgz
      shared: true
      required: true
  requirements:
    - extension: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

labels: []

other:
  concurrent-build-plugin: system-default
