---
version: 2
plan:
  project-key: AJL
  key: DNRCONVERTERINCREMENT
  name: DNR Converter - increment
variables:
  dockerContainer: adguard/node-ssh:22.17--0

stages:
  - Increment:
      manual: true
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            branch="${bamboo.planRepository.branchName}"

            # Throw error if current branch is not "master",
            # because we do not deploy changes from other branches
            if [ $branch != "master" ]
            then
              echo "increment is not supported on branch ${branch}"
              exit 1;
            fi

            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}
            pnpm install

            # Increment @adguard/dnr-converter
            pnpm run increment dnr-converter
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number for DNR Converter'
          selectedRepository: defaultRepository
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: true

labels: [ ]

other:
  concurrent-build-plugin: system-default
