---
# This plan describes two increments: one for tswebextension and another for tsurlfilter
# This needs, because now we develop two packages in one branch
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONINCR
  name: tswebextension - increment
variables:
  dockerContainer: adguard/node-ssh:14.18--0

stages:
  - Increment-tswebextension:
      manual: 'false'
      final: 'false'
      jobs:
        - Increment-tswebextension

Increment-tswebextension:
  key: INCRTSWEBEXT
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - stop-job:
        success: 'true'
        conditions:
        - variable:
            not-equals:
              # Stop build when current branch not 'epic/tswebextension'
              bamboo.planRepository.branchName: epic/tswebextension
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Increment tswebextension
            npx lerna run --scope @adguard/tswebextension increment
            # Increment tsurlfilter alpha version for linking tswebextension,
            # e.x. when install tswebextension in extension package
            npx lerna run --scope @adguard/tsurlfilter increment:alpha
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build numbers'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

labels: [ ]

other:
  concurrent-build-plugin: system-default
