---
version: 2
plan:
  project-key: AJL
  key: ESLINTPLUGINLOGGERBUILD
  name: eslint-plugin-logger-context - build
variables:
  dockerContainer: adguard/node-ssh:22.14--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Create dummy artifact for Bamboo check (needed for AG-40151)
            mkdir -p packages/eslint-plugin-logger-context/
            touch packages/eslint-plugin-logger-context/eslint-plugin-logger-context.tgz
            echo "Dummy artifact generated at packages/eslint-plugin-logger-context/eslint-plugin-logger-context.tgz"
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh packages/eslint-plugin-logger-context/eslint-plugin-logger-context.tgz"
  artifacts:
    - name: eslint-plugin-logger-context.tgz
      location: packages/eslint-plugin-logger-context/
      pattern: eslint-plugin-logger-context.tgz
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []

other:
  concurrent-build-plugin: system-default
