---
version: 2
plan:
  project-key: AJL
  key: AGTSWEBEXTMVTHREETEST
  name: examples-tswebextension-mv3 - tests
variables:
  dockerContainer: adguard/node-ssh:18.19--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            # Install deps
            pnpm install

            # Lint
            pnpm --filter tswebextension-mv3 lint

            # Build
            npx lerna run build --scope tswebextension-mv3 --include-dependencies

#            # Test
#            # Should be run after build, since test requires build
#            # TODO fail if tests are not passing
#            pnpm --filter tswebextension-mv3 test
# TODO add artifacts for testing
#  artifacts:
#    - name: extension.zip
#      location: packages/examples/adguard-api/build
#      pattern: extension.zip
#      shared: true
#      required: false
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            pnpm clean
  
            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
