---
version: 2
plan:
  project-key: AJL
  key: TSURLFILTERTEST
  name: tsurlfilter - tests
variables:
  dockerContainer: adguard/node-ssh:15.14--6

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            ls -alt

            yarn install

            cd ./packages/tsurlfilter && yarn install
            cd ../..

            npx lerna bootstrap
            npx lerna run --scope @adguard/tsurlfilter test:prod
            npx lerna run --scope @adguard/tsurlfilter build
  final-tasks:
    - clean
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]
other:
  concurrent-build-plugin: system-default
