---
version: 2
plan:
  project-key: AJL
  key: TSURLFILTERTEST
  name: tsurlfilter - tests
variables:
  dockerContainer: adguard/node-ssh:22.14--0
  testTimeout: 180s

# State 1:
# Some packages are independent of each other
# so we can run them in parallel, i.e. logger and css-tokenizer.
#
# Next stages are about single package tests since they depend on each other:
# - AGTree;
# - TSUrlFilter;
# - TSWebExtension and DNR-Rulesets — can be run in parallel.
#
# State 2:
# - AGTree test run;
# - CSS Tokenizer benchmarks which are non-relevant to AGTree and can be run in parallel.
#
# State 3:
# - TSUrlFilter test run;
# - AGTree benchmarks which are non-relevant to TSUrlFilter and can be run in parallel.
#
# State 4:
# - TSWebExtension and DNR-Rulesets test run.
#
# State 5:
# - Examples APIs test run;
# - Examples TSWebExtensions test run;
# - Update TSUrlFilter docs MV3.
#
# Final state:
# - Cleanup.

# Experiment:
# Only jobs from State 1 use requires clean checkout.
# Since later jobs rely on previous jobs, let's try this approach.

stages:
  - State 1:
      manual: false
      final: false
      jobs:
        - TestLogger
        - TestCssTokenizer
  - State 2:
      manual: false
      final: false
      jobs:
        - TestAgTree
        # add non-relevant to agtree job to run in parallel
        - TestBenchmarkCssTokenizer
  - State 3:
      manual: false
      final: false
      jobs:
        - TestTSUrlFilter
        # add non-relevant to tsurlfilter job to run in parallel
        - TestBenchmarkAGTree
        - TestBenchmarkAGTreeBrowser
  - State 4:
      manual: false
      final: false
      jobs:
        - TestTSWebExtension
        - TestDNRRulesets
  - State 5:
      manual: false
      final: false
      jobs:
        - TestExamplesApi
        - TestExamplesApiMV3
        - TestExamplesTSWebExtension2
        - TestExamplesTSWebExtension3
        - UpdateTSUrlFilterDocsMV3
  - Cleanup:
      manual: false
      final: true
      jobs:
        - Cleanup

# NOTE: Each script is separate because, otherwise, Bamboo does not fail in the case of an error.

TestLogger:
  key: TESTLOGGER
  docker: &docker
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script: &setup-script
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/setup-tests.sh"
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/logger-tests.sh"
  requirements: &requirements
    - adg-docker: 'true'
    - extension: 'true'

TestCssTokenizer:
  key: TESTCSSTOKENIZER
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/css-tokenizer-tests.sh"
  requirements: *requirements

TestAgTree:
  key: TESTAGTREE
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/agtree-tests.sh"
  requirements: *requirements

TestTSUrlFilter:
  key: TESTTSURLFILTER
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tsurlfilter-tests.sh"
  requirements: *requirements

TestTSWebExtension:
  key: TESTTSWEBEXTENSION
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tswebextension-tests.sh"
  requirements: *requirements

TestDNRRulesets:
  key: TESTDNRRULESETS
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/dnr-rulesets-tests.sh"
  requirements: *requirements

TestExamplesTSWebExtension2:
  key: TESTEXAMPLESTSWEBEXTENSION2
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-tswebextension-mv2-tests.sh"
  requirements: *requirements

TestExamplesTSWebExtension3:
  key: TESTEXAMPLESTSWEBEXTENSION3
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-tswebextension-mv3-tests.sh"
  requirements: *requirements

TestExamplesApi:
  key: TESTEXAMPLESAPI
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-adguard-api-tests.sh"
  artifacts:
    - name: examples-adguard-api-extension.zip
      location: packages/examples/adguard-api/build
      pattern: extension.zip
      shared: false
      required: false
  requirements: *requirements

TestExamplesApiMV3:
  key: TESTEXAMPLESAPI3
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-adguard-api-mv3-tests.sh"
  artifacts:
    - name: examples-adguard-api-mv3-extension.zip
      location: packages/examples/adguard-api-mv3/build
      pattern: extension.zip
      shared: false
      required: false
  requirements: *requirements

TestBenchmarkCssTokenizer:
  key: TESTBENCHMARKCSSTOKENIZER
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/benchmarks-css-tokenizer-benchmark-tests.sh"
  requirements: *requirements

TestBenchmarkAGTree:
  key: TESTBENCHMARKAGTREE
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/benchmarks-agtree-benchmark-tests.sh"
  requirements: *requirements

TestBenchmarkAGTreeBrowser:
  key: TESTBENCHMARKAGTREEBROWSER
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/benchmarks-agtree-browser-benchmark-tests.sh"
  requirements: *requirements

UpdateTSUrlFilterDocsMV3:
  key: UPDTSURLFILTERDOCSMV3
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tsurlfilter-update-docs-mv3.sh"
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic update tsurlfilter MV3 docs'
          selectedRepository: defaultRepository
  requirements: *requirements

Cleanup:
  key: CLEAN
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: false
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            du -h . | sort -hr | head -n 30

            # Check if node_modules directory exists
            if [ -d "node_modules" ]; then
              # to run clean commands in the packages
              pnpm -r clean

              # to remove node_modules
              pnpm clean
            else
              echo "node_modules directory does not exist, skipping pnpm clean"
            fi

            echo "Size after cleanup:" && du -h | tail -n 1
  requirements: *requirements

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
