---
version: 2
plan:
  project-key: AJL
  key: TSURLFILTERTEST
  name: tsurlfilter - tests
variables:
  dockerContainer: adguard/node-ssh:16.17--1

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            npx lerna@6 bootstrap --scope @adguard/tsurlfilter --include-dependencies

            npx lerna@6 run --scope @adguard/tsurlfilter lint

            npx lerna@6 run --scope @adguard/tsurlfilter build

            # IMPORTANT: run tests after the build because smoke tests requires tsurlfilter to have built dist dir
            npx lerna@6 run --scope @adguard/tsurlfilter test:prod

            # cleanup parent
            rm -rf node_modules
            # cleanup child packages
            npx lerna@6 clean -y
  final-tasks:
    - clean
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
