---
version: 2
plan:
  project-key: AJL
  key: TSURLFILTERTEST
  name: tsurlfilter - tests
variables:
  dockerContainer: adguard/node-ssh:22.14--0
  testTimeout: 180s

# Some packages are independent of each other so we can run them in parallel (different jobs on same stage)
# other packages depend on each other so they should be run one after another (different stages),
# e.g. CSSTokenizer and Logger are totally independent,
# but DNR-Ruleset depends on TSUrlFilter, so even if it does not depend on TSWebExtension,
# they should run on different stages, this way bamboo cache is used ("[local cache]" in logs).
#
# Dependencies are described in the README.md file ("Dependency Tree" section).

# State 1:
# - Logger test run;
# - CSS Tokenizer test run.
#
# State 2:
# - AGTree test run;
# - CSS Tokenizer benchmarks which are non-relevant to AGTree and can be run in parallel.
#
# State 3:
# - TSUrlFilter test run;
# - AGTree benchmarks which are non-relevant to TSUrlFilter and can be run in parallel.
#
# State 4:
# - TSWebExtension test run;
# - Update TSUrlFilter Docs MV3.
#
# State 5:
# - DNR-Rulesets test run;
#
# State 6:
# - Example TSWebExtensions for MV2 and MV3.
#
# State 7:
# - Example APIs for MV2 and MV3.
#
# Final state:
# - Cleanup.

# Experiment:
# Only jobs from State 1 use requires clean checkout.
# Since later jobs rely on previous jobs, let's try this approach.
# And default value for 'force-clean-build' is false.

stages:
  - State 1: &stage
      manual: false
      final: false
      jobs:
        - Test Logger
        - Test CSSTokenizer
  - State 2:
      <<: *stage
      jobs:
        - Test AGTree
        - Test Benchmark CSSTokenizer
  - State 3:
      <<: *stage
      jobs:
        - Test TSUrlFilter
        - Test Benchmark AGTree
        - Test Benchmark AGTree Browser
  - State 4:
      <<: *stage
      jobs:
        - Test TSWebExtension
        - Update TSUrlFilter Docs MV3
  - State 5:
      <<: *stage
      jobs:
        - Test DNR-Rulesets
  - State 6:
      <<: *stage
      jobs:
        - Test Example TSWebExtensions - MV2 and MV3
  - State 7:
      <<: *stage
      jobs:
        - Test Example APIs - MV2 and MV3
  - Cleanup:
      <<: *stage
      final: true
      jobs:
        - Cleanup

# NOTE: Each script is separate because, otherwise, Bamboo does not fail in the case of an error.

Test Logger:
  key: TESTLOGGER
  docker: &docker
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script: &setup-script
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            ls -alt

            # Fix mixed logs
            exec 2>&1

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/logger-tests.sh"
  requirements: &requirements
    - adg-docker: 'true'
    - extension: 'true'

Test CSSTokenizer:
  key: TESTCSSTOKENIZER
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/css-tokenizer-tests.sh"
  requirements: *requirements

Test AGTree:
  key: TESTAGTREE
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/agtree-tests.sh"
  requirements: *requirements

Test TSUrlFilter:
  key: TESTTSURLFILTER
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tsurlfilter-tests.sh"
  requirements: *requirements

Test TSWebExtension:
  key: TESTTSWEBEXTENSION
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tswebextension-tests.sh"
  requirements: *requirements

Test DNR-Rulesets:
  key: TESTDNRRULESETS
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/dnr-rulesets-tests.sh"
  requirements: *requirements

Test Example TSWebExtensions - MV2 and MV3:
  key: TESTEXAMPLETSWEBEXTENSIONS
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-tswebextension-mv2-tests.sh"
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-tswebextension-mv3-tests.sh"
  requirements: *requirements

Test Example APIs - MV2 and MV3:
  key: TESTEXAMPLEAPIS
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          # try another timeout limit
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-adguard-api-tests.sh"
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/examples-adguard-api-mv3-tests.sh"
  artifacts:
    - name: examples-adguard-api-extension.zip
      location: packages/examples/adguard-api/build
      pattern: extension.zip
      shared: false
      required: false
    - name: examples-adguard-api-mv3-extension.zip
      location: packages/examples/adguard-api-mv3/build
      pattern: extension.zip
      shared: false
      required: false
  requirements: *requirements

Test Benchmark CSSTokenizer:
  key: TESTBENCHMARKCSSTOKENIZER
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/benchmarks-css-tokenizer-benchmark-tests.sh"
  requirements: *requirements

Test Benchmark AGTree:
  key: TESTBENCHMARKAGTREE
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/benchmarks-agtree-benchmark-tests.sh"
  requirements: *requirements

Test Benchmark AGTree Browser:
  key: TESTBENCHMARKAGTREEBROWSER
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/benchmarks-agtree-browser-benchmark-tests.sh"
  requirements: *requirements

Update TSUrlFilter Docs MV3:
  key: UPDTSURLFILTERDOCSMV3
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tsurlfilter-update-docs-mv3.sh"
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic update tsurlfilter MV3 docs'
          selectedRepository: defaultRepository
  requirements: *requirements

Cleanup:
  key: CLEAN
  docker: *docker
  tasks:
    - checkout
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            du -h . | sort -hr | head -n 30

            # Check if node_modules directory exists
            if [ -d "node_modules" ]; then
              # to run clean commands in the packages
              pnpm -r clean

              # to remove node_modules
              pnpm clean
            else
              echo "node_modules directory does not exist, skipping pnpm clean"
            fi

            echo "Size after cleanup:" && du -h | tail -n 1
  requirements: *requirements

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
