---
version: 2
plan:
  project-key: AJL
  key: TSURLFILTERTEST
  name: tsurlfilter - tests
variables:
  dockerContainer: adguard/node-ssh:18.19--0

stages:
  - Tests:
      manual: false
      final: false
      docker:
        image: "${bamboo.dockerContainer}"
        volumes:
          ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
      # Jobs will run in parallel to reduce the total plan time
      jobs:
        - AGTree tests
        - CSS Tokenizer tests
        - Example AdGuard API tests
        - Example TsWebExtension MV2 tests
        - Example TsWebExtension MV3 tests
        - Logger tests
        - TsUrlFilter tests
        - TsWebExtension tests
  - Update docs:
      docker:
        image: "${bamboo.dockerContainer}"
        volumes:
          ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
      manual: false
      final: false
      jobs:
        - Update docs
  - Clean:
      docker:
        image: "${bamboo.dockerContainer}"
        volumes:
          ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
      manual: false
      final: true
      jobs:
        - Clean

AGTree tests:
  key: AGTREETESTS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/agtree-tests.sh
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

CSS Tokenizer tests:
  key: CSSTOKENIZERTETS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/css-tokenizer-tests.sh
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

Example AdGuard API tests:
  key: EXAMPLESADGUARDAPITESTS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/examples-adguard-api-tests.sh
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

Example TsWebExtension MV2 tests:
  key: EXAMPLESTSWEBEXTENSIONMV2TESTS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/examples-tswebextension-mv2-tests.sh
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

Example TsWebExtension MV3 tests:
  key: EXAMPLESTSWEBEXTENSIONMV3TESTS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/examples-tswebextension-mv3-tests.sh
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

Logger tests:
  key: LOGGERTESTS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/logger-tests.sh
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

TsUrlFilter tests:
  key: TSURLFILTERTESTS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/tsurlfilter-tests.sh
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

TsWebExtension tests:
  key: TSWEBEXTENSIONTESTS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/tswebextension-tests.sh
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

Update docs:
  key: DOCS
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/setup-tests.sh
    - script:
        interpreter: SHELL
        scripts:
          - bamboo-specs/scripts/tsurlfilter-update-docs-mv3.sh
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic update tsurlfilter MV3 docs'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

Clean:
  key: CLEAN
  tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            du -h . | sort -hr | head -n 30

            # Check if node_modules directory exists
            if [ -d "node_modules" ]; then
              # to run clean commands in the packages
              pnpm -r clean

              # to remove node_modules
              pnpm clean
            else
              echo "node_modules directory does not exist, skipping pnpm clean"
            fi

            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: examples-adguard-api-extension.zip
      location: packages/examples/adguard-api/build
      pattern: extension.zip
      shared: false
      required: false
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
