---
version: 2
plan:
  project-key: AJL
  key: TSURLFILTERUPDDOCSMV3
  name: tsurlfilter - update docs mv3
variables:
  dockerContainer: adguard/node-ssh:22.17--0
  testTimeout: 600s

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: TSURLFILTERDOCSMV3
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            branch="${bamboo.planRepository.branchName}"

            # Only allow master and release/* branches.
            if [ "$branch" != "master" ] && [[ "$branch" != release/* ]]
            then
              echo "tsurlfilter docs mv3 update is not supported on branch ${branch}."
              exit 0;
            fi

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/timeout-wrapper.sh ${bamboo.testTimeout} ./bamboo-specs/scripts/tsurlfilter-update-docs-mv3.sh"
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic update tsurlfilter MV3 docs'
          selectedRepository: defaultRepository
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

# run docs update at 10:00 every day
triggers:
  - cron:
      expression: 0 0 10 ? * *

branches:
  create: manually
  delete: never
  link-to-jira: true

labels: [ ]

other:
  concurrent-build-plugin: system-default
