---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONBUILD
  name: tswebextension - build
variables:
  dockerContainer: adguard/node-ssh:16.17--1

stages:
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            npx lerna bootstrap --scope @adguard/tswebextension --include-dependencies
            npx lerna run --scope @adguard/tswebextension build

            cd packages/tswebextension/
            yarn pack --filename tswebextension.tgz
            cd ../../

            # cleanup parent
            rm -rf node_modules
            # cleanup child packages
            npx lerna clean -y
    - inject-variables:
        file: ./packages/tswebextension/dist/build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: tswebextension-v${bamboo.inject.version}
  artifacts:
    - name: tswebextension.tgz
      location: packages/tswebextension/
      pattern: tswebextension.tgz
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []

other:
  concurrent-build-plugin: system-default
