---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONINCR
  name: tswebextension - increment
variables:
  dockerContainer: adguard/node-ssh:14.18--0

stages:
  - Increment:
      manual: 'false'
      final: 'false'
      jobs:
        - Increment

Increment:
  key: INCR
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - stop-job:
        success: 'true'
        conditions:
        - variable:
            not-equals:
              # Stop build when current branch not 'epic/tswebextension'
              bamboo.planRepository.branchName: epic/tswebextension
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            ls -alt

            yarn install

            npx lerna run --scope @adguard/tswebextension increment

            # cleanup parent
            rm -rf node_modules
            # cleanup child packages
            npx lerna exec -- rm -rf node_modules
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

labels: [ ]

other:
  concurrent-build-plugin: system-default
