---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONTEST
  name: tswebextension - tests
variables:
  dockerContainer: adguard/node-ssh:16.17--1

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - stop-job:
        success: 'true'
        conditions:
        - variable:
            not-equals:
              # Stop build when target PR branch not 'epic/tswebextension'
              bamboo.repository.pr.targetBranch: epic/tswebextension
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            npx lerna bootstrap

            # build tsurlfilter first, because it is used in tswebextension tests
            npx lerna run --scope @adguard/tsurlfilter build
  
            npx lerna run --scope @adguard/tswebextension test:prod
            npx lerna run --scope @adguard/tswebextension build

            # cleanup parent
            rm -rf node_modules
            # cleanup child packages
            npx lerna clean -y
  final-tasks:
    - clean
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
