---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONBUILD
  name: tswebextension - build
variables:
  dockerContainer: adguard/node-ssh:22.14--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}
            pnpm install

            npx lerna run build --scope @adguard/tswebextension --include-dependencies

            cd packages/tswebextension

            pnpm tgz
    - inject-variables:
        file: ./packages/tswebextension/dist/build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: tswebextension-v${bamboo.inject.version}
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh packages/tswebextension/tswebextension.tgz"
  artifacts:
    - name: tswebextension.tgz
      location: packages/tswebextension/
      pattern: tswebextension.tgz
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []

other:
  concurrent-build-plugin: system-default
