---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONBUILD
  name: tswebextension - build
variables:
  dockerContainer: adguard/node-ssh:22.14--0

stages:
  - Test before build: &stage
      manual: false
      final: false
      jobs:
        - Test prod with no cache
  - Build:
      <<: *stage
      jobs:
        - Build
  - Cleanup:
      <<: *stage
      final: true

Test prod with no cache:
  key: TESTPROD
  other:
    clean-working-dir: true
  docker: &docker
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script: &setup-script
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            ls -alt

            # Fix mixed logs
            exec 2>&1

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}
    - script:
        interpreter: SHELL
        scripts:
          - |-
            pnpm install

            # Build dependencies, then the package itself
            npx lerna run build --scope @adguard/tswebextension --include-dependencies

            # IMPORTANT:
            # The 'test:prod' command includes 'no-cache' flag
            # so it should be run before the build,
            # since 'no-cache' flag disables cache usage in the monorepo specs.
            pnpm --filter @adguard/tswebextension test:prod
  requirements: &requirements
    - adg-docker: 'true'
    - extension: 'true'

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
       ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - |-
            pnpm install

            npx lerna run build --scope @adguard/tswebextension --include-dependencies

            cd packages/tswebextension

            pnpm tgz
    - inject-variables:
        file: ./packages/tswebextension/dist/build.txt
        scope: RESULT
        namespace: inject
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: tswebextension-v${bamboo.inject.version}
  artifacts:
    - name: tswebextension.tgz
      location: packages/tswebextension/
      pattern: tswebextension.tgz
      shared: true
      required: true
  requirements: *requirements

Cleanup:
  key: CLEAN
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - |-
            echo "Size before cleanup:" && du -h | tail -n 1

            du -h . | sort -hr | head -n 30

            # Check if node_modules directory exists
            if [ -d "node_modules" ]; then
              # to run clean commands in the packages
              pnpm -r clean

              # to remove node_modules
              pnpm clean
            else
              echo "node_modules directory does not exist, skipping pnpm clean"
            fi

            echo "Size after cleanup:" && du -h | tail -n 1
  requirements: *requirements


triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []

other:
  concurrent-build-plugin: system-default
