---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONINCR
  name: tswebextension - increment
stages:
  - Increment:
      manual: true
      final: false
      jobs:
        - Increment

Increment:
  key: INCRTSWEBEXTENSION
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            BRANCH="${bamboo.planRepository.branchName}"

            if [ "$BRANCH" != "master" ]; then
              echo "increment is not supported on branch ${BRANCH}"
              exit 1
            fi

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --target increment-tswebextension-output \
              --output type=local,dest=output \
              .

            if [ -d output/modified ]; then
              cp -R output/modified/. .
            fi
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number for TSWebextension'
          selectedRepository: defaultRepository
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements:
    - extension: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: true

labels: [ ]

other:
  concurrent-build-plugin: system-default
