---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONTEST
  name: tswebextension - tests
variables:
  dockerContainer: adguard/node-ssh:18.19--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
      # This is needed to see the diff between the current and the target branch
      # using the NX CLI
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            # Install deps only for root dependencies
            pnpm install -w

            branch="${bamboo_planRepository_branchName}"

            # Default to 'master' if the variable is not set or is empty
            targetBranch="${bamboo_repository_pr_targetBranch:-master}"

            echo "bamboo_repository_pr_targetBranch: $bamboo_repository_pr_targetBranch"
            echo "bamboo_planRepository_branchName: $bamboo_planRepository_branchName"
            echo "targetBranch: $targetBranch"
            echo "branch: $branch"

            git branch -a

            # Run NX CLI to find projects changed since the master branch and check if the specified project is affected.
            # And store grep exit status to determine if the project was found (0) or not (1).
            is_affected=$(npx nx show projects --affected --select=projects --base=${targetBranch} --head=HEAD | grep -q "@adguard/tswebextension" && echo true || echo false)

            # If not on 'master' and the project is not affected, skip tests for it.
            if [ "$branch" != "master" ] && [ "$is_affected" = false ]; then
              echo "No changes in project, skipping tests"
              exit 0;
            fi

            # Install remained dependencies
            pnpm install

            # TODO make sure that we use monospace correctly
            # build tsurlfilter first, because it is used in tswebextension tests
            npx lerna run build --scope @adguard/tswebextension --include-dependencies

            # IMPORTANT: run lint after the build because linting requires types to be generated
            pnpm --filter @adguard/tswebextension lint

            # IMPORTANT: run tests after the build because smoke tests requires tswebextension to have built dist dir
            pnpm --filter @adguard/tswebextension test:prod
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            pnpm clean

            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
