---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONTEST
  name: tswebextension - tests
variables:
  dockerContainer: adguard/node-ssh:18.13--1

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Ignore testing if pr target branch is "v1".
            # Because @adguard/tswebextension is not implemented on this branch.
            if [ ! -z bamboo.repository.pr.targetBranch && bamboo.repository.pr.targetBranch == "v1" ]
            then
              echo "ignore tests on branch v1"
              exit 0;
            fi

            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            npx lerna@6 bootstrap --scope @adguard/tswebextension --scope @adguard/tsurlfilter --include-dependencies

            # build tsurlfilter first, because it is used in tswebextension tests
            npx lerna@6 run --scope @adguard/tsurlfilter build

            npx lerna@6 run --scope @adguard/tswebextension build

            # IMPORTANT: run lint after the build because linting requires types to be generated
            npx lerna@6 run --scope @adguard/tswebextension lint

            # IMPORTANT: run tests after the build because smoke tests requires tswebextension to have built dist dir
            npx lerna@6 run --scope @adguard/tswebextension test:prod
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            
            # cleanup parent
            rm -rf node_modules
            # cleanup child packages
            npx lerna@6 clean -y
            # cleanup smoke test packages
            rm -rf packages/tswebextension/test/builders/rollup-ts/node_modules
  
            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
