---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONTEST
  name: tswebextension - tests
variables:
  dockerContainer: adguard/node-ssh:16.17--1

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      "${system.YARN_DIR}": "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # Ignore testing if pr target branch is "v1".
            # Because @adguard/tswebextension is not implemented on this branch.
            if [ ! -z bamboo.repository.pr.targetBranch && bamboo.repository.pr.targetBranch == "v1" ]
            then
              echo "ignore tests on branch v1"
              exit 0;
            fi

            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # We need to fit into the new 1GB memory limit when running plans.
            # To do this, memory for nodejs processes is limited. In addition to nodejs, the distribution running in the container also consumes memory, so we experimentally chose a value of 768.
            # jest will start to use memory more sparingly if the flag is set explicitly. 
            # It is important that the running commands are executed in the same thread.
            export NODE_OPTIONS='--max-old-space-size=768'

            npx lerna bootstrap

            # build tsurlfilter first, because it is used in tswebextension tests
            npx lerna run --scope @adguard/tsurlfilter build
  
            npx lerna run --scope @adguard/tswebextension test:prod
            npx lerna run --scope @adguard/tswebextension build

            # cleanup parent
            rm -rf node_modules
            # cleanup child packages
            npx lerna clean -y
  final-tasks:
    - clean
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
