---
version: 2
plan:
  project-key: AJL
  key: TSWEBEXTENSIONTEST
  name: tswebextension - tests
variables:
  dockerContainer: adguard/node-ssh:18.19--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            # Fix mixed logs
            exec 2>&1

            ls -alt

            # Set cache directory
            pnpm config set store-dir ${bamboo.cachePnpm}

            branch="${bamboo_planRepository_branchName}"
            target_branch="${bamboo_repository_pr_targetBranch:-master}"

            is_root_affected() {
              git diff --name-only "${target_branch}"...HEAD | grep -v '^packages/' > /dev/null
            }

            is_project_affected() {
              local project_name="$1"
              pnpm list --filter "...[${target_branch}]" --depth=-1 | grep -q "${project_name}"
            }

            if [ "$branch" != "master" ] && ! is_root_affected && ! is_project_affected "@adguard/tswebextension"; then
              echo "No changes in project, skipping tests"
              exit 0;
            fi

            # Install dependencies
            pnpm install

            # TODO make sure that we use monospace correctly
            # build tsurlfilter first, because it is used in tswebextension tests
            npx lerna run build --scope @adguard/tswebextension --include-dependencies

            # IMPORTANT: run lint after the build because linting requires types to be generated
            pnpm --filter @adguard/tswebextension lint

            # IMPORTANT: run tests after the build because smoke tests requires tswebextension to have built dist dir
            pnpm --filter @adguard/tswebextension test:prod

            # Commit changes and mv3-examples update only in release/v3.1 branch.
            # FIXME: Remove this line.
            if [ "$branch" != "release/v3.1" ]; then
              echo "No changes in project, skipping tests"
              exit 0;
            fi

            # FIXME remove this line before merging to master
            (cd packages/tswebextension && pnpm pack && mv adguard-tswebextension-*.tgz tswebextension.tgz)

            # FIXME remove this line before merging to master
            (cd packages/tsurlfilter && pnpm pack && mv adguard-tsurlfilter-*.tgz tsurlfilter.tgz)

            # FIXME move this task to the separate plan
            pnpm --filter @adguard/tsurlfilter examples
    # FIXME remove this task
    # Note: commented due to limited number of build agent
    # - any-task:
    #     plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
    #     configuration:
    #       commitMessage: 'skipci: Automatic update tsurlfilter and tswebextension tgz files and MV3 examples'
    #       selectedRepository: defaultRepository
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1

            # Check if node_modules directory exists
            if [ -d "node_modules" ]; then
              pnpm clean
            else
              echo "node_modules directory does not exist, skipping pnpm clean"
            fi

            echo "Size after cleanup:" && du -h | tail -n 1
  requirements:
    - adg-docker: 'true'
    - extension: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]

other:
  concurrent-build-plugin: system-default
