module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"fi" },
      "Validation Summary:":[ null,
        "Validoinnin yhteenveto:" ],
      Code:[ null,
        "Koodi" ],
      Message:[ null,
        "Viesti" ],
      Description:[ null,
        "Kuvaus" ],
      File:[ null,
        "Tiedosto" ],
      Line:[ null,
        "Rivi" ],
      Column:[ null,
        "Sarake" ],
      "Invalid nesting of selectors found":[ null,
        "Löydettiin virheellinen valitsimien sarja" ],
      "A CSS syntax error was encountered":[ null,
        "Havaittiin CSS-kielioppivirhe" ],
      "Your FTL is not valid.":[ null,
        "Määrittelemäsi FTL ei ole kelvollinen." ],
      "Your FTL file could not be parsed.":[ null,
        "FTL-tiedostoasi ei voitu jäsentää." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Lisäosakäytäntöjen vuoksi etäskriptejä ei sallita." ],
      "Inline scripts blocked by default":[ null,
        "Sisennetyt skriptit on oletusarvoisesti estetty" ],
      "Unadvised 3rd-party JS library":[ null,
        "Ei suositeltu kolmannen osapuolen JS-kirjasto" ],
      "Known JS library detected":[ null,
        "Tunnettu JS-kirjasto havaittu" ],
      "{{api}} is not supported":[ null,
        "{{api}} ei ole tuettu" ],
      "This API has not been implemented by Firefox.":[ null,
        "Tätä API:a ei ole vielä toteutettu Firefoxissa." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} ei ole tuettu Firefox-versiossa {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Tätä API:a ei ole vielä toteutettu annetussa Firefoxin minimiversiossa" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} ei ole tuettu Firefoxin Android-versiossa {{minVersion}}" ],
      "Content script file could not be found.":[ null,
        "Sisältökriptitiedostoa ei löytynyt." ],
      "Content script file could not be found":[ null,
        "Sisältökriptitiedostoa ei löytynyt" ],
      "Content script file name should not be empty.":[ null,
        "Sisällön skriptitiedoston nimi ei saa olla tyhjä." ],
      "Content script file name should not be empty":[ null,
        "Sisällön skriptitiedoston nimi ei saa olla tyhjä" ],
      "JavaScript syntax error":[ null,
        "JavaScript-syntaksivirhe" ],
      "Unexpected global passed as an argument":[ null,
        "" ],
      "Use of document.write strongly discouraged.":[ null,
        "Document.write:n käyttöä ei suositella." ],
      "Banned 3rd-party JS library":[ null,
        "Kielletty kolmannen osapuolen JS-kirjasto" ],
      "Your JSON contains block comments.":[ null,
        "Määrittelemäsi JSON sisältää lohkokommentteja." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Kahdennetut avaimet eivät ole sallittuja JSON-tiedostoissa." ],
      "Your JSON is not valid.":[ null,
        "Määrittelemäsi JSON ei ole kelvollinen." ],
      "Your JSON file could not be parsed.":[ null,
        "JSON-tiedostoasi ei voitu jäsentää." ],
      "Reserved filename found.":[ null,
        "Varattu tiedostonimi löytyi." ],
      "We were unable to decompress the zip file.":[ null,
        "Zip-tiedostoa ei voitu purkaa." ],
      "manifest.json was not found":[ null,
        "manifest.json-tiedostoa ei löytynyt" ],
      "File is too large to parse.":[ null,
        "Tiedosto on liian suuri jäsennettäväksi." ],
      "Hidden file flagged":[ null,
        "Piilotettu tiedosto merkitty" ],
      "Flagged filename found":[ null,
        "" ],
      "Flagged file extensions found":[ null,
        "" ],
      "Package contains duplicate entries":[ null,
        "" ],
      "Flagged file type found":[ null,
        "Merkitty tiedostotyyppi löytyi" ],
      "Package already signed":[ null,
        "Paketti on jo allekirjoitettu" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox-lisäosat eivät saa ajaa kolikonkaivajia." ],
      "String name is reserved for a predefined message":[ null,
        "" ],
      "Placeholder for message is missing":[ null,
        "Viestin paikkamerkki puuttuu" ],
      "A placeholder used in the message is not defined.":[ null,
        "" ],
      "Placeholder name contains invalid characters":[ null,
        "" ],
      "Placeholder is missing the content property":[ null,
        "" ],
      "Translation string is missing the message property":[ null,
        "Käännösmerkkijonosta puuttuu \"message\" -ominaisuus" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Viestiominaisuutta \"message\" ei ole asetettu merkkijonolle (https://mzl.la/2DSBTjA)." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" manifest.json-tiedostossa ei ole kelvollinen arvo" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Katso lisätietoja osoitteesta https://mzl.la/20PenXl (MDN-dokumentit)." ],
      "The \"name\" property must be a string.":[ null,
        "Ominaisuuden \"name\" täytyy olla merkkijono." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Katso lisätietoja osoitteesta http://mzl.la/1STmr48 (MDN-dokumentit)." ],
      "The \"version\" property must be a string.":[ null,
        "Ominaisuuden \"version\" pitää olla merkkijono." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Katso lisätietoja osoitteesta http://mzl.la/1kXIADa (MDN web docs)." ],
      "The field is invalid.":[ null,
        "Kenttä on virheellinen." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Ominaisuus \"version\" käyttää Firefoxin formaattia." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Katso lisätietoja osoitteesta https://mzl.la/1ZOhoEN (MDN-dokumentit)." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" ei ole sallittu." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Firefox ei käytä \"update_url\"-ominaisuutta." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" ei ole vaadittu." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Manifestissa määritettyä kuvaketta ei löytynyt paketista." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Kuvaketta ei löytynyt polusta \"%(path)s\"." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Taustaskriptiä ei löydetty polusta \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Taustasivua ei löydetty polusta \"%(path)s\"." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "The manifest contains multiple dictionaries.":[ null,
        "" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "" ],
      "Forbidden content found in add-on.":[ null,
        "Lisäosasta löytyi kiellettyä sisältöä." ],
      "This add-on contains forbidden content.":[ null,
        "Tämä lisäosa sisältää kiellettyä sisältöä." ],
      "Icons must be square.":[ null,
        "Kuvakkeiden tulee olla muodoltaan neliöitä." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Kuvakkeen polussa \"%(path)s\" tulee olla neliö." ],
      "The size of the icon does not match the manifest.":[ null,
        "Kuvakkeen koko ei vastaa manifestia." ],
      "Corrupt image file":[ null,
        "Vahingoittunut kuvatiedosto" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Odotettu kuvatiedosto polussa \"%(path)s\" on vioittunut" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "" ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Katso lisätietoja osoitteesta https://mzl.la/2T11Lkc (MDN-dokumentit)." ],
      "Theme image file has an unsupported file extension":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "" ],
      "Theme image file has an unsupported mime type":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Kohteesta \"default_locale\" puuttuu lokalisaatioita." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" puuttuu, mutta \"_locales\" on olemassa." ],
      "Unsupported image extension":[ null,
        "Kuvan tiedostotyyppiä ei tueta" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Kuvakkeen tulee olla muotoa JPG/JPEG, WebP, GIF, PNG tai SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "Tyhjä kielihakemisto" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "messages.json -tiedosto puuttuu polusta \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "Käyttöoikeustyyppi ei ole tuettu." ],
      "The field is required.":[ null,
        "Tämä kenttä vaaditaan." ],
      "Unknown permission.":[ null,
        "Tuntematon käyttöoikeus." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Katso lisätietoja osoitteesta https://mzl.la/1R1n1t0 (MDN-dokumentit)." ] } } }