module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;",
        lang:"cs" },
      "Validation Summary:":[ null,
        "Souhrn validace:" ],
      Code:[ null,
        "Kód" ],
      Message:[ null,
        "Zpráva" ],
      Description:[ null,
        "Popisek" ],
      File:[ null,
        "Soubor" ],
      Line:[ null,
        "Řádek" ],
      Column:[ null,
        "Sloupec" ],
      "Invalid nesting of selectors found":[ null,
        "Bylo nalezeno neplatné vnoření" ],
      "A CSS syntax error was encountered":[ null,
        "Byla zjištěna chyba syntaxe CSS" ],
      "Your FTL is not valid.":[ null,
        "Váš FTL není validní." ],
      "Your FTL file could not be parsed.":[ null,
        "Váš FTL nemohl být parsován." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Vzdálené skripty nejsou povoleny bezpečnostní politikou doplňků." ],
      "Inline scripts blocked by default":[ null,
        "Vložené skripty jsou ve výchozím nastavení zablokovány" ],
      "Unadvised 3rd-party JS library":[ null,
        "Nedoporučené externí JS knihovny" ],
      "Known JS library detected":[ null,
        "Rozpoznána známá JS knihovna" ],
      "{{api}} is not supported":[ null,
        "{{api}} není podporováno" ],
      "This API has not been implemented by Firefox.":[ null,
        "Tato API nemohla být přidána do Firefoxu." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" bylo v Manifestu verze 3 (`manifest_version`) odstraněno" ],
      "{{api}} is deprecated":[ null,
        "{{api}} je zastaralé" ],
      "This API has been deprecated by Firefox.":[ null,
        "Toto API je ve Firefoxu označeno jako zastaralé." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" je zastaralé, nebo není vůbec implementované" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` bylo voláno se čtvrtým parametrem." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} není ve verzi Firefoxu {{minVersion}} podporováno" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Tato API nejsou uvedenou minimální verzí Firefoxu implementována" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} není ve verzi Firefoxu pro Android {{minVersion}} podporováno" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Tato API nejsou uvedenou minimální verzí Firefoxu pro Android implementována" ],
      "Content script file could not be found.":[ null,
        "Obsah souboru se skriptem nebyl nalezen." ],
      "Content script file could not be found":[ null,
        "Obsah skriptu nemohl být nalezen" ],
      "Content script file name should not be empty.":[ null,
        "Název skriptu by neměl být prázdný." ],
      "Content script file name should not be empty":[ null,
        "Název skriptu by neměl být prázdný" ],
      "JavaScript syntax error":[ null,
        "JavaScript syntax error" ],
      "Unexpected global passed as an argument":[ null,
        "Neočekávaná globální proměnná byla předaná jako parametr" ],
      "Use of document.write strongly discouraged.":[ null,
        "Používání document.write není zcela doporučováno." ],
      "Banned 3rd-party JS library":[ null,
        "Zakázané externí JS knihovny" ],
      "Your JSON contains block comments.":[ null,
        "Váš JSON obsahuje blokové komentáře." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "V JSON souborech nejsou duplicitní klíče povoleny." ],
      "Your JSON is not valid.":[ null,
        "Váš JSON není platný." ],
      "Your JSON file could not be parsed.":[ null,
        "Váš JSON nemohl být parsován." ],
      "Reserved filename found.":[ null,
        "Nalezen soubor s rezervovaným názvem." ],
      "We were unable to decompress the zip file.":[ null,
        "Nepodařilo se nám rozbalit zip archiv." ],
      "manifest.json was not found":[ null,
        "manifest.json nebyl nalezen" ],
      "File is too large to parse.":[ null,
        "Soubor je příliš velký pro parsování." ],
      "Hidden file flagged":[ null,
        "Skrytý soubor označen" ],
      "Flagged filename found":[ null,
        "Označený soubor nalezen" ],
      "Flagged file extensions found":[ null,
        "Označený soubor rozšíření nalezen" ],
      "Package contains duplicate entries":[ null,
        "Balíček obsahuje duplicitní položky" ],
      "Flagged file type found":[ null,
        "Typ označených souborů nalezen" ],
      "Package already signed":[ null,
        "Balíček již byl podepsán" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Doplňky Firefoxu nesmí těžit kryptoměny." ],
      "String name is reserved for a predefined message":[ null,
        "Jméno řetězce je rezervováno pro předdefinovanou zprávu" ],
      "Placeholder for message is missing":[ null,
        "Placeholder pro zprávu chybí" ],
      "A placeholder used in the message is not defined.":[ null,
        "Placeholder použitý ve zprávě není definován." ],
      "Placeholder name contains invalid characters":[ null,
        "Placeholder obsahuje neplatné znaky" ],
      "Placeholder is missing the content property":[ null,
        "Zástupnému textu chybí vlastnost content" ],
      "Translation string is missing the message property":[ null,
        "Řetězci překladu chybí parametr message" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Pro řetězec není nastavena zpráva ve vlastnosti „message“ (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Podrobnosti najdete v MDN Docs na adrese https://mzl.la/2Qn0fWC." ],
      "Invalid host permission.":[ null,
        "Neplatné oprávnění pro server." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" není v souboru manifest.json platná hodnota." ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Podívejte se na https://mzl.la/20PenXl (MDN dokumentace) pro více informací." ],
      "The \"name\" property must be a string.":[ null,
        "Hodnota \"name\" musí být řetězec." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Podívejte se na http://mzl.la/1STmr48 (MDN Dokumenty) pro více informací." ],
      "The \"version\" property must be a string.":[ null,
        "Hodnota \"version\" musí být řetězec." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Podívejte se na http://mzl.la/1kXIADa (MDN Dokumenty) pro více informací." ],
      "The field is invalid.":[ null,
        "Pole není platné." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Hodnota \"version\" používá ve Firefoxu specifický formát." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Podívejte se na https://mzl.la/1ZOhoEN (MDN dokumentace) pro více informací." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" není povoleno." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Obsah \"update_url\" parametru není používán Firefoxem." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" není vyžadováno." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Ikona definovaná v manifestu nebyla v balíčku nalezena." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "V umístění \"%(path)s\" nebyla nalezena ikona." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Skript běžící na pozadí definovaný v manifestu nebyl nalezen." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Stránka běžící na pozadí definovaná v manifestu nebyla nalezena." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Background skript nebyl na cestě „%(path)s“ nalezen." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Background stránka nebyla na cestě „%(path)s“ nalezena." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Obsahový skript definovaný v manifestu nebyl nalezen." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Styly obsahového skriptu definované v manifestu nebyly nalezeny." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Obsahový skript definovaný v manifestu nebyl na cestě „%(path)s“ nalezen." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Styly obsahového skriptu definované v manifestu nebyly na cestě „%(path)s“ nalezeny." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Slovníkový soubor definovaný v manifestu nebyl nalezen." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Slovníkový soubor definovaný v manifestu nebyl na cestě „%(path)s“ nalezen." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifest obsahuje vícero slovníků." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "V manifestu bylo definováno vícero slovníků, což není podporováno." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifest obsahuje prázdný objekt slovníků." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "V manifestu byl definován objekt slovníků, ale je prázdný." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifest obsahuje slovník bez id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "V manifestu byl nalezen slovník, ale nemá nastaven identifikátor." ],
      "Forbidden content found in add-on.":[ null,
        "V doplňku byl nalezen zakázaný obsah." ],
      "This add-on contains forbidden content.":[ null,
        "Tento doplněk obsahuje zakázaný obsah." ],
      "Icons must be square.":[ null,
        "Ikony musí být čtvercové." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikona na cestě „%(path)s“ musí být čtverec." ],
      "The size of the icon does not match the manifest.":[ null,
        "Velikost ikony neodpovídá manifestu." ],
      "Corrupt image file":[ null,
        "Poškozený soubor obrázku" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Očekávaný soubor ikony na cestě „%(path)s“ je poškozený" ],
      "This property has been deprecated.":[ null,
        "Tato vlastnost je zastaralá." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Tento LWT alias vzhledu je od verze Firefoxu 70 odstraněn." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Více informací najdete v dokumentaci MDN na adrese https://mzl.la/2T11Lkc ." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Obrázek vzhledu s typem „%(type)s“ nebyl na cestě „%(path)s“ nalezen." ],
      "Corrupted theme image file":[ null,
        "Poškozený obrázku vzhledu" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Obrázek vzhledu na cestě „%(path)s“ je poškozený" ],
      "Theme image file has an unsupported file extension":[ null,
        "Obrázek vzhledu má nepodporovanou koncovku" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Soubor s obrázkem \"%(path)s\" má nepodporovanou koncovku názvu" ],
      "Theme image file has an unsupported mime type":[ null,
        "Obrázek vzhledu je nepodporovaného typu" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Soubor s obrázkem \"%(path)s\" je typu \"%(mime)s\", který není podporován" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Typ a koncovka názvu obrázku nesouhlasí" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Koncovka souboru s obrázkem \"%(path)s\" neodpovídá jeho skutečnému typu \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Jazyku „default_locale“ chybí překlady." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Jazyk „default_locale“ chybí, ale „_locales“ existuje." ],
      "Unsupported image extension":[ null,
        "Nepodporovaný formát obrázku" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikona by měla mít formát JPG, JPEG, WebP, GIFF, PNG nebo SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Vlastnost \"applications\" je nahrazena za \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Prázdný adresář jazyků" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "messages.json na cestě \"%(path)s\" chybí" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Klíč v manifestu není uvedenou minimální verzí Firefoxu podporován" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Oprávnění nepodporované uvedenou minimální verzí Firefoxu" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Klíč v manifestu není uvedenou minimální verzí Firefoxu pro Android podporován" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Oprávnění nepodporované uvedenou minimální verzí Firefoxu pro Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Odkazování ní \"addons.mozilla.org\" není dovoleno" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Odkazy směřující na \"addons.mozilla.org\" není možné nastavit jako domovskou stránku" ],
      "The permission type is unsupported.":[ null,
        "Tento typ oprávnění není podporován." ],
      "The field is required.":[ null,
        "Toto pole je vyžadováno." ],
      "Unknown permission.":[ null,
        "Neznámé oprávnění." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Podívejte se na https://mzl.la/1R1n1t0 (MDN dokumentace) pro více informací." ] } } }