import fs from 'node:fs/promises';

import {
    Filter,
    FilterConverter,
    type IRulesetWithSourceMap,
    Rule,
    RulesetWithSourceMap,
    RulesHashMap,
} from '@adguard/dnr-converter';

/**
 * Loads ruleset and filter.
 *
 * @param rulesetPath Path to the ruleset.
 * @param id String id (e.g., '999').
 *
 * @returns Promise with loaded Ruleset (as IRulesetWithSourceMap).
 */
export async function loadRulesetAndFilter(
    rulesetPath: string,
    id: string,
): Promise<IRulesetWithSourceMap> {
    const rulesetRaw = await fs.readFile(rulesetPath, 'utf8');

    // Extract metadata, lazyMetadata, and filter content from ruleset JSON.
    // First element is always the metadata rule.
    const parsedRuleset = JSON.parse(rulesetRaw);
    const metadataRule = parsedRuleset[0];

    const ruleMetadata = metadataRule.metadata;
    if (!ruleMetadata || typeof ruleMetadata.filterContent !== 'string') {
        throw new Error(
            `Unsupported ruleset format in ${rulesetPath}: `
            + 'expected "filterContent" field in metadata rule. '
            + 'This ruleset may have been generated by an older converter version.',
        );
    }
    const {
        metadata,
        lazyMetadata,
        filterContent,
    } = ruleMetadata;

    const filterId = Number(id);
    const filter = new Filter(filterId, filterContent);

    // Prepare RulesetWithSourceMap.deserialize dependencies
    const ruleSetId = FilterConverter.getRuleSetId(filterId);
    const rawData = JSON.stringify(metadata);
    const loadLazyData = async () => JSON.stringify(lazyMetadata);
    const loadDeclarativeRules = async () => JSON.stringify(parsedRuleset.slice(1));
    const filters = [filter];

    // Deserialize RulesetWithSourceMap
    const {
        data: {
            regexpRulesCount,
            unsafeRulesCount,
            safeRulesCount,
            ruleSetHashMapRaw,
            badFilterRulesRaw,
            unsafeRules,
        },
        ruleSetContentProvider,
    } = await RulesetWithSourceMap.deserialize(
        ruleSetId,
        rawData,
        loadLazyData,
        loadDeclarativeRules,
        filters,
    );

    // Convert raw badfilter rule strings to Rule objects
    const badFilterRules = badFilterRulesRaw
        .map((rawString: string) => Rule.createFromText(0, 0, rawString))
        .flat();

    // Deserialize the rules hash map
    const hashMapSources = RulesHashMap.deserializeSources(ruleSetHashMapRaw);
    const rulesHashMap = new RulesHashMap(hashMapSources);

    const ruleSet = new RulesetWithSourceMap(
        ruleSetId,
        safeRulesCount,
        unsafeRulesCount,
        regexpRulesCount,
        ruleSetContentProvider,
        badFilterRules,
        rulesHashMap,
        unsafeRules,
    );

    console.log(`Loaded ruleset with ID ${id} from ${rulesetPath}`);

    return ruleSet;
}
