module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"da" },
      "Validation Summary:":[ null,
        "Valideringsoversigt:" ],
      Code:[ null,
        "Kode" ],
      Message:[ null,
        "Meddelelse" ],
      Description:[ null,
        "Beskrivelse" ],
      File:[ null,
        "Fil" ],
      Line:[ null,
        "Linje" ],
      Column:[ null,
        "Kolonne" ],
      "Invalid nesting of selectors found":[ null,
        "Ugyldig indlejring af selektorer fundet" ],
      "A CSS syntax error was encountered":[ null,
        "Der opstod en CSS-syntaksfejl" ],
      "Your FTL is not valid.":[ null,
        "FTL er ikke gyldig." ],
      "Your FTL file could not be parsed.":[ null,
        "Din FTL-fil kunne ikke tolkes." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Eksterne scripts er ikke tilladt i henhold til politikken for tilføjelser." ],
      "Inline scripts blocked by default":[ null,
        "Inline-scripts er blokeret som standard" ],
      "Unadvised 3rd-party JS library":[ null,
        "Ikke-anbefalet tredjeparts JS-bibliotek" ],
      "Known JS library detected":[ null,
        "Kendt JS-bibliotek detekteret" ],
      "{{api}} is not supported":[ null,
        "{{api}} er ikke understøttet" ],
      "This API has not been implemented by Firefox.":[ null,
        "Denne API er ikke blevet implementeret af Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener blev kaldt med truthy fjerde argument." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} understøttes ikke i Firefox {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Denne API er ikke implementeret af den angivne minimumsversion af Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} understøttes ikke i Firefox til Android version {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Denne API er ikke implementeret af den angivne minimumsversion af Firefox til Android" ],
      "Content script file could not be found.":[ null,
        "Indholds-scriptfilen blev ikke fundet." ],
      "Content script file could not be found":[ null,
        "Indholds-scriptfilen blev ikke fundet" ],
      "Content script file name should not be empty.":[ null,
        "Indholds-scriptfilens navn bør ikke være tomt." ],
      "Content script file name should not be empty":[ null,
        "Indholds-scriptfilens navn bør ikke være tomt" ],
      "JavaScript syntax error":[ null,
        "JavaScript-syntaksfejl" ],
      "Unexpected global passed as an argument":[ null,
        "Uventet global blev anvendt som argument" ],
      "Use of document.write strongly discouraged.":[ null,
        "Brug af document.write frarådes kraftigt." ],
      "Banned 3rd-party JS library":[ null,
        "Forbudt tredjeparts JS-bibliotek" ],
      "Your JSON contains block comments.":[ null,
        "JSON indeholder block-kommentarer." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "" ],
      "Your JSON is not valid.":[ null,
        "Din JSON er ikke gyldig." ],
      "Your JSON file could not be parsed.":[ null,
        "Din JSON-fil kunne ikke fortolkes." ],
      "Reserved filename found.":[ null,
        "" ],
      "We were unable to decompress the zip file.":[ null,
        "Vi kunne ikke pakke zip-filen ud." ],
      "manifest.json was not found":[ null,
        "manifest.json blev ikke fundet" ],
      "File is too large to parse.":[ null,
        "Filen er for stor til at kunne fortolkes." ],
      "Hidden file flagged":[ null,
        "" ],
      "Flagged filename found":[ null,
        "" ],
      "Flagged file extensions found":[ null,
        "" ],
      "Package contains duplicate entries":[ null,
        "" ],
      "Flagged file type found":[ null,
        "" ],
      "Package already signed":[ null,
        "" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "" ],
      "String name is reserved for a predefined message":[ null,
        "" ],
      "Placeholder for message is missing":[ null,
        "" ],
      "A placeholder used in the message is not defined.":[ null,
        "" ],
      "Placeholder name contains invalid characters":[ null,
        "" ],
      "Placeholder is missing the content property":[ null,
        "" ],
      "Translation string is missing the message property":[ null,
        "" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "" ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "" ],
      "The \"name\" property must be a string.":[ null,
        "" ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "" ],
      "The \"version\" property must be a string.":[ null,
        "" ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "" ],
      "The field is invalid.":[ null,
        "Feltet er ugyldigt." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "" ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "" ],
      "\"update_url\" is not allowed.":[ null,
        "" ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "" ],
      "\"strict_max_version\" not required.":[ null,
        "" ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "" ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "" ],
      "A background script defined in the manifest could not be found.":[ null,
        "" ],
      "A background page defined in the manifest could not be found.":[ null,
        "" ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "" ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "" ],
      "A content script defined in the manifest could not be found.":[ null,
        "" ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "" ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "" ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "The manifest contains multiple dictionaries.":[ null,
        "" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "" ],
      "Forbidden content found in add-on.":[ null,
        "" ],
      "This add-on contains forbidden content.":[ null,
        "" ],
      "Icons must be square.":[ null,
        "" ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "" ],
      "The size of the icon does not match the manifest.":[ null,
        "" ],
      "Corrupt image file":[ null,
        "" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "" ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "" ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "" ],
      "Corrupted theme image file":[ null,
        "" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "" ],
      "Theme image file has an unsupported file extension":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "" ],
      "Theme image file has an unsupported mime type":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "" ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "" ],
      "Unsupported image extension":[ null,
        "" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "" ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "" ],
      "The field is required.":[ null,
        "Dette felt er påkrævet." ],
      "Unknown permission.":[ null,
        "Ukendt tilladelse." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "" ] } } }