module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"it" },
      "Validation Summary:":[ null,
        "Riepilogo della convalida:" ],
      Code:[ null,
        "Codice" ],
      Message:[ null,
        "Messaggio" ],
      Description:[ null,
        "Descrizione" ],
      File:[ null,
        "File" ],
      Line:[ null,
        "Riga" ],
      Column:[ null,
        "Colonna" ],
      "Invalid nesting of selectors found":[ null,
        "Rilevato annidamento di selettori non valido" ],
      "A CSS syntax error was encountered":[ null,
        "È stato riscontrato un errore nella sintassi CSS" ],
      "Your FTL is not valid.":[ null,
        "Il file FTL non è valido." ],
      "Your FTL file could not be parsed.":[ null,
        "Impossibile analizzare il file FTL." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Gli script remoti non sono consentiti secondo la politica dei componenti aggiuntivi." ],
      "Inline scripts blocked by default":[ null,
        "Gli script inline sono bloccati per impostazione predefinita" ],
      "Unadvised 3rd-party JS library":[ null,
        "Librerie JS di terze parti sconsigliate" ],
      "Known JS library detected":[ null,
        "Rilevata una libreria JS nota" ],
      "{{api}} is not supported":[ null,
        "{{api}} non è supportato" ],
      "This API has not been implemented by Firefox.":[ null,
        "Questa API non è stata implementata da Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "“{{api}}” è stato rimosso dalla versione 3 del manifesto (proprietà “manifest_version”)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} è deprecato" ],
      "This API has been deprecated by Firefox.":[ null,
        "Questa API è deprecata in Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "“{{api}}” è deprecato o non implementato" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener chiamato con il quarto argomento truthy." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} non è supportata nella versione {{minVersion}} di Firefox" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Questa API non è stata implementata nella versione minima richiesta di Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} non è supportata nella versione {{minVersion}} di Firefox per Android" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Questa API non è stata implementata nella versione minima richiesta di Firefox per Android" ],
      "Content script file could not be found.":[ null,
        "Impossibile trovare il file content script." ],
      "Content script file could not be found":[ null,
        "Impossibile trovare il file content script" ],
      "Content script file name should not be empty.":[ null,
        "Il nome del file content script non può essere vuoto." ],
      "Content script file name should not be empty":[ null,
        "Il nome del file content script non può essere vuoto" ],
      "JavaScript syntax error":[ null,
        "Errore di sintassi JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Variabile globale inattesa passata come argomento" ],
      "Use of document.write strongly discouraged.":[ null,
        "L'uso di document.write è sconsigliato." ],
      "Banned 3rd-party JS library":[ null,
        "Librerie JS di terze parti non consentite" ],
      "Your JSON contains block comments.":[ null,
        "Il file JSON contiene commenti di blocco." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Le chiavi duplicate non sono ammesse nei file JSON." ],
      "Your JSON is not valid.":[ null,
        "Il file JSON non è valido." ],
      "Your JSON file could not be parsed.":[ null,
        "Impossibile analizzare il file JSON." ],
      "Reserved filename found.":[ null,
        "Rilevato un nome di file riservato." ],
      "We were unable to decompress the zip file.":[ null,
        "Non è stato possibile decomprimere il file zip." ],
      "manifest.json was not found":[ null,
        "Impossibile trovare manifest.json" ],
      "File is too large to parse.":[ null,
        "Il file è troppo grande per essere analizzato." ],
      "Hidden file flagged":[ null,
        "Segnalato file nascosto" ],
      "Flagged filename found":[ null,
        "Rilevato un nome di file segnalato" ],
      "Flagged file extensions found":[ null,
        "Rilevate estensioni di file segnalate" ],
      "Package contains duplicate entries":[ null,
        "Il pacchetto contiene voci duplicate" ],
      "Flagged file type found":[ null,
        "Rilevato un tipo di file segnalato" ],
      "Package already signed":[ null,
        "Pacchetto già firmato" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Il Bitcoin mining non è consentito nei componenti aggiuntivi per Firefox." ],
      "String name is reserved for a predefined message":[ null,
        "Nome stringa riservato per un messaggio predefinito" ],
      "Placeholder for message is missing":[ null,
        "Segnaposto per messaggio mancante" ],
      "A placeholder used in the message is not defined.":[ null,
        "Un segnaposto utilizzato nel messaggio non è stato definito." ],
      "Placeholder name contains invalid characters":[ null,
        "Il nome del segnaposto contiene caratteri non validi" ],
      "Placeholder is missing the content property":[ null,
        "Proprietà “content“ mancante nel segnaposto" ],
      "Translation string is missing the message property":[ null,
        "Proprietà “message“ mancante nella stringa tradotta" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Nessuna proprietà “message“ è impostata per una stringa (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Visita https://mzl.la/2Qn0fWC (Documentazione MDN) per maggiori informazioni." ],
      "Invalid host permission.":[ null,
        "“host permission\" non valido." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" nel file manifest.json non è un valore valido" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Visita https://mzl.la/20PenXl (Documentazione MDN) per maggiori informazioni." ],
      "The \"name\" property must be a string.":[ null,
        "La proprietà \"name\" deve essere di tipo stringa." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Visita http://mzl.la/1STmr48 (Documentazione MDN) per maggiori informazioni." ],
      "The \"version\" property must be a string.":[ null,
        "La proprietà \"version\" deve essere di tipo stringa." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Visita http://mzl.la/1kXIADa (Documentazione MDN) per maggiori informazioni." ],
      "The field is invalid.":[ null,
        "Il campo è non valido." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "La proprietà \"version\" utilizza un formato specifico di Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Visita https://mzl.la/1ZOhoEN (Documentazione MDN) per maggiori informazioni." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" non è consentito." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "La proprietà \"update_url\" non viene utilizzata da Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" non richiesto." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Non è possibile trovare nel pacchetto un'icona definita nel manifesto." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Impossibile trovare l’icona in \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Impossibile trovare uno script di background definito nel file manifesto." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Impossibile trovare una pagina di background definita nel file manifesto." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Impossibile trovare in \"%(path)s\" il background script." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Impossibile trovare in \"%(path)s\" la background page." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Impossibile trovare uno script di contenuto definito nel file manifesto." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Impossibile trovare il file css con uno script di contenuto definito nel file manifesto." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Impossibile trovare il content script definito nel manifesto in \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Impossibile trovare il file content script css definito nel manifesto in \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Impossibile trovare un file dizionario definito nel file manifesto." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Impossibile trovare il file dizionario definito nel file manifesto in “%(path)s”." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Il file manifesto contiene più dizionari." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Nel file manifesto sono stati definiti più dizionari. Questa opzione non è supportata." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Il file manifesto contiene un oggetto dictionaries, che tuttavia risulta vuoto." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Nel file manifesto è stato definito un oggetto dictionaries, che tuttavia risulta vuoto." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Il file manifesto contiene un dizionario, ma è privo di proprietà ID." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Nel file manifesto è stato rilevato un dizionario senza set ID." ],
      "Forbidden content found in add-on.":[ null,
        "Rilevato contenuto non consentito nel componente aggiuntivo." ],
      "This add-on contains forbidden content.":[ null,
        "Questo componente aggiuntivo include un contenuto non consentito." ],
      "Icons must be square.":[ null,
        "Le icone devono essere quadrate." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "L'icona in \"%(path)s\" deve essere quadrata." ],
      "The size of the icon does not match the manifest.":[ null,
        "La grandezza dell'icona non corrisponde al manifesto." ],
      "Corrupt image file":[ null,
        "File immagine danneggiato" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Il file icona previsto in \"%(path)s\" è danneggiato" ],
      "This property has been deprecated.":[ null,
        "Questa proprietà è deprecata." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Il tema LWT alias è stato rimosso in Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Visita https://mzl.la/2T11Lkc (Documentazione MDN) per maggiori informazioni." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Impossibile trovare l’immagine del tema “%(type)s” in “%(path)s”" ],
      "Corrupted theme image file":[ null,
        "File immagine del tema danneggiato" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Il file immagine del tema in “%(path)s” è danneggiato" ],
      "Theme image file has an unsupported file extension":[ null,
        "L’estensione del file immagine del tema non è supportata" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "L’estensione del file immagine del tema in “%(path)s” non è supportata" ],
      "Theme image file has an unsupported mime type":[ null,
        "Il tipo MIME del file immagine del tema non è supportato" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Il tipo MIME “%(mime)s” del file immagine del tema in “%(path)s” non è supportato" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Il tipo MIME del file immagine del tema non corrisponde all’estensione del file" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "L’estensione del file immagine del tema in “%(path)s” non corrisponde al tipo MIME effettivo “%(mime)s”" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "La traduzione per \"default_locale\" è incompleta." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Rilevato \"_locales\", ma non \"default_locale\"." ],
      "Unsupported image extension":[ null,
        "Estensione di immagine non supportata" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Le icone devono essere in formato JPG/JPEG, WebP, GIF, PNG o SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Proprietà “applications” sostituita dalla proprietà “browser_specific_settings”" ],
      "Empty language directory":[ null,
        "Cartella lingue vuota" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Il file messages.json non è presente in \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Il manifest key non è supportato nella versione minima specificata di Firefox" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Il permesso non è supportato nella versione minima specificata di Firefox" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Il manifest key non è supportato nella versione minima specificata di Firefox per Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Il permesso non è supportato nella versione minima specificata di Firefox per Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Il collegamento a “addons.mozilla.org” non è consentito" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Non è possibile utilizzare link che puntano a “addons.mozilla.org” come pagina iniziale" ],
      "The permission type is unsupported.":[ null,
        "Il tipo di permesso non è supportato." ],
      "The field is required.":[ null,
        "Campo obbligatorio." ],
      "Unknown permission.":[ null,
        "Permesso sconosciuto." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Visita https://mzl.la/1R1n1t0 (Documentazione MDN) per maggiori informazioni." ] } } }