module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);",
        lang:"ru" },
      "Validation Summary:":[ null,
        "Сводка валидации:" ],
      Code:[ null,
        "Код" ],
      Message:[ null,
        "Сообщение" ],
      Description:[ null,
        "Описание" ],
      File:[ null,
        "Файл" ],
      Line:[ null,
        "Строка" ],
      Column:[ null,
        "Столбец" ],
      "Invalid nesting of selectors found":[ null,
        "Найдено некорректное использование вложенных селекторов" ],
      "A CSS syntax error was encountered":[ null,
        "Обнаружена ошибка в синтаксисе CSS" ],
      "Your FTL is not valid.":[ null,
        "Ваш FTL некорректен." ],
      "Your FTL file could not be parsed.":[ null,
        "Не удалось распарсить ваш FTL файл." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Внешние скрипты не разрешены Политикой дополнений." ],
      "Inline scripts blocked by default":[ null,
        "Встроенные скрипты блокируются по умолчанию" ],
      "Unadvised 3rd-party JS library":[ null,
        "Нерекомендуемая сторонняя JS библиотека" ],
      "Known JS library detected":[ null,
        "Обнаружена известная JS библиотека" ],
      "{{api}} is not supported":[ null,
        "{{api}} не поддерживается" ],
      "This API has not been implemented by Firefox.":[ null,
        "Это API не реализовано в Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" было удалено из Манифеста версии 3 (свойство `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} устарело" ],
      "This API has been deprecated by Firefox.":[ null,
        "Это API объявлено Firefox устаревшим." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" устарело или не реализовано" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener вызывается с истинным четвёртым аргументом." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} не поддерживается в Firefox {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Это API не реализовано в указанной минимальной версии Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} не поддерживается в Firefox для Android {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Это API не реализовано в указанной минимальной версии Firefox для Android" ],
      "Content script file could not be found.":[ null,
        "Не удалось найти файл скрипта содержимого." ],
      "Content script file could not be found":[ null,
        "Не удалось найти файл скрипта содержимого" ],
      "Content script file name should not be empty.":[ null,
        "Имя файла скрипта содержимого не должно быть пустым." ],
      "Content script file name should not be empty":[ null,
        "Имя файла скрипта содержимого не должно быть пустым" ],
      "JavaScript syntax error":[ null,
        "Синтаксическая ошибка JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Неожиданное использование глобальной переменной в качестве аргумента" ],
      "Use of document.write strongly discouraged.":[ null,
        "Использование document.write настоятельно не рекомендуется." ],
      "Banned 3rd-party JS library":[ null,
        "Запрещённая сторонняя JS библиотека" ],
      "Your JSON contains block comments.":[ null,
        "Ваш JSON содержит многострочные комментарии." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Дублирующиеся ключи не разрешены в JSON файлах." ],
      "Your JSON is not valid.":[ null,
        "Ваш JSON некорректен." ],
      "Your JSON file could not be parsed.":[ null,
        "Не удалось распарсить ваш JSON файл." ],
      "Reserved filename found.":[ null,
        "Используется зарезервированное имя файла." ],
      "We were unable to decompress the zip file.":[ null,
        "Нам не удалось разархивировать zip файл." ],
      "manifest.json was not found":[ null,
        "не найден manifest.json" ],
      "File is too large to parse.":[ null,
        "Файл слишком большой для парсинга." ],
      "Hidden file flagged":[ null,
        "Найден отмеченный флагом скрытый файл" ],
      "Flagged filename found":[ null,
        "Найдено отмеченное флагом имя файла" ],
      "Flagged file extensions found":[ null,
        "Найдено отмеченное флагом расширение файла" ],
      "Package contains duplicate entries":[ null,
        "Пакет содержит дублирующиеся записи" ],
      "Flagged file type found":[ null,
        "Найден отмеченный флагом тип файла" ],
      "Package already signed":[ null,
        "Пакет уже подписан" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Дополнениям Firefox не разрешено запускать майнинг." ],
      "String name is reserved for a predefined message":[ null,
        "Имя строки зарезервировано для предустановленного сообщения" ],
      "Placeholder for message is missing":[ null,
        "Замещающий текст для сообщения не задан" ],
      "A placeholder used in the message is not defined.":[ null,
        "Замещающий текст, используемый в сообщении, не определён." ],
      "Placeholder name contains invalid characters":[ null,
        "Имя замещающего текста содержит неправильные символы" ],
      "Placeholder is missing the content property":[ null,
        "Отсутствует свойство \"content\" в замещающем тексте" ],
      "Translation string is missing the message property":[ null,
        "В переведённой строке отсутствует свойство \"message\"" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Свойство сообщения \"message\" для строки не задано (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Смотрите https://mzl.la/2Qn0fWC (Документацию на MDN) для получения дополнительной информации." ],
      "Invalid host permission.":[ null,
        "Недействительное разрешение хоста." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" в файле manifest.json имеет некорректное значение" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Смотрите https://mzl.la/20PenXl (Документацию на MDN) для получения дополнительной информации." ],
      "The \"name\" property must be a string.":[ null,
        "Свойство \"name\" должно быть строкой." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Смотрите http://mzl.la/1STmr48 (Документацию на MDN) для получения дополнительной информации." ],
      "The \"version\" property must be a string.":[ null,
        "Свойство \"version\" должно быть строкой." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Смотрите http://mzl.la/1kXIADa (Документацию на MDN) для получения дополнительной информации." ],
      "The field is invalid.":[ null,
        "Недопустимое поле." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Свойство \"version\" использует специфичный для Firefox формат." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Смотрите https://mzl.la/1ZOhoEN (Документацию на MDN) для получения дополнительной информации." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" не разрешено." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Свойство \"update_url\" не используется Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" не требуется." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Значок, обозначенный в манифесте, не удалось найти в пакете." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Не удалось найти значок по пути \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Не удалось найти фоновый скрипт, определённый в манифесте." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Не удалось найти фоновую страницу, определённую в манифесте." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Не удалось найти файл фонового скрипта по пути \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Не удалось найти фоновую страницу по пути \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Не удалось найти скрипт содержимого, определённый в манифесте." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Не удалось найти CSS файл скрипта содержимого, определённый в манифесте." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Не удалось найти скрипт содержимого, обозначенный в манифесте, по пути \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "CSS файл скрипта содержимого, обозначенный в манифесте, не найден по пути \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Не удалось найти файл словаря, определённый в манифесте." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Не удалось найти файл словаря, определённый в манифесте, по пути \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Манифест содержит несколько словарей." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "В манифесте определены несколько словарей, что не поддерживается." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Манифест содержит объект словарей, но он пустой." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Объект словарей определен в манифесте, но он пустой." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Манифест содержит словарь, но без свойства «id»." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "В манифесте найден словарь, но «id» не установлен." ],
      "Forbidden content found in add-on.":[ null,
        "В дополнении найдено запрещённое содержимое." ],
      "This add-on contains forbidden content.":[ null,
        "Это дополнение содержит запрещённое содержимое." ],
      "Icons must be square.":[ null,
        "Значки должны быть квадратными." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Значок по пути \"%(path)s\" должен быть квадратным." ],
      "The size of the icon does not match the manifest.":[ null,
        "Размер значка не соответствует манифесту." ],
      "Corrupt image file":[ null,
        "Повреждённый файл изображения" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Ожидаемый файл значка по пути \"%(path)s\" повреждён" ],
      "This property has been deprecated.":[ null,
        "Это свойство устарело." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "LWT-алиас этой темы был удалён в Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Смотрите https://mzl.la/2T11Lkc (Документацию на MDN) для получения дополнительной информации." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Изображение темы для \"%(type)s\" не найдено по пути \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Повреждённый файл изображения темы" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Файл изображения темы по пути \"%(path)s\" повреждён" ],
      "Theme image file has an unsupported file extension":[ null,
        "Файл изображения темы имеет неподдерживаемое расширение" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Файл изображения темы по пути \"%(path)s\" имеет неподдерживаемое расширение" ],
      "Theme image file has an unsupported mime type":[ null,
        "Файл изображения темы имеет неподдерживаемый MIME-тип" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Файл изображения темы по пути \"%(path)s\" имеет неподдерживаемый MIME-тип \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "MIME-тип файла изображения темы не соответствует его расширению" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Расширение файла изображения темы по пути \"%(path)s\" не соответствует его MIME-типу \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Отсутствуют переводы для \"default_locale\"." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" отсутствует, а \"_locales\" существует." ],
      "Unsupported image extension":[ null,
        "Неподдерживаемое расширение изображения" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Значок должен быть в одном из следующих форматов — JPG/JPEG, WebP, GIF, PNG или SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "свойство \"applications\" переопределено свойством \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Пустой каталог языков" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Файл messages.json отсутствует по пути \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Ключ манифеста не поддерживается указанной минимальной версией Firefox" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Разрешение не поддерживается указанной минимальной версией Firefox" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Ключ манифеста не поддерживается указанной минимальной версией Firefox для Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Разрешение не поддерживается указанной минимальной версией Firefox для Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Ссылка на \"addons.mozilla.org\" не разрешена" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Ссылки, ведущие на \"addons.mozilla.org\", не могут быть использованы на главной странице" ],
      "The permission type is unsupported.":[ null,
        "Неподдерживаемый тип разрешения." ],
      "The field is required.":[ null,
        "Это обязательное поле." ],
      "Unknown permission.":[ null,
        "Неизвестное разрешение." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Смотрите https://mzl.la/1R1n1t0 (Документацию на MDN) для получения дополнительной информации." ] } } }