module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n != 1);",
        lang:"sv_SE" },
      "Validation Summary:":[ null,
        "Valideringsöversikt:" ],
      Code:[ null,
        "Kod" ],
      Message:[ null,
        "Meddelande" ],
      Description:[ null,
        "Beskrivning" ],
      File:[ null,
        "Fil" ],
      Line:[ null,
        "Rad" ],
      Column:[ null,
        "Kolumn" ],
      "Invalid nesting of selectors found":[ null,
        "Ogiltig nestning av selektorer hittad" ],
      "A CSS syntax error was encountered":[ null,
        "Ett CSS-syntaxfel uppstod" ],
      "Your FTL is not valid.":[ null,
        "Din FTL är inte giltig." ],
      "Your FTL file could not be parsed.":[ null,
        "Din FTL-fil kunde inte tolkas." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Fjärrskript är inte tillåtna enligt tilläggspolicyn." ],
      "Inline scripts blocked by default":[ null,
        "Inline-skript blockeras som standard" ],
      "Unadvised 3rd-party JS library":[ null,
        "Ej rekommenderat JS-biblioteket från tredje part" ],
      "Known JS library detected":[ null,
        "Känt JS-bibliotek upptäckt" ],
      "{{api}} is not supported":[ null,
        "{{api}} stöds ej" ],
      "This API has not been implemented by Firefox.":[ null,
        "Detta API har inte implementerats av Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" har tagits bort i Manifest Version 3 (egenskapen `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} är föråldrat" ],
      "This API has been deprecated by Firefox.":[ null,
        "Detta API har föråldrats av Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" är föråldrat eller ej implementerat" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` kallas med truthy som fjärde argument." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} stöds inte i Firefox version {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Detta API har inte implementerats den givna lägsta Firefox-versionen" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} stöds inte i Firefox för Android version {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Detta API har inte implementerats av den givna lägsta Firefox-versionen för Android" ],
      "Content script file could not be found.":[ null,
        "Innehållsskriptfilen kunde inte hittas." ],
      "Content script file could not be found":[ null,
        "Innehållsskriptfilen kunde inte hittas" ],
      "Content script file name should not be empty.":[ null,
        "Innehållsskriptfilnamnet ska inte vara tomt." ],
      "Content script file name should not be empty":[ null,
        "Innehållsskriptfilnamnet ska inte vara tomt" ],
      "JavaScript syntax error":[ null,
        "JavaScript-syntaxfel" ],
      "Unexpected global passed as an argument":[ null,
        "Oväntad global skickad som ett argument" ],
      "Use of document.write strongly discouraged.":[ null,
        "Användning av document.write rekommenderas inte." ],
      "Banned 3rd-party JS library":[ null,
        "Förbjudet JS-bibliotek från tredje part" ],
      "Your JSON contains block comments.":[ null,
        "Din JSON innehåller blockkommentarer." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Dubble nycklar är inte tillåtna i JSON-filer." ],
      "Your JSON is not valid.":[ null,
        "Din JSON är inte giltig." ],
      "Your JSON file could not be parsed.":[ null,
        "Din JSON-fil kunde inte tolkas." ],
      "Reserved filename found.":[ null,
        "Reserverat filnamn hittades." ],
      "We were unable to decompress the zip file.":[ null,
        "Vi kunde inte dekomprimera zip-filen." ],
      "manifest.json was not found":[ null,
        "manifest.json hittades inte" ],
      "File is too large to parse.":[ null,
        "Filen är för stor för att tolkas." ],
      "Hidden file flagged":[ null,
        "Dold fil flaggad" ],
      "Flagged filename found":[ null,
        "Flaggat filnamn hittades" ],
      "Flagged file extensions found":[ null,
        "Flaggad filändelse hittades" ],
      "Package contains duplicate entries":[ null,
        "Paket innehåller dubbla poster" ],
      "Flagged file type found":[ null,
        "Flaggad filtyp hittades" ],
      "Package already signed":[ null,
        "Paket redan signerat" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Firefox tillägg får inte köra coin-miners." ],
      "String name is reserved for a predefined message":[ null,
        "Strängnamn är reserverat för ett fördefinierat meddelande" ],
      "Placeholder for message is missing":[ null,
        "Platshållare för meddelande saknas" ],
      "A placeholder used in the message is not defined.":[ null,
        "En platshållare som används i meddelandet är inte definierad." ],
      "Placeholder name contains invalid characters":[ null,
        "Namn på platshållare innehåller ogiltiga tecken" ],
      "Placeholder is missing the content property":[ null,
        "Platshållaren saknar innehållsegenskapen" ],
      "Translation string is missing the message property":[ null,
        "Översättningssträngen saknar meddelandegenskapen" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Ingen meddelandeegenskap \"message\" är satt för en sträng (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Se https://mzl.la/2Qn0fWC (MDN Docs) för mer information." ],
      "Invalid host permission.":[ null,
        "Ogiltig värdbehörighet." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" i manifest.json har inte ett giltigt värde" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Se https://mzl.la/20PenXl (MDN Docs) för mer information." ],
      "The \"name\" property must be a string.":[ null,
        "Egenskapen \"namn\" måste vara en sträng." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Se http://mzl.la/1STmr48 (MDN Docs) för mer information." ],
      "The \"version\" property must be a string.":[ null,
        "Egenskapen \"version\" måste vara en sträng." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Se http://mzl.la/1kXIADa (MDN Docs) för mer information." ],
      "The field is invalid.":[ null,
        "Fältet är ogiltigt." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Egenskapen \"version\" använder ett Firefox-specifikt format." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Se https://mzl.la/1ZOhoEN (MDN Docs) för mer information." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" är inte tillåtet." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Egenskapen \"update_url\" används inte av Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" krävs inte." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "En ikon definierad i manifestet kunde inte hittas i paketet." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Ikonen kunde inte hittas på \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Ett bakgrundsskript definierat i manifestet kunde inte hittas." ],
      "A background page defined in the manifest could not be found.":[ null,
        "En bakgrundssida definierad i manifestet kunde inte hittas." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Bakgrundsskript kunde inte hittas på \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Bakgrundssidan kunde inte hittas på \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Ett innehållsskript som definierats i manifestet kunde inte hittas." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "En css-fil med innehållsskript definierat i manifestet kunde inte hittas." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Innehållsskript definierat i manifestet kunde inte hittas på \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Innehållsskriptets css-fil definierat i manifestet kunde inte hittas på \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "En ordboksfil som definierats i manifestet kunde inte hittas." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Ordbokfil definierad i manifestet kunde inte hittas på \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Manifestet innehåller flera ordböcker." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Flera ordböcker definierades i manifestet, vilket inte stöds." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Manifestet innehåller ett ordboksobjekt, men det är tomt." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Ett ordboksobjekt definierades i manifestet, men det var tomt." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Manifestet innehåller en ordbok men ingen ID-egenskap." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "En ordbok hittades i manifestet, men det fanns ingen angiven ID." ],
      "Forbidden content found in add-on.":[ null,
        "Förbjudet innehåll hittades i tillägget." ],
      "This add-on contains forbidden content.":[ null,
        "Detta tillägg innehåller förbjudet innehåll." ],
      "Icons must be square.":[ null,
        "Ikoner måste vara kvadratiska." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Ikonen på \"%(path)s\" måste vara kvadratisk." ],
      "The size of the icon does not match the manifest.":[ null,
        "Ikonens storlek matchar inte manifestet." ],
      "Corrupt image file":[ null,
        "Skadad bildfil" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Förväntad ikonfil på \"%(path)s\" är skadad" ],
      "This property has been deprecated.":[ null,
        "Den här egenskapen är föråldrad." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Detta tema LWT-alias har tagits bort i Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Se https://mzl.la/2T11Lkc (MDN Docs) för mer information." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Temabild för \"%(type)s\" kunde inte hittas på \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Skadad temabildfil" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Temabildfil \"%(path)s\" är skadad" ],
      "Theme image file has an unsupported file extension":[ null,
        "Temabildfil har ett filändelse som inte stöds" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Temabildfil på \"%(path)s\" har en filändelse som inte stöds" ],
      "Theme image file has an unsupported mime type":[ null,
        "Temabildfil har en mime-typ som inte stöds" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Temabildfil på \"%(path)s\" har en mime-typ \"%(mime)s\" som inte stöds" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Mime-typ för temabildfil matchar inte filändelsen" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Filändelsen för temabildfil på \"%(path)s\" matchar inte med den verkliga mime-typen \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "\"default_locale\" saknar lokaliseringar." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" saknas men \"_locales\" existerar." ],
      "Unsupported image extension":[ null,
        "Filändelse för bild stöds ej" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Ikoner bör vara av JPG/JPEG, WebP, GIFF, PNG eller SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Egenskapen \"applications\" åsidosatt av egenskapen \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Tom språkkatalog" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "messages.json fil saknas i \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Manifest-nyckel stöds inte av den angivna lägsta Firefox-versionen" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Behörighet stöds inte av den angivna lägsta Firefox-versionen" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Manifest-nyckel stöds inte av den angivna lägsta versionen av Firefox för Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Behörighet stöds inte av den angivna lägsta Firefox-versionen för Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Det är inte tillåtet att länka till \"addons.mozilla.org\"." ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Länkar som leder till \"addons.mozilla.org\" är inte tillåtna att användas för hemsidan" ],
      "The permission type is unsupported.":[ null,
        "Behörighetstyp stöds inte." ],
      "The field is required.":[ null,
        "Fältet är obligatoriskt." ],
      "Unknown permission.":[ null,
        "Okänd behörighet." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Se https://mzl.la/1R1n1t0 (MDN Docs) för mer information." ] } } }