module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n > 1);",
        lang:"pt_BR" },
      "Validation Summary:":[ null,
        "Resumo da validação:" ],
      Code:[ null,
        "Código" ],
      Message:[ null,
        "Mensagem" ],
      Description:[ null,
        "Descrição" ],
      File:[ null,
        "Arquivo" ],
      Line:[ null,
        "Linha" ],
      Column:[ null,
        "Coluna" ],
      "Invalid nesting of selectors found":[ null,
        "Agrupamento de seletores inválidos encontrado" ],
      "A CSS syntax error was encountered":[ null,
        "Um erro de sintaxe CSS foi encontrado" ],
      "Your FTL is not valid.":[ null,
        "O seu FTL não é válido." ],
      "Your FTL file could not be parsed.":[ null,
        "Seu arquivo FTL não pôde ser analisado." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Scripts remotos não são permitidos conforme as políticas de extensões." ],
      "Inline scripts blocked by default":[ null,
        "Scripts em linha bloqueados por padrão" ],
      "Unadvised 3rd-party JS library":[ null,
        "Biblioteca JS de terceiros desaconselhada" ],
      "Known JS library detected":[ null,
        "Biblioteca JS conhecida detectada" ],
      "{{api}} is not supported":[ null,
        "{{api}} não é suportada" ],
      "This API has not been implemented by Firefox.":[ null,
        "Esta API ainda não foi implementada pelo Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" foi removida no Manifesto Versão 3 (propriedade `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} está obsoleta" ],
      "This API has been deprecated by Firefox.":[ null,
        "Esta API foi tornada obsoleta pelo Firefox." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" está obsoleto ou não foi implementado" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener ` chamada do quarto argumento válido." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} não suportado no Firefox versão {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Esta API não é implementada pela versão mínima indicada do Firefox" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} não suportado no Firefox para Android versão {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Esta API não é implementada pela versão mínima indicada do Firefox para Android" ],
      "Content script file could not be found.":[ null,
        "O arquivo de script de conteúdo não pôde ser encontrado." ],
      "Content script file could not be found":[ null,
        "O arquivo de script de conteúdo não pôde ser encontrado" ],
      "Content script file name should not be empty.":[ null,
        "O nome do arquivo de script de conteúdo não deve estar vazio." ],
      "Content script file name should not be empty":[ null,
        "O nome do arquivo de script de conteúdo não deve estar vazio" ],
      "JavaScript syntax error":[ null,
        "Erro de sintaxe JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Variável global inesperado passada como argumento" ],
      "Use of document.write strongly discouraged.":[ null,
        "O uso de document.write é fortemente desencorajado." ],
      "Banned 3rd-party JS library":[ null,
        "Biblioteca JS de terceiros banida" ],
      "Your JSON contains block comments.":[ null,
        "Seu JSON contém comentários em bloco." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Chaves duplicadas não são permitidas em arquivos JSON." ],
      "Your JSON is not valid.":[ null,
        "Seu JSON não é válido." ],
      "Your JSON file could not be parsed.":[ null,
        "Seu arquivo JSON não pôde ser analisado." ],
      "Reserved filename found.":[ null,
        "Encontrado nome de arquivo reservado." ],
      "We were unable to decompress the zip file.":[ null,
        "Não foi possível descompactar o arquivo zip." ],
      "manifest.json was not found":[ null,
        "manifest.json não foi encontrado" ],
      "File is too large to parse.":[ null,
        "Arquivo grande demais para ser analisado." ],
      "Hidden file flagged":[ null,
        "Arquivo oculto marcado" ],
      "Flagged filename found":[ null,
        "Nome do arquivo marcado encontrado" ],
      "Flagged file extensions found":[ null,
        "Extensões de arquivo marcada encontrada" ],
      "Package contains duplicate entries":[ null,
        "O pacote contém entradas duplicadas" ],
      "Flagged file type found":[ null,
        "Tipo de arquivo marcado encontrado" ],
      "Package already signed":[ null,
        "Pacote já assinado" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "As extensões do Firefox não têm permissão para executar mineradores de moeda." ],
      "String name is reserved for a predefined message":[ null,
        "O nome da string é reservado para uma mensagem predefinida" ],
      "Placeholder for message is missing":[ null,
        "Está faltando o marcador de posição da mensagem" ],
      "A placeholder used in the message is not defined.":[ null,
        "Um marcador de posição utilizado na mensagem não está definido." ],
      "Placeholder name contains invalid characters":[ null,
        "O nome do marcador de posição contém caracteres inválidos" ],
      "Placeholder is missing the content property":[ null,
        "Está faltando a propriedade de conteúdo do marcador de posição" ],
      "Translation string is missing the message property":[ null,
        "Está faltando a propriedade da mensagem de tradução da string" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Nenhuma propriedade de mensagem \"message\" está definida para uma string (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Consulte mais informações em https://mzl.la/2Qn0fWC (MDN Docs)." ],
      "Invalid host permission.":[ null,
        "Permissão de servidor inválida." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "O \"manifest_version\" no manifest.json não é válido" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Veja https://mzl.la/20PenXl (Documentação da MDN) para mais informações." ],
      "The \"name\" property must be a string.":[ null,
        "A propriedade \"name\" deve ser uma string." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Veja http://mzl.la/1STmr48 (Documentação MDN) para mais informações." ],
      "The \"version\" property must be a string.":[ null,
        "A propriedade \"versão\" deve ser uma string." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Veja mais informações em http://mzl.la/1kXIADa (MDN Docs)." ],
      "The field is invalid.":[ null,
        "O campo é inválido." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "A propriedade \"version\" usa um formato específico do Firefox." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Veja https://mzl.la/1ZOhoEN (Documentação da MDN) para mais informações." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" não é permitido." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "A propriedade \"update_url\" não é utilizada pelo Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" não é obrigatório." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Um ícone definido no manifesto não foi encontrado no pacote." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "O ícone não pôde ser encontrado em \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Um script de segundo plano definido no manifesto não foi encontrado." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Uma página de segundo plano definida no manifesto não foi encontrada." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "O script de segundo plano não foi encontrado em \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "A página de segundo plano não foi encontrada em \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Um script de conteúdo definido no manifesto não foi encontrado." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Um arquivo css de script de conteúdo definido no manifesto não foi encontrado." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "O script de conteúdo definido no manifesto não foi encontrado em \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "O script de conteúdo do arquivo css definido no manifesto não foi encontrado em \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Um arquivo de dicionário definido no manifesto não foi encontrado." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Arquivo de dicionário definido no manifesto não foi encontrado em \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "O manifesto contém vários dicionários." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "Vários dicionários foram definidos no manifesto, o que não é suportado." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "O manifesto contém um objeto de dicionários, mas está vazio." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "Um objeto de dicionários foi definido no manifesto, mas está vazio." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "O manifesto contém um dicionário, mas nenhuma propriedade id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "Um dicionário foi encontrado no manifesto, mas não há nenhum id definido." ],
      "Forbidden content found in add-on.":[ null,
        "Conteúdo proibido encontrado na extensão." ],
      "This add-on contains forbidden content.":[ null,
        "Esta extensão contém conteúdo proibido." ],
      "Icons must be square.":[ null,
        "Os ícones devem ser quadrados." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "O ícone em \"%(path)s\" tem que ser quadrado." ],
      "The size of the icon does not match the manifest.":[ null,
        "O tamanho do ícone não corresponde ao manifesto." ],
      "Corrupt image file":[ null,
        "Arquivo de imagem corrompido" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "O arquivo do ícone esperado em \"%(path)s\" está corrompido" ],
      "This property has been deprecated.":[ null,
        "Esta propriedade está obsoleta." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Este alias LWT de tema foi removido no Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Veja mais informações em https://mzl.la/2T11Lkc (MDN Docs)." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Imagem de tema de \"%(type)s\" não foi encontrada em \"%(path)s\"." ],
      "Corrupted theme image file":[ null,
        "Arquivo de imagem de tema corrompido" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Arquivo de imagem de tema em \"%(path)s\" está corrompido" ],
      "Theme image file has an unsupported file extension":[ null,
        "Arquivo de imagem de tema tem uma extensão de arquivo não suportada" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Arquivo de imagem de tema em \"%(path)s\" tem uma extensão de arquivo não suportada" ],
      "Theme image file has an unsupported mime type":[ null,
        "Arquivo de imagem de tema tem um tipo mime não suportado" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Arquivo de imagem de tema em \"%(path)s\" tem o tipo mime não suportado \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Tipo mime do arquivo de imagem de tema não combina com sua extensão de arquivo" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Extensão de arquivo de imagem de tema em \"%(path)s\" não combina com seu verdadeiro tipo mime \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Falta idiomas no \"default_locale\"." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "Está faltando \"default_locale\" mas \"_locales\" existe." ],
      "Unsupported image extension":[ null,
        "Extensão de imagem não suportada" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Os ícones devem ter uma das extensões JPG/JPEG,, WebP, GIF, PNG ou SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Propriedade \"applications\" substituída pela propriedade \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Diretório de idiomas vazio" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Está faltando o arquivo messages.json em \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Chave de manifesto não suportada pela versão mínima especificada do Firefox" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Permissão não suportada pela versão mínima especificada do Firefox" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Chave de manifesto não suportada pela versão mínima especificada do Firefox para Android" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Permissão não suportada pela versão mínima especificada do Firefox para Android" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Não é permitido link para \"addons.mozilla.org\"" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Links direcionando para \"addons.mozilla.org\" não são permitidos na página inicial" ],
      "The permission type is unsupported.":[ null,
        "O tipo de permissão não é suportado." ],
      "The field is required.":[ null,
        "O campo é requerido." ],
      "Unknown permission.":[ null,
        "Permissão desconhecida." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Veja mais informações em https://developer.mozilla.org/pt-BR/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permiss%C3%B5es (MDN Docs)." ] } } }