module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);",
        lang:"uk" },
      "Validation Summary:":[ null,
        "Підсумок валідації:" ],
      Code:[ null,
        "Код" ],
      Message:[ null,
        "Повідомлення" ],
      Description:[ null,
        "Опис" ],
      File:[ null,
        "Файл" ],
      Line:[ null,
        "Рядок" ],
      Column:[ null,
        "Стовпчик" ],
      "Invalid nesting of selectors found":[ null,
        "Знайдено некоректне число вкладених селекторів" ],
      "A CSS syntax error was encountered":[ null,
        "Виявлено помилку в синтаксисі CSS" ],
      "Your FTL is not valid.":[ null,
        "Ваш FTL неправильний." ],
      "Your FTL file could not be parsed.":[ null,
        "Не вдалося прочитати ваш файл FTL." ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "Віддалені скрипти не дозволені політикою додатків." ],
      "Inline scripts blocked by default":[ null,
        "Вбудовані скрипти типово блокуються" ],
      "Unadvised 3rd-party JS library":[ null,
        "Нерекомендована стороння бібліотека JS" ],
      "Known JS library detected":[ null,
        "Виявлено відому бібліотеку JS" ],
      "{{api}} is not supported":[ null,
        "{{api}} не підтримується" ],
      "This API has not been implemented by Firefox.":[ null,
        "Цей API не було впроваджено в Firefox." ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "\"{{api}}\" вилучено у маніфесті версії 3 (властивість `manifest_version`)" ],
      "{{api}} is deprecated":[ null,
        "{{api}} більше не підтримується" ],
      "This API has been deprecated by Firefox.":[ null,
        "Firefox більше не підтримує цей API." ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "\"{{api}}\" більше не підтримується або прибрано" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "addEventListener` викликається справжнім четвертим аргументом." ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "{{api}} не підтримується в Firefox версії {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "Цей API не впроваджено в Firefox вказаної мінімальної версії" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "{{api}} не підтримується в Firefox для Android версії {{minVersion}}" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "Цей API не впроваджено в Firefox для Android вказаної мінімальної версії" ],
      "Content script file could not be found.":[ null,
        "Не вдається знайти файл скрипту вмісту." ],
      "Content script file could not be found":[ null,
        "Не вдається знайти файл скрипту вмісту" ],
      "Content script file name should not be empty.":[ null,
        "Назва файлу скрипту вмісту не повинна бути порожня." ],
      "Content script file name should not be empty":[ null,
        "Назва файлу скрипту вмісту не повинна бути порожня" ],
      "JavaScript syntax error":[ null,
        "Синтаксична помилка JavaScript" ],
      "Unexpected global passed as an argument":[ null,
        "Неочікуване використання глобальної змінної в якості аргументу" ],
      "Use of document.write strongly discouraged.":[ null,
        "Використання document.write категорично не рекомендується." ],
      "Banned 3rd-party JS library":[ null,
        "Заблокована стороння бібліотека JS" ],
      "Your JSON contains block comments.":[ null,
        "Ваш JSON містить багаторядкові коментарі." ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "Дублікати ключів не дозволені в файлах JSON." ],
      "Your JSON is not valid.":[ null,
        "Ваш JSON неправильний." ],
      "Your JSON file could not be parsed.":[ null,
        "Не вдалося розібрати ваш файл JSON." ],
      "Reserved filename found.":[ null,
        "Знайдено зарезервовану назву файлу." ],
      "We were unable to decompress the zip file.":[ null,
        "Нам не вдалося розпакувати файл zip." ],
      "manifest.json was not found":[ null,
        "manifest.json не знайдено" ],
      "File is too large to parse.":[ null,
        "Надто великий файл." ],
      "Hidden file flagged":[ null,
        "Прихований файл позначено" ],
      "Flagged filename found":[ null,
        "Знайдено позначену назву файлу" ],
      "Flagged file extensions found":[ null,
        "Знайдено позначені розширення файлів" ],
      "Package contains duplicate entries":[ null,
        "Пакунок містить повторювані записи" ],
      "Flagged file type found":[ null,
        "Знайдено позначений тип файлу" ],
      "Package already signed":[ null,
        "Пакунок вже підписано" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "Додаткам Firefox не дозволено добування криптовалют." ],
      "String name is reserved for a predefined message":[ null,
        "Назва рядка зарезервована для попередньо визначеного повідомлення" ],
      "Placeholder for message is missing":[ null,
        "Текст заміщення для повідомлення не задано" ],
      "A placeholder used in the message is not defined.":[ null,
        "Текст заміщення, що використовується в повідомленні, не визначено." ],
      "Placeholder name contains invalid characters":[ null,
        "Назва тексту заміщення містить неприпустимі символи" ],
      "Placeholder is missing the content property":[ null,
        "В тексті заміщення відсутня властивість \"content\"" ],
      "Translation string is missing the message property":[ null,
        "В рядку перекладу відсутня властивість \"message\"" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "Властивість повідомлення \"message\" для рядка не задано (https://mzl.la/2DSBTjA)." ],
      "See https://mzl.la/2Qn0fWC (MDN Docs) for more information.":[ null,
        "Перегляньте https://mzl.la/2Qn0fWC (Документацію MDN) для отримання докладної інформації." ],
      "Invalid host permission.":[ null,
        "Недійсний дозвіл вузла." ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "\"manifest_version\" в файлі manifest.json має неправильне значення" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "Перегляньте https://mzl.la/20PenXl (Документацію MDN) для отримання докладної інформації." ],
      "The \"name\" property must be a string.":[ null,
        "Властивість \"name\" повинна бути рядком." ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "Перегляньте http://mzl.la/1STmr48 (Документацію MDN) для отримання докладної інформації." ],
      "The \"version\" property must be a string.":[ null,
        "Властивість \"version\" повинна бути рядком." ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "Перегляньте http://mzl.la/1kXIADa (Документацію MDN) для отримання докладної інформації." ],
      "The field is invalid.":[ null,
        "Це поле неправильне." ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "Властивість \"version\" використовує специфічний для Firefox формат." ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "Перегляньте https://mzl.la/1ZOhoEN (Документацію MDN) для отримання докладної інформації." ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" не дозволено." ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "Властивість \"update_url\" не використовується в Firefox." ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" не вимагається." ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "Не вдалося знайти визначену в маніфесті піктограму в пакунку." ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "Не вдалося знайти піктограму в \"%(path)s\"." ],
      "A background script defined in the manifest could not be found.":[ null,
        "Не вдалося знайти визначений в маніфесті скрипт заднього плану." ],
      "A background page defined in the manifest could not be found.":[ null,
        "Не вдалося знайти визначену в маніфесті сторінку заднього плану." ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "Не вдалося знайти фоновий скрипт в \"%(path)s\"." ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "Не вдалося знайти фонову сторінку в \"%(path)s\"." ],
      "A content script defined in the manifest could not be found.":[ null,
        "Не вдалося знайти визначений в маніфесті скрипт вмісту." ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "Не вдалося знайти визначений в маніфесті css файл зі скриптом вмісту." ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Не вдалося знайти визначений в маніфесті скрипт вмісту в \"%(path)s\"." ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Не вдалося знайти визначений в маніфесті css файл в \"%(path)s\"." ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "Не вдалося знайти визначений в маніфесті файл словника." ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "Файл словника, визначений в маніфесті, не вдалося знайти  в \"%(path)s\"." ],
      "The manifest contains multiple dictionaries.":[ null,
        "Маніфест містить декілька словників." ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "В маніфесті визначено декілька словників, що не підтримується." ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "Маніфест містить об'єкт словників, але він порожній." ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "В маніфесті визначено об'єкт словників, але він порожній." ],
      "The manifest contains a dictionary but no id property.":[ null,
        "Маніфест містить словник, але не властивість id." ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "В маніфесті знайдено словник, але немає встановленого id." ],
      "Forbidden content found in add-on.":[ null,
        "В додатку знайдено заборонений вміст." ],
      "This add-on contains forbidden content.":[ null,
        "Цей додаток містить заборонений вміст." ],
      "Icons must be square.":[ null,
        "Піктограми повинні бути квадратними." ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "Піктограми в \"%(path)s\" повинні бути квадратними." ],
      "The size of the icon does not match the manifest.":[ null,
        "Розмір піктограми не відповідає маніфесту." ],
      "Corrupt image file":[ null,
        "Пошкоджений файл зображення" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "Очікуваний файл піктограми в \"%(path)s\" пошкоджений" ],
      "This property has been deprecated.":[ null,
        "Ця властивість більше не підтримується." ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "Цей псевдонім LWT-теми було вилучено в Firefox 70." ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "Перегляньте https://mzl.la/2T11Lkc (Документацію MDN) для отримання докладної інформації." ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "Зображення теми для \"%(type)s\" не вдалося знайти в \"%(path)s\"" ],
      "Corrupted theme image file":[ null,
        "Пошкоджений файл зображення теми" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "Файл зображення теми в \"%(path)s\" пошкоджений" ],
      "Theme image file has an unsupported file extension":[ null,
        "Файл зображення теми має непідтримуване розширення" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "Файл зображення теми в \"%(path)s\" має непідтримуване розширення" ],
      "Theme image file has an unsupported mime type":[ null,
        "Файл зображення теми має непідтримуваний тип mime" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "Файл зображення теми в \"%(path)s\" має непідтримуваний тип mime \"%(mime)s\"" ],
      "Theme image file mime type does not match its file extension":[ null,
        "Тип mime файлу зображення теми не збігається з його розширенням файлу" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "Розширення файлу зображення теми в \"%(path)s\" не збігається з його типом mime \"%(mime)s\"" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "Відсутні переклади для \"default_locale\"." ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" відсутня, але \"_locales\" наявна." ],
      "Unsupported image extension":[ null,
        "Розширення зображення не підтримується" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "Піктограми повинні мати формат JPG/JPEG, WebP, GIF, PNG або SVG." ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "Властивість \"applications\" замінено властивістю \"browser_specific_settings\"" ],
      "Empty language directory":[ null,
        "Порожній каталог мов" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "Файл messages.json відсутній в \"%(path)s\"" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "Ключ маніфесту не підтримується в Firefox вказаної мінімальної версії" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "Дозвіл не підтримується в Firefox вказаної мінімальної версії" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "Ключ маніфесту не підтримується в Firefox для Android вказаної мінімальної версії" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "Дозвіл не підтримується в Firefox для Android вказаної мінімальної версії" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "Посилання на \"addons.mozilla.org\" заборонено" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "Посилання, що спрямовують на \"addons.mozilla.org\", заборонено використовувати на домашній сторінці" ],
      "The permission type is unsupported.":[ null,
        "Тип дозволу не підтримується." ],
      "The field is required.":[ null,
        "Це поле обов'язкове." ],
      "Unknown permission.":[ null,
        "Невідомий дозвіл." ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "Перегляньте https://mzl.la/1R1n1t0 (Документацію MDN) для отримання докладної інформації." ] } } }