module.exports = { domain:"messages",
  locale_data:{ messages:{ "":{ domain:"messages",
        plural_forms:"nplurals=2; plural=(n > 1);",
        lang:"bn" },
      "Validation Summary:":[ null,
        "যাচাইকরণ সারাংশ:" ],
      Code:[ null,
        "কোড" ],
      Message:[ null,
        "বার্তা" ],
      Description:[ null,
        "বর্ণনা" ],
      File:[ null,
        "ফাইল" ],
      Line:[ null,
        "লাইন" ],
      Column:[ null,
        "কলাম" ],
      "Invalid nesting of selectors found":[ null,
        "সিলেক্টরের অকার্যকর নেস্টিং পাওয়া গেছে" ],
      "A CSS syntax error was encountered":[ null,
        "একটি CSS সিনট্যাক্স ভুল হয়েছে" ],
      "Your FTL is not valid.":[ null,
        "আপনার FTL অকার্যকর।" ],
      "Your FTL file could not be parsed.":[ null,
        "আপনার FTL ফাইল পার্স করা যায় নি।" ],
      "Remote scripts are not allowed as per the Add-on Policies.":[ null,
        "" ],
      "Inline scripts blocked by default":[ null,
        "" ],
      "Unadvised 3rd-party JS library":[ null,
        "" ],
      "Known JS library detected":[ null,
        "পরিচিত JS লাইব্রেরি সন্ধান পাওয়া গেছে" ],
      "{{api}} is not supported":[ null,
        "{{api}} সাপোর্ট করে না" ],
      "This API has not been implemented by Firefox.":[ null,
        "এই API টি Firefox দ্বারা বাস্তবায়িত হয়নি।" ],
      "\"{{api}}\" has been removed in Manifest Version 3 (`manifest_version` property)":[ null,
        "" ],
      "\"{{api}}\" is deprecated or unimplemented":[ null,
        "" ],
      "addEventListener` called with truthy fourth argument.":[ null,
        "" ],
      "{{api}} is not supported in Firefox version {{minVersion}}":[ null,
        "" ],
      "This API is not implemented by the given minimum Firefox version":[ null,
        "" ],
      "{{api}} is not supported in Firefox for Android version {{minVersion}}":[ null,
        "" ],
      "This API is not implemented by the given minimum Firefox for Android version":[ null,
        "" ],
      "Content script file could not be found.":[ null,
        "কনটেন্ট স্ক্রিপ্ট ফাইল খুঁজে পাওয়া যায়নি।" ],
      "Content script file could not be found":[ null,
        "কনটেন্ট স্ক্রিপ্ট ফাইল খুঁজে পাওয়া যায়নি" ],
      "Content script file name should not be empty.":[ null,
        "কনটেন্ট স্ক্রিপ্ট ফাইলের নাম ফাঁকা হবে না।" ],
      "Content script file name should not be empty":[ null,
        "কনটেন্ট স্ক্রিপ্ট ফাইলের নাম ফাঁকা হবে না" ],
      "JavaScript syntax error":[ null,
        "JavaScript সিনট্যাক্স ভুল" ],
      "Unexpected global passed as an argument":[ null,
        "" ],
      "Use of document.write strongly discouraged.":[ null,
        "document.write ব্যবহারে জোড়ালোভাবে অনুৎসাহিত করা হচ্ছে।" ],
      "Banned 3rd-party JS library":[ null,
        "" ],
      "Your JSON contains block comments.":[ null,
        "আপনার JSON ব্লক কমেন্ট ধারণ করে।" ],
      "Duplicate keys are not allowed in JSON files.":[ null,
        "" ],
      "Your JSON is not valid.":[ null,
        "আপনার JSON অকার্যকর।" ],
      "Your JSON file could not be parsed.":[ null,
        "আপনার JSON ফাইল পার্স করা যায়নি।" ],
      "Reserved filename found.":[ null,
        "" ],
      "We were unable to decompress the zip file.":[ null,
        "" ],
      "manifest.json was not found":[ null,
        "manifest.json পাওয়া যায়নি" ],
      "File is too large to parse.":[ null,
        "ফাইল পার্স করার জন্য বেশ বড়।" ],
      "Hidden file flagged":[ null,
        "লুকানো ফাইল ফ্লাগ করা হয়েছে" ],
      "Flagged filename found":[ null,
        "ফ্লাগ করা ফাইল পাওয়া যায়নি" ],
      "Flagged file extensions found":[ null,
        "ফ্লাগকরা ফাইল এক্সটেনশন পাওয়া গেছে" ],
      "Package contains duplicate entries":[ null,
        "" ],
      "Flagged file type found":[ null,
        "ফ্লাগকরা ফাইল টাইপ পাওয়া গেছে" ],
      "Package already signed":[ null,
        "প্যাকেজ ইতোমধ্যেই সাইন করা হয়েছে" ],
      "Firefox add-ons are not allowed to run coin miners.":[ null,
        "" ],
      "String name is reserved for a predefined message":[ null,
        "" ],
      "Placeholder for message is missing":[ null,
        "" ],
      "A placeholder used in the message is not defined.":[ null,
        "" ],
      "Placeholder name contains invalid characters":[ null,
        "" ],
      "Placeholder is missing the content property":[ null,
        "" ],
      "Translation string is missing the message property":[ null,
        "" ],
      "No \"message\" message property is set for a string (https://mzl.la/2DSBTjA).":[ null,
        "" ],
      "\"manifest_version\" in the manifest.json is not a valid value":[ null,
        "manifest.json এ \"manifest_version\" এর মান ঠিক নাই" ],
      "See https://mzl.la/20PenXl (MDN Docs) for more information.":[ null,
        "আরও তথ্যের জন্য https://mzl.la/20PenXl (MDN ডকস) দেখুন।" ],
      "The \"name\" property must be a string.":[ null,
        "\"name\" প্রোপার্টি অবশ্যই একটি স্ট্রিং হবে।" ],
      "See http://mzl.la/1STmr48 (MDN Docs) for more information.":[ null,
        "আরও তথ্যের জন্য http://mzl.la/1STmr48 (MDN ডকস) দেখুন।" ],
      "The \"version\" property must be a string.":[ null,
        "\"version\" প্রোপার্টি অবশ্যই একটি স্ট্রিং হবে।" ],
      "See http://mzl.la/1kXIADa (MDN Docs) for more information.":[ null,
        "আরও তথ্যের জন্য http://mzl.la/1kXIADa (MDN ডকস) দেখুন।" ],
      "The field is invalid.":[ null,
        "ফিল্ডটি অবৈধ।" ],
      "The \"version\" property uses a Firefox-specific format.":[ null,
        "\"version\" প্রোপার্টি Firefox এর নির্দিষ্ট ফরম্যাট ব্যবহার করে।" ],
      "See https://mzl.la/1ZOhoEN (MDN Docs) for more information.":[ null,
        "" ],
      "\"update_url\" is not allowed.":[ null,
        "\"update_url\" অনুমোদিত নয়।" ],
      "The \"update_url\" property is not used by Firefox.":[ null,
        "\"update_url\" প্রোপার্টি টি Firefox এর দ্বারা ব্যবহৃত হয় না।" ],
      "\"strict_max_version\" not required.":[ null,
        "\"strict_max_version\" প্রয়োজন ছিল না।" ],
      "An icon defined in the manifest could not be found in the package.":[ null,
        "" ],
      "Icon could not be found at \"%(path)s\".":[ null,
        "\"%(path)s\" এ কোন আইকন পাওয়া যায়নি।" ],
      "A background script defined in the manifest could not be found.":[ null,
        "" ],
      "A background page defined in the manifest could not be found.":[ null,
        "" ],
      "Background script could not be found at \"%(path)s\".":[ null,
        "\"%(path)s\"-এ কোন ব্যাকগ্রাউন্ড স্ক্রিপ্ট পাওয়া যায়নি।" ],
      "Background page could not be found at \"%(path)s\".":[ null,
        "\"%(path)s\"-এ কোন ব্যাকগ্রাউন্ড পাতা পাওয়া যায়নি।" ],
      "A content script defined in the manifest could not be found.":[ null,
        "" ],
      "A content script css file defined in the manifest could not be found.":[ null,
        "" ],
      "Content script defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "Content script css file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "A dictionary file defined in the manifest could not be found.":[ null,
        "" ],
      "Dictionary file defined in the manifest could not be found at \"%(path)s\".":[ null,
        "" ],
      "The manifest contains multiple dictionaries.":[ null,
        "" ],
      "Multiple dictionaries were defined in the manifest, which is unsupported.":[ null,
        "" ],
      "The manifest contains a dictionaries object, but it is empty.":[ null,
        "" ],
      "A dictionaries object was defined in the manifest, but it was empty.":[ null,
        "" ],
      "The manifest contains a dictionary but no id property.":[ null,
        "" ],
      "A dictionary was found in the manifest, but there was no id set.":[ null,
        "" ],
      "Forbidden content found in add-on.":[ null,
        "অ্যাড-অনে নিষিদ্ধ কনটেন্ট পাওয়া গেছে।" ],
      "This add-on contains forbidden content.":[ null,
        "অ্যাড-অনটি নিষিদ্ধ কনটেন্টে পরিপূর্ণ রয়েছে।" ],
      "Icons must be square.":[ null,
        "আইকন অবশ্যই বর্গাকৃতির হবে।" ],
      "Icon at \"%(path)s\" must be square.":[ null,
        "\"%(path)s\" এর আইকনটি অবশ্যই বর্গাকৃতির হবে।" ],
      "The size of the icon does not match the manifest.":[ null,
        "নীতিমালার সাথে আইকনের সাইজ যায় না।" ],
      "Corrupt image file":[ null,
        "নষ্ট হওয়া ছবির ফাইল" ],
      "Expected icon file at \"%(path)s\" is corrupted":[ null,
        "" ],
      "This property has been deprecated.":[ null,
        "" ],
      "This theme LWT alias has been removed in Firefox 70.":[ null,
        "" ],
      "See https://mzl.la/2T11Lkc (MDN Docs) for more information.":[ null,
        "" ],
      "Theme image for \"%(type)s\" could not be found at \"%(path)s\"":[ null,
        "" ],
      "Corrupted theme image file":[ null,
        "" ],
      "Theme image file at \"%(path)s\" is corrupted":[ null,
        "" ],
      "Theme image file has an unsupported file extension":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has an unsupported file extension":[ null,
        "" ],
      "Theme image file has an unsupported mime type":[ null,
        "" ],
      "Theme image file at \"%(path)s\" has the unsupported mime type \"%(mime)s\"":[ null,
        "" ],
      "Theme image file mime type does not match its file extension":[ null,
        "" ],
      "Theme image file extension at \"%(path)s\" does not match its actual mime type \"%(mime)s\"":[ null,
        "" ],
      "The \"default_locale\" is missing localizations.":[ null,
        "\"default_locale\" লোকালাইজেশন ছাড়া।" ],
      "The \"default_locale\" is missing but \"_locales\" exist.":[ null,
        "\"default_locale\" ছাড়া কিন্তু \"_locales\" আছে।" ],
      "Unsupported image extension":[ null,
        "অসমর্থিত ছবি এক্সটেনসন" ],
      "Icons should be one of JPG/JPEG, WebP, GIF, PNG or SVG.":[ null,
        "" ],
      "\"applications\" property overridden by \"browser_specific_settings\" property":[ null,
        "" ],
      "Empty language directory":[ null,
        "খালি ভাষা ডিরেক্টরি" ],
      "messages.json file missing in \"%(path)s\"":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox version":[ null,
        "" ],
      "Manifest key not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Permission not supported by the specified minimum Firefox for Android version":[ null,
        "" ],
      "Linking to \"addons.mozilla.org\" is not allowed":[ null,
        "" ],
      "Links directing to \"addons.mozilla.org\" are not allowed to be used for homepage":[ null,
        "" ],
      "The permission type is unsupported.":[ null,
        "" ],
      "The field is required.":[ null,
        "ফিল্ডটি প্রয়োজনীয়।" ],
      "Unknown permission.":[ null,
        "অজানা অনুমতি।" ],
      "See https://mzl.la/1R1n1t0 (MDN Docs) for more information.":[ null,
        "আরও তথ্যের জন্য https://mzl.la/1R1n1t0 (MDN ডকস) দেখুন।" ] } } }