name: Mirror

# Mirrors code to the public repo on every push to master.

on:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  mirror:
    uses: AdGuardSoftwareLimited/actions/.github/workflows/mirror.yml@master
    with:
      team: extensions
      target_repo: git@github.com:AdguardTeam/tsurlfilter.git
    secrets: inherit
