# Tests build
name: test

env:
  NODE_VERSION: 16

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # actions/setup-node@v3 already has caching under hood.
          cache: 'yarn'
      - name: Run bash commands
        shell: bash
        run: |
          ls -alt

          # install deps
          npx lerna@4 bootstrap

          # run linter
          npx lerna@4 run --scope @adguard/tsurlfilter lint

          # run tests
          npx lerna@4 run --scope @adguard/tsurlfilter test:prod

          # run build
          npx lerna@4 run --scope @adguard/tsurlfilter build
  notify:
    needs: [ test ]
    # Secrets are not passed to workflows that are triggered by a pull request from a fork
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@v1
      - name: Send Slack notif
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: workflow, repo, message, commit, author, eventName, ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
