# Tests build
name: test

env:
  NODE_VERSION: 20

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Run bash commands
        shell: bash
        run: |
          ls -alt

          # install deps
          pnpm install

          # css-tokenizer
          npx lerna run --scope @adguard/css-tokenizer check-types
          npx lerna run --scope @adguard/css-tokenizer lint
          npx lerna run --scope @adguard/css-tokenizer test
          npx lerna run --scope @adguard/css-tokenizer build

          # agtree
          npx lerna run --scope @adguard/agtree check-types
          npx lerna run --scope @adguard/agtree lint
          npx lerna run --scope @adguard/agtree test
          npx lerna run --scope @adguard/agtree build
          npx lerna run --scope @adguard/agtree test:smoke

          # tsurlfilter
          npx lerna run --scope @adguard/tsurlfilter lint
          npx lerna run --scope @adguard/tsurlfilter build
          # IMPORTANT: run tests after the build because smoke tests requires a built dist dir
          npx lerna run --scope @adguard/tsurlfilter test:prod

          # tswebextension
          npx lerna run --scope @adguard/tswebextension lint
          npx lerna run --scope @adguard/tswebextension build
          # IMPORTANT: run tests after the build because smoke tests requires a built dist dir
          npx lerna run --scope @adguard/tswebextension test:prod

          # api
          npx lerna run --scope @adguard/api lint
          npx lerna run --scope @adguard/api build
  notify:
    needs: test
    # Run this job only if the previous job failed and the event was triggered by the 'AdguardTeam/tsurlfilter' repository
    # Note: 'always()' is needed to run the notify job even if the test job was failed
    if:
      ${{
        always() &&
        needs.test.result == 'failure' &&
        github.repository == 'AdguardTeam/tsurlfilter' &&
        (
          github.event_name == 'push' ||
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notif
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: workflow, repo, message, commit, author, eventName, ref, job
          job_name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
