# Tests build
name: test

env:
  NODE_VERSION: 16

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run bash commands
        shell: bash
        run: |
          ls -alt

          # install deps
          npx lerna@6 bootstrap --scope=@adguard/{agtree,tsurlfilter,tswebextension,api}

          # agtree
          npx lerna@6 run --scope @adguard/agtree check-types
          npx lerna@6 run --scope @adguard/agtree check-compatibility-tables
          npx lerna@6 run --scope @adguard/agtree lint
          npx lerna@6 run --scope @adguard/agtree test
          npx lerna@6 run --scope @adguard/agtree build

          # tsurlfilter
          npx lerna@6 run --scope @adguard/tsurlfilter lint
          npx lerna@6 run --scope @adguard/tsurlfilter build
          # IMPORTANT: run tests after the build because smoke tests requires a built dist dir
          npx lerna@6 run --scope @adguard/tsurlfilter test:prod

          # tswebextension
          npx lerna@6 run --scope @adguard/tswebextension lint
          npx lerna@6 run --scope @adguard/tswebextension build
          # IMPORTANT: run tests after the build because smoke tests requires a built dist dir
          npx lerna@6 run --scope @adguard/tswebextension test:prod

          # api
          npx lerna@6 run --scope @adguard/api lint
          npx lerna@6 run --scope @adguard/api build
  notify:
    needs: [ test ]
    # Secrets are not passed to workflows that are triggered by a pull request from a fork
    # always() we use in order to send notification even if the test step failed
    if: ${{ always() && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@v3
      - name: Send Slack notif
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: workflow, repo, message, commit, author, eventName, ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
