# Tests build
name: tswebextension-tests

env:
  NODE_VERSION: 20

on:
  workflow_dispatch:
    inputs:
      id:
        type: 'string'
        description: 'Unique identifier for the workflow run'

run-name: ${{github.workflow}} [ID:${{ inputs.id }}]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Number of commits to fetch. 0 indicates all history.
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Run bash commands
        shell: bash
        run: |
          ls -alt

          # install deps
          pnpm install

          # tswebextension
          npx lerna run --scope @adguard/tswebextension build --include-dependencies

          cd packages/tswebextension
          pnpm pack && mv adguard-tswebextension-*.tgz tswebextension.tgz

          cd ../tsurlfilter
          pnpm pack && mv adguard-tsurlfilter-*.tgz tsurlfilter.tgz
      - name: Save tswebextension dist
        uses: actions/upload-artifact@v4
        with:
          name: tswebextension.tgz
          path: packages/tswebextension/tswebextension.tgz
      - name: Save tsurlfilter dist
        uses: actions/upload-artifact@v4
        with:
          name: tsurlfilter.tgz
          path: packages/tsurlfilter/tsurlfilter.tgz