/* eslint-disable no-bitwise */
/**
 * @file Utility class for handling byte arrays.
 */

/**
 * ByteBuffer class for handling operations on byte arrays.
 * This class allows for the manipulation of Uint8Array chunks,
 * supporting operations like set and get for Uint8 and Uint32 values.
 */
export class ByteBuffer {
    /**
     * Array of Uint8Array chunks.
     */
    public chunks: Uint8Array[] = [];

    /**
     * Current byte offset.
     */
    public byteOffset = 0;

    /**
     * TextEncoder instance for encoding strings to bytes.
     */
    private encoder = new TextEncoder();

    /**
     * TextDecoder instance for decoding bytes to strings.
     */
    private decoder = new TextDecoder();

    /**
     * Gets the total byte length of all chunks.
     *
     * @returns The total byte length.
     */
    public get byteLength(): number {
        return this.chunks.length << 6;
    }

    /**
     * Constructs a new ByteBuffer instance.
     *
     * @param chunks Initial chunks to store in the buffer. Defaults to an empty array.
     */
    constructor(chunks: Uint8Array[] = []) {
        this.chunks = chunks;
    }

    /**
     * Sets a Uint8 value at the specified byte offset.
     *
     * @param byteOffset The offset where the value will be set.
     * @param value The Uint8 value to set.
     */
    public setUint8(byteOffset: number, value: number): void {
        this.chunks[byteOffset >> 6][byteOffset & 63] = value;
    }

    /**
     * Gets a Uint8 value from the specified byte offset.
     *
     * @param byteOffset The offset to retrieve the value from.
     * @returns The Uint8 value at the specified offset.
     */
    public getUint8(byteOffset: number): number {
        return this.chunks[byteOffset >> 6][byteOffset & 63];
    }

    /**
     * Adds a Uint8 value to the buffer at the specified byte offset.
     * Allocates more space if necessary.
     *
     * @param byteOffset The offset where the value will be added.
     * @param value The Uint8 value to add.
     */
    public addUint8(byteOffset: number, value: number): void {
        if (!this.hasCapacity(byteOffset)) {
            this.allocate();
        }

        this.setUint8(byteOffset, value);
        this.byteOffset += 1;
    }

    /**
     * Sets a Uint32 value at the specified byte offset.
     *
     * @param byteOffset The offset where the value will be set.
     * @param value The Uint32 value to set.
     */
    public setUint32(byteOffset: number, value: number) {
        this.setUint8(byteOffset, value >> 24);
        this.setUint8(byteOffset + 1, value >> 16);
        this.setUint8(byteOffset + 2, value >> 8);
        this.setUint8(byteOffset + 3, value);
    }

    /**
     * Gets a Uint32 value from the specified byte offset.
     *
     * @param byteOffset The offset to retrieve the value from.
     * @returns The Uint32 value at the specified offset.
     */
    public getUint32(byteOffset: number) {
        return ((this.getUint8(byteOffset + 3) << 0)
            | (this.getUint8(byteOffset + 2) << 8)
            | (this.getUint8(byteOffset + 1) << 16)
            | (this.getUint8(byteOffset + 0) << 24)) >>> 0;
    }

    /**
     * Adds a Uint32 value to the buffer at the specified byte offset.
     * Allocates more space if necessary.
     *
     * @param byteOffset The offset where the value will be added.
     * @param value The Uint32 value to add.
     */
    public addUint32(byteOffset: number, value: number): void {
        if (!this.hasCapacity(byteOffset + 3)) {
            this.allocate();
        }

        this.setUint32(byteOffset, value);
        this.byteOffset += 4;
    }

    /**
     * Checks if there is sufficient capacity in the buffer for a new entry.
     *
     * @param index The index to check for capacity.
     * @returns True if there is enough capacity, false otherwise.
     */
    private hasCapacity(index: number): boolean {
        return index + 1 >> 6 < this.chunks.length;
    }

    /**
     * Allocates a new chunk in the buffer.
     */
    private allocate(): void {
        this.chunks.push(new Uint8Array(64));
    }

    /**
     * Adds a string to the buffer, encoding it and allocating more space if necessary.
     *
     * @param str The string to add.
     */
    public addString(str: string): void {
        // The goal is to keep the Uint8Array generated by encoder, and do not create new ones
        const encoded = this.encoder.encode(str);
        const { length } = encoded;

        // Add the length of the string as Uint32
        // This is necessary to know how many data should be read when getting the string
        this.addUint32(this.byteOffset, length);

        // Skip if the string is empty
        if (length < 1) {
            return;
        }

        let offset = 0;
        const freeSpaceInCurrentChunk = 64 - (this.byteOffset & 63);

        // If there are remaining space in the current chunk, we need to fill its free space first
        if (freeSpaceInCurrentChunk > 0) {
            this.chunks[this.byteOffset >> 6].set(encoded.subarray(0, freeSpaceInCurrentChunk), this.byteOffset & 63);
            this.byteOffset += freeSpaceInCurrentChunk;
            offset += freeSpaceInCurrentChunk;
        }

        // After the last chunk is filled, we store the rest of the encoded string,
        // by splitting the encoded array into chunks.
        // To do this, we get the maximum multiple of 64 that is less than the length of the encoded string,
        // and add as many 64-byte chunks as possible.
        const maxDivisibleBy64 = (length - offset) & ~63;

        while (offset < maxDivisibleBy64) {
            this.chunks.push(encoded.subarray(offset, offset + 64));
            this.byteOffset += 64;
            offset += 64;
        }

        // If we still have remaining bytes (but less than 64), we add a new 64-byte chunk and fill it
        // with the remaining bytes. This way, we can guarantee that all chunks are 64 bytes long.
        if (offset < length) {
            const remainingBytes = length - offset;
            const newChunk = new Uint8Array(64);
            newChunk.set(encoded.subarray(offset, offset + remainingBytes));
            this.chunks.push(newChunk);
            this.byteOffset += remainingBytes;
        }
    }

    /**
     * Reads a string from the buffer starting at the specified byte offset.
     *
     * @param byteOffset The offset to start reading from.
     * @returns The string read from the buffer.
     */
    public getString(byteOffset: number): string {
        // Read the length of the string as Uint32
        const length = this.getUint32(byteOffset);

        // Skip if the string is empty
        if (length < 1) {
            return '';
        }

        // Skip the length indicator
        const startOffset = byteOffset + 4;
        const stringData = new Uint8Array(length);
        let copiedBytes = 0;

        while (copiedBytes < length) {
            const chunkIndex = (startOffset + copiedBytes) >> 6;
            const chunkOffset = (startOffset + copiedBytes) & 63;
            const bytesToCopy = Math.min(length - copiedBytes, 64 - chunkOffset);

            stringData.set(this.chunks[chunkIndex].subarray(chunkOffset, chunkOffset + bytesToCopy), copiedBytes);
            copiedBytes += bytesToCopy;
        }

        return this.decoder.decode(stringData);
    }
}
